project_id = "leraarbob"

[functions.rechten-duo]
verify_jwt = true

[functions.rechten-class]
verify_jwt = true

[functions.rechten-learn]
verify_jwt = true

[functions.vector-class]
verify_jwt = true
