project_id = "leraarbob"

[functions.rechten-duo]
verify_jwt = true

[functions.rechten-class]
verify_jwt = true

[functions.rechten-learn]
verify_jwt = true

[functions.vector-class]
verify_jwt = true

[functions.bewerkingen-class]
verify_jwt = true

[functions.algebra-class]
verify_jwt = true

[functions.numbers-session]
verify_jwt = true
