/* Cooperative workboards cover released cooperative map nodes, without changing battle pools. */
(function(root,factory){if(typeof module==='object')module.exports=factory(require('./mission-runtime.js'),require('./content/area-maps.js'),require('./derive-core.js'),require('./hills-core.js'));else {root.RechtenLearnGame=factory(root.RechtenV2Runtime,root.RechtenV2Areas,root.RechtenV2Derive,root.RechtenV2Hills);if(new URLSearchParams(location.search).get('mode')==='learn'){root.BattleGame=root.RechtenLearnGame;document.body.classList.add('cooperative-player');}}})(globalThis,(R,A,D,H)=>{
 const order=['puntenbaai','hellingrug','grenspas','formulewerf','signaalstad'];
 const worlds=order.map(id=>({id,name:A.get(id).name,skills:A.all(A.get(id)).filter(n=>n.playable&&!n.soloOnly).map(n=>n.key)}));
 const skills=order.flatMap(world=>A.all(A.get(world)).filter(n=>n.playable&&!n.soloOnly).map(n=>({id:n.key,label:n.name,world})));
 function generate(spec){const item=skills.find(s=>s.id===spec.skill);if(!item||!Number.isInteger(spec.seed)||!Number.isInteger(spec.variant))throw Error('Onbekende samen-leeropgave');const variant=item.id==='line_behavior'?[0,1,3,5,7,8][spec.variant%6]:spec.variant;let state=R.battle(item.world,item.id,spec.seed,variant,{fullSequence:true});const m=R.active(state);if(m.phase==='hill-inspect')state=R.beginHills(state);R.active(state).blindBattle=true;return state;}
 function nextPhase(state){const m=R.active(state);const phase=D.skills.includes(m.skill)?D.nextPhase(m.skill,m.phase):({'hill-dx':'hill-dy','hill-fill':'hill-calculate','line-plot':'line-behavior','grens-root':'grens-inequality'})[m.phase];return phase&&phase!=='next-task'?phase:null;}
 function nextInput(state){const next=nextPhase(state);if(!next)return state;const result=R.active(R.commit(state)).feedback?.result;if(!result||result.kind==='interaction_error')throw Error(result?.message||'Vul deze stap eerst in.');const copy=structuredClone(state),m=R.active(copy);m.phase=next;m.feedback=null;m.history=[];m.locks={};m.values.deriveSlot=D.slots(next)[0]||'';return copy;}
 function restore(spec,answer){let state=generate(spec);const steps=Array.isArray(answer?.steps)?answer.steps:[],history=[];for(let i=0;i<steps.length&&i<8;i++){const step=steps[i];if(step.phase!==R.active(state).phase)break;for(const [k,v] of Object.entries(step.values||{}))state=R.edit(state,k,v);if(i<steps.length-1&&nextPhase(state)){try{state=nextInput(state);history.push(structuredClone(step))}catch{break;}}}return {state,history};}
 function validate(initial,answer){try{if(!Array.isArray(answer?.steps)||!answer.steps.length||answer.steps.length>8)return {ok:false};let state=structuredClone(initial);for(let i=0;i<answer.steps.length;i++){const step=answer.steps[i],m=R.active(state);if(step.phase!==m.phase||!step.values||typeof step.values!=='object')return {ok:false};for(const [k,v] of Object.entries(step.values))state=R.edit(state,k,v);state=R.commit(state);const f=R.active(state).feedback;if(!f?.result.ok)return {ok:false,step:i+1,message:f?.result.message||'Bekijk deze stap opnieuw.'};if(f.next==='next-task')return {ok:i===answer.steps.length-1};state=R.advance(state);}return {ok:false};}catch{return {ok:false}}}
 return Object.freeze({id:'rechten-learn',worlds,skills,generate,validate,nextPhase,nextInput,restore});
});
