'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const J=require('../games/algebra-trainer/journey-core.js'),W=require('../games/algebra-trainer/world-core.js');
const done=run=>({...run,completed:true,results:run.results.map(e=>({...e,done:true}))});
const first=done(J.freshMission('route-two',null,123));first.rewardId='route-two:first';
const base=J.record(null,first.skill,first.results),initial=J.rewardRound(base.progress,first.skill,first,first.results,base.xp);
assert.equal(initial.xp,30);assert.equal(J.xp(initial.progress),30);
assert.equal(J.rewardRound(initial.progress,first.skill,first,first.results).xp,0);
const replay=done(J.freshMission('route-two',first,456));replay.rewardId='route-two:second';
assert(replay.tasks.every(t=>!first.tasks.map(J.questionSignature).includes(J.questionSignature(t))));
const partial={...replay,completed:false};assert.equal(J.rewardRound(initial.progress,replay.skill,partial,replay.results).xp,0);
const repeat=J.rewardRound(initial.progress,replay.skill,replay,replay.results);
assert.equal(repeat.xp,30);assert.equal(J.xp(repeat.progress),60);
const restored=J.normalize(JSON.parse(JSON.stringify(repeat.progress)));
assert.equal(J.xp(restored),60);assert.equal(J.rewardRound(restored,replay.skill,replay,replay.results).xp,0);
assert.equal(J.platform(restored,null,null).completed.length,1);
let legacy=W.normalize(null);for(const k of ['B1','B2'])legacy=W.recordMission(legacy,'eq-'+k,Array.from({length:5},()=>({done:true}))).progress;
const migrated=J.rewardRound(J.record(null,first.skill,first.results,legacy).progress,first.skill,first,first.results,0);
assert.equal(W.xp(legacy)+J.xp(migrated.progress),90,'Legacy60 XP plus new completed round30');
const evidence=Array.from({length:5},()=>({done:true}));assert.equal(J.rewardRound(null,'unknown',{completed:true,rewardId:'invalid'},evidence).xp,0);const system={completed:true,rewardId:'sys-substitution:new'};
const sysBase=W.recordMission(null,'sys-substitution',evidence),sysFirst=J.rewardRound(null,'sys-substitution',system,evidence,sysBase.xp),sysReplay=J.rewardRound(sysFirst.progress,'sys-substitution',{...system,rewardId:'sys-substitution:repeat'},evidence,0);
assert.equal(W.xp(sysBase.progress)+J.xp(sysReplay.progress),60);assert.equal(J.rewardRound(sysReplay.progress,'sys-substitution',{...system,rewardId:'sys-substitution:repeat'},evidence).xp,0);
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../js/catalog-progress.js'),'utf8'),sandbox);
const snapshot={state:{storage:{'leraarbob.algebra.v1':JSON.stringify({chapterJourney:repeat.progress}),'leraarbob.stelsels.workshop.v1':JSON.stringify({journey:sysBase.progress,roundJourney:sysReplay.progress})}}};
assert.equal(sandbox.window.LeraarBobCatalogProgress.earnedXP({id:'algebra-trainer'},snapshot),120);
assert.equal(sandbox.window.LeraarBobCatalogProgress.summarize({id:'algebra-trainer'},snapshot).completed,2);
console.log('Per-round XP, fresh tasks, idempotent reload, legacy migration, system replay and unique level totals passed');
