'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out='/tmp/leraarbob-getallenwereld';fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let file=path.join(root,new URL(req.url,'http://local').pathname);try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.woff2':'font/woff2','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,executablePath:process.env.ALGEBRA_CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});
try{const context=await browser.newContext({viewport:{width:1280,height:800}}),page=await context.newPage(),errors=[],saved=new Map();page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!==base)return r.fulfill({body:''});if(u.pathname==='/shared/axioma-auth.js')return r.fulfill({contentType:'text/javascript',body:`window.__listeners=[];window.__account={id:localStorage.getItem('getallen-user')||'student-a',role:'student',alias:'Testalias',class_code:'3TBO'};window.AxiomaAuth={ready:async()=>({account:__account,pending:false}),getAccount:async()=>__account,onChange:fn=>__listeners.push(fn),client:()=>({rpc:async()=>({data:null,error:null}),auth:{}})};window.testSwitch=()=>{window.__account={id:'student-b',role:'student',alias:'Andere alias'};localStorage.setItem('getallen-user','student-b');__listeners.forEach(fn=>fn({account:__account,pending:false}));};`});if(u.pathname==='/shared/axioma-progress.js')return r.fulfill({contentType:'text/javascript',body:`window.AxiomaProgress={load:async(game,user)=>window.testLoad(game,user),save:async(game,state,revision,user)=>window.testSave(game,state,revision,user)};`});return r.continue();});
await page.exposeFunction('testLoad',(game,user)=>saved.get(user+':'+game)||null);await page.exposeFunction('testSave',(game,state,revision,user)=>{assert.equal(game,'getallenwereld');saved.set(user+':'+game,{state,revision:revision+1});return{status:'saved',revision:revision+1};});
async function open(url='/games/getallenwereld/'){await page.goto(base+url);await page.waitForFunction(()=>window.GetallenWorld&&AxiomaGame.active);}
const snapshot=()=>page.evaluate(()=>GetallenWorld.snapshot());const task=()=>page.evaluate(()=>GetallenWorld.task());
async function solve(){const t=await task();await page.locator('[data-rule="'+t.correct+'"]').click();for(let stage=0;stage<t.stages.length;stage++){for(let i=0;i<t.stages[stage].slots.length;i++){await page.locator('[data-slot="'+i+'"]').click();await page.locator('[data-choice='+JSON.stringify(t.stages[stage].slots[i].answer)+']').click();}await page.locator('[data-action=check]').click();}assert((await snapshot()).mission.done,t.id+' completed via input');}
async function fit(label){await page.screenshot({path:out+'/'+label+'.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,label+' overflow');const target=page.locator('[data-action=check], [data-rule]').first();if(await target.count()){await target.scrollIntoViewIfNeeded();const b=await target.boundingBox();assert(b.width>=44&&b.height>=44,label+' touch target');}assert.equal(await page.locator('.orientation').count(),0);}
await open();assert.equal(await page.locator('leraarbob-topbar').count(),1);assert.equal(await page.locator('.theme').count(),3);await page.locator('.theme[data-theme=machten]').click();assert.equal(await page.locator('[data-stop]').count(),8);assert.equal((await snapshot()).mission,null);await page.locator('[data-stop=machten-product]').click();assert.equal((await snapshot()).mission,null,'selection does not start');await page.locator('[data-action=start]').click();
const original=await task();await page.locator('[data-rule]').filter({hasText:original.choices.find(c=>c.id!==original.correct).label}).click();assert.equal((await snapshot()).mission.attempts,1);await page.locator('[data-rule="'+original.correct+'"]').click();await page.locator('[data-slot="0"]').click();await page.locator('[data-choice]').first().click();const pending=await snapshot();
for(const [width,height]of [[1280,800],[780,360],[640,360],[390,844],[320,700]]){await page.setViewportSize({width,height});await fit('play-'+width);await page.locator('leraarbob-topbar .collapse').click();assert.equal(await page.locator('.lb-restore').getAttribute('aria-expanded'),'false');await fit('collapsed-'+width);const restore=await page.locator('.lb-restore').boundingBox(),head=await page.locator('.workshop-nav [data-action=chapter]').boundingBox();assert(restore.width>=44&&restore.height>=44);assert(restore.x+restore.width<=head.x||restore.y+restore.height<=head.y,'restore does not cover back action '+width);assert.deepEqual((await snapshot()).mission,pending.mission);await page.evaluate(()=>AxiomaGame.flush());await page.reload();await page.waitForFunction(()=>window.GetallenWorld&&AxiomaGame.active).catch(async e=>{console.error('reload debug',await page.evaluate(()=>({errors:window.__errs,active:window.AxiomaGame?.active,status:window.AxiomaGame?.status,body:document.body.innerText.slice(-500)})),errors);throw e;});assert.deepEqual((await snapshot()).mission,pending.mission);assert.equal(await page.locator('.lb-restore').getAttribute('aria-expanded'),'false');await page.locator('.lb-restore').click();}
await page.setViewportSize({width:1280,height:800});await page.locator('leraarbob-topbar .theme-toggle').click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.mode),'dark');assert.deepEqual((await snapshot()).mission,pending.mission);
await page.locator('.workfoot [data-action=help]').click();assert.equal((await snapshot()).mission.assisted,true);assert.notEqual(await page.locator('.question').textContent(),'');await page.locator('.workfoot [data-action=help-return]').click();assert.equal((await snapshot()).mission.values[0],pending.mission.values[0]);await page.locator('[data-action=undo]').click();await solve();await page.locator('[data-action=next]').click();await solve();await page.locator('[data-action=next]').click();await solve();await page.locator('[data-action=next]').click();await solve();await page.locator('[data-action=next]').click();await solve();await page.locator('[data-action=next]').click();await solve();await page.locator('[data-action=next]').click();assert.equal((await snapshot()).screen,'summary');assert.equal(await page.evaluate(()=>AxiomaGame.state.completed.length),1);assert.equal((await snapshot()).entries['machten-product'].independent.length,5);assert.match(await page.locator('leraarbob-topbar .progress').getAttribute('aria-label'),/1.*19/);
await page.evaluate(()=>AxiomaGame.flush());const savedA=saved.get('student-a:getallenwereld');assert(savedA);assert.equal(savedA.state.xp,undefined);assert.deepEqual(Object.keys(savedA.state.storage),['leraarbob.getallenwereld.v1']);assert.equal(saved.has('student-a:bewerkingen-trainer'),false);
const firstSeed=(await snapshot()).mission.seed;await page.locator('[data-action=again]').click();assert.notEqual((await snapshot()).mission.seed,firstSeed,'a repeated part has fresh tasks');
// Complete one real question on every other route and verify chapter/level deep targets.
const stops=await page.evaluate(()=>GetallenLessons.STOPS.map(s=>s.id));for(const id of stops){if(id==='machten-product')continue;await open('/games/getallenwereld/?onderdeel='+id);assert.equal((await snapshot()).screen,'chapter');assert.equal((await snapshot()).selected,id);await page.locator('[data-action=start]').click();await solve();}
await open('/games/getallenwereld/?thema=wortels');assert.equal((await snapshot()).theme,'wortels');assert.equal((await snapshot()).screen,'chapter');await page.evaluate(()=>LeraarBobGameRegistry.ready());await page.locator('leraarbob-topbar .menu').click();const worldLinks=await page.locator('#trainerMenu a[data-world-link]').evaluateAll(a=>a.map(e=>({href:e.href,title:e.textContent})));assert(worldLinks.length>=3);for(const ref of worldLinks){assert.doesNotMatch(ref.title,/Bewerkingentrainer/);assert.match(new URL(ref.href).searchParams.get('returnTo'),/games\/getallenwereld/);}await page.locator('leraarbob-topbar .close').click();
await page.evaluate(()=>AxiomaGame.flush());await page.evaluate(()=>testSwitch());assert.equal(await page.evaluate(()=>AxiomaGame.active),false);await page.reload();await page.waitForFunction(()=>window.GetallenWorld&&AxiomaGame.active);assert.equal((await snapshot()).mission,null);assert.deepEqual((await snapshot()).entries,{});await page.evaluate(()=>localStorage.setItem('getallen-user','student-a'));await page.reload();await page.waitForFunction(()=>window.GetallenWorld&&AxiomaGame.active);assert((await snapshot()).entries['machten-product'].done.length===6,'returning account restores its own work');assert.deepEqual(errors,[]);
await page.goto(base+'/index.html?view=catalog');await page.waitForSelector('a[href$="/games/getallenwereld/"]');assert.equal(await page.locator('.featured-grid a[href$="/games/getallenwereld/"]').count(),1);await context.close();console.log('PASS: 19 actual gameplay routes, 5 screen sizes, select then play, help, partial work/reload, collapse and account isolation; catalog.');
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exit(1)});
