'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const D=require('../games/rechten/trainer-v2/derive-core.js'),R=require('../games/rechten/trainer-v2/mission-runtime.js'),W=require('../games/rechten/trainer/wave-core.js'),V=require('../games/rechten/trainer-v2/components/derive-view.js'),A=require('../games/rechten/trainer-v2/content/area-maps.js');
function solve(s,{reverse=false,point='A'}={}){let m=R.active(s),t=m.task,v={};if(m.phase==='derive-substitute')s=R.selectDerivePoint(s,point);m=R.active(s);const name=D.selectedPoint(m.values),p=t.points[name];switch(m.phase){case'derive-fill':v=reverse?{y1:'A.y',y0:'B.y',x1:'A.x',x0:'B.x'}:{y1:'B.y',y0:'A.y',x1:'B.x',x0:'A.x'};break;case'derive-slope':v={a:W.text(t.model.a)};break;case'derive-substitute':v={subY:name+'.y',subA:'a',subX:name+'.x'};break;case'derive-product':v={product:W.text(W.mul(t.model.a,p.x))};break;case'derive-intercept':v={b:W.text(t.model.b)};break;case'derive-formula':v={answerFactor:W.text(t.model.a),answerSign:t.model.b.n<0?'−':'+',answerConstant:W.text(W.mul(t.model.b.n<0?-1:1,t.model.b))};break}
 for(const [k,value]of Object.entries(v))s=D.slots(m.phase).includes(k)?R.putDeriveToken(s,k,value):R.edit(s,k,value);s=R.commit(s);assert(R.active(s).feedback.result.ok,JSON.stringify(R.active(s).feedback));V.render(R.active(s),'');return R.advance(s)}
test('six exact derivations per skill support both directions, either point, fractions, negatives, horizontal lines and replay',()=>{
 for(const skill of D.skills)for(let run=1;run<=3;run++){let s=R.start(R.initial(),skill);R.active(s).run=run;R.active(s).task=D.makeTask(skill,0,run);const variants=new Set();let turns=0;while(!R.active(s).completed){const m=R.active(s);variants.add(m.task.variant);for(const p of Object.values(m.task.points))assert(W.onLine(p,m.task.model));s=solve(s,{reverse:run%2===0,point:skill==='equation_from_two_points'&&run!==1?'B':'A'});assert(++turns<40)}assert.equal(R.active(s).completion.length,6);assert(variants.has('fraction'));assert(variants.has('horizontal'));assert(s.events.every(e=>e.correct&&e.mastery===false));}
});
test('slope setup catches same-point, swapped-axis and inconsistent directions; repair preserves correct numerator',()=>{
 let s=R.start(R.initial(),'equation_from_two_points');assert.equal(R.active(R.commit(s)).feedback.result.kind,'interaction_error');for(const [k,v]of Object.entries({y1:'B.y',y0:'A.y',x1:'A.x',x0:'B.x'}))s=R.putDeriveToken(s,k,v);s=R.advance(R.commit(s));assert.deepEqual(R.active(s).locks,{y1:true,y0:true});s=R.putDeriveToken(s,'x1','B.x');s=R.putDeriveToken(s,'x0','A.x');s=R.advance(R.commit(s));assert.equal(R.active(s).phase,'derive-slope');assert(R.active(s).locks.x0);s=R.edit(s,'a','-4/2');assert(R.active(R.commit(s)).feedback.result.ok);
 const t=D.makeTask('equation_from_two_points');for(const v of [{y1:'A.x',y0:'B.x',x1:'A.y',x0:'B.y'},{y1:'A.y',y0:'A.y',x1:'A.x',x0:'A.x'}])assert(!D.check(t,v,'derive-fill').ok);
});
test('substitution explicitly distinguishes x, y and a; correct fields survive repair, point switches reset only substitution',()=>{
 let s=R.start(R.initial(),'equation_from_two_points');s=solve(s);s=solve(s);for(const [k,v]of Object.entries({subY:'A.y',subA:'A.x',subX:'a'}))s=R.putDeriveToken(s,k,v);s=R.advance(R.commit(s));assert(R.active(s).locks.subY);assert(!R.active(s).locks.subA);const a=R.active(s).values.a;s=R.selectDerivePoint(s,'B');assert.equal(R.active(s).values.subY,undefined);assert.equal(R.active(s).locks.subY,undefined);assert.equal(R.active(s).values.a,a);assert(R.active(s).locks.a);s=R.undo(s);assert.equal(D.selectedPoint(R.active(s).values),'A');assert.equal(R.active(s).values.subY,'A.y');s=solve(s,{point:'B'});assert.equal(R.active(s).phase,'derive-product');assert.equal(D.selectedPoint(R.active(R.selectDerivePoint(s,'A')).values),'B');
});
test('each arithmetic step is checked, incorrect numbers do not advance and exact equivalent notation is accepted',()=>{
 let s=solve(R.start(R.initial(),'intercept_from_point'));assert.equal(R.active(s).phase,'derive-product');s=R.edit(s,'product','not a number');s=R.advance(R.commit(s));assert.equal(R.active(s).errors,0);s=R.edit(s,'product','3');s=R.advance(R.commit(s));assert.equal(R.active(s).errors,1);assert.equal(R.active(s).phase,'derive-product');s=R.edit(s,'product','4/2');s=R.advance(R.commit(s));s=R.edit(s,'b','1,0');assert(R.active(R.commit(s)).feedback.result.ok);assert.equal(R.active(s).index,0);
 const t=D.makeTask('intercept_from_point',5);assert(D.check(t,{product:'-1,5'},'derive-product').ok);assert(D.check(t,{b:'1/2'},'derive-intercept').ok);
});
test('formula signs represent b exactly, accept equivalent signed constants and lock correct components',()=>{
 const t=D.makeTask('equation_from_point_slope');assert(D.check(t,{answerFactor:'-2',answerSign:'−',answerConstant:'2'},'derive-formula').ok);assert(D.check(t,{answerFactor:'-2',answerSign:'+',answerConstant:'-2'},'derive-formula').ok);const bad=D.check(t,{answerFactor:'-2',answerSign:'+',answerConstant:'2'},'derive-formula');assert(!bad.ok);assert(bad.keep.answerFactor);assert(!bad.keep.answerSign);
});
test('answers and worked calculations appear only after their own explicit check; completed map stops require the final stage',()=>{
 for(const skill of D.skills){let s=R.start(R.initial(),skill);let html=V.render(R.active(s),'');assert(!html.includes('class="derive-found"'));assert(!html.includes('class="derive-final"'));if(skill==='equation_from_two_points')assert(!html.includes('a = −2'));
 while(!R.active(s).completed){const before=R.active(s);assert.notEqual(A.statuses(s,'formulewerf').nodes.find(n=>n.id===skill).state,'completed');s=solve(s);if(!R.active(s).completed&&R.active(s).index===before.index){const partial=structuredClone(s);partial.events=partial.events.filter(e=>e.taskId.includes(':5:run'));assert.notEqual(A.statuses(partial,'formulewerf').nodes.find(n=>n.id===skill).state,'completed')}}assert.equal(A.statuses(s,'formulewerf').nodes.find(n=>n.id===skill).state,'completed');s=R.start(s,skill,true);assert.equal(A.statuses(s,'formulewerf').nodes.find(n=>n.id===skill).state,'completed');}
});
test('independent resume, undo and hints preserve other tasks and completion; a new example restarts the derivation',()=>{
 let s=R.edit(R.start(R.initial(),'equation_from_ab'),'factor','2'),old=structuredClone(s.missions.equation_from_ab);s=R.start(s,'equation_from_two_points');s=R.putDeriveToken(s,'y1','B.y');const partial=structuredClone(R.active(s));s=R.start(R.start(s,'intercept_from_point'),'equation_from_two_points');assert.deepEqual(R.active(s),partial);s=R.undo(s);assert.equal(R.active(s).values.y1,undefined);s=solve(s);s=solve(s);for(let i=0;i<5;i++)s=R.hint(s);const before=R.active(s).task;s=R.newAfterExample(s);assert.equal(R.active(s).phase,'derive-fill');assert.notDeepEqual(R.active(s).task.model.b,before.model.b);assert.deepEqual(R.active(s).values,{});assert.deepEqual(s.missions.equation_from_ab,old);assert.deepEqual(JSON.parse(JSON.stringify(s)),s);
});
