const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../games/rechten/arcade/core.js');
const fixture=[[1,0],[1,3],[0,5],[2,0],[.5,0],[.5,6],[1.5,0],[1.5,4],[-1,0],[-1,-3],[0,-5],[-2,0],[-.5,0],[-.5,-6],[-1.5,0],[-1.5,-4]];
test('all sixteen original rescue missions keep exact start heights and target points',()=>{
 fixture.forEach(([a,b],i)=>{assert(C.rescueCorrect(i+1,a,b));assert(!C.rescueCorrect(i+1,a,b+1));const t=C.rescueTask(i+1);assert.equal(a*t.x+b,t.y);const m={ox:51,oy:180,unit:19};const origin=C.scenePoint(m,0,b),end=C.scenePoint(m,t.x,t.y);assert.equal(origin.x,m.ox);assert.equal(origin.y,m.oy-b*m.unit);assert.equal((origin.y-end.y)/(end.x-origin.x),a);});
});
test('telescoping sections end exactly at every commanded ladder length',()=>{for(const len of [2,10,50,200,800]){const sections=C.ladderSections(len,30);assert.equal(sections[0].offset,0);assert(Math.abs(sections.at(-1).offset+sections.at(-1).length-len)<1e-9);assert(sections.every(s=>s.length<=len));}});
test('a retry is eventual success, never first-attempt success; duplicate events do not count',()=>{
 const run=C.newRun('kleiduiven');C.append(run,{id:'a',kind:'attempt',task:'1',correct:false,skill:'helling'});C.append(run,{id:'b',kind:'attempt',task:'1',correct:true,skill:'helling'});assert.equal(C.append(run,{id:'b',kind:'attempt',task:'1',correct:true}),false);const s=C.summary(run);assert.equal(s.first,0);assert.equal(s.eventually,1);assert.equal(s.wrong,1);assert.equal(s.score,500);
});
test('model answers give no independent learning points',()=>{const run=C.newRun('redding');C.append(run,{id:'a',kind:'attempt',task:'1',correct:true,modeled:true});const s=C.summary(run);assert.equal(s.score,0);assert.equal(s.assisted,1);assert.equal(s.eventually,0);});
test('naval misses are recorded separately from mathematical errors',()=>{const run=C.newRun('zeeslag');C.append(run,{id:'a',kind:'naval-shot',hits:0});C.append(run,{id:'b',kind:'naval-shot',hits:2});assert.equal(C.summary(run).wrong,0);assert.equal(C.summary(run).hits,2);assert.equal(C.summary(run).shots,2);});
test('top scores compare complete runs under the same conditions and keep one best run per alias',()=>{const good=C.newRun('kleiduiven',{actor:'Bob',tempo:5});good.complete=true;good.elapsedMs=4000;C.append(good,{id:'a',kind:'attempt',task:'1',correct:true});const worse=structuredClone(good);worse.id='worse';worse.elapsedMs=6000;const other=structuredClone(good);other.actor='Sara';const wrongMode=structuredClone(good);wrongMode.actor='Duo';wrongMode.mode='duo';const wrongSpeed=structuredClone(good);wrongSpeed.actor='8s';wrongSpeed.tempo=8;const rows=C.rankings([good,worse,other,wrongMode,wrongSpeed],'kleiduiven',5);assert.equal(rows.length,2);assert.equal(rows[0].rank,1);assert.equal(rows[1].rank,1);assert.equal(rows[0].elapsedMs,4000);});
test('CSV is Dutch-compatible and neutralizes formulas in aliases without breaking numeric negatives',()=>{const text=C.csv([['=SUM(A1)','+cmd','-name','@name','a;"b',-1,.5]]);assert(text.startsWith('\uFEFF'));assert(text.includes('"\'=SUM(A1)"'));assert(text.includes('"-1"'));assert(text.includes('"a;""b"'));assert(text.endsWith('\r\n'));const run=C.newRun('redding',{actor:'Bob'});assert(C.resultsCSV([run]).includes('Juist eerste poging'));assert(C.attemptsCSV([run]).includes('Vaardigheid'));});
