const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../shared/multiplayer/rechten-learn-engine.cjs'),G=require('../games/rechten/rechtenwereld/battle-config.js'),R=require('../games/rechten/rechtenwereld/mission-runtime.js'),W=require('../games/rechten/core/wave-core.js');
const make=(n=2)=>({id:'room',code:'ABCD12',version:1,now:'2026-09-30T00:00:00Z',members:['a','b','c'].slice(0,n).map(id=>({id,alias:id,seen_at:'2026-09-30T00:00:00Z'})),data:{skill:'point_plot',seed:19,phase:'lobby',round:0,revision:0,left:[],ideas:{},draft:{steps:[]},approvals:[]}});
const good=r=>{const m=R.active(G.generate(E.spec(r)));return {steps:[{phase:m.phase,values:{point:{x:W.num(m.task.target.x),y:W.num(m.task.target.y)}}}]};};
function act(r,u,a,d={}){r.data=E.change(r,u,a,d);r.version++;return r;}
function build(r){act(r,'a','start');const answer=good(r);for(const m of r.members)act(r,m.id,'idea',{answer});return r;}
test('ideas are private until everyone contributes; no fourth party can mutate',()=>{const r=make(3);act(r,'a','start');act(r,'a','idea',{answer:good(r)});assert.equal(E.project(r,'b').ideas,null);assert.equal(E.project(r,'b').mine.answer,undefined);assert.throws(()=>act(r,'x','idea',{answer:good(r)}),/deel/);act(r,'b','idea',{answer:good(r)});assert.equal(r.data.phase,'idea');act(r,'c','idea',{answer:{steps:[]},skipped:true});assert.equal(r.data.phase,'build');assert.equal(E.project(r,'b').ideas.length,3);});
test('editing invalidates all approvals and old revisions cannot approve/check',()=>{const r=build(make());let revision=r.data.revision;act(r,'a','approve',{revision});act(r,'b','approve',{revision});assert.equal(r.data.phase,'build');act(r,'a','draft',{revision,answer:{steps:[]}});assert.deepEqual(r.data.approvals,[]);assert.throws(()=>act(r,'b','approve',{revision}),/nieuwste/);assert.throws(()=>act(r,'a','check',{revision:r.data.revision}),/Iedereen/);});
test('six full tasks rotate roles, then each student receives an independent check',()=>{const r=build(make());for(let i=0;i<6;i++){if(i){for(const m of r.members)act(r,m.id,'idea',{answer:good(r)});}const revision=r.data.revision;for(const m of r.members)act(r,m.id,'approve',{revision});const who=E.builder(r);act(r,who,'check',{revision});assert.equal(r.data.correct,true);act(r,who,'next');}assert.equal(r.data.phase,'individual');assert.notEqual(E.project(r,'a').task.seed,E.project(r,'b').task.seed);act(r,'a','individual',{answer:{steps:[]}});assert.equal(E.project(r,'b').mine.check,null);assert.equal(r.data.phase,'individual');act(r,'b','individual',{answer:{steps:[]}});assert.equal(r.data.phase,'finished');assert.equal(E.project(r,'a').mine.check.correct,false);assert.equal(r.data.platformXp,undefined);});
test('trio becomes duo only after two explicit votes and an absent member; leaving preserves solo exit',()=>{const r=build(make(3));assert.throws(()=>act(r,'a','continue-duo'),/Wacht/);r.members[2].seen_at='2026-09-29T23:59:00Z';act(r,'a','continue-duo');assert.equal(E.project(r,'a').members.length,3);act(r,'b','continue-duo');assert.equal(E.project(r,'a').members.length,2);assert.equal(E.project(r,'c').participating,false);act(r,'b','leave');assert.equal(r.data.phase,'paused');});

test('a departed third learner cannot keep completed own ideas waiting forever',()=>{const r=make(3);act(r,'a','start');act(r,'a','idea',{answer:good(r)});act(r,'b','idea',{answer:good(r)});act(r,'c','leave');assert.equal(r.data.phase,'build');assert.equal(E.project(r,'a').members.length,2);});
