const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../games/rechten/trainer/wave-core.js');
const task=(skill,options={})=>({id:'test',skill,difficulty:options.difficulty||0,params:C.generate(skill,options)});
function answer(t,w,reverse=false){const stage=C.stages(t)[w.index];return stage==='ys'||stage==='xs'?(reverse?['A','B']:['B','A']):stage==='point'?'B':stage==='subY'?'y':stage==='subX'?'x':C.expected(t,w)}
function solve(t,reverse=false){const w=C.fresh(t);while(!w.done)assert(C.submit(t,w,answer(t,w,reverse)).ok,JSON.stringify({t,w}));return w}
test('exact fractions, decimal comma, signs, invalid division and vertical rendering',()=>{assert(C.eq(C.fromNumber(2/3),C.q(2,3)));assert.deepEqual(C.parse('-1,25'),C.q(-5,4));assert(C.eq(C.q(6,-4),C.q(-3,2)));assert(C.eq(C.add(C.q(1,3),C.q(2,3)),1));assert.throws(()=>C.div(1,0));for(const s of ['','1/0','NaN','-','1,'])assert.equal(C.parse(s),null);assert.match(C.html(C.q(-13,7)),/−<span class="frac"><span>13/);assert.equal(C.formula(C.q(0),C.q(4)),'y = 4')});
test('3600 controlled tasks: exact model, bounded points, every step, both directions',()=>{let count=0;const coverage={};for(const skill of Object.keys(C.catalog)){coverage[skill]=new Set();for(let difficulty=0;difficulty<3;difficulty++)for(let seed=1;seed<=200;seed++){const t=task(skill,{difficulty,variant:seed%12,seed}),p=t.params,m=p.model;coverage[skill].add(p.variant);for(const P of [p.A,p.B]){assert(Math.abs(C.num(P.x))<=5);assert(Math.abs(C.num(P.y))<=5);if(m.kind==='affine'){
 // Independent integer cross multiplication: y = a*x + b.
 assert.equal(P.y.n*m.a.d*P.x.d*m.b.d,(m.a.n*P.x.n*m.b.d+m.b.n*m.a.d*P.x.d)*P.y.d);
 }else if(m.kind==='vertical')assert(C.eq(P.x,m.c))}solve(t,false);solve(t,true);count++}}
 assert.equal(count,3600);for(const key of ['slope_from_two_points','special_lines','equation_from_two_points'])for(const variant of ['horizontal','vertical','identical'])assert(coverage[key].has(variant),key+' '+variant);
 for(const key of Object.keys(C.catalog).filter(k=>k!=='special_lines'))for(const variant of ['positive','negative','positive-fraction','negative-fraction','horizontal'])assert(coverage[key].has(variant),key+' '+variant);
});
test('audit examples accept both orders, reject mixed order by point identity',()=>{const q=C.q,A={x:q(2),y:q(3)},B={x:q(6),y:q(11)},t={skill:'slope_from_two_points',params:{A,B,model:C.model(A,B)}};assert(C.eq(t.params.model.a,2));solve(t);solve(t,true);const w=C.fresh(t);C.submit(t,w,['B','A']);assert.equal(C.submit(t,w,['A','B']).code,'wave.direction');assert.equal(w.index,1);C.submit(t,w,['B','A']);assert.equal(w.index,2);
 const horizontal={...t,params:{A:{x:q(-2),y:q(4)},B:{x:q(5),y:q(4)}}};horizontal.params.model=C.model(horizontal.params.A,horizontal.params.B);solve(horizontal,true);
});
test('special lines: horizontal, vertical and identical have different conclusions',()=>{const q=C.q;for(const [A,B,kind] of [[[-2,4],[5,4],'affine'],[[3,-2],[3,5],'vertical'],[[3,-2],[3,-2],'identical']]){const p={A:{x:q(A[0]),y:q(A[1])},B:{x:q(B[0]),y:q(B[1])}};p.model=C.model(p.A,p.B);assert.equal(p.model.kind,kind);const w=solve({skill:'special_lines',params:p});if(kind==='vertical'){assert.equal(w.values.axis,'x');assert.equal(w.values.function,'geen functie');assert(C.eq(w.values.constant,3))}if(kind==='affine'){assert.equal(w.values.property,'a0');assert.equal(w.values.function,'functie')}if(kind==='identical')assert.equal(w.steps.length,1)}});
test('b error retains a and selected point; repair, undo and JSON roundtrip preserve diagnosis',()=>{const t=task('equation_from_two_points',{difficulty:2,variant:3,seed:5}),w=C.fresh(t);while(C.stages(t)[w.index]!=='b')C.submit(t,w,answer(t,w));const before=structuredClone(w.values);assert.equal(C.submit(t,w,C.add(t.params.model.b,1)).code,'wave.b');assert.deepEqual(w.values,before);const restored=JSON.parse(JSON.stringify(w));while(!restored.done)assert(C.submit(t,restored,answer(t,restored)).ok);assert(restored.errors.includes('wave.b'));const index=restored.index;C.undo(restored);assert.equal(restored.index,index-1);assert(C.eq(restored.values.a,t.params.model.a));assert.deepEqual(C.stages(t).slice(-2),['verifyA','verifyB'])});
const skill=()=>({intro:false,seen:0,correct:0,strength:0,recent:[]});
const state=()=>({version:701,skills:Object.fromEntries(C.order.map(k=>[k,skill()])),review:[],access:[]});
test('pure migration preserves historical data, unknown IDs, reviews, XP and old access',()=>{const s=state();s.version=700;s.xp=97;s.telemetry=[{skill:'ab',ok:true}];s.review=[{skill:'future',kind:'repair',due:8}];s.skills.ab={...skill(),intro:true,seen:8,strength:.8};s.skills.future={custom:7};const before=structuredClone(s),m=C.migrate(s);assert.deepEqual(s,before);assert.deepEqual(m.skills,s.skills);assert.equal(m.xp,97);assert.deepEqual(m.review,s.review);assert.deepEqual(m.telemetry,s.telemetry);assert(m.access.includes('fx'));assert(m.access.includes('ab'));assert(m.access.includes('delta'));assert.equal(m.version,701);assert.deepEqual(C.migrate(m),m)});
test('all 17 skills reachable; unlocks permanent; no deferred prerequisite',()=>{const s=state();assert.deepEqual(C.unlock(s),['point']);for(const k of C.order){assert(C.unlock(s).includes(k),'reachable '+k);Object.assign(s.skills[k],{intro:true,seen:4,strength:.5,recent:[true,true,true,true]})}assert.equal(C.unlock(s).length,17);for(const v of Object.values(s.skills))v.strength=0;assert.equal(C.unlock(s).length,17);assert(!Object.values(C.requirements).flat().includes('rewrite_linear_equation'));assert(!Object.values(C.requirements).flat().includes('information_sufficiency'))});
test('mastery needs variant coverage and later different independent tasks, assisted repair supplies none',()=>{const st=skill(),t=task('line_behavior');C.evidence(st,t,0,false);assert(!st.coverage);C.evidence(st,t,0,true);assert(!C.mastered(st,t.skill));for(const [i,variant] of [0,1,4].entries())C.evidence(st,task('line_behavior',{variant,seed:i+3}),i+4,true);assert(C.mastered(st,t.skill))});
