(() => {
'use strict';
const C=RechtenArcadeCore,$=id=>document.getElementById(id),KEY='axioma.rechten.arcade.runs.v1',STORE='axioma.rechten.arcade.hub.v1';
let game='zeeslag',mode='solo',actors=[],actorIndex=0,seed='',duoTempo=5;
const names=C.games;
function localRuns(){try{const data=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(data)?data:[];}catch{return [];}}
function notice(text){$('notice').textContent=text;$('notice').hidden=!text;}
function screen(id){for(const name of ['menuScreen','playScreen'])$(name).hidden=name!==id;}
function download(name,text){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportRuns(runs,attempts=false){download(attempts?'rechten-arcade-pogingen.csv':'rechten-arcade-resultaten.csv',attempts?C.attemptsCSV(runs):C.resultsCSV(runs));}
function persist(){try{sessionStorage.setItem(STORE,JSON.stringify({game,mode,actors,actorIndex,seed}));}catch{}}
function choose(){document.querySelectorAll('[data-game]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.game===game)));document.querySelectorAll('[data-game]').forEach(b=>b.classList.toggle('selected',b.dataset.game===game));document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('modeHelp').textContent=mode==='duo'?(game==='zeeslag'?'Online duel · elk een toestel':game==='redding'?'Planner en controleur · één toestel':'Zelfde doelen · om de beurt op één toestel'):game==='zeeslag'?'Tegen de computer · ook zonder account':'Je eigen tempo · ook zonder account';$('launchBtn').textContent='Spelen →';}
function progress(p){const node=$('arcade-progress');node.dataset.platformProgress='levels';node.dataset.value=p.value;node.dataset.total=p.total;node.dataset.unit=p.unit||'levels';window.dispatchEvent(new CustomEvent('axioma:game-progress'));}
function play(){
 screen('playScreen');$('gameTitle').textContent=names[game].name;$('arcade-current').textContent=names[game].name;$('arcade-current').hidden=false;$('actorLabel').textContent=actors[actorIndex]||'';$('liveScore').textContent=game==='zeeslag'?'0 treffers':'0 pt';progress({value:0,total:game==='redding'?16:1,unit:game==='kleiduiven'?'reeksen':game==='zeeslag'?'partijen':'levels'});
 const url=new URL(names[game].path,location.href);url.searchParams.set('mode',mode);if(actors[actorIndex])url.searchParams.set('actor',actors[actorIndex]);if(seed)url.searchParams.set('seed',seed);url.searchParams.set('level','1');
 if(game==='zeeslag'&&mode!=='duo')url.searchParams.set('solo','1');if(mode==='duo'&&game==='kleiduiven'){url.searchParams.set('tempo',duoTempo);url.searchParams.set('lockTempo','1');}
 $('gameFrame').title=names[game].name;$('gameFrame').src=url.href;persist();
}
function finish(detail){
 if(mode==='duo'&&game==='kleiduiven'&&actorIndex===0){$('handoverTitle').textContent='Geef het toestel door';$('handoverText').textContent=actors[1]+' krijgt dezelfde zeven doelen op hetzelfde tempo.';$('handoverNext').onclick=()=>{actorIndex=1;$('handoverDialog').close();play();};$('handoverDialog').showModal();}
 else if(mode==='duo'&&game==='kleiduiven'){
  const runs=localRuns().filter(r=>r.seed===seed&&r.mode==='duo'&&r.complete),rows=runs.map(r=>({actor:r.actor,...C.summary(r)})).sort((a,b)=>b.score-a.score||a.elapsedMs-b.elapsedMs);
  $('handoverTitle').textContent='Duo afgerond';$('handoverText').textContent=rows.map(r=>r.actor+': '+r.score+' punten · '+(r.elapsedMs/1000).toFixed(1).replace('.',',')+' s').join(' / ');$('handoverNext').onclick=()=>{$('handoverDialog').close();back();};$('handoverDialog').showModal();
 }
}
function back(){persist();$('gameFrame').src='about:blank';screen('menuScreen');choose();$('arcade-progress').removeAttribute('data-platform-progress');$('gameTitle').textContent='';$('arcade-current').hidden=true;window.dispatchEvent(new CustomEvent('axioma:game-progress'));}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('gameFrame').contentWindow||!/^rechten-arcade:/.test(e.data?.type)||e.data.game!==game)return;const d=e.data;if(d.platformProgress)progress(d.platformProgress);if(game==='zeeslag'&&d.run)progress({value:Number(C.summary(d.run).won===true),total:1,unit:'partijen'});if(d.status)$('actorLabel').textContent=d.status;if(d.run){const s=C.summary(d.run);$('liveScore').textContent=game==='zeeslag'?s.hits+' treffers':s.score.toLocaleString('nl-BE')+' pt';}if(d.type==='rechten-arcade:finish')finish(d);});
document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>{game=b.dataset.game;choose();});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;choose();});
$('launchBtn').onclick=async()=>{notice('');seed=C.uuid();actorIndex=0;if(mode==='duo'&&game!=='zeeslag'){$('duoTempoLabel').hidden=game!=='kleiduiven';$('duoHelp').textContent=game==='redding'?'Eén maakt het plan, de andere controleert. Wissel na elke redding.':'Jullie spelen om de beurt dezelfde doelen. Eerst telt juistheid, daarna tijd.';$('duoDialog').showModal();}else{actors=[];play();}};
$('duoForm').onsubmit=e=>{e.preventDefault();const form=new FormData(e.target),a=C.identity(form.get('actor1')),b=C.identity(form.get('actor2'));if(a===b){notice('Kies twee verschillende spelersnamen.');return;}actors=game==='redding'?[a+' & '+b]:[a,b];duoTempo=Number(form.get('tempo'))||5;$('duoDialog').close();play();};
$('backBtn').onclick=back;$('arcadeMenu').onclick=back;$('gameHomeBtn').onclick=back;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
function scores(){const id=$('scoreGame').value,tempo=id==='kleiduiven'?Number($('scoreTempo').value):0;$('tempoFilter').hidden=id!=='kleiduiven';$('scoreList').replaceChildren();$('scoreNote').textContent=id==='zeeslag'?'De online ranglijst telt bevestigde gewonnen partijen. Je kunt die in de Zeeslag-lobby openen.':'Beste volledige soloreeks per speler op dit toestel. Eerste poging: 1000 pt; na herkansing: 500 pt. Hetzelfde spel en tempo worden vergeleken.';if(id==='zeeslag'){const b=document.createElement('button');b.textContent='Open Zeeslag-ranglijst';b.onclick=()=>{$('scoresDialog').close();game='zeeslag';mode='duo';play();};$('scoreList').append(b);return;}
 const rows=C.rankings(localRuns(),id,tempo);if(!rows.length){const li=document.createElement('li');li.textContent='Nog geen volledige reeks. Speel je eerste ronde!';$('scoreList').append(li);return;}for(const r of rows){const li=document.createElement('li'),rank=document.createElement('b'),copy=document.createElement('div'),name=document.createElement('strong'),note=document.createElement('small'),score=document.createElement('output');rank.textContent=String(r.rank).padStart(2,'0');name.textContent=r.actor;note.textContent=r.first+' / '+r.total+' eerste poging'+(r.elapsedMs?' · '+(r.elapsedMs/1000).toFixed(1).replace('.',',')+' s':'');score.textContent=r.score.toLocaleString('nl-BE')+' pt';copy.append(name,note);li.append(rank,copy,score);$('scoreList').append(li);}}
$('scoresBtn').onclick=()=>{scores();$('scoresDialog').showModal();};$('scoreGame').onchange=$('scoreTempo').onchange=scores;
$('archiveBtn').onclick=async()=>{const node=$('sessionList');node.replaceChildren();for(const r of localRuns().slice().reverse().slice(0,50)){const row=document.createElement('div');row.className='session-row';const text=document.createElement('div'),strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=r.actor+' · '+names[r.game]?.name;small.textContent=new Date(r.startedAt).toLocaleString('nl-BE')+' · '+(r.complete?'afgerond':'in uitvoering');text.append(strong,small);const b=document.createElement('button');b.textContent='CSV';b.onclick=()=>exportRuns([r]);row.append(text,b);node.append(row);}if(!node.children.length)node.textContent='Hier verschijnen je gespeelde sessies.';$('archiveDialog').showModal();};
$('exportResults').onclick=()=>exportRuns(localRuns());$('exportAttempts').onclick=()=>exportRuns(localRuns(),true);
try{const saved=JSON.parse(sessionStorage.getItem(STORE)||'null');if(saved){game=names[saved.game]?saved.game:game;mode=saved.mode==='duo'?'duo':'solo';}}catch{}choose();
})();
