(()=>{
'use strict';
const C=BewerkingenCore,$=id=>document.getElementById(id),KEY='leraarbob.bewerkingen.v1';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const math=tex=>window.katex?katex.renderToString(tex,{throwOnError:false,strict:'ignore'}):esc(tex);
const R=window.LeraarBobRoutes,params=new URLSearchParams(location.search);
let router,worksheetIntent=params.get('intent')==='worksheet',returnTo=R?.safeReturn(params.get('returnTo'),'games/getallenwereld/')||'../getallenwereld/';
let state={version:1,screen:'setup',mode:'solo',selected:C.SKILLS.filter(s=>s.group==='machten').map(s=>s.id),level:1,count:10,names:['Speler 1','Speler 2'],sessions:{},solved:[],history:[],includeKey:false,sheetTasks:[],sheetSource:'session',journey:AlgebraWorld.normalize(null),worldLegacy:[],mission:null};
try{const saved=JSON.parse(AxiomaGame.storage.getItem(KEY)||'null');if(saved?.version===1){
 state={...state,...saved};state.selected=(saved.selected||[]).filter(id=>C.SKILLS.some(s=>s.id===id));state.solved=[...new Set((saved.solved||[]).filter(id=>C.SKILLS.some(s=>s.id===id)))];state.history=Array.isArray(saved.history)?saved.history.slice(-30):[];
 state.mode=['solo','duo','teacher'].includes(state.mode)?state.mode:'solo';state.level=[0,1,2].includes(state.level)?state.level:1;state.count=[5,10,15,20,30].includes(state.count)?state.count:10;state.names=[0,1].map(i=>String(saved.names?.[i]||'Speler '+(i+1)).slice(0,30));
 const sessions={};for(const mode of ['solo','duo','teacher']){const s=saved.sessions?.[mode];if(Array.isArray(s?.tasks)&&s.tasks.length&&s.tasks.length<=30&&s.tasks.every(t=>C.SKILLS.some(k=>k.id===t.skill))){
  const tasks=s.tasks.map(t=>C.generate(t.skill,t.seed,t.level,t.variant));sessions[mode]={...s,tasks,index:Math.max(0,Math.min(tasks.length-1,Math.floor(Number(s.index))||0)),work:s.work&&typeof s.work==='object'?s.work:{}};
 }}state.sessions=sessions;state.sheetTasks=Array.isArray(saved.sheetTasks)&&saved.sheetTasks.length<=30?saved.sheetTasks.filter(t=>C.SKILLS.some(k=>k.id===t.skill)).map(t=>C.generate(t.skill,t.seed,t.level,t.variant)):[];state.sheetSource=saved.sheetSource==='generated'?'generated':'session';if(!['setup','play','sheet'].includes(state.screen)||(state.screen==='play'&&!sessions[state.mode])||(state.screen==='sheet'&&!sessions[state.mode]&&!state.sheetTasks.length))state.screen='setup';
}}catch{state.screen='setup';state.sessions={};$('setupNotice').textContent='De vorige reeks kon niet worden hervat. Kies een nieuwe reeks.';}
state.journey=AlgebraWorld.normalize(state.journey);try{const old=JSON.parse(AxiomaGame.storage.getItem(KEY)||'null');state.worldLegacy=(Array.isArray(old?.worldLegacy)?old.worldLegacy:old?.solved||[]).filter(id=>C.SKILLS.some(s=>s.id===id));}catch{state.worldLegacy=[];}
if(state.mission&&state.sessions.solo)state.sessions.solo.mission=state.mission;
function selectedGroup(){const groups=[...new Set(state.selected.map(id=>C.SKILLS.find(s=>s.id===id)?.group))];return groups.length===1?groups[0]:'';}
function routingTopic(){return state.screen!=='setup'&&AlgebraWorld.topic(state.mission)?.engine==='operations'?state.mission:selectedGroup();}
function navigationGroup(){
 if(state.screen==='play')return C.SKILLS.find(s=>s.id===task()?.skill)?.group||'';
 if(state.screen==='sheet'){
  const tasks=state.sheetSource==='generated'&&state.sheetTasks.length?state.sheetTasks:session()?.tasks||[];
  const groups=[...new Set(tasks.map(t=>C.SKILLS.find(s=>s.id===t.skill)?.group))];
  return groups.length===1?groups[0]:'';
 }
 return selectedGroup();
}
function applySelection(query){const group=query.get('world')||query.get('topic'),mode=query.get('mode'),requestedScreen=query.get('screen');
 if(C.GROUPS.some(g=>g.id===group)){const selected=state.selected.filter(id=>C.SKILLS.find(s=>s.id===id)?.group===group);state.selected=selected.length?selected:C.SKILLS.filter(s=>s.group===group).map(s=>s.id);}
 if(!worksheetIntent&&['solo','duo','teacher'].includes(mode))state.mode=mode;
 if((worksheetIntent&&requestedScreen!=='sheet')||requestedScreen==='setup'||((group||mode)&&!['play','sheet'].includes(requestedScreen)))state.screen='setup';
 else if(requestedScreen==='play')state.screen=state.sessions[state.mode]?'play':'setup';
 else if(requestedScreen==='sheet')state.screen=(state.sheetTasks.length||state.sessions[state.mode])?'sheet':'setup';
 if(state.screen==='setup')state.mission=null;
}
applySelection(params);
function boundedText(text,bytes){let out='',used=0;for(const char of String(text)){const size=new TextEncoder().encode(char).length;if(used+size>bytes)break;out+=char;used+=size;}return out;}
const session=()=>state.sessions[state.mode],task=()=>session()?.tasks[session().index];
const taskSeeds=tasks=>tasks.map(({skill,seed,level,variant})=>({skill,seed,level,variant}));
function persist(){if(!AxiomaGame.active)return;const saved={...state,sheetTasks:taskSeeds(state.sheetTasks),sessions:Object.fromEntries(Object.entries(state.sessions).map(([mode,s])=>[mode,{...s,tasks:taskSeeds(s.tasks)}]))};AxiomaGame.storage.setItem(KEY,JSON.stringify(saved));AxiomaGame.report(state.solved,C.SKILLS.length);const p=$('operationProgress');p.dataset.value=state.solved.length;p.textContent=state.solved.length+'/'+C.SKILLS.length+' vraagvormen zelfstandig opgelost';if(state.mission){p.dataset.platformProgress='xp';p.dataset.value=AlgebraWorld.xp(state.journey);p.textContent=p.dataset.value+' XP';}else p.dataset.platformProgress='levels';AxiomaGame.emit(state.solved,C.SKILLS.length);}
function shuffle(list){for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}return list;}
function buildTasks(){const selected=shuffle([...state.selected]),count=Math.max(state.count,selected.length);return Array.from({length:count},(_,i)=>C.generate(selected[i%selected.length],crypto.getRandomValues(new Uint32Array(1))[0],state.level,i%4));}
function work(player=0){const s=session(),k=s.index+':'+player;if(!s.work[k])s.work[k]={value:'',notes:'',attempts:0,help:false,reveal:0,done:false,skipped:false,message:'',hint:false,recorded:false};return s.work[k];}
function picker(){
 $('skillPicker').innerHTML=C.GROUPS.map(g=>`<fieldset class="skill-group"><legend>${esc(g.label)}</legend><div class="skill-options">${C.SKILLS.filter(s=>s.group===g.id).map(s=>`<label class="skill-option"><input type="checkbox" value="${s.id}" ${state.selected.includes(s.id)?'checked':''}><span>${esc(s.label)}</span>${state.solved.includes(s.id)?'<small aria-label="Zelfstandig opgelost">✓</small>':''}</label>`).join('')}</div></fieldset>`).join('');
 $('level').value=state.level;$('count').value=state.count;state.names.forEach((n,i)=>$('name'+i).value=n);modeUI();
}
function modeUI(){document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode&&!worksheetIntent)));$('duoNames').hidden=state.mode!=='duo'||worksheetIntent;document.querySelector('.mode-grid').hidden=worksheetIntent;$('setupTitle').textContent=worksheetIntent?'Maak een oefenblad':'Kies je eigen reeks';$('setupIntro').textContent=worksheetIntent?'Kies vraagvormen, niveau en aantal.':'Machten, wetenschappelijke schrijfwijze en vierkantswortels.';$('progressHint').hidden=worksheetIntent;$('startBtn').textContent=worksheetIntent?'Oefenblad maken →':({solo:'Start met oefenen →',duo:'Start de bordbattle →',teacher:'Start samen leren →'})[state.mode];$('startBtn').disabled=!state.selected.length;$('selectionSummary').textContent=state.selected.length?`${state.selected.length} vraagvormen · ${Math.max(state.count,state.selected.length)} vragen`:'Kies minstens één vraagvorm.';updateNavigation();}
function updateNavigation(){const group=navigationGroup(),label=C.GROUPS.find(g=>g.id===group)?.label||'Eigen reeks';$('crumbGroup').textContent=label;$('crumbMode').textContent=state.screen==='sheet'||worksheetIntent?'Oefenblad':({solo:'Eigen reeks',duo:'Bordduo',teacher:'Samen leren'})[state.mode];$('crumbMode').hidden=$('crumbMode').textContent===label;
 $('worldReturn').href=returnTo;
 const classURL=new URL('../../klasbattle/',location.href);classURL.searchParams.set('game','getallenwereld');classURL.searchParams.set('view','create');if(group)classURL.searchParams.set('world',group);if(R)classURL.searchParams.set('returnTo',R.href(location.href,{gameId:'getallenwereld',world:selectedGroup(),topic:selectedGroup(),screen:'setup',returnTo:''}));document.querySelectorAll('a[href="classroom.html"],a[data-getallen-class]').forEach(a=>{a.href=classURL.pathname+classURL.search;a.dataset.getallenClass='';a.dataset.platformRoute='';});
}
function syncRoute(){if(!router)return;router.update({world:selectedGroup(),topic:routingTopic(),screen:state.screen,returnTo});const url=new URL(location.href);if(worksheetIntent)url.searchParams.set('intent','worksheet');else url.searchParams.delete('intent');url.searchParams.set('mode',state.mode);history.replaceState(history.state,'',url.pathname+url.search+url.hash);}
function screen(name){if(!AxiomaGame.active)return;if(name==='play'&&!session()){state.screen='setup';$('setupNotice').textContent='Kies je vragen en klik op Start.';}else if(name==='sheet'&&!session()&&!state.sheetTasks.length){worksheetIntent=true;state.screen='setup';}else state.screen=name;
 if(state.screen==='sheet'&&!session())state.sheetSource='generated';
 if(state.screen==='play'){worksheetIntent=false;state.mission=session()?.mission||null;}
 document.body.dataset.screen=state.screen;document.body.dataset.playMode=state.mode;
 for(const n of ['setup','play','sheet'])$(n+'Screen').hidden=state.screen!==n;
 if(state.screen==='setup')picker();if(state.screen==='play')renderPlay();if(state.screen==='sheet')renderSheet();
 $('resumeBtn').disabled=!session();$('sessionLabel').textContent=session()?`${{solo:'Zelf oefenen',duo:'Bordduo',teacher:'Samen leren'}[state.mode]} · vraag ${session().index+1}/${session().tasks.length}`:'';updateNavigation();persist();syncRoute();
}
function record(w){if(w.recorded||state.mode!=='solo')return;w.recorded=true;const t=task(),independent=w.done&&!w.help&&!w.attempts;if(independent&&!state.solved.includes(t.skill))state.solved.push(t.skill);state.history.push({skill:t.skill,level:t.level,correct:w.done,independent,attempts:w.attempts,assisted:w.help,at:new Date().toISOString()});state.history=state.history.slice(-30);if(state.mission&&t.skill===AlgebraWorld.topic(state.mission)?.skill&&w.done&&!w.help){const reward=AlgebraWorld.record(state.journey,state.mission,t.expression,state.worldLegacy.map(id=>'op-'+id));state.journey=reward.progress;if(reward.xp)w.message+=' Topic afgerond: +'+reward.xp+' XP!';}}
function guide(t){if(t.inputHelp)return '<p class="input-guide">'+esc(t.inputHelp)+'</p>';return '<p class="input-guide">Typ bijvoorbeeld <code>3x^2</code>, <code>1/x^2</code>, <code>4sqrt(5)</code> of <code>1,7*10^8</code>.</p>';}
function stepsHTML(t,count){return `<div class="steps">${t.steps.slice(0,count).map((s,i)=>`<div class="step"><span class="sr-only" hidden>Stap ${i+1}:</span>${math(s)}</div>`).join('')}</div>`;}
function card(player){const t=task(),w=work(player),duo=state.mode==='duo',s=session(),score=s.tasks.reduce((n,_,i)=>n+(s.work[i+':'+player]?.done&&!s.work[i+':'+player]?.skipped?1:0),0);
 const other=duo?work(1-player):null,roundDone=duo&&(w.done||w.skipped)&&(other.done||other.skipped);
 if(duo&&(w.done||w.skipped)&&!roundDone)return `<article class="work-card" data-player="${player}"><div class="player-head"><h2>${esc(s.names[player])}</h2><span class="score">${score} juist</span></div><div class="question">${math(t.tex)}</div><p class="feedback" role="status">${w.done?'Juist!':'Je hebt gepast.'} Wacht op de andere speler.</p></article>`;
 return `<article class="work-card" data-player="${player}">${duo?`<div class="player-head"><h2>${esc(s.names[player])}</h2><span class="score">${score} juist</span></div>`:''}<div class="question-block"><div class="question">${math(t.tex)}</div>${t.instruction?`<p class="task-instruction">${esc(t.instruction)}</p>`:''}<p class="condition">${esc(t.condition)}</p><details class="scratch" ${w.notes?'open':''}><summary>Tussenstappen</summary><textarea maxlength="800" data-notes="${player}" aria-label="Tussenstappen${duo?' van '+esc(s.names[player]):''}" placeholder="Noteer je redenering.">${esc(w.notes)}</textarea></details></div><form class="answer-form" data-answer="${player}"><label for="answer${player}">${esc(t.answerLabel||'Jouw vereenvoudigde antwoord')}</label><div class="answer-row"><input id="answer${player}" data-input="${player}" maxlength="180" value="${esc(w.value)}" autocomplete="off" autocapitalize="off" spellcheck="false" aria-describedby="guide${player} feedback${player}" ${w.done||w.skipped?'disabled':''}><button class="primary" ${w.done||w.skipped?'disabled':''}>Controleer</button></div><div id="guide${player}">${guide(t)}</div><div class="keys" aria-label="Wiskundige invoer">${[['^()','Macht'],['sqrt()','Wortel'],['/','Breuk'],['*','×'],['-','−'],['(', '('],[')',')']].map(([token,label])=>`<button type="button" data-token="${token}" data-for="${player}" ${w.done||w.skipped?'disabled':''}>${label}</button>`).join('')}</div><div class="answer-preview" id="preview${player}" aria-label="Voorbeeld van je invoer"></div></form><p id="feedback${player}" class="feedback" role="status" data-kind="${w.done?'correct':w.message?'wrong':''}">${esc(w.message)}</p>${!duo?`<div class="work-actions"><button data-help="${player}" ${w.done||w.skipped?'disabled':''}>Hint</button><button data-reveal="${player}">Toon uitwerking</button><button data-skip="${player}" ${w.done||w.skipped?'disabled':''}>Overslaan</button>${w.done||w.skipped?'<button class="primary" data-next>Verder →</button>':''}</div>${w.hint?`<p class="hint">${esc(t.hint)}</p>`:''}${w.reveal?stepsHTML(t,w.reveal):''}`:w.done||w.skipped?stepsHTML(t,t.steps.length):'<button data-skip="'+player+'">Ik pas</button>'}</article>`;
}
function renderPlay(){renderMission();const s=session(),t=task();if(!t)return;$('modeLabel').textContent=({solo:'ZELF OEFENEN',duo:'MET TWEE AAN HET BORD',teacher:'LERAARMODUS'})[state.mode];$('questionTitle').textContent=C.SKILLS.find(k=>k.id===t.skill).label;$('roundLabel').textContent=`${s.index+1} / ${s.tasks.length}`;$('previousBtn').disabled=s.index===0;$('nextBtn').disabled=s.index===s.tasks.length-1||(state.mode==='duo'&&![0,1].every(p=>work(p).done||work(p).skipped));
 if(state.mode==='teacher'){const w=work();$('playHost').innerHTML=`<article class="work-card teacher"><div class="question">${math(t.tex)}</div>${t.instruction?`<p class="task-instruction">${esc(t.instruction)}</p>`:''}<p class="condition">${esc(t.condition)}</p><div class="work-actions"><button id="teacherStep" class="primary" ${w.reveal>=t.steps.length?'disabled':''}>Volgende uitwerkingsstap</button><button id="teacherAll">Volledige uitwerking</button><button id="teacherHide">Uitwerking verbergen</button><button data-screen="sheet">Oefenblad maken</button></div>${stepsHTML(t,w.reveal)}<p class="hint">${esc(t.hint)}</p><details class="scratch" ${w.notes?'open':''}><summary>Bordnotities</summary><textarea maxlength="800" data-notes="0" aria-label="Bordnotities">${esc(w.notes)}</textarea></details></article>`;
 }else $('playHost').innerHTML=state.mode==='duo'?`<div class="duo-board">${card(0)}${card(1)}</div>`:card(0);
 document.querySelectorAll('[data-input]').forEach(e=>preview(Number(e.dataset.input)));
 const players=state.mode==='duo'?2:1,all=s.tasks.every((_,i)=>Array.from({length:players},(_,p)=>s.work[i+':'+p]?.done||s.work[i+':'+p]?.skipped).every(Boolean));$('endSummary').hidden=!all||state.mode==='teacher';
 if(all){const scores=Array.from({length:players},(_,p)=>s.tasks.filter((_,i)=>s.work[i+':'+p]?.done).length);$('endSummary').innerHTML=`<h2>Reeks afgerond</h2><p>${state.mode==='duo'?s.names.map((n,i)=>esc(n)+': '+scores[i]+' juist').join(' · '):scores[0]+' van '+s.tasks.length+' vragen opgelost.'}</p>${state.mission?'<a class="world-return" href="../algebra-trainer/?world='+AlgebraWorld.topic(state.mission).world+'">Terug naar de wereldkaart →</a>':'<button data-screen="setup">Nieuwe reeks kiezen</button>'}`;}
}
function preview(p){const target=$('preview'+p);if(!target)return;const v=work(p).value;if(!v){target.textContent='';return;}try{C.parse(v);target.innerHTML=math(C.tex(v));}catch{target.textContent='Maak je antwoord verder af…';}}
function move(delta){const s=session();if(!s)return;const next=s.index+delta;if(next>=0&&next<s.tasks.length){s.index=next;screen('play');}}
function renderSheet(){const s=state.sheetSource==='generated'&&state.sheetTasks.length?{tasks:state.sheetTasks}:session();$('includeKey').checked=state.includeKey;if(!s)return;let pages='';for(let start=0;start<s.tasks.length;start+=6){pages+=`<article class="paper"><span class="eyebrow">LERAARBOB · GETALLENWERELD</span><h1>Werk de opdrachten uit.</h1><p>Naam: ____________________ &nbsp; Klas: __________</p><ol start="${start+1}">${s.tasks.slice(start,start+6).map(t=>`<li>${t.instruction?`<p class="sheet-instruction">${esc(t.instruction)}</p>`:''}<div class="question">${math(t.tex)}</div>${t.condition?`<div class="sheet-condition">${esc(t.condition)}</div>`:''}<div class="answer-space"></div></li>`).join('')}</ol></article>`;}
 if(state.includeKey)for(let start=0;start<s.tasks.length;start+=6)pages+=`<article class="paper"><h1>Uitwerkingen</h1><ol start="${start+1}">${s.tasks.slice(start,start+6).map(t=>`<li>${t.instruction?`<p class="sheet-instruction">${esc(t.instruction)}</p>`:''}<div class="question">${math(t.tex)}</div>${stepsHTML(t,t.steps.length)}</li>`).join('')}</ol></article>`;$('sheetHost').innerHTML=pages;
}
$('skillPicker').addEventListener('change',()=>{if(!AxiomaGame.active)return;state.selected=[...$('skillPicker').querySelectorAll('input:checked')].map(e=>e.value);modeUI();persist();syncRoute();});
$('selectAll').onclick=()=>{if(!AxiomaGame.active)return;state.selected=state.selected.length===C.SKILLS.length?[]:C.SKILLS.map(s=>s.id);picker();persist();syncRoute();};
$('level').onchange=()=>{state.level=Number($('level').value);persist();};$('count').onchange=()=>{state.count=Number($('count').value);modeUI();persist();};[0,1].forEach(i=>$('name'+i).oninput=()=>{state.names[i]=$('name'+i).value;persist();});
$('startBtn').onclick=()=>{if(!AxiomaGame.active||!state.selected.length)return;if(worksheetIntent){state.sheetTasks=buildTasks();state.sheetSource='generated';screen('sheet');return;}state.mission=null;$('worldMission').hidden=true;state.sessions[state.mode]={tasks:buildTasks(),index:0,work:{},names:state.names.map((n,i)=>n.trim()||'Speler '+(i+1))};screen('play');};
$('previousBtn').onclick=()=>move(-1);$('nextBtn').onclick=()=>move(1);$('includeKey').onchange=()=>{state.includeKey=$('includeKey').checked;renderSheet();persist();};$('printBtn').onclick=()=>window.print();
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||!AxiomaGame.active)return;
 if(b.dataset.screen){if(b.dataset.screen==='sheet'&&session()&&!worksheetIntent)state.sheetSource='session';screen(b.dataset.screen);return;}if(b.dataset.mode){worksheetIntent=false;state.mode=b.dataset.mode;screen('setup');return;}
 if(b.hasAttribute('data-next')){move(1);return;}if(b.dataset.token){const input=$('answer'+b.dataset.for),start=input.selectionStart,end=input.selectionEnd,token=b.dataset.token;input.setRangeText(token,start,end,'end');if(token.endsWith('()'))input.setSelectionRange(start+token.length-1,start+token.length-1);input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();return;}
 if(b.dataset.help!==undefined){const w=work(Number(b.dataset.help));w.help=true;w.hint=true;renderPlay();persist();}
 if(b.dataset.reveal!==undefined){const w=work(Number(b.dataset.reveal));w.help=true;w.reveal=task().steps.length;renderPlay();persist();}
 if(b.dataset.skip!==undefined){const w=work(Number(b.dataset.skip));w.skipped=true;w.message='Overgeslagen. Bekijk de uitwerking en probeer dit type later opnieuw.';w.reveal=task().steps.length;record(w);renderPlay();persist();}
 if(['teacherStep','teacherAll','teacherHide'].includes(b.id)){const w=work();w.reveal=b.id==='teacherHide'?0:b.id==='teacherAll'?task().steps.length:Math.min(task().steps.length,w.reveal+1);renderPlay();persist();}
 });
$('playHost').addEventListener('input',e=>{if(!AxiomaGame.active)return;if(e.target.dataset.input!==undefined){const p=Number(e.target.dataset.input);work(p).value=boundedText(e.target.value,300);if(e.target.value!==work(p).value)e.target.value=work(p).value;preview(p);persist();}if(e.target.dataset.notes!==undefined){const w=work(Number(e.target.dataset.notes));w.notes=boundedText(e.target.value,800);if(e.target.value!==w.notes)e.target.value=w.notes;persist();}});
$('playHost').addEventListener('submit',e=>{e.preventDefault();if(!AxiomaGame.active)return;const p=Number(e.target.dataset.answer),w=work(p);if(w.done||w.skipped)return;const r=C.check(task(),w.value);w.message=boundedText(r.message,320);if(r.ok){w.done=true;record(w);}else w.attempts++;renderPlay();persist();if(!r.ok)$('answer'+p)?.focus();else if(state.mode==='solo')document.querySelector('[data-next]')?.focus();});
function renderMission(){const t=AlgebraWorld.topic(state.mission),el=$('worldMission');el.hidden=!t;document.body.dataset.worldMission=String(!!t);if(!t)return;const n=state.journey.topics[t.id]?.answers.length||0;el.innerHTML=`<a class="world-return" href="../algebra-trainer/?world=${t.world}">← ${esc(AlgebraWorld.world(t.world).title)}</a><p><strong>${esc(t.title)}</strong> · ${n} / ${AlgebraWorld.GOAL} opdrachten · ${AlgebraWorld.REWARD} XP</p><small>Los drie verschillende opdrachten op. Je mag verbeteren; met een hint of getoonde uitwerking telt deze opdracht niet voor het topic.</small>`;}
const requested=AlgebraWorld.topic(params.get('topic'));
if(requested?.engine==='operations'){
 const legacy=state.worldLegacy.map(id=>'op-'+id);
 if(!AlgebraWorld.unlocked(state.journey,requested.id,legacy)){state.screen='setup';state.mission=null;$('setupNotice').textContent='Dit topic is nog gesloten. Open de algebrawereld om je volgende topic te kiezen.';}
 else if(state.mission!==requested.id||!state.sessions.solo||(performance.getEntriesByType('navigation')[0]?.type!=='reload'&&state.sessions.solo.tasks.every((_,i)=>state.sessions.solo.work[i+':0']?.done||state.sessions.solo.work[i+':0']?.skipped))){
  const used=new Set(state.journey.topics[requested.id]?.answers||[]),tasks=[];
  for(let attempt=0;tasks.length<AlgebraWorld.GOAL&&attempt<300;attempt++){const t=C.generate(requested.skill,crypto.getRandomValues(new Uint32Array(1))[0],0,attempt%4);if(used.has(t.expression))continue;used.add(t.expression);tasks.push(t);}
  // Completed topics may be practised again without receiving a second reward.
  if(!tasks.length)tasks.push(C.generate(requested.skill,crypto.getRandomValues(new Uint32Array(1))[0],0,0));
  state.mission=requested.id;state.mode='solo';state.selected=[requested.skill];state.sessions.solo={tasks,index:0,work:{},names:state.names,mission:requested.id};state.screen='play';
 }else{state.mode='solo';state.screen='play';}
}
renderMission();screen(state.screen);
if(R)router=R.mount({gameId:'getallenwereld',enabled:()=>AxiomaGame.active,read:()=>({world:selectedGroup(),topic:routingTopic(),screen:state.screen,returnTo}),apply:context=>{worksheetIntent=new URLSearchParams(location.search).get('intent')==='worksheet';returnTo=R.safeReturn(context.returnTo,'games/getallenwereld/');applySelection(new URLSearchParams(location.search));screen(state.screen);}});
window.BewerkingenTrainer=Object.freeze({snapshot:()=>JSON.parse(JSON.stringify(state))});
})();
