(()=>{
'use strict';
const C=BewerkingenCore,host=document.getElementById('work'),status=document.getElementById('status');let task,current;
const math=tex=>katex.renderToString(tex,{throwOnError:false,strict:'ignore'}),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const draftKey=()=>`bewerkingen-class-draft:${current.learner}:${current.match}:${current.index}`;
function saveDraft(value){if(current.projector)return;try{sessionStorage.setItem(draftKey(),value.slice(0,180));}catch{}}
function freeze(message){host.querySelectorAll('input,button').forEach(e=>e.disabled=true);status.textContent=message;}
BattlePlayer.connect({start(spec){current=spec;task=BattleGame.generate(spec);document.body.classList.toggle('projector',!!spec.projector);status.textContent='';host.innerHTML=`<article class="work-card"><h2>${esc(C.SKILLS.find(s=>s.id===task.skill).label)}</h2><div class="question">${math(task.tex)}</div>${task.instruction?`<p class="task-instruction">${esc(task.instruction)}</p>`:''}<p class="condition">${esc(task.condition)}</p><form id="answerForm" class="answer-form"><label for="answer">${esc(task.answerLabel||'Jouw vereenvoudigde antwoord')}</label><div class="answer-row"><input id="answer" maxlength="180" autocomplete="off" autocapitalize="off" spellcheck="false" aria-describedby="guide status"><button class="primary">Dien antwoord in</button></div><p class="input-guide" id="guide">${esc(task.inputHelp||'Gebruik bijvoorbeeld 3x^2, 1/x^2, 4sqrt(5) of 1,7*10^8.')}</p><div class="keys">${[['^()','Macht'],['sqrt()','Wortel'],['/','Breuk'],['*','×'],['-','−']].map(([token,label])=>`<button type="button" data-token="${token}">${label}</button>`).join('')}</div><div id="preview" class="answer-preview"></div></form><button id="pass">Ik pas</button><div id="review"></div></article>`;
const input=document.getElementById('answer');if(!spec.projector)try{input.value=(sessionStorage.getItem(draftKey())||'').slice(0,180);}catch{}input.oninput=()=>{if(BattlePlayer.locked)return;saveDraft(input.value);try{C.parse(input.value);document.getElementById('preview').innerHTML=math(C.tex(input.value));}catch{document.getElementById('preview').textContent='Maak je antwoord verder af…';}};
host.querySelector('form').onsubmit=e=>{e.preventDefault();if(BattlePlayer.locked||spec.projector)return;try{C.parse(input.value);}catch(err){status.textContent=err.message;return;}BattlePlayer.submit({value:input.value});};
document.getElementById('pass').onclick=()=>{if(!spec.projector)BattlePlayer.submit({},true);};
host.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{if(BattlePlayer.locked)return;const start=input.selectionStart,token=b.dataset.token;input.setRangeText(token,start,input.selectionEnd,'end');if(token.endsWith('()'))input.setSelectionRange(start+token.length-1,start+token.length-1);input.oninput();input.focus();});input.oninput();
},freeze,retry(){host.querySelectorAll('input,button').forEach(e=>e.disabled=false);status.textContent='Probeer opnieuw.';}});
addEventListener('message',e=>{if(e.source!==parent||e.origin!==location.origin||e.data?.type!=='vector-class-review'||!current||e.data.match!==current.match||e.data.index!==current.index)return;freeze('Bespreek de uitwerking.');document.getElementById('review').innerHTML='<div class="steps">'+task.steps.map(s=>`<div class="step">${math(s)}</div>`).join('')+'</div>';});
})();
