(() => {
'use strict';
const L=window.Logic,C=window.LogicContent,$=id=>document.getElementById(id),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,extra='',cls='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
let owner='guest',progress={version:1,records:[],lastStop:0,reducedMotion:false},screen='world',district=0,selected=0,lessonPage=0,run=null,answer=null,tablePage=0,feedback=null,pending=null,storageOK=true,menuReturn='world',progressPage=0;
let purpose='learn',launchMode='solo',ready=false;
const params=new URLSearchParams(location.search);const requestedMode=params.get('mode');
const OS=window.LogicaOS;
const modeName={solo:'Solo Learn','duo-learn':'Duo Learn','solo-battle':'Solo Battle',local:'Duo Battle',bonus:'Poorten verdiepen'};
const progressKey=()=>`logicawereld:v1:${encodeURIComponent(owner)}`;
const runKey=()=>progressKey()+':run:'+(run?.mode||launchMode)+':'+(run?.selected??selected);
const resumeKey=()=>progressKey()+':resume:'+launchMode;
const legacyRunKey=()=>progressKey()+':run';
const stopRecords=id=>progress.records.filter(r=>r.skill===id);
const stopStatus=id=>L.mastered(stopRecords(id))?'mastered':stopRecords(id).some(r=>r.attempts>0)?'started':'new';
const statusText=id=>({mastered:'Zelfstandig gelukt',started:'In oefening',new:'Nieuw'})[stopStatus(id)];
const taskNow=()=>run?C.tasks.find(t=>t.id===run.tasks[run.index]):null;
const player=()=>['solo','solo-battle','bonus'].includes(run?.mode)?'solo':run.index%2===0?'A':'B';
const playerLabel=()=>player()==='solo'?'Jij':'Speler '+player();
function persist(){if(!ready)return;try{const stored=L.sanitizeProgress(JSON.parse(localStorage.getItem(progressKey())||'null'),C.tasks.map(t=>t.id));const seen=new Map();for(const list of [stored.records,progress.records]){const occurrences=new Map();for(const record of list){const sig=record.eventId||JSON.stringify(record),n=(occurrences.get(sig)||0)+1;occurrences.set(sig,n);seen.set(sig+':'+n,record);}}progress.records=[...seen.values()].slice(-1500);localStorage.setItem(progressKey(),JSON.stringify(progress));localStorage.setItem(runKey(),JSON.stringify(run?{run,answer,tablePage,feedback,pending,screen,lessonPage}:null));if(run)localStorage.setItem(resumeKey(),String(run.selected));storageOK=true;}catch{storageOK=false;}updateChrome();}
function updateChrome(){const crumb=$('stopCrumb');if(crumb){crumb.textContent=C.stops[selected].name;crumb.hidden=screen==='world';}const n=C.stops.filter(s=>stopStatus(s.id)==='mastered').length;const p=$('platformProgress');p.textContent=n+'/18 haltes';p.dataset.value=n;window.dispatchEvent(new Event('axioma:game-progress'));document.body.dataset.reducedMotion=progress.reducedMotion?'true':'false';}
function setCollapsed(value){window.LeraarBobTopbar?.setCollapsed(value,true);}
function go(where){screen=where;persist();$('app').focus({preventScroll:true});render();}
function render(){if(!ready)return;try{const url=new URL(location.href);url.searchParams.set('stop',String(selected+1));url.searchParams.set('mode',launchMode);url.searchParams.set('view',screen);history.replaceState(null,'',url);}catch{}document.body.dataset.district=String(C.stops[selected].district);const focused=document.activeElement,signature=focused&&$('app').contains(focused)?{...focused.dataset}:null;document.body.dataset.screen=screen;updateChrome();$('app').innerHTML=screen==='world'?world():screen==='lesson'?lesson():screen==='modes'?modes():screen==='bonus-intro'?bonusIntro():screen==='play'||screen==='review'?play():screen==='summary'?summary():screen==='progress'?progressView():screen==='hint'?hintView():menu();const replacement=signature?.action?[...$('app').querySelectorAll('[data-action]')].find(n=>Object.entries(signature).every(([k,v])=>n.dataset[k]===v)):null;(replacement||$('app')).focus({preventScroll:true});window.dispatchEvent(new Event('logica:context'));}
function districtStopButtons(d){return d.stops.map(id=>{const s=C.stops[id];return button(`<span class="stop-marker">${stopStatus(id)==='mastered'?'✓':String(id+1).padStart(2,'0')}</span><span><strong>${escape(s.name)}</strong><small>${statusText(id)}</small></span><span class="arrow">›</span>`,'select-stop',`data-id="${id}" aria-current="${selected===id?'step':'false'}" data-status="${stopStatus(id)}"`,'stop');}).join('');}
function world(){const d=C.districts[district],done=C.stops.filter(x=>stopStatus(x.id)==='mastered').length;return `<section class="world screen"><div class="world-heading"><div><p class="eyebrow">LOGICAWERELD</p><h1>Propositielogica</h1><p class="intro">Kies een onderdeel en oefen.</p></div><div class="world-count"><strong>${done}<span>/18</span></strong><small>zelfstandig gelukt</small></div></div><div class="world-layout"><div class="city-map" aria-label="De zes onderdelen van propositielogica"><picture><source media="(max-width:900px)" srcset="assets/regelstad-small.webp"><img src="assets/regelstad.webp" alt="Zes herkenbare gebouwen rond een rivier: de leerroute van Logicawereld" draggable="false" fetchpriority="high"></picture>${C.districts.map((x,i)=>button(`<span class="district-number">${i+1}</span><span><strong>${escape(x.name)}</strong><small>${x.stops.filter(id=>stopStatus(id)==='mastered').length}/${x.stops.length} haltes</small></span>`,'district',`data-id="${i}" aria-pressed="${i===district}" style="--district:${x.color}"`,'district district-'+i)).join('')}</div><aside class="district-detail" style="--district:${d.color}"><div class="district-title"><span class="district-symbol" aria-hidden="true">${d.symbol}</span><div><p class="eyebrow">GEBIED ${district+1} / 6</p><h2>${escape(d.name)}</h2></div></div><div class="stops">${districtStopButtons(d)}</div><div class="stop-detail"><p>${escape(C.stops[selected].goal)}</p><div class="example">${escape(C.stops[selected].example)}</div></div><div class="district-actions">${button('Kijk even mee','lesson','','secondary')}${button(modeName[launchMode]+' <span>→</span>','practice','','primary')}</div></aside></div><footer class="world-footer"><div class="world-tools">${button('Werkvormen','modes','','tool-link')}${button('Oefenblad','worksheet','','tool-link')}</div>${run?button('Hervat je ronde →','resume','','resume'):`<span class="save-note">${storageOK?'Voortgang bewaard':'Opslag niet beschikbaar'}</span>`}</footer></section>`;}
function lesson(){const s=C.stops[selected],slide=s.lesson[lessonPage];return `<section class="lesson screen"><div class="screen-nav">${button('← Leerroute','world')}<span>Halte ${selected+1} · ${s.name}</span><span class="eyebrow">KIJK EVEN MEE</span></div><div class="blackboard"><div class="lesson-copy"><p class="eyebrow">${lessonPage+1} / ${s.lesson.length} · ÉÉN IDEE</p><h1>${escape(slide[0])}</h1><p>${escape(slide[1])}</p></div><div class="chalk-example">${escape(s.example)}<span class="chalk-line"></span><small>${lessonPage===0?'Lees de betekenis.':lessonPage===1?'Test het kritieke geval.':'Gebruik de regel zelf.'}</small></div></div><footer class="lesson-footer"><div class="lesson-dots">${s.lesson.map((_,i)=>button(String(i+1),'lesson-page',`data-id="${i}" aria-pressed="${i===lessonPage}"`)).join('')}</div>${lessonPage>0?button('← Vorige','lesson-page',`data-id="${lessonPage-1}"`):'<span></span>'}${button(lessonPage<s.lesson.length-1?'Volgende →':'Zelf proberen →',lessonPage<s.lesson.length-1?'lesson-page':'practice',lessonPage<s.lesson.length-1?`data-id="${lessonPage+1}"`:'','primary')}</footer></section>`;}
function modes(){const s=C.stops[selected];return `<section class="modes screen"><div class="screen-nav">${button('← Leerroute','world')}<span>Halte ${selected+1} · ${escape(s.name)}</span></div><div class="mode-content"><div class="mode-heading"><p class="eyebrow">KIES HOE JE OEFENT</p><h1>${escape(s.name)}</h1><p>${escape(s.goal)}</p></div><div class="mode-toolbar"><div class="segmented" role="group" aria-label="Doel">${button('◎ Learn','purpose','data-id="learn" aria-pressed="'+(purpose==='learn')+'"')}${button('⚑ Battle','purpose','data-id="battle" aria-pressed="'+(purpose==='battle')+'"')}</div>${button('Oefenblad','worksheet','','paper-link')}</div><div class="mode-options">${[
 [purpose==='learn'?'solo':'solo-battle','◎','Solo',purpose==='learn'?'Vijf opdrachten op jouw tempo.':'Acht vragen uit dit gebied.'],[purpose==='learn'?'duo-learn':'local','♧','Duo op één toestel',purpose==='learn'?'Om de beurt. Je partner kijkt mee.':'Tien beurten. Een score per speler.']
 ].map(([id,icon,name,desc])=>button(`<span class="mode-icon">${icon}</span><span><strong>${name}</strong><span>${desc}</span></span><b>→</b>`,'start',`data-mode="${id}"`,'mode-option')).join('')}</div><p class="mode-note">${purpose==='learn'?'Lees, bouw en bespreek. Een fout helpt je verder.':'10 punten bij de eerste poging, 5 punten na verbeteren. Geen tijdsdruk.'}</p></div></section>`;}
function shuffled(items){const a=items.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function start(mode){launchMode=mode;if(run?.record?.attempts>0&&run.index<run.tasks.length&&player()==='solo'){progress.records.push({...structuredClone(run.record),abandoned:true});}const tasks=mode==='bonus'?C.bonus:mode==='solo'||mode==='duo-learn'?C.stops[selected].tasks:shuffled(C.districts[district].stops.flatMap(i=>C.stops[i].tasks)).slice(0,mode==='local'?10:8);run={id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2),mode,tasks:tasks.map(t=>t.id),index:0,records:[],record:null,selected,startedAt:new Date().toISOString()};newTask();go('play');}
function bonusIntro(){return `<section class="lesson screen"><div class="screen-nav">${button('← Leerroute','world')}<span>Optionele zijroute · Poorten verdiepen</span></div><div class="blackboard"><div class="lesson-copy"><p class="eyebrow">BEKENDE POORTEN COMBINEREN</p><h1>NAND & NOR</h1><p>NAND = AND gevolgd door NOT.<br>NOR = OR gevolgd door NOT.<br>Bereken eerst de gewone poort; keer daarna de uitkomst om.</p></div><div class="chalk-example">NAND: ¬(p ∧ q)<br>NOR: ¬(p ∨ q)<span class="chalk-line"></span><small>Vier extra opdrachten.</small></div></div><footer class="lesson-footer"><p class="interaction-note">De kernroute blijft 18 haltes.</p>${button('Zelf proberen →','start-bonus','','primary')}</footer></section>`;}
function newTask(){const t=taskNow();if(!t)return;run.record=L.newRecord(t,player());run.record.eventId=(run.id||run.startedAt)+':'+run.index;answer=t.type==='build'?{left:'p',right:'q',op:'∧',leftNot:false,rightNot:false,outerNot:false}:t.type==='circuit'?['PASS','PASS','AND']:t.type==='table'?L.cases(t.vars||L.variables(t.columns.map(c=>c.expr).join(''))).map(()=>t.columns.map(()=>null)):t.type==='difference'?Object.fromEntries([...new Set([...L.variables(t.expr),...L.variables(t.other)])].map(v=>[v,false])):t.type==='multi'?[]:null;tablePage=0;feedback=null;pending=null;persist();}
function defs(t){return t.defs?`<div class="definitions">${Object.entries(t.defs).map(([v,label])=>`<span><b>${v}</b><span>${escape(label)}</span></span>`).join('')}</div>`:'';}
function truthValue(v){return v?'W':'V';}
function facts(env,labels={}){return `<div class="facts">${Object.entries(env).map(([v,b])=>`<div class="fact"><span class="fact-variable">${v}</span><strong class="truth truth-${b?'true':'false'}">${truthValue(b)}</strong>${labels[v]?`<small>${escape(labels[v])}</small>`:''}</div>`).join('')}</div>`;}
function gateSVG(t){const env=t.env||{p:false,q:false},shown=feedback&&typeof answer==='boolean';let result=shown?L.value(t.expr,env):null;const op=t.expr.includes('∧')?'AND':t.expr.includes('∨')?'OR':'NOT';return `<svg class="circuit-illustration" viewBox="0 0 420 185" role="img" aria-label="${op}-poort met twee onafhankelijke invoeren"><path d="M60 48H139V76H178M60 140H139V109H178M265 92H352" stroke="currentColor" stroke-width="3" fill="none"/><circle cx="54" cy="48" r="23" class="signal-${env.p?'on':'off'}"/><circle cx="54" cy="140" r="23" class="signal-${env.q?'on':'off'}"/><rect x="178" y="56" width="87" height="73" rx="8" class="gate-box"/><circle cx="355" cy="92" r="26" class="${result===null?'signal-unknown':result?'signal-on':'signal-off'}"/><g text-anchor="middle" fill="currentColor" font-family="system-ui" font-size="20"><text x="54" y="55">${env.p?'1':'0'}</text><text x="54" y="147">${env.q?'1':'0'}</text><text x="222" y="99" font-size="19">${op}</text><text x="355" y="99">${result===null?'?':result?'1':'0'}</text><text x="22" y="22" font-size="17">p</text><text x="22" y="174" font-size="17">q</text></g></svg>`;}
function evidence(t){if(t.type==='table')return '';if(t.type==='circuit')return `<div class="evidence"><p class="eyebrow">REGELCIRCUIT</p>${defs(t)}<div class="circuit-builder-art"><svg viewBox="0 0 520 200" aria-hidden="true"><g stroke="currentColor" stroke-width="3" fill="none"><path d="M30 50H95M175 50H270V85H305M30 150H95M175 150H270V115H305M400 100H477"/><rect x="95" y="27" width="80" height="46" rx="7"/><rect x="95" y="127" width="80" height="46" rx="7"/><rect x="305" y="67" width="95" height="66" rx="7"/><circle cx="485" cy="100" r="16"/></g><g fill="currentColor" text-anchor="middle" font-family="system-ui" font-size="20"><text x="20" y="28">p</text><text x="20" y="128">q</text><text x="135" y="57">${answer[0]==='PASS'?'→':'NOT'}</text><text x="135" y="157">${answer[1]==='PASS'?'→':'NOT'}</text><text x="353" y="107">${answer[2]}</text></g></svg></div><p class="evidence-note">Test controleert je schakeling voor alle vier invoergevallen.</p></div>`;
 if(t.type==='difference')return `<div class="evidence comparison"><p class="eyebrow">TWEE REGELS</p><div class="comparison-rule"><small>Regel A</small><div class="formula">${escape(t.expr)}</div>${feedback?`<b>${truthValue(L.value(t.expr,answer))}</b>`:''}</div><div class="comparison-rule"><small>Regel B</small><div class="formula">${escape(t.other)}</div>${feedback?`<b>${truthValue(L.value(t.other,answer))}</b>`:''}</div><p class="evidence-note">Eén andere uitkomst weerlegt gelijkwaardigheid.</p></div>`;
 if(t.type==='counter')return `<div class="evidence"><p class="eyebrow">BREK DE CLAIM</p>${defs(t)}<div class="counter-rule"><span>Voorwaarde</span><b>W</b><span>Gevolg</span><b>V</b></div><p class="domain">Domein: ${t.domain.some(x=>x<0)?'gehele':'positieve gehele'} getallen</p><p class="evidence-note">Een geldig tegenvoorbeeld respecteert de voorwaarde en laat het gevolg falen.</p></div>`;
 if(t.type==='puzzle')return `<div class="evidence puzzle-evidence"><p class="eyebrow">HET MODULEDOSSIER</p>${t.rules.map((r,i)=>`<div class="witness"><span class="robot-mark">${['N','I','M'][i]}</span><span><strong>${t.ruleNames[i]}</strong><small>${['Ilias of Mei heeft haar.','Noor heeft haar niet.','Ilias heeft haar niet.'][i]}</small></span></div>`).join('')}</div>`;
 if(t.type==='predict')return `<div class="evidence ${t.visual==='monitor'?'rule-monitor':''}"><p class="eyebrow">${t.visual==='monitor'?'TWEE FEITEN · ÉÉN AFSPRAAK':t.visual==='gate'?'VOORSPEL HET SIGNAAL':'WAARHEIDSWAARDE'}</p>${facts(t.env,t.defs)}<div class="formula">${escape(t.expr)}</div>${t.visual==='gate'?gateSVG(t):''}${t.visual==='monitor'?'<p class="evidence-note">Beoordeel de afspraak. De feiten veranderen niet.</p>':''}</div>`;
 if(t.type==='classify')return `<div class="evidence"><p class="eyebrow">ALLE WAARHEIDSTOEKENNINGEN</p><div class="formula big">${escape(t.expr)}</div>${feedback?`<div class="truth-strip">${L.cases(L.variables(t.expr)).map(e=>`<span title="${escape(JSON.stringify(e))}">${truthValue(L.value(t.expr,e))}</span>`).join('')}</div>`:'<p class="evidence-note">Zoek of er ware én valse gevallen mogelijk zijn.</p>'}</div>`;
 return `<div class="evidence"><p class="eyebrow">${t.type==='build'?'BOUW DE BETEKENIS':'LEES PRECIES'}</p>${defs(t)}${t.stem?`<p class="stem">${escape(t.stem)}</p>`:`<div class="quiet-symbol">${C.districts[C.stops[t.skill].district].symbol}</div>`}<span class="evidence-line"></span></div>`;
}
function optionsHTML(t,locked){const disabled=locked?'disabled':'';return `<div class="choices ${t.type==='multi'?'multi-choices':''}">${t.options.map((o,i)=>button(`<span class="option-marker">${t.type==='multi'?(answer?.includes(o.id)?'✓':'○'):String.fromCharCode(65+i)}</span><span>${escape(o.label)}</span>`,'choice',`data-id="${o.id}" ${disabled} aria-pressed="${t.type==='multi'?answer?.includes(o.id):answer===o.id}"`,'choice')).join('')}</div>`;}
function builder(t,locked){const disabled=locked?'disabled':'';return `<div class="formula-work"><p class="eyebrow">JOUW REGEL</p><div class="build-preview formula">${escape(L.formatBuild(answer))}</div><div class="build-parts"><div><span class="field-label">Links</span>${button(answer.left,'build-var','data-key="left" '+disabled+' aria-label="Linker uitspraak wisselen"','part')}${button('¬','build-not',`data-key="leftNot" ${disabled} aria-pressed="${answer.leftNot}" aria-label="Linker deel ontkennen"`,'part negate')}</div><div><span class="field-label">Verbinding</span><div class="operator-palette">${(t.skill>=11?['∧','∨','⇒','⇔']:['∧','∨']).map(op=>button(op,'build-op',`data-id="${op}" ${disabled} aria-pressed="${answer.op===op}" aria-label="${{'∧':'EN','∨':'OF','⇒':'Als dan','⇔':'Als en slechts als'}[op]}"`,'part')).join('')}</div></div><div><span class="field-label">Rechts</span>${button(answer.right,'build-var','data-key="right" '+disabled+' aria-label="Rechter uitspraak wisselen"','part')}${button('¬','build-not',`data-key="rightNot" ${disabled} aria-pressed="${answer.rightNot}" aria-label="Rechter deel ontkennen"`,'part negate')}</div></div>${!t.requireInnerNegation?button('NIET rond het geheel','build-not',`data-key="outerNot" ${disabled} aria-pressed="${answer.outerNot}"`,'outer-negation'):''}<p class="interaction-note">Tik p of q om te wisselen. Tik ¬ om dat deel te ontkennen.</p></div>`;}
function tableWork(t,locked){const envs=L.cases(t.vars||L.variables(t.columns.map(c=>c.expr).join(''))),vars=Object.keys(envs[0]);return `<div class="table-work"><table class="truth-table"><thead><tr>${vars.map(v=>`<th scope="col">${v}</th>`).join('')}${t.columns.map(c=>`<th scope="col">${escape(c.label)}</th>`).join('')}</tr></thead><tbody>${envs.slice(tablePage*4,tablePage*4+4).map((env,i)=>`<tr ${feedback?.row===i+tablePage*4?'class="flagged"':''}>${vars.map(v=>`<td class="given">${truthValue(env[v])}</td>`).join('')}${t.columns.map((c,j)=>`<td>${button(answer[i+tablePage*4][j]===null?'·':truthValue(answer[i+tablePage*4][j]),'cell',`data-row="${i+tablePage*4}" data-col="${j}" ${locked?'disabled':''} aria-label="Rij ${i+tablePage*4+1}, ${escape(c.label)}: ${answer[i+tablePage*4][j]===null?'nog leeg':truthValue(answer[i+tablePage*4][j])}"`,'table-cell '+(answer[i+tablePage*4][j]===null?'empty':answer[i+tablePage*4][j]?'filled cell-true':'filled cell-false')+(feedback?.row===i+tablePage*4&&feedback?.column===j?' cell-error':''))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function workspace(t,locked){const disabled=locked?'disabled':'';if(t.type==='table')return tableWork(t,locked);if(t.type==='choice'||t.type==='multi')return optionsHTML(t,locked);if(t.type==='build')return builder(t,locked);if(t.type==='predict')return `<div class="predict-work"><p class="eyebrow">${screen==='review'?'ANTWOORD VAN JE PARTNER':'JOUW VOORSPELLING'}</p><div class="truth-choices">${[true,false].map(b=>button(`<strong>${truthValue(b)}</strong><span>${b?'Waar':'Vals'}</span>`,'truth',`data-value="${b}" ${disabled} aria-pressed="${answer===b}"`,'truth-answer')).join('')}</div><p class="interaction-note">${t.visual==='gate'?'W = signaal 1 · V = signaal 0':'Waar en vals zijn waarden van de formule.'}</p></div>`;
 if(t.type==='circuit')return `<div class="circuit-work"><p class="eyebrow">KIES DE POORTEN</p>${[0,1,2].map((i)=>`<div class="gate-choice"><span>${['Invoer p','Invoer q','Verbinding'][i]}</span><div>${(i<2?['PASS','NOT']:t.allowDerived?['AND','OR','NAND','NOR']:['AND','OR']).map(g=>button(g==='PASS'?'Doorlaten':g,'gate',`data-index="${i}" data-id="${g}" ${disabled} aria-pressed="${answer[i]===g}"`)).join('')}</div></div>`).join('')}</div>`;
 if(t.type==='difference')return `<div class="difference-work"><p class="eyebrow">MAAK EEN ONDERSCHEIDEND GEVAL</p><div class="case-controls">${Object.entries(answer).map(([v,b])=>button(`<span>${v}</span><strong>${truthValue(b)}</strong>`,'env',`data-id="${v}" ${disabled} aria-label="Waarheidswaarde van ${v} wisselen"`,'case-control')).join('')}</div><p class="interaction-note">Verander de invoer. Test daarna beide regels.</p></div>`;
 if(t.type==='counter')return `<div class="counter-work"><p class="eyebrow">KIES EEN TEGENVOORBEELD</p><div class="number-choices">${t.domain.map(n=>button(String(n).replace('-','−'),'number',`data-value="${n}" ${disabled} aria-pressed="${answer===n}"`)).join('')}</div>${feedback&&answer!==null?facts(t.environments[answer],t.defs):'<p class="interaction-note">Er kan meer dan één juiste keuze zijn.</p>'}</div>`;
 if(t.type==='classify')return `<div class="classify-work">${[['altijd','Altijd','Tautologie'],['soms','Soms','Contingent'],['nooit','Nooit','Contradictie']].map(([id,label,note])=>button(`<strong>${label}</strong><small>${note}</small>`,'classify',`data-id="${id}" ${disabled} aria-pressed="${answer===id}"`,'classification')).join('')}</div>`;
 if(t.type==='puzzle')return `<div class="puzzle-work"><p class="eyebrow">WIE PAST BIJ ALLE GEGEVENS?</p>${t.candidates.map(c=>button(`<span class="robot-mark">${c.label[0]}</span><strong>${c.label}</strong>`,'choice',`data-id="${c.id}" ${disabled} aria-pressed="${answer===c.id}"`,'robot-choice')).join('')}${feedback?`<p class="interaction-note">${feedback.correct?'Twee uitspraken zijn waar.':'Controleer de drie uitspraken voor jouw kandidaat.'}</p>`:''}</div>`;
 return '';
}
function play(){const t=taskNow();if(!t)return '<p>Deze ronde is afgerond.</p>';const locked=!!feedback?.correct||screen==='review',s=C.stops[t.skill],allRows=t.type==='table'?answer.length:0,filled=t.type==='table'?answer.flat().filter(x=>x!==null).length:0;return `<section style="--district:${C.districts[s.district].color}" class="play screen ${t.type==='table'?'is-table':''} ${screen==='review'?'is-review':''}"><header class="play-head">${button('←','route-back','aria-label="Terug naar leerroute"','back')}<div class="play-heading"><p class="eyebrow">${screen==='review'?'SPELER '+(player()==='A'?'B':'A')+' BEOORDEELT':modeName[run.mode]+' · '+playerLabel()} <span> / ${s.name}</span></p><h1>${escape(t.prompt)}</h1></div><div class="play-meta">${allRows>4?`<div class="table-pages">${button('p = W','table-page','data-id="0" aria-pressed="'+(tablePage===0)+'"')}${button('p = V','table-page','data-id="1" aria-pressed="'+(tablePage===1)+'"')}<small>${filled}/${allRows*t.columns.length} ingevuld</small></div>`:`<span class="question-count">${run.index+1}<small> / ${run.tasks.length}</small></span><div class="round-dots">${run.tasks.map((_,i)=>`<i class="${i<run.index?'done':i===run.index?'current':''}"></i>`).join('')}</div>`}</div></header><div class="play-body ${t.type==='table'?'table-body':''}">${evidence(t)}<div class="work-area">${workspace(t,locked)}</div></div><footer class="work-footer"><div class="feedback ${feedback?(feedback.correct?'correct':'incorrect'):''}" role="status" aria-live="polite">${screen==='review'?'Bekijk de keuze van je partner. Klopt het antwoord volgens jou?':feedback?`<strong>${feedback.correct?'✓ Gelukt.':'↳ Denk nog eens.'}</strong> ${escape(feedback.message)}`:instruction(t)}</div><div class="work-actions">${screen==='review'?button('Ik twijfel','peer','data-value="false"','secondary')+button('Ik keur goed','peer','data-value="true"','primary'):feedback?.correct?button(run.index+1===run.tasks.length?'Resultaat →':'Volgende →','next','','primary'):button('Hint','hint','','hint-btn')+button('Test','test','','primary')}</div></footer></section>`;}
function instruction(t){return escape(({choice:'Kies één antwoord en test je redenering.',multi:'Kies alle passende antwoorden en test.',predict:'Kies W of V vóór je test.',build:'Bouw je regel en test alle gevallen.',circuit:'Kies poorten en test alle gevallen.',table:'Tik een lege cel: · → W → V. Vul alles in.',difference:'Kies een invoer waarbij de regels verschillen.',counter:'Kies een getal dat de claim breekt.',classify:'Onderzoek de formule. Kies en test.',puzzle:'Test één kandidaat tegen de drie uitspraken.'})[t.type]);}
function hintView(){const t=taskNow();return `<section class="hint-screen screen"><div class="screen-nav">${button('← Opgave','back-play')}<span>Hulp bij halte ${t.skill+1}</span></div><div class="hint-content"><p class="eyebrow">EEN DUWTJE IN DE JUISTE RICHTING</p><h1>${escape(C.stops[t.skill].name)}</h1><p>${escape(t.type==='counter'&&t.defs?.p&&t.defs?.q?'Zoek een getal waarvoor “'+t.defs.p+'” waar is en “'+t.defs.q+'” vals. Dan geldt de voorwaarde, maar niet het gevolg.':t.hint)}</p><div class="hint-anchor">${escape(t.prompt)}</div>${button('Terug naar mijn antwoord →','back-play','','primary')}<small>Deze opdracht telt als oefenen met hulp.</small></div></section>`;}
function test(){const t=taskNow();if(screen==='review'||feedback?.correct)return;if(answer===null||t.type==='multi'&&answer.length===0||t.type==='table'&&answer.flat().includes(null)){feedback={correct:false,message:t.type==='table'?'Vul eerst alle cellen in, ook in de andere groep.':'Kies eerst een antwoord.',incomplete:true};if(t.type==='table'){tablePage=Math.floor(answer.findIndex(r=>r.includes(null))/4);}render();return;}
 const result=L.validate(t,answer);if(run.mode==='duo-learn'){pending={answer:structuredClone(answer),result};persist();go('review');return;}completeAttempt(result);
}
function completeAttempt(result){run.record=L.attempt(run.record,answer,result);feedback=result;pending=null;if(result.row!==undefined)tablePage=Math.floor(result.row/4);screen='play';persist();render();}
function next(skipped=false){if(!run)return;run.record.skipped=skipped;run.records.push(structuredClone(run.record));if(player()==='solo'){progress.records.push(structuredClone(run.record));progress.lastStop=taskNow().skill;}
 run.index++;if(run.index>=run.tasks.length){run.finishedAt=new Date().toISOString();persist();go('summary');}else{newTask();go('play');}}
function score(records){return records.reduce((n,r)=>n+(r.firstCorrect?10:r.eventuallyCorrect?5:0),0);}
function summary(){const r=run,st=L.stats(r.records),duo=r.mode==='duo-learn'||r.mode==='local';const a=r.records.filter(x=>x.player==='A'),b=r.records.filter(x=>x.player==='B');return `<section class="summary screen"><div class="screen-nav">${button('← Leerroute','finish-world')}<span>${modeName[r.mode]} · Resultaat</span></div><div class="summary-content"><div class="summary-seal">✓</div><p class="eyebrow">RONDE AFGEROND</p><h1>${duo&&r.mode==='local'?(score(a)===score(b)?'Gelijk gespeeld.':score(a)>score(b)?'Speler A wint.':'Speler B wint.'):'Je regels zijn scherper.'}</h1><p>${st.eventuallyCorrect} van ${st.total} opdrachten uiteindelijk juist.</p><div class="result-metrics"><div><strong>${st.firstCorrect}</strong><span>juist bij eerste poging</span></div><div><strong>${st.wrongAttempts}</strong><span>foute pogingen</span></div><div><strong>${st.hints}</strong><span>hints gebruikt</span></div></div>${duo?`<div class="duo-scores"><span>Speler A <b>${score(a)}</b> punten</span><span>Speler B <b>${score(b)}</b> punten</span></div>`:`<p class="summary-note">${L.mastered(r.records)?'Drie verschillende opdrachten en de transfer lukten zonder hint bij de eerste poging.':'Een fout is een nuttig testgeval. Oefen deze halte later nog eens.'}</p>`}<div class="summary-actions">${button('Resultaat exporteren','export','','secondary')}${button('Terug naar leerroute →','finish-world','','primary')}</div><small>${duo?'De twee spelers worden afzonderlijk gerapporteerd.':'Deze voortgang wordt voor je account op dit toestel bewaard.'}</small></div></section>`;}
function progressView(){const slice=C.stops.slice(progressPage*6,progressPage*6+6);return `<section class="progress-screen screen"><div class="screen-nav">${button('← Leerroute','world')}<span>Mijn voortgang · op dit toestel</span><div>${button('←','progress-page',`data-id="${Math.max(0,progressPage-1)}" aria-label="Vorige zes haltes"`)}<span>${progressPage+1}/3</span>${button('→','progress-page',`data-id="${Math.min(2,progressPage+1)}" aria-label="Volgende zes haltes"`)}</div></div><div class="progress-content"><h1>Wat lukt al zelfstandig?</h1><div class="progress-list">${slice.map(s=>{const st=L.stats(stopRecords(s.id));return button(`<span class="stop-marker">${s.id+1}</span><span><strong>${s.name}</strong><small>${statusText(s.id)} · ${st.firstCorrect} eerste antwoorden juist / ${st.total} aangeboden</small></span><span>→</span>`,'progress-stop',`data-id="${s.id}" data-status="${stopStatus(s.id)}"`,'progress-row');}).join('')}</div><p class="progress-note">“Zelfstandig gelukt” vraagt drie verschillende opdrachten juist bij de eerste poging zonder hint, met minstens één transfer. Dit is een oefenstatus.</p>${button('Alles exporteren','export-all','','secondary')}</div></section>`;}
function menu(){return `<section class="menu-screen screen"><div class="screen-nav">${button('← Terug','menu-return')}<span>Logicawereld · Menu</span></div><div class="menu-content"><div><p class="eyebrow">WAAR WIL JE HEEN?</p><h1>Propositielogica</h1><p>Leerroute, hulp en jouw werk.</p></div><div class="menu-actions">${button('<span>◎</span> Leerroute','world')}${run&&run.index<run.tasks.length?button('<span>▷</span> Oefening hervatten','resume'):''}${button('<span>↗</span> Mijn voortgang','progress')}${button('<span>▤</span> Oefenblad','worksheet')}${button('<span>♧</span> Werkvormen','modes')}${button('<span>∧</span> Poorten verdiepen','bonus')}${button('<span>□</span> Volledig scherm','fullscreen')}${button('<span>≈</span> Minder beweging: '+(progress.reducedMotion?'aan':'uit'),'motion',`aria-pressed="${progress.reducedMotion}"`)}${run&&run.index<run.tasks.length&&!feedback?.correct?button('<span>↷</span> Deze opdracht overslaan','skip'):''}<a class="menu-home" href="${escape($('homeLink').href)}" target="_top"><span>⌂</span> Naar leraarBob OS</a></div><p class="menu-note">Versie ${C.version} · ${storageOK?'Voortgang op dit toestel bewaard.':'De browser blokkeert opslag; exporteer je resultaat.'} ${feedback?.notice?escape(feedback.notice):''}</p></div></section>`;}
function exportCSV(records){const rows=[['speler','opdracht','halte','vaardigheid','eerste_poging_juist','uiteindelijk_juist','foute_pogingen','hints','pogingen','overgeslagen','foutcategorieen','eerste_antwoord','partner_beoordelingen']];records.forEach(r=>rows.push([r.player,r.taskId,r.skill+1,C.stops[r.skill]?.name,r.firstCorrect?1:0,r.eventuallyCorrect?1:0,r.wrongAttempts,r.hints,r.attempts,r.skipped?1:0,(r.categories||[]).join('|'),JSON.stringify(r.firstAnswer),JSON.stringify(r.peerReviews||[])]));const csv='\ufeff'+rows.map(row=>row.map(cell=>'"'+String(cell??'').replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Logicawereld-resultaten-'+new Date().toISOString().slice(0,10)+'.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function changed(){feedback=null;persist();render();}
$('app').addEventListener('click',async event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;const d=b.dataset,a=d.action;if(['choice','truth','build-var','build-not','build-op','cell','env','number','classify','gate'].includes(a)&&(screen==='review'||feedback?.correct))return;
 if(a==='district'){district=Number(d.id);selected=C.districts[district].stops[0];render();}
 else if(a==='select-stop'){selected=Number(d.id);render();}
 else if(a==='begin'){selected=0;district=0;go('modes');}
 else if(a==='world'||a==='route-back'){persist();go('world');}
 else if(a==='finish-world'){selected=run.selected;district=C.stops[selected].district;run=null;persist();go('world');}
 else if(a==='lesson'){lessonPage=0;go('lesson');}
 else if(a==='lesson-page'){lessonPage=Number(d.id);render();}
 else if(a==='modes'){if(!OS?.openModes(selected,b))go('modes');}
 else if(a==='practice'){if(run?.mode===launchMode&&run.selected===selected)go(pending?'review':run.index<run.tasks.length?'play':'summary');else start(launchMode);}
 else if(a==='purpose'){purpose=d.id;render();}
 else if(a==='worksheet')OS?.openWorksheet(selected);
 else if(a==='start')start(d.mode);
 else if(a==='bonus')go('bonus-intro');
 else if(a==='start-bonus')start('bonus');
 else if(a==='resume'){selected=run.selected;district=C.stops[selected].district;go(pending?'review':run.index<run.tasks.length?'play':'summary');}
 else if(a==='choice'){if(taskNow().type==='multi'){answer=answer.includes(d.id)?answer.filter(x=>x!==d.id):[...answer,d.id];}else answer=d.id;changed();}
 else if(a==='truth'){answer=d.value==='true';changed();}
 else if(a==='build-var'){answer[d.key]=answer[d.key]==='p'?'q':'p';changed();}
 else if(a==='build-not'){answer[d.key]=!answer[d.key];changed();}
 else if(a==='build-op'){answer.op=d.id;changed();}
 else if(a==='gate'){answer[Number(d.index)]=d.id;changed();}
 else if(a==='cell'){const r=Number(d.row),c=Number(d.col);answer[r][c]=answer[r][c]===null?true:answer[r][c]===true?false:null;changed();}
 else if(a==='table-page'){tablePage=Number(d.id);persist();render();}
 else if(a==='env'){answer[d.id]=!answer[d.id];changed();}
 else if(a==='number'){answer=Number(d.value);changed();}
 else if(a==='classify'){answer=d.id;changed();}
 else if(a==='test')test();
 else if(a==='next')next();
 else if(a==='peer'){const approval=d.value==='true',result=pending.result;run.record.peerReviews||=[];run.record.peerReviews.push({reviewer:player()==='A'?'B':'A',approved:approval,assessmentCorrect:approval===result.correct});const prefix=approval===result.correct?'Je partner zag het goed. ':approval?'Je partner keurde goed, maar ': 'Je partner twijfelde, maar ';completeAttempt({...result,message:prefix+result.message});}
 else if(a==='hint'){run.record.hints++;persist();go('hint');}
 else if(a==='back-play')go('play');
 else if(a==='progress'){progressPage=0;go('progress');}
 else if(a==='progress-page'){progressPage=Number(d.id);render();}
 else if(a==='progress-stop'){selected=Number(d.id);district=C.stops[selected].district;go('modes');}
 else if(a==='menu-return')go(menuReturn);
 else if(a==='motion'){progress.reducedMotion=!progress.reducedMotion;persist();render();}
 else if(a==='skip'){next(true);}
 else if(a==='fullscreen'){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{feedback={notice:'Volledig scherm is hier niet beschikbaar. Gebruik de optie in het browsermenu.'};render();}}
 else if(a==='export')exportCSV(run.records);
 else if(a==='export-all')exportCSV(progress.records);
});
for(const [id,where] of [['routeMenu','world'],['progressMenu','progress'],['toolsMenu','menu']])if($(id))$(id).onclick=()=>{if(where==='menu')menuReturn=screen;go(where);};
$('worldLink').onclick=()=>{persist();go('world');};$('menuBtn').onclick=()=>{menuReturn=screen;go('menu');};$('collapseBtn').onclick=()=>setCollapsed(true);$('restoreBtn').onclick=()=>setCollapsed(false);
addEventListener('keydown',e=>{if(e.key==='Escape'&&screen==='menu'){go(menuReturn);e.preventDefault();}});
let identityTurn=0,authWatched=false,authUnsubscribe;
addEventListener('pagehide',()=>{authUnsubscribe?.();ready=false;identityTurn++;});
async function init(){
 try{document.documentElement.dataset.mode=window!==parent?parent.document.documentElement.dataset.mode:localStorage.getItem('axioma-mode')||'light';}catch{}
 const turn=++identityTurn;let savedScreen;ready=false;run=null;answer=null;feedback=null;pending=null;screen='world';
 const auth=OS?.auth();if(OS?.context().embedded){document.body.classList.add('embedded');$('platformHeader').hidden=true;}
 if(auth){
  if(!authWatched){authWatched=true;authUnsubscribe=auth.onChange?.(v=>{if(v.pending){ready=false;identityTurn++;$('app').innerHTML='<p class="loading">Account controleren…</p>';return;}const id=v.account?.id||'guest';if(id!==owner||!ready)init();});}
  try{const v=await auth.ready();if(turn!==identityTurn)return;owner=v?.account?.id||'guest';}catch{if(turn!==identityTurn)return;$('app').innerHTML='<p class="loading">Je account kon niet worden gecontroleerd. Herlaad om opnieuw te proberen.</p>';return;}
 }
 owner=OS?.context().accountId||owner;
 launchMode=modeName[requestedMode]?requestedMode:'solo';
 try{
  progress=L.sanitizeProgress(JSON.parse(localStorage.getItem(progressKey())||'null'),C.tasks.map(t=>t.id));
  const rawStop=(params.get('stop')||'').replace('halte-',''),area=/^gebied-(\d+)$/.exec(rawStop),chosen=area?C.districts[Number(area[1])-1]?.stops[0]:Number(rawStop)-1;
  selected=rawStop&&Number.isInteger(chosen)&&C.stops[chosen]?chosen:Number(localStorage.getItem(resumeKey())??progress.lastStop);if(!C.stops[selected])selected=0;
  const saved=JSON.parse(localStorage.getItem(runKey())??localStorage.getItem(progressKey()+':run:'+launchMode)??localStorage.getItem(legacyRunKey())??'null');
  if(saved?.run&&Array.isArray(saved.run.tasks)&&saved.run.tasks.length&&saved.run.tasks.every(id=>C.tasks.some(t=>t.id===id))&&Number.isInteger(saved.run.selected)&&C.stops[saved.run.selected]&&saved.run.index>=0&&saved.run.index<=saved.run.tasks.length&&saved.run.mode===launchMode&&(!params.has('stop')||saved.run.selected===selected)){run=saved.run;answer=saved.answer;tablePage=saved.tablePage||0;feedback=saved.feedback;pending=saved.pending;savedScreen=saved.screen;if(!localStorage.getItem(runKey()))localStorage.setItem(runKey(),JSON.stringify(saved));}
 }catch{storageOK=false;progress={version:1,records:[],lastStop:0,reducedMotion:false};}
 selected=progress.lastStop;district=C.stops[selected].district;
 const raw=params.get('stop')||'';const area=/^gebied-(\d+)$/.exec(raw);const requested=area?C.districts[Number(area[1])-1]?.stops[0]+1:Number(raw.replace('halte-',''));
 if(Number.isInteger(requested)&&requested>=1&&requested<=18){selected=requested-1;district=C.stops[selected].district;}
 ready=true;
 if(params.get('view')==='worksheet'){OS?.openWorksheet(selected,true);return;}
 if(params.get('view')==='lesson'){lessonPage=0;screen='lesson';}
 else if(run&&(!requested||run.selected===selected)){selected=run.selected;district=C.stops[selected].district;screen=pending?'review':run.index>=run.tasks.length?'summary':['world','play','hint','lesson','progress'].includes(savedScreen)?savedScreen:'play';}
 else if(requested&&modeName[requestedMode]&&params.get('view')!=='world'){start(launchMode);return;}
 render();
}
window.Logicawereld=Object.freeze({version:C.version,exportResults:()=>exportCSV(progress.records),state:()=>({screen,selected,district,mode:run?.mode||launchMode,taskId:taskNow()?.id,owner,ready,progress:L.stats(progress.records)}),navigate:where=>{if(['world','progress','menu','resume'].includes(where)){if(where==='menu')menuReturn=screen;if(where==='resume'&&run)go(pending?'review':run.index<run.tasks.length?'play':'summary');else if(where!=='resume')go(where);}},worksheet:()=>OS?.openWorksheet(selected),integration:{gameId:'logicawereld',progressSource:'[data-platform-progress]',persistence:'local-account-scoped',liveClass:false,onlineDuo:false,worksheets:true,registryFile:'games.json'}});
init();
})();
