(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./logic.js'));else root.LogicaWorksheet=factory(root.Logic);})(typeof globalThis==='object'?globalThis:this,function(L){
 'use strict';
 const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const tf=v=>v?'W':'V';
 function select(content,{stop=0,scope='stop',count=5}={}){const selected=content.stops[stop]||content.stops[0];const pool=scope==='district'?content.districts[selected.district].stops.flatMap(i=>content.stops[i].tasks):selected.tasks;return pool.slice(0,Math.min(Math.max(1,Number(count)||5),pool.length));}
 function table(t,solved){const envs=L.cases(t.vars||L.variables(t.columns.map(c=>c.expr).join(''))),vars=Object.keys(envs[0]);return '<table><thead><tr>'+[...vars,...t.columns.map(c=>c.label)].map(v=>'<th>'+e(v)+'</th>').join('')+'</tr></thead><tbody>'+envs.map(env=>'<tr>'+vars.map(v=>'<td>'+tf(env[v])+'</td>').join('')+t.columns.map(c=>'<td>'+(solved?tf(L.value(c.expr,env)):'&nbsp;')+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
 function solution(t){if(t.type==='choice')return t.options.find(o=>o.id===t.correct).label;if(t.type==='multi')return t.options.filter(o=>t.correct.includes(o.id)).map(o=>o.label).join('; ');if(t.type==='predict')return tf(L.value(t.expr,t.env));if(t.type==='table')return table(t,true);if(t.type==='build'||t.type==='circuit')return t.requiredForm==='contraposition'?'¬q ⇒ ¬p':t.expr;if(t.type==='difference'){const vars=[...new Set([...L.variables(t.expr),...L.variables(t.other)])].sort();return L.cases(vars).filter(env=>L.validate(t,env).correct).map(env=>Object.entries(env).map(([v,b])=>v+' = '+tf(b)).join(', ')).join(' / ');}if(t.type==='counter')return t.domain.filter(n=>L.validate(t,n).correct).join(', ');if(t.type==='classify')return {altijd:'Tautologie',soms:'Contingent',nooit:'Contradictie'}[L.classify(t.expr)];if(t.type==='puzzle')return t.candidates.filter(c=>L.validate(t,c.id).correct).map(c=>c.label).join(', ');throw Error('Onbekend vraagtype');}
 function question(t){let html=t.stem?'<p class="stem">'+e(t.stem)+'</p>':'';if(t.defs&&t.type!=='puzzle')html+='<p class="defs">'+Object.entries(t.defs).map(([v,s])=>'<b>'+e(v)+'</b>: '+e(s)).join(' &nbsp; · &nbsp; ')+'</p>';
 if(t.type==='table')return html+table(t,false);
 if(t.type==='predict')html+='<p class="math">'+e(t.expr)+'</p><p>'+Object.entries(t.env).map(([v,b])=>e(v)+' = '+tf(b)).join(' &nbsp; · &nbsp; ')+'</p><p>□ Waar &emsp; □ Vals</p>';
 else if(['choice','multi'].includes(t.type))html+='<ul class="options">'+t.options.map(o=>'<li>□ '+e(o.label)+'</li>').join('')+'</ul>';
 else if(t.type==='difference')html+='<p class="math">A: '+e(t.expr)+' &emsp; B: '+e(t.other)+'</p><p>Geef een waarheidstoekenning waarbij de uitkomsten verschillen.</p><div class="answer-line"></div>';
 else if(t.type==='counter')html+='<p>Kies een tegenvoorbeeld uit: '+t.domain.map(e).join(', ')+'.</p><div class="answer-line"></div>';
 else if(t.type==='classify')html+='<p class="math">'+e(t.expr)+'</p><p>□ Tautologie &emsp; □ Contingent &emsp; □ Contradictie</p>';
 else if(t.type==='circuit')html+='<p>Teken een schakeling met '+(t.allowDerived?'AND, OR, NOT, NAND of NOR':'AND, OR en NOT')+'.</p><div class="drawing"></div>';
 else if(t.type==='build')html+='<p>Schrijf een passende formule'+(t.requireInnerNegation?' zonder negatie rond het geheel':'')+'.</p><div class="answer-line"></div>';
 else if(t.type==='puzzle')html+='<p>'+t.candidates.map(c=>'□ '+e(c.label)).join(' &emsp; ')+'</p><div class="answer-line"></div>';
 return html;
 }
 function render(content,options={}){const tasks=select(content,options),s=content.stops[options.stop||0],title=options.scope==='district'?content.districts[s.district].name:s.name;return '<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Propositielogica — '+e(title)+'</title><style>'+css+'</style></head><body><div class="tools"><button onclick="window.print()">Afdrukken / bewaren als PDF</button><span>'+tasks.length+' opdrachten'+(options.solutions?' · verbetersleutel op aparte pagina':'')+'</span></div><header><span>leraar<strong>Bob</strong> / Logicawereld</span><span>OEFENBLAD</span></header><h1>Propositielogica</h1><h2>'+e(title)+'</h2><p class="student">Naam: __________________________ &emsp; Klas: __________ &emsp; Datum: __________</p><ol class="questions">'+tasks.map(t=>'<li><h3>'+e(t.prompt)+'</h3>'+question(t)+'</li>').join('')+'</ol>'+(options.solutions?'<section class="solutions"><header>leraarBob / Verbetersleutel</header><h1>'+e(title)+'</h1><ol>'+tasks.map(t=>'<li><h3>'+e(t.prompt)+'</h3><div class="solution">'+(t.type==='table'?solution(t):e(solution(t)))+'</div><p>'+e(t.explanation)+'</p></li>').join('')+'</ol></section>':'')+'<footer>Logicawereld · '+e(content.version)+' · '+tasks.map(t=>e(t.id)).join(' / ')+'</footer></body></html>';}
 const css='*{box-sizing:border-box}body{font:15px/1.5 system-ui,sans-serif;color:#223c42;max-width:820px;margin:30px auto;padding:0 28px}header{display:flex;justify-content:space-between;border-bottom:1px solid #78958d;padding-bottom:12px}h1{font:36px Georgia,serif;margin:20px 0 6px}h2{font-size:20px;font-weight:500;margin:0 0 22px}h3{font-size:15px;line-height:1.4;margin:0 0 10px}p{margin:8px 0}.student{font-size:12px;padding-bottom:10px}.questions{padding-left:23px}.questions>li,.solutions li{padding:14px 0 18px 6px;break-inside:avoid;border-bottom:1px solid #d7ddd7}.options{padding:0;list-style:none}.options li{margin:7px 0}.math{font:24px Georgia,serif}.defs{font-size:13px;color:#455e5e}.answer-line{height:34px;border-bottom:1px solid #abb9b4}.drawing{height:85px;border:1px dashed #c2cec8;margin-top:15px}table{border-collapse:collapse;margin:12px 0;width:100%;table-layout:fixed}th,td{border:1px solid #abb9b4;text-align:center;padding:5px 12px;height:29px}th{background:#f0f3ee}.solutions{break-before:page;margin-top:40px}.solution{font-weight:600}.tools{padding:12px;background:#edf2e9;display:flex;align-items:center;gap:15px;margin-bottom:20px;font-size:13px}.tools button{padding:10px 14px;border:0;background:#24484b;color:white;border-radius:5px;cursor:pointer}footer{font-size:10px;color:#627574;margin-top:20px}@page{size:A4;margin:16mm}@media print{body{margin:0;padding:0;max-width:none;font-size:11pt}.tools{display:none}h1{font-size:26pt}h3{font-size:11pt}.questions>li{padding:10px 0 13px 5px}.solutions{margin-top:0}header{font-size:10pt}}';
 return Object.freeze({select,solution,question,render});
});
