/* Small isolated application: semantic actions, existing auth, versioned pilot storage. */
(function(){
'use strict';
const R=RechtenV2Runtime,M=RechtenV2Math,C=RechtenV2Workbench,W=RechtenWave,S=RechtenV2Shell,A=RechtenV2Areas,G=RechtenV2Boundary;
const legacySlice=new URLSearchParams(location.search).has('slice');
const app=document.getElementById('app'),esc=C.esc,copy=v=>JSON.parse(JSON.stringify(v));
const names={grenspas:'Grenspas',hellingrug:'Hellingrug',signaalstad:'Signaalstad'};
const descriptions={grenspas:'Open de doorgang met een x-gebied.',hellingrug:'Bouw een route tussen twee punten.',signaalstad:'Herstel een verkeerd aangesloten signaal.'};
const statusText={guest:'Bewaard op dit toestel',teacher:'Docentproef op dit toestel',saved:'Bewaard in je account',saving:'Wordt bewaard…',pending:'Op dit toestel bewaard; synchronisatie volgt',offline:'Op dit toestel bewaard; cloud niet bereikbaar',loading:'Je plek wordt opgehaald…',error:'Je account kon niet worden geladen',conflict:'Er zijn twee versies van je werk', 'account-change':'Je account is veranderd','storage-error':'Bewaren op dit toestel lukt niet','schema-error':'Deze bewaarde versie kan niet worden geopend'};
const blocked=new Set(['conflict','account-change','storage-error','schema-error','error']);
let state=R.initial(),ready=false,menuOpen=false,hintOpen=false,storeStatus='loading';
const store=RechtenV2Storage.create({initial:R.initial,onChange:update=>{
 storeStatus=update.status;
 if(!ready)return;
 if(storeStatus==='account-change'){state=R.initial();menuOpen=false;hintOpen=false}
 if(blocked.has(storeStatus))render();
 else {const el=document.getElementById('save-status');if(el)el.textContent=statusText[storeStatus]||storeStatus;}
}});
function save(){if(!store.writable)return;store.commit(state).catch(()=>{storeStatus='storage-error';render()})}
function apply(next,{paint=true,focus=null}={}){state=next;save();if(paint){render();if(focus)document.querySelector(focus)?.focus()}}
function icon(kind){const paths={menu:'M4 6h16M4 12h16M4 18h16',profile:'M8 7a4 4 0 1 0 8 0a4 4 0 1 0 -8 0M4 22c0-9 16-9 16 0',pause:'M8 5v14M16 5v14',undo:'M8 7H3V2M3 7c8-9 22 6 11 13'};return `<svg aria-hidden="true" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[kind]}"/></svg>`}
function viewOptions(mission=false){return {menuOpen,legacy:store.legacy,mission,account:store.account,status:statusText[storeStatus]||storeStatus}}
function header(){return S.header(state,viewOptions())}
function landscape(world,done){let content='';
 if(world==='grenspas')content=`<path d="M20 128L80 50l35 62 55-50 100 66"/><path d="M100 130h95M104 110v35M190 110v35"/><path class="world-state" d="${done?'M116 122H178':'M132 109v35M154 109v35'}"/>`;
 if(world==='hellingrug')content=`<path d="M12 144L106 35l60 75 32-46 94 80"/><path class="world-state" d="${done?'M60 126h60V85h60V43':'M60 126h60V85'}"/><circle cx="60" cy="126" r="6"/><circle cx="180" cy="43" r="6"/>`;
 if(world==='signaalstad')content=`<path d="M22 144V70h45v74M90 144V40h48v104M158 144V84h38v60M220 144V55h56v89"/><path class="world-state" d="${done?'M30 56h28l12-20 15 34 20-50 17 36H275':'M30 56h28l12-20 15 34M150 56h125'}"/>`;
 return `<svg viewBox="0 0 300 170" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round"><ellipse cx="150" cy="148" rx="144" ry="17" fill="#dce8df" stroke="none"/>${content}</svg>`;
}
function world(){return S.world(state,viewOptions())}
function area(){return S.area(state,viewOptions())}
function book(){return S.book(state,viewOptions())}
function profile(){return S.profile(state,viewOptions())}
function select(name,label,options,m){const v=m.values[name],disabled=!!m.feedback||!!m.locks[name];return `<label class="value-field">${esc(label)}<select name="${name}" aria-label="${esc(label)}" ${disabled?'disabled':''}>${options.map(([value,text])=>`<option value="${esc(value)}" ${String(v??'')===String(value)?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`}
function field(m,name,label){return C.field(name,label,m.values[name]??'',{disabled:!!m.feedback||!!m.locks[name]})}
function choices(m,name,options){return `<div class="control-row" role="group" aria-label="${name==='direction'?'Richting':name==='side'?'x-gebied':name==='closed'?'Grens inbegrepen':'Proefkeuze'}">${options.map(([value,label])=>C.choice(name,label,value,m.values[name]).replace('<button ',`<button ${m.feedback||m.locks[name]?'disabled ':''}`)).join('')}</div>`}
function symbol(m){return `<div class="symbol-row">${m.task.model.a.n?'<span aria-hidden="true">x</span>':''}${select('symbol','Teken',[['','Kies'],['<','<'],['>','>'],['=','='],['all','Alle x'],['none','Geen x']],m)}${m.task.model.a.n?field(m,'symbolBoundary','Notatiegrens'):''}</div>`}
function boundary(m){return G.render(m)}
function slope(m){const t=m.task,v=m.values,f=m.feedback,A=t.points.A,B=t.points.B,tableGiven=t.given_representations.includes('table');
 const title=m.phase==='deltas'?'Welke twee stappen brengen je naar het andere punt?':m.phase==='rate'?'Bouw de helling uit je twee verschillen.':`Voorspel de hoogte bij x = ${W.text(t.hidden.x)}.`;
 const coords=`<p class="given-points"><span>A (${W.html(A.x)}, ${W.html(A.y)})</span><span>B (${W.html(B.x)}, ${W.html(B.y)})</span></p>`;
 const dx=M.parse(v.dx),dy=M.parse(v.dy);let candidate=null;
 if(f&&m.phase==='rate'){const n=M.parse(v.numerator),d=M.parse(v.denominator);if(n&&d?.n){const a=W.div(n,d);candidate={kind:'affine',a,b:W.sub(A.y,W.mul(a,A.x))}}}
 const given=!tableGiven?C.graph({points:t.points,bounds:t.bounds,probes:f?.result.probes||[],candidate,delta:dx&&dy?{A:v.direction==='BA'?B:A,dx,dy}:null,caption:'Gegeven punten A en B; jouw gerichte stappen'}):C.table([A,B]);
 let tray='';if(m.phase==='deltas')tray=`${choices(m,'direction',[['AB','A → B'],['BA','B → A']])}<div class="control-row">${field(m,'dx','Δx')}${field(m,'dy','Δy')}</div>`;
 else if(m.phase==='rate')tray=`<p class="retained">${esc(v.direction==='BA'?'B → A':'A → B')}: Δx = ${esc(v.dx)}, Δy = ${esc(v.dy)}</p><div class="rate-builder"><span>Helling =</span>${C.fraction(v.numerator??'',v.denominator??'',!!f)}</div>`;
 else tray=`<p class="retained">Jouw helling = ${W.html(W.div(M.parse(v.numerator),M.parse(v.denominator)))}</p><p class="retained">Nieuwe invoer: x = ${W.html(t.hidden.x)}</p>${field(m,'hidden','Voorspelde y')}`;
 return {title,workspace:`<div class="evidence" data-representation="${tableGiven?'table':'graph'}">${given}${coords}</div><div class="answer-tray">${tray}</div>`};
}
function signal(m){const t=m.task,v=m.values,f=m.feedback;
 const title=m.phase==='probe'?'Welke proef laat zien waar het signaal afwijkt?':m.phase==='repair'?'Herstel de defecte koppeling.':`Test de herstelde verbinding bij x = ${W.text(t.hidden.x)}.`;
 const pins=(v.pins||['formula','graph']).slice(-2);
 const view=pin=>pin==='formula'?C.formula(t.model):pin==='table'?C.table(t.rows):C.graph({model:m.phase==='hidden'?t.model:t.faultModel,bounds:t.bounds,probes:f?.result.probes||[],candidate:m.phase==='repair'&&f&&M.parse(v.a)&&M.parse(v.b)?{kind:'affine',a:M.parse(v.a),b:M.parse(v.b)}:null,caption:m.phase==='hidden'?'Herstelde grafiek':'Ontvangen grafiek met defecte koppeling'});
 let tray='';if(m.phase==='probe')tray=`${choices(m,'probe',[['zero','x = 0'],['difference','Eén stap x']])}${field(m,'expected',v.probe==='difference'?'Verwachte Δy':'Verwachte y')}`;
 else if(m.phase==='repair')tray=`${select('feature','Defect',[['','Kies de koppeling'],['swapped','a en b verwisseld'],['sign','Teken omgekeerd'],['offset','Alles verschoven']],m)}${field(m,'a','Helling a')}${field(m,'b','y-afsnede b')}`;
 else tray=field(m,'hidden','Voorspelde y');
 return {title,extra:'signal-workspace',controls:`<div class="pin-controls" role="group" aria-label="Kies maximaal twee weergaven">${[['formula','Formule'],['table','Tabel'],['graph','Grafiek']].map(([key,label])=>`<button type="button" data-pin="${key}" aria-pressed="${pins.includes(key)}" ${f?'disabled':''}>${label}</button>`).join('')}</div>`,workspace:`<div class="evidence"><div class="representation-pair">${pins.map(p=>`<div data-representation="${p}"><span class="rep-name">${p==='formula'?'Gegeven formule':p==='table'?'Gegeven tabel':'Ontvangen grafiek'}</span>${view(p)}</div>`).join('')}</div></div><div class="answer-tray">${tray}</div>`};
}
function feedbackText(m){if(m.feedback){const r=m.feedback.result;return `${r.ok?'✓ ':r.kind==='interaction_error'?'':'↻ '}${esc(r.message)}${m.phase==='probe'&&r.expected?` Gegevens: ${esc(W.text(r.expected))}; grafiek: ${esc(W.text(r.actual))}.`:''}`;}if(hintOpen&&m.hints)return esc(m.task.hints[m.hints-1]);return m.hints>=5?'Probeer nu een nieuw geval zonder het voorbeeld.':'Leg je keuze vast om de proef te zien.'}
function mission(){const m=R.active(state);if(!m){state.screen='world';return world();}if(RechtenV2Lines.skills.includes(m.skill))return RechtenV2LinesView.render(m,S.header(state,viewOptions(true)));if(RechtenV2Hills.skills.includes(m.skill))return RechtenV2HillsView.render(m,S.header(state,viewOptions(true)));if(m.world==='puntenbaai')return RechtenV2PointsView.render(m,S.header(state,viewOptions(true)));if(m.world==='grenspas')return boundaryMission(m);let body;
 if(m.completed)body={title:'De doorgang is hersteld.',workspace:`<div class="evidence">${landscape(m.world,true)}</div><div class="world-reaction">${m.world==='grenspas'?'Het pad is open.':m.world==='hellingrug'?'De route sluit aan.':'Het signaal komt aan.'}<small>Je waarnemingen staan in je veldboek.</small><button type="button" data-restart="${m.world}">Opnieuw onderzoeken</button></div>`};
 else body=m.world==='grenspas'?boundary(m):m.world==='hellingrug'?slope(m):signal(m);
 const feedback=m.feedback;return `<form id="mission" class="mission-shell ${hintOpen?'hint-active':''}" data-world="${m.world}" data-phase="${m.phase}" novalidate><header class="mission-top"><button type="button" id="pause" aria-label="Pauzeer en ga naar de wereld">${icon('pause')}</button><span class="mission-name">${names[m.world]} · ${m.index+1} / ${m.world==='grenspas'?4:2}</span>${body.controls||''}<button type="button" id="hint" aria-label="Volgende hint" ${m.completed||m.feedback||m.hints>=5?'disabled':''}>? <span class="sr-only">Hint</span></button></header><h1 class="mission-question">${body.title}</h1><main class="workspace ${body.extra||''}">${body.workspace}</main><footer class="mission-footer"><button type="button" id="undo" aria-label="Maak laatste bewerking ongedaan" ${feedback||m.completed||!m.history.length?'disabled':''}>${icon('undo')}</button><div id="feedback" class="feedback ${feedback?feedback.result.ok?'success':'error':''}" role="status" aria-live="polite">${m.completed?'Ontdek je volgende plek.':feedbackText(m)}</div>${m.completed?'<button type="button" class="primary" data-screen="world">Naar de wereld →</button>':m.hints>=5&&!feedback?'<button type="button" class="primary" id="new-example">Nieuw geval →</button>':feedback?`<button type="button" class="primary" id="continue">${feedback.result.ok?'Verder →':'Herstel ↻'}</button>`:'<button type="submit" class="primary" id="commit">Leg vast →</button>'}</footer></form><section id="rotateGate"><h1>Draai je scherm</h1><p>Deze werktafel heeft liggend minstens 640 × 360 pixels nodig. Je werk blijft bewaard.</p><button data-screen="world">Terug naar de wereld</button></section>`;
}
function boundaryMission(m){
 const f=m.feedback,body=m.completed?null:G.render(m);
 const complete=`<section class="boundary-complete"><img src="assets/grenspas-island.webp" width="1536" height="1024" alt=""><h1>Je doorgang is open!</h1><p>Je vond de grens én het juiste gebied.</p><span class="proof-badge">${S.icon('check')} Oefening afgerond</span><button type="button" data-restart="grenspas">Opnieuw oefenen</button></section>`;
 return `<form id="mission" class="boundary-mission ${m.hintOpen?'hint-active':''}" data-world="grenspas" data-phase="${m.phase}" novalidate>${S.header(state,viewOptions(true))}<main class="boundary-workspace">${m.completed?complete:body.workspace}</main><footer class="boundary-footer"><button type="button" class="paper-pill" id="pause" aria-label="Pauzeer en ga naar Grenspas">${S.icon('back')}<span>Vorige</span></button><div class="feedback-bubble"><button type="button" class="hint-button" id="hint" aria-label="Volgende hint" ${m.completed||f||m.hints>=5?'disabled':''}>${S.icon('light',23)}</button><div id="feedback" class="feedback ${f?f.result.ok?'success':'error':''}" role="status" aria-live="polite">${m.completed?'Je werk is bewaard in Mijn voortgang.':feedbackText(m)}</div></div>${m.completed?'<button type="button" class="paint-button" data-screen="area">Naar Grenspas '+S.icon('arrow')+'</button>':m.hints>=5&&!f?'<button type="button" class="paint-button" id="new-example">Nieuw geval '+S.icon('arrow')+'</button>':f?`<button type="button" class="paint-button" id="continue">${f.result.ok?'Volgende':'Herstel'} ${S.icon(f.result.ok?'arrow':'undo')}</button>`:`<button type="submit" class="paint-button" id="commit">Controleer ${S.icon('arrow')}</button>`}</footer></form><section id="rotateGate"><span class="rotate-symbol" aria-hidden="true">↻</span><h1>Even je scherm draaien</h1><p>Liggend heb je alle ruimte om de grafiek te ontdekken. Je werk blijft bewaard.</p><button type="button" class="paper-pill" data-screen="area">Terug naar Grenspas</button></section>`;
}
function block(){const status=storeStatus;return `<main class="system-block"><h1>${esc(statusText[status]||'Je werk is gepauzeerd')}</h1><p>${status==='conflict'?'Beide versies blijven als kopie bewaard. Kies met welke versie je verder wilt.':status==='account-change'?'Open de plek van het huidige account.':'Bewaar een kopie en probeer opnieuw.'}</p><div>${status==='conflict'?'<button id="use-local">Verder met dit toestel</button><button id="use-remote">Andere versie openen</button>':'<button id="reload-account">Opnieuw openen</button>'}<button id="backup">Bewaar een kopie</button></div><a href="../trainer/">Huidige trainer</a></main>`}
function render(){hintOpen=state.screen==='mission'&&!!R.active(state)?.hintOpen;app.dataset.ready=String(ready);app.dataset.screen=S.route(state);app.dataset.reducedMotion=String(!!state.settings.reducedMotion);app.setAttribute('aria-busy',String(!ready));if(!ready)return;app.innerHTML=blocked.has(storeStatus)?block():state.screen==='mission'?mission():state.screen==='book'?book():state.screen==='profile'?profile():S.route(state)==='stop'?S.stop(state,viewOptions()):S.route(state)==='area'?area():world();
 app.querySelectorAll('.atlas-main,.atlas-footer,.journal-main,.stop-main,.boundary-workspace,.boundary-footer').forEach(el=>el.inert=menuOpen);
 const m=R.active(state);if(state.screen==='mission'&&m?.feedback){app.querySelectorAll('.answer-tray input').forEach(e=>e.readOnly=true);app.querySelectorAll('.answer-tray button,.answer-tray select').forEach(e=>e.disabled=true)}
}
function navigationState(source,screen,location={}){return A.locationState(source,screen,location)}
function reflectRoute(replace=false){if(legacySlice)return;const hash=A.hash(state);if(location.hash!==hash)history[replace?'replaceState':'pushState']({atlas:true},'',hash);}
function focusHeading(){const heading=document.querySelector('h1');heading?.setAttribute('tabindex','-1');heading?.focus({preventScroll:true})}
function goto(screen,location={}){menuOpen=false;hintOpen=false;apply(navigationState(state,screen,location));reflectRoute();if(location.returnNode)document.querySelector(`[data-node="${location.returnNode}"]`)?.focus({preventScroll:true});else focusHeading();}
function edit(name,value,paint=false){if(!store.writable)return;const m=R.active(state);if(!m||m.values[name]===value)return;apply(R.edit(state,name,value),{paint});if(!paint&&['root','boundary','dx','dy'].includes(name)&&state.screen==='mission'){const current=R.active(state),template=document.createElement('template');template.innerHTML=(current.world==='grenspas'?boundary(current):slope(current)).workspace;const nextEvidence=template.content.querySelector('.evidence');if(nextEvidence)document.querySelector('#mission .evidence')?.replaceWith(nextEvidence)}const undo=document.getElementById('undo');if(undo&&!m.feedback)undo.disabled=false;}
function exportBackup(){const data=JSON.stringify(store.exportBackup(),null,2),url=URL.createObjectURL(new Blob([data],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='lijnenwereld-kopie.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
app.addEventListener('input',e=>{const el=e.target;if(el.name){edit(el.name,el.type==='checkbox'?el.checked:el.value)}});
app.addEventListener('change',e=>{const el=e.target;if(el.name){edit(el.name,el.type==='checkbox'?el.checked:el.value);if(el.name==='probe')render()}if(el.id==='reduced-motion'){const next=copy(state);next.settings.reducedMotion=el.checked;apply(next)}});
app.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='mission'&&store.writable){hintOpen=false;apply(R.commit(state),{focus:'#continue'})}});
app.addEventListener('click',async e=>{
 const b=e.target.closest('button,a');if(!b||b.disabled)return;
 if(b.dataset.screen){e.preventDefault();goto(b.dataset.screen,{area:b.dataset.area,zone:b.dataset.zone,stop:b.dataset.stop,returnNode:b.dataset.returnNode});return}
 if(b.dataset.start||b.dataset.restart){hintOpen=false;menuOpen=false;const world=b.dataset.start||b.dataset.restart,skill=b.dataset.pointSkill||b.dataset.skill||'point',m=state.missions[world==='puntenbaai'||RechtenV2Hills.skills.includes(skill)?skill:world],restart=!!b.dataset.restart||((world==='puntenbaai'||RechtenV2Hills.skills.includes(skill))&&m?.completed)||(!legacySlice&&world==='grenspas'&&(m?.completed||m?.index>=2));apply(R.start(navigationState(state,'area',{area:world}),world,restart,skill),{focus:'#pause'});reflectRoute();return}
 if(b.hasAttribute('data-hint')){const next=R.hint(state);apply(next,{focus:R.active(next).hints>=5?'#new-example':'#hint'});return}
 if(b.dataset.linePoint){if(Date.now()<lineClickGuard)return;edit('selectedPoint',b.dataset.linePoint,true);document.querySelector('[data-line-picker]')?.focus({preventScroll:true});return}
 if(b.dataset.coordinateSlot){edit('selectedSlot',b.dataset.coordinateSlot,true);document.querySelector(`[data-coordinate-slot="${b.dataset.coordinateSlot}"]`)?.focus();return}
 if(b.dataset.coordinateToken){const m=R.active(state);apply(R.putCoordinate(state,m.values.selectedSlot||'y1',b.dataset.coordinateToken));document.querySelector(`[data-coordinate-slot="${R.active(state).values.selectedSlot}"]`)?.focus({preventScroll:true});return}
 if(b.dataset.choice){edit(b.dataset.choice,b.dataset.choice==='closed'?b.dataset.value==='true':b.dataset.value,true);document.querySelector(`[data-choice="${b.dataset.choice}"][data-value="${b.dataset.value}"]`)?.focus({preventScroll:true});return}
 if(b.dataset.step){const current=M.parse(R.active(state).values[b.dataset.step]||'0');if(current)edit(b.dataset.step,W.text(W.add(current,Number(b.dataset.amount))),true);return}
 if(b.dataset.pin){const pins=[...R.active(state).values.pins],i=pins.indexOf(b.dataset.pin);if(i<0){pins.push(b.dataset.pin);while(pins.length>2)pins.shift()}else if(pins.length>1)pins.splice(i,1);edit('pins',pins,true);document.querySelector(`[data-pin="${b.dataset.pin}"]`)?.focus();return}
 switch(b.id){
 case 'menu':menuOpen=!menuOpen;render();document.querySelector(menuOpen?'#main-menu button':'#menu')?.focus();break;
 case 'pause':goto(legacySlice?'world':'area',{area:R.active(state)?.world||'grenspas'});break;
 case 'hint':{const next=R.hint(state);apply(next,{focus:R.active(next).hints>=5?'#new-example':'#hint'});break;}
 case 'undo':apply(R.undo(state),{focus:'#undo'});break;
 case 'continue':{hintOpen=false;const m=R.active(state),finished=!legacySlice&&m.world==='grenspas'&&m.feedback?.result.ok&&m.feedback.next==='next-task';let next=R.advance(state);if(finished)next=navigationState(next,'area',{area:m.world});apply(next);reflectRoute();if(finished)focusHeading();else document.querySelector('[data-line-picker],[data-point-picker],.answer-tray input:not([readonly]),.answer-tray button:not(:disabled),.answer-tray select:not(:disabled),.hill-result input:not([readonly]),.coordinate-slot:not(:disabled),#hill-begin,#pause')?.focus({preventScroll:true});break;}
 case 'line-clear':apply(R.clearLinePoints(state),{focus:'[data-line-picker]'});break;
 case 'hill-begin':apply(R.beginHills(state),{focus:'[data-coordinate-slot="y1"]'});break;
 case 'new-example':hintOpen=false;apply(R.newAfterExample(state),{focus:'#pause'});break;
 case 'sync':await store.sync();render();break;
 case 'backup':exportBackup();break;
 case 'reload-account':ready=false;state=await store.start();ready=true;render();break;
 case 'use-local':case 'use-remote':state=await store.resolveConflict(b.id==='use-local'?'local':'remote');render();break;
 }
});
function placePoint(svg,e){if(!store.writable||menuOpen)return;const m=R.active(state);if(m?.world!=='puntenbaai'||m.skill!=='point_plot'||m.feedback||m.completed)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse());if(p.x<30||p.x>470||p.y<30||p.y>470)return;edit('point',{x:Math.max(-5,Math.min(5,Math.round((p.x-250)/40))),y:Math.max(-5,Math.min(5,Math.round((250-p.y)/40)))},true);document.querySelector('[data-point-picker]')?.focus({preventScroll:true})}
app.addEventListener('pointerup',e=>{const svg=e.target.closest('[data-point-picker]');if(svg&&e.isPrimary&&e.button===0)placePoint(svg,e)});
app.addEventListener('keydown',e=>{const svg=e.target.closest('[data-point-picker]'),delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,1],ArrowDown:[0,-1]}[e.key];if(!svg||!delta||!store.writable||menuOpen)return;e.preventDefault();const p=R.active(state).values.point||{x:0,y:0};edit('point',{x:Math.max(-5,Math.min(5,p.x+delta[0])),y:Math.max(-5,Math.min(5,p.y+delta[1]))},true);document.querySelector('[data-point-picker]')?.focus({preventScroll:true})});
let lineDrag=null,lineClickGuard=0;
function linePointAt(svg,e){const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse()),step=R.active(state).task.gridStep;if(p.x<30||p.x>470||p.y<30||p.y>470)return null;return {x:Math.max(-5,Math.min(5,Math.round((p.x-250)/40/step)*step)),y:Math.max(-5,Math.min(5,Math.round((250-p.y)/40/step)*step))}}
function placeLine(svg,name,e){if(!store.writable||menuOpen)return;const p=linePointAt(svg,e);if(p){apply(R.placeLinePoint(state,name,p));document.querySelector('[data-line-picker]')?.focus({preventScroll:true})}}
app.addEventListener('pointerdown',e=>{const marker=e.target.closest('[data-line-marker]'),token=e.target.closest('[data-line-point]');if(marker||token&&e.pointerType==='touch'&&!token.disabled){lineDrag={name:marker?.dataset.lineMarker||token.dataset.linePoint,x:e.clientX,y:e.clientY};(marker?.closest('svg')||token).setPointerCapture(e.pointerId)}});
app.addEventListener('pointerup',e=>{if(!e.isPrimary||e.button!==0)return;const drag=lineDrag;lineDrag=null;const svg=(drag?document.elementFromPoint(e.clientX,e.clientY):e.target)?.closest('[data-line-picker]');if(!svg)return;const moved=drag&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5;if(moved)lineClickGuard=Date.now()+300;placeLine(svg,drag?.name||R.active(state).values.selectedPoint||'A',e)});
app.addEventListener('pointercancel',()=>{lineDrag=null});
app.addEventListener('keydown',e=>{const svg=e.target.closest('[data-line-picker]'),delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,1],ArrowDown:[0,-1]}[e.key];if(!svg||!delta||!store.writable||menuOpen)return;e.preventDefault();const m=R.active(state),name=m.values.selectedPoint||'A',p=m.values['plot'+name]||{x:0,y:0},step=m.task.gridStep;apply(R.placeLinePoint(state,name,{x:Math.max(-5,Math.min(5,p.x+delta[0]*step)),y:Math.max(-5,Math.min(5,p.y+delta[1]*step))}));document.querySelector('[data-line-picker]')?.focus({preventScroll:true})});
app.addEventListener('dragstart',e=>{const point=e.target.closest('[data-line-point]');if(point&&!point.disabled&&store.writable){e.dataTransfer.setData('text/plain','line-point:'+point.dataset.linePoint);e.dataTransfer.effectAllowed='copy';return}const token=e.target.closest('[data-coordinate-token]');if(!token||token.disabled||!store.writable)return;e.dataTransfer.setData('text/plain',token.dataset.coordinateToken);e.dataTransfer.effectAllowed='copy'});
app.addEventListener('dragover',e=>{if(e.target.closest('[data-line-picker]')){e.preventDefault();e.dataTransfer.dropEffect='copy';return}const slot=e.target.closest('[data-coordinate-slot]');if(slot&&!slot.disabled){e.preventDefault();e.dataTransfer.dropEffect='copy'}});
app.addEventListener('drop',e=>{const svg=e.target.closest('[data-line-picker]'),data=e.dataTransfer.getData('text/plain');if(svg&&/^line-point:[AB]$/.test(data)){e.preventDefault();placeLine(svg,data.at(-1),e);return}const slot=e.target.closest('[data-coordinate-slot]');if(!slot||slot.disabled||!store.writable||menuOpen)return;e.preventDefault();apply(R.putCoordinate(state,slot.dataset.coordinateSlot,e.dataTransfer.getData('text/plain')));document.querySelector(`[data-coordinate-slot="${R.active(state).values.selectedSlot}"]`)?.focus({preventScroll:true})});
app.addEventListener('pointerup',e=>{const svg=e.target.closest('[data-axis-picker]');if(!svg||!store.writable)return;const m=R.active(state);if(m?.feedback)return;const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse()),{xMin,xMax}=m.task.bounds;const x=Math.max(xMin,Math.min(xMax,Math.round(xMin+(point.x-Number(svg.dataset.plotStart||42))/Number(svg.dataset.plotWidth||520)*(xMax-xMin))));edit('root',String(x),true)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menuOpen){menuOpen=false;render();document.getElementById('menu')?.focus();e.preventDefault()}else if(e.key==='Escape'&&hintOpen){const next=copy(state);R.active(next).hintOpen=false;apply(next,{focus:'#hint'});e.preventDefault()}});
window.addEventListener('online',()=>store.sync());
window.RechtenV2App=Object.freeze({snapshot:()=>copy(state)});
function stateForHash(source){if(!location.hash)return source;if(location.hash==='#oefenen')return R.start(source,source.active||'grenspas');return A.fromHash(source,location.hash)}
window.addEventListener('popstate',()=>{if(legacySlice||!store.writable)return;menuOpen=false;apply(stateForHash(state));focusHeading()});
(async()=>{state=await store.start();const slice=new URLSearchParams(location.search).get('slice');if(R.worlds.includes(slice)&&store.writable&&!(state.active===slice&&state.missions[slice])){state=R.start(state,slice);await store.commit(state)}else if(!legacySlice&&store.writable){state.settings.shell||={area:null};state=stateForHash(state);await store.commit(state)}ready=true;render();reflectRoute(true)})().catch(()=>{storeStatus='error';ready=true;render()});
})();
