(()=>{'use strict';const C=AlgebraCore,G=BattleGame,B=BattlePlayer,host=document.getElementById('work'),status=document.getElementById('status');let task,spec,states=[],operations=[],selected=null,locked=true;
 const math=tex=>`<span data-tex="${C.escapeHTML(tex)}"></span>`,eq=value=>math(C.latexEq(value,task.policy)),current=()=>states.at(-1),key=()=>`algebra-class-work:${spec.learner||'guest'}:${spec.match}:${spec.index}`;
 function save(){if(spec.projector)return;try{localStorage.setItem(key(),JSON.stringify({operations,value:document.getElementById('answer')?.value||''}));}catch{}}
 function solvedValue(){const e=current();if(!C.solvedEquation(e))return '';const q=e.l.t==='var'?e.r.q:e.l.q;return q.d===1?String(q.n):q.n+'/'+q.d;}
 function render(value=solvedValue()){
  host.className=spec.projector?'projector':'';
  host.innerHTML=`<section class="paper"><h1>Los de vergelijking op</h1><div class="given">${eq(task.start)}</div>${!spec.projector?`<div class="working-equation" aria-label="Jouw huidige vergelijking">${eq(current())}</div><details id="history"><summary>Jouw tussenstappen (${operations.length})</summary><ol>${states.slice(1).map((s,i)=>`<li>${math(C.operationLatex(operations[i].op,C.cloneExpr(operations[i].operand),task.policy))}<span>→</span>${eq(s)}</li>`).join('')}</ol></details>`:''}</section>${!spec.projector?`<form id="answerForm"><fieldset id="controls" ${locked?'disabled':''}><legend>Jouw antwoord</legend><div class="op-buttons" role="group" aria-label="Bewerk beide kanten">${[['+','+'],['-','−'],['*','×'],['/','÷']].map(([op,label])=>`<button type="button" data-op="${op}" aria-label="${{'+':'Tel op aan beide kanten','-':'Trek af aan beide kanten','*':'Vermenigvuldig beide kanten','/':'Deel beide kanten'}[op]}" aria-pressed="${selected===op}">${label}</button>`).join('')}<button type="button" id="undo" ${!operations.length?'disabled':''}>↶ Terug</button></div><div id="operands"></div><label class="answer-label" for="answer"><span>x =</span><input id="answer" type="text" inputmode="text" maxlength="40" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="Getal of breuk" value="${C.escapeHTML(value)}" aria-describedby="answerHelp"></label><p id="answerHelp">Je kunt ook meteen antwoorden. Gebruik bijvoorbeeld −2, 0,5 of 1/2.</p><p id="inputError" role="alert"></p><button class="primary" id="submit">Indienen →</button></fieldset></form>`:''}`;
  C.renderMathNodes(host);if(spec.projector)return;
  host.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>{selected=b.dataset.op;render(document.getElementById('answer').value);});
  if(selected){const values=C.candidateOperands(task,current(),selected),box=document.getElementById('operands');box.innerHTML='<p>Kies waarmee je beide kanten bewerkt:</p><div class="operand-grid">'+values.map((v,i)=>`<button type="button" data-value="${i}">${math(C.latexExpr(v,task.policy))}</button>`).join('')+'</div>';C.renderMathNodes(box);box.querySelectorAll('[data-value]').forEach((b,i)=>b.onclick=()=>{
   try{if(operations.length>=30)throw Error('Ga enkele stappen terug om je uitwerking korter te maken.');const next=C.applyEquation(current(),selected,values[i]);if(C.exprNodeCount(next.l)+C.exprNodeCount(next.r)>160)throw Error('Deze uitwerking wordt te groot. Ga een stap terug.');operations.push({op:selected,operand:C.cloneExpr(values[i])});states.push(next);selected=null;render();save();}catch(e){document.getElementById('inputError').textContent=e.message;}
  });}
  document.getElementById('undo').onclick=()=>{if(operations.length){operations.pop();states.pop();selected=null;render();save();}};
  document.getElementById('answer').oninput=save;
  document.getElementById('answerForm').onsubmit=e=>{e.preventDefault();if(locked)return;const value=document.getElementById('answer').value;if(!G.parse(value)){document.getElementById('inputError').textContent='Vul een getal of breuk in, bijvoorbeeld −2 of 1/2.';return;}save();B.submit({value});};
 }
 function start(value){spec=value;task=G.generate(spec);operations=[];states=[C.cloneEq(task.start)];selected=null;locked=false;status.textContent='';let answer='';if(!spec.projector)try{const stored=JSON.parse(localStorage.getItem(key())||'null');if(stored&&Array.isArray(stored.operations)&&stored.operations.length<=30){for(const op of stored.operations){if(!['+','-','*','/'].includes(op.op))throw Error();const operand=C.cloneExpr(op.operand),next=C.applyEquation(current(),op.op,operand);if(C.exprNodeCount(next.l)+C.exprNodeCount(next.r)>160)throw Error();states.push(next);operations.push({op:op.op,operand});}answer=typeof stored.value==='string'?stored.value:'';}}catch{states=[C.cloneEq(task.start)];operations=[];}render(answer);}
 B.connect({start,freeze(message){locked=true;document.getElementById('controls')?.setAttribute('disabled','');status.textContent=message;},retry(){start(spec);}});
 addEventListener('message',event=>{const d=event.data;if(event.source!==parent||event.origin!==location.origin||d?.type!=='vector-class-review'||d.match!==spec?.match||d.index!==spec?.index)return;locked=true;status.textContent='Bespreek welke bewerkingen de vergelijking oplossen.';host.className='review';host.innerHTML=`<section class="paper"><h1>Een mogelijke uitwerking</h1><ol class="review-steps"><li>${eq(task.start)}</li>${task.steps.map((step,i)=>`<li><small>${math(C.operationLatex(step.op,step.operand,task.policy))}</small>${eq(task.states[i+1])}</li>`).join('')}</ol><p>Een andere volgorde van geldige bewerkingen kan ook.</p></section>`;C.renderMathNodes(host);});
})();
