(function(root,factory){if(typeof module==='object')module.exports=factory(require('./core.js'),require('./stelsels/core.js'),require('./journey-core.js'));else root.BattleGame=factory(root.AlgebraCore,root.StelselsCore,root.AlgebraJourney)})(globalThis,(C,S,J)=>{
 const skills=[...C.TYPES.map(t=>({id:t.id,label:t.label,level:t.level,description:t.desc,topicId:'equations'})),{id:'S1',label:'Eenvoudige stelsels',level:'systems',topicId:'systems',description:'Twee vergelijkingen met x en y. Eén oplossing in gehele getallen.'}];
 const worlds=[{id:'equations',name:'Vergelijkingen',topicId:'equations',skills:C.TYPES.map(t=>t.id)},{id:'systems',name:'Stelsels',topicId:'systems',skills:['S1']}];
 const presets=(J?.stops||[]).map(t=>({id:t.id,label:t.title,skills:[...t.skills]}));
 function generate(s){if(!skills.some(t=>t.id===s.skill)||!Number.isInteger(s.seed)||s.seed<0||s.seed>4294967295||!Number.isInteger(s.variant)||s.variant<0||s.variant>3)throw Error('Ongeldige algebra-opgave');if(s.skill==='S1')return {...S.generate((s.seed+Math.imul(s.variant,0x9e3779b9))>>>0,'beginner','unique'),topic:'systems',skill:'S1',generatorVersion:1};return C.generateSeeded(s.skill,{allowFractions:s.fractions===true,allowDecimals:s.decimals===true,allowNegative:s.negative===true},s.variant,s.seed);}
 function parse(value){if(typeof value!=='string'||value.length>40)return null;const s=value.trim().replace('−','-').replace(',','.');if(!/^[+-]?\d+(?:\.\d{1,6})?(?:\s*\/\s*[+-]?\d+(?:\.\d{1,6})?)?$/.test(s))return null;const decimal=x=>{const [a,b='']=x.trim().split('.');return new C.Rat(Number(a+b),10**b.length);};try{const [n,d]=s.split('/');return d===undefined?decimal(n):decimal(n).div(decimal(d));}catch{return null;}}
 function validate(task,answer){if(task.topic==='systems'){const x=parse(answer?.x),y=parse(answer?.y);return {ok:!!x&&!!y&&task.solution.kind==='unique'&&x.eq(task.solution.x)&&y.eq(task.solution.y)};}const q=parse(answer?.value);return {ok:!!q&&q.eq(task.solution)};}
 return Object.freeze({id:'algebra',title:'Algebrawereld',rpc:'axioma_game_class',classFunction:'algebra-class',classReview:true,multiSelect:true,playerURL:'battle-player.html',skills,worlds,presets,mixedSkills:skills.map(s=>s.id),generate,parse,validate});
});
