(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.AlgebraWorld=api})(typeof window==='object'?window:globalThis,()=>{
'use strict';
// Stable topic IDs and explicit dependencies keep new branches independent of menu order.
const worlds=[
 {id:'balance',title:'Balansbaai',subject:'Eén bewerking',description:'Ontdek hoe je x alleen laat staan.',icon:'⚖',color:'blue',requires:[],engine:'equations',topics:[['A2','Optelling wegwerken','x + 4 = 9'],['A3','Aftrekking wegwerken','x − 3 = 5'],['A1','Een factor wegwerken','3x = 12'],['A4','Een deling wegwerken','x / 2 = 6']]},
 {id:'steps',title:'Vergelijkingenstad',subject:'Twee stappen plannen',description:'Kies een volgorde en voorspel wat er overblijft.',icon:'▥',color:'orange',requires:['eq-A4'],engine:'equations',topics:[['B1','Eerst de losse term','3x + 6 = 18'],['B2','Een aftrekking ongedaan maken','3x − 2 = 10']]},
 {id:'signs',title:'Tekenatelier',subject:'Tekens begrijpen',description:'Behoud mintekens bij termen en factoren.',icon:'−',color:'purple',requires:['eq-B2'],engine:'equations',topics:[['B3','Een negatieve x-term','10 − 2x = 4']]},
 {id:'brackets',title:'Haakjeswerkplaats',subject:'Haakjes en groepen',description:'Herken een groep; deel of werk distributief uit.',icon:'( )',color:'purple',requires:['eq-B3'],engine:'equations',topics:[['C1','Een volledige groep delen','2(x + 3) = 14'],['C2','Uitwerken met een minteken','3(x − 2) = 12'],['D1','Een factor binnen de groep','2(3x + 1) = 14'],['D3','Binnen en buiten de groep','2(3x − 1) + 4 = 14']]},
 {id:'fractions',title:'Breukenbrug',subject:'Breuken en delingsstructuur',description:'Zie welke termen door de noemer gedeeld worden.',icon:'½',color:'teal',requires:['eq-D3'],engine:'equations',topics:[['B4','Alleen x in de breuk','x / 2 + 3 = 7'],['B5','Een breuk en een aftrekking','x / 3 − 2 = 4'],['D2','Een volledige teller delen','(2x + 4) / 3 = 6']]},
 {id:'both',title:'Overkant',subject:'x aan beide leden',description:'Verzamel x-termen en vergelijk geldige routes.',icon:'⇄',color:'teal',requires:['eq-D2'],engine:'equations',topics:[['E3','Een losse term rechts','3x = x + 8'],['E2','Een losse term links','3x − 4 = x'],['E1','Routes vergelijken','4x + 6 = 2x + 10']]},
 {id:'powers',title:'Machtenberg',subject:'Machten & letters',description:'Bouw verder met exponenten en eentermen.',icon:'x²',color:'green',requires:[],engine:'operations',topics:[['power-power','Macht van een macht','(x²)³'],['power-product','Machten vermenigvuldigen','x² · x³'],['power-quotient','Machten delen','x⁵ / x²'],['power-monomial','Macht van een eenterm','(2x²)³'],['power-negative','Negatieve machten','x⁻²'],['power-mixed','Machten combineren','x³ · x² / x']]},
 {id:'roots',title:'Wortelwoud',subject:'Vierkantswortels',description:'Vind kwadraten en vereenvoudig wortels.',icon:'√',color:'teal',requires:[],engine:'operations',topics:[['square-factor','Een kwadraatfactor vinden','12 = 4 · 3'],['root-simplify','Een wortel vereenvoudigen','√12'],['root-product','Wortels vermenigvuldigen','√2 · √8'],['root-quotient','Wortels delen','√18 / √2'],['root-fraction','Wortel van een breuk','√(9 / 16)'],['root-power','Wortels en machten','√(3²)'],['root-letters','Wortels met letters','√(x⁴)'],['root-sum','Gelijke wortels optellen','2√3 + 4√3'],['root-sum-mixed','Vereenvoudigen en optellen','√12 + √27']]},
 {id:'scientific',title:'Getallensterren',subject:'Wetenschappelijke schrijfwijze',description:'Schrijf heel grote en heel kleine getallen korter.',icon:'10ⁿ',color:'purple',requires:[],engine:'operations',topics:[['scientific','Schrijven met machten van tien','3500 = 3,5 · 10³']]},
 {id:'systems',title:'Kruispunt',subject:'Stelsels',description:'Onderzoek twee vergelijkingen tegelijk.',icon:'╳',color:'orange',requires:['eq-E1'],engine:'systems',topics:[['graphic','Grafisch oplossen','Twee rechten, één gezamenlijk punt'],['substitution','Substitutie','Maak vrij en vul in'],['combination','Combinatie','Maak één onbekende weg'],['unique','Eén oplossing','Twee rechten kruisen elkaar'],['none','Geen oplossing','Twee evenwijdige rechten'],['infinite','Oneindig veel oplossingen','Twee keer dezelfde rechte']]}
].map(w=>({...w,topics:w.topics.map(([skill,title,example],index)=>({id:(w.engine==='equations'?'eq-':w.engine==='operations'?'op-':'sys-')+skill,skill,title,example,world:w.id,engine:w.engine,requires:index?[(w.engine==='equations'?'eq-':w.engine==='operations'?'op-':'sys-')+w.topics[index-1][0]]:w.requires}))}));
worlds.find(w=>w.id==='systems').topics.find(t=>t.id==='sys-unique').requires=['eq-E1'];
const topics=worlds.flatMap(w=>w.topics),GOAL=3,REWARD=30;
const topic=id=>topics.find(t=>t.id===id),world=id=>worlds.find(w=>w.id===id);
function normalize(raw){const out={topics:{}};for(const t of topics){const r=raw?.topics?.[t.id];if(!r)continue;const answers=[...new Set((Array.isArray(r.answers)?r.answers:[]).filter(s=>typeof s==='string'&&s.length<=1000))].slice(0,GOAL);const evidence=Array.isArray(r.evidence)?r.evidence.slice(0,5).map(e=>({kind:String(e.kind||'solve'),goal:String(e.goal||'').slice(0,180),supported:!!e.supported,errors:Math.max(0,Number(e.errors)||0),done:e.done===true})):[];const finished=evidence.length===5&&evidence.every(e=>e.done);const rewarded=(answers.length===GOAL||finished)&&r.rewarded===true;out.topics[t.id]={answers,rewarded,xp:rewarded?REWARD:0,...(evidence.length?{evidence,finished}:{})};}return out;}
function merge(...records){const out={topics:{}};for(const raw of records)Object.assign(out.topics,normalize(raw).topics);return out;}
function complete(progress,id,legacy=[]){const r=normalize(progress).topics[id];return !!r?.finished||r?.answers.length===GOAL||legacy.includes(id);}
// Accessibility is independent of practice, completion, grade and profile metadata.
function unlocked(progress,id,legacy=[]){return !!topic(id);}
function record(progress,id,answer,legacy=[]){const next=normalize(progress),t=topic(id);if(!t||!unlocked(next,id,legacy)||typeof answer!=='string'||!answer||answer.length>1000)return {progress:next,xp:0};const r=next.topics[id]||(next.topics[id]={answers:[],rewarded:false,xp:0});if(!r.answers.includes(answer)&&r.answers.length<GOAL)r.answers.push(answer);let xp=0;if(r.answers.length===GOAL&&!r.rewarded){r.rewarded=true;r.xp=REWARD;xp=REWARD;}return {progress:next,xp};}
function recordMission(progress,id,evidence,legacy=[]){const next=normalize(progress),t=topic(id);if(!t||!unlocked(next,id,legacy)||!Array.isArray(evidence)||evidence.length!==5||evidence.some(e=>!e.done))return {progress:next,xp:0};const old=next.topics[id]||{answers:[],rewarded:false,xp:0};next.topics[id]={...old,evidence,finished:true,rewarded:true,xp:REWARD};return {progress:normalize(next),xp:old.rewarded?0:REWARD};}
function platformProgress(progress){const p=normalize(progress),tracked=topics.filter(t=>t.engine!=='operations');return {completed:tracked.filter(t=>p.topics[t.id]?.finished).map(t=>t.id),total:tracked.length};}
function xp(progress){return Object.values(normalize(progress).topics).filter(t=>t.rewarded).length*REWARD;}
return Object.freeze({worlds,topics,topic,world,normalize,merge,complete,unlocked,record,recordMission,platformProgress,xp,GOAL,REWARD});
});
