(function(){
'use strict';
const J=window.RechtenJourney;
// Visual reactions only: learning state and rewards remain owned by the trainer.
const shown=new WeakMap();
const drawing=path=>`<svg viewBox="0 0 60 60" aria-hidden="true"><path d="${path}" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const landscape=`<svg class="journey-land" viewBox="0 0 800 450" preserveAspectRatio="none" aria-hidden="true"><path d="M-20 110Q120 15 260 110T530 100T850 55M-20 135Q120 40 260 135T530 125T850 80M-20 365Q160 255 310 355T850 330"/><path class="river" d="M515-20C375 90 635 170 470 265S545 390 465 490"/><path d="M70 240l20-42 20 42m13 8 15-32 15 32M670 200l20-42 20 42"/></svg>`;
const stateLabel=s=>s.review?'↻ Herhaling gepland':s.strong?'✓ Stevig':!s.open?'◇ Later':s.introduced?'In ontwikkeling':'Beschikbaar';
window.RechtenJourneyUI={render(root,{state,unlocked,ready,phase,order,requirements,labels,busy,onSelect,onRegion,onAtlas,onRecommend,onStart,onResume,onStop}){
 const j=J.data(state),a=j.active,rec=J.recommend(state,unlocked,ready,order),r=J.regions.find(r=>r.id===j.region)||J.regions[0];
 const view=j.view,selected=view==='atlas'?rec.place:r.places.find(p=>p.id===j.selected)||r.places[0];
 const stats=p=>J.status(state,p,unlocked,phase),s=stats(selected),resume=a||busy,round=(state.routeStep||0)+1;
 const proof=J.skills.filter(k=>j.proof[k]),needs=J.missing(state,ready),completed=J.places.filter(p=>j.visits[p.id]).length;
 const last=j.last,newSkills=last?.newSkills||[],lastName=last?.mode==='camp'?'Gemengd herhalen':last?.mode==='challenge'?'Onderwerptoets':J.places.find(p=>p.id===last?.place)?.name||'Oefenronde';
 const previous=shown.get(j),seen=previous?.round===state.routeStep?previous.views:new Set(),reactionKey=`${state.routeStep}:${view}:${view==='area'?j.region:''}`;
 const react=!!last&&!seen.has(reactionKey);if(last){seen.add(reactionKey);shown.set(j,{round:state.routeStep,views:seen})}
 const activeName=a?.mode==='challenge'?'Onderwerptoets':a?.mode==='camp'?'Gemengd herhalen':J.places.find(p=>p.id===a?.place)?.name||'Je lopende oefenronde';
 const recommended=selected.id===rec.place.id;
 const skillLabel=k=>({point:'Coördinaten lezen',point_plot:'Een punt plaatsen',slope_from_two_points:'Helling uit twee punten'})[k]||labels[k]?.label||k;
 const focus=view==='area'?selected.name:resume?activeName:(skillLabel(rec.skill)||selected.name);
 const intro=view==='area'?selected.story:resume?'Je antwoorden staan klaar. Ga verder met dezelfde opgave.':rec.reason;
 const focusSkills=selected.skills.map(k=>`<li><span>${labels[k].label}</span><small>${!unlocked.includes(k)?'Nog niet beschikbaar':!state.skills[k].intro?'Nieuwe stap':ready(state,k)?'Voldoende voorbereid':state.skills[k].seen<4?'Nog aan het opbouwen':'Verder oefenen'}</small></li>`).join('');
 const missing=[...new Set(selected.skills.flatMap(k=>(requirements[k]||[]).filter(dep=>!ready(state,dep))))];
 const action=resume?'<button class="primary" data-primary data-resume>Hervat opdracht →</button>':s.open?`<button class="primary" data-primary ${view==='atlas'?'data-next-round':`data-start="discover"${recommended?' data-next-round':''}`}>${state.routeStep?'Start volgende ronde':'Start eerste ronde'} →</button>`:'<button class="primary" data-primary data-recommend>Ga naar beschikbare stap →</button>';
 const result=last?`<details class="journey-result ${react?'result-arrived':''}"><summary><span class="journey-result-star" aria-hidden="true">★</span><span><strong>Ronde ${state.routeStep} afgerond</strong><small>${last.independent}/${last.answered} zelfstandig gelukt</small></span></summary><div><p>${lastName}</p>${last.practice?.length?'<p>Wat nog hulp vroeg, komt later terug. Je afgeronde ronde blijft staan.</p>':''}${newSkills.length?`<p>Nieuw beschikbaar: ${newSkills.map(k=>labels[k]?.label||k).join(' · ')}</p>`:''}</div></details>`:'';
 const details=`<aside class="journey-details"><div class="journey-detail-main"><span class="journey-context">${resume?'Verder waar je was':`Ronde ${round} · ${recommended?'aanbevolen':'jouw keuze'}`}</span><h3>${focus}</h3><p>${intro}</p>${resume&&view==='area'?`<p class="journey-focus">Lopende ronde: <strong>${activeName}</strong></p>`:''}${view==='area'&&recommended&&!resume&&rec.skill?`<p class="journey-focus">Deze ronde: <strong>${skillLabel(rec.skill)}</strong></p>`:''}${!s.open&&!resume?`<p class="journey-preparation">Bereid eerst ${missing.map(k=>labels[k]?.label||k).join(' en ')||'de eerdere leerdoelen'} voor.</p>`:''}${action}<p class="journey-small">${resume?`${state.session.answered} van 12 opgaven beantwoord.`:'12 opgaven · nieuwe varianten en herhaling'}</p>${resume?'<button class="journey-text-button" data-stop-round>Ronde stoppen en opnieuw kiezen</button><p class="journey-small">Je behaalde resultaten blijven bewaard. De onafgewerkte opgave stopt.</p>':''}${view==='atlas'?'<button class="journey-text-button" data-recommend>Bekijk de aanbevolen deelkaart →</button>':!recommended&&s.open&&!resume?'<button class="journey-text-button" data-recommend>Terug naar de aanbevolen stap →</button>':''}</div><div class="journey-detail-extra">${result}<details class="journey-goals"><summary>${view==='atlas'?'Over dit leerdoel':'Vaardigheden en voorbereiding'}</summary><ul>${focusSkills}</ul></details><p class="journey-status">${stateLabel(s)}${s.completed?' · ★ Ronde afgerond':''}</p></div></aside>`;
 function badges(done,isNew){return `${done?'<span class="journey-earned" aria-label="Ronde afgerond">★</span>':''}${isNew?'<small class="journey-new-label">Nieuw beschikbaar</small>':''}`}
 function placeButton(p,i){const t=stats(p),pos=r.places.length===4?[[23,28],[74,28],[23,71],[74,71]]:r.places.length===2?[[28,60],[73,37]]:[[20,64],[49,30],[79,65]],isNew=p.skills.some(k=>newSkills.includes(k)),justDone=last?.place===p.id&&last.mode!=='camp';return `<button class="journey-place ${p.id===selected.id?'selected':''} ${t.open?'':'later'} ${p.id===rec.place.id?'recommended':''} ${react&&justDone?'just-completed':''} ${react&&isNew?'just-unlocked':''}" style="left:${pos[i][0]}%;top:${pos[i][1]}%" data-place="${p.id}" aria-pressed="${p.id===selected.id}"><span class="journey-landmark">${drawing(p.icon)}${badges(t.completed,false)}</span><strong>${p.name}</strong><small>${p.id===rec.place.id?'→ Volgende stap':stateLabel(t)}</small>${isNew?'<small class="journey-new-label">Nieuw beschikbaar</small>':''}</button>`}
 const map=view==='atlas'?`<section class="journey-map" aria-label="Hoofdkaart Rechten">${landscape}<p class="journey-map-note">Kies een onderwerp</p>${J.regions.map(region=>{const ss=region.places.map(stats),done=ss.filter(s=>s.completed).length,strong=ss.filter(s=>s.strong).length,open=ss.some(s=>s.open),recommended=rec.place.region===region.id,isNew=region.places.some(p=>p.skills.some(k=>newSkills.includes(k))),justDone=region.places.some(p=>p.id===last?.place)&&last.mode!=='camp';return `<button class="journey-place ${open?'':'later'} ${recommended?'recommended':''} ${react&&justDone?'just-completed':''} ${react&&isNew?'just-unlocked':''}" style="left:${region.at[0]}%;top:${region.at[1]}%" data-region="${region.id}"><span class="journey-landmark">${drawing(region.places[0].icon)}${badges(done,false)}</span><strong>${region.name}</strong><small>${recommended?'→ Volgende stap':strong===ss.length?'✓ Stevig':open?'Beschikbaar':'◇ Later'}</small>${done?`<small>${done}/${ss.length} plaatsen geoefend</small>`:''}${isNew?'<small class="journey-new-label">Nieuw beschikbaar</small>':''}</button>`}).join('')}<span class="journey-map-key">★ Ronde afgerond · ✓ Stevig · ↻ Herhaling</span></section>`:`<section class="journey-map journey-area" aria-label="Deelkaart ${r.name}">${landscape}<p class="journey-map-note">Selecteer een leerdoel</p>${r.places.map(placeButton).join('')}<span class="journey-map-key">★ Ronde afgerond · ✓ Stevig · ↻ Herhaling</span></section>`;
 const header=`<div class="journey-heading"><div><span>${view==='atlas'?'Hoofdkaart':'Rechten / deelkaart'}</span><h2 tabindex="-1">${view==='atlas'?'Rechten':r.name}</h2></div>${view==='area'?'<button data-atlas>← Hoofdkaart</button>':`<span class="journey-overview">★ ${completed}/14 stopplaatsen geoefend</span>`}</div>`;
 const footer=`<div class="journey-footer"><span>Andere activiteiten</span><button data-start="camp" ${resume?'disabled':''}>Gemengd herhalen</button>${view==='area'&&r.id==='points'?`<button data-start="challenge" ${resume||needs.length?'disabled':''}>Onderwerptoets · ${proof.length}/5</button><span class="journey-test-hint">${needs.length?'Beschikbaar zodra de vijf leerdoelen voorbereid zijn.':'Hulp mag; zelfstandig bewijs telt.'}</span>`:''}</div>`;
 root.innerHTML=`<div class="journey-content">${header}<div class="journey-body">${map}${details}</div>${footer}</div>`;
 root.querySelector('[data-resume]')?.addEventListener('click',onResume);
 root.querySelector('[data-stop-round]')?.addEventListener('click',onStop);
 root.querySelector('[data-atlas]')?.addEventListener('click',onAtlas);
 root.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>onRegion(b.dataset.region));
 root.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>onSelect(b.dataset.place));
 root.querySelector('[data-next-round]:not([data-start])')?.addEventListener('click',()=>onStart(rec.place.id,'discover'));
 root.querySelectorAll('[data-recommend]').forEach(b=>b.onclick=onRecommend);
 root.querySelectorAll('[data-start]').forEach(b=>{b.disabled=!!resume||b.dataset.start==='challenge'&&!!needs.length;b.onclick=()=>onStart(selected.id,b.dataset.start)});
}};
})();
