(function(){
'use strict';
const J=window.RechtenJourney;
const drawing=path=>`<svg viewBox="0 0 60 60" aria-hidden="true"><path d="${path}" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const landscape=`<svg class="journey-land" viewBox="0 0 800 450" preserveAspectRatio="none" aria-hidden="true"><path d="M-20 110Q120 15 260 110T530 100T850 55M-20 135Q120 40 260 135T530 125T850 80M-20 365Q160 255 310 355T850 330"/><path class="river" d="M515-20C375 90 635 170 470 265S545 390 465 490"/><path d="M70 240l20-42 20 42m13 8 15-32 15 32M670 200l20-42 20 42"/></svg>`;
const stateLabel=s=>s.review?'↻ Herhaling gepland':s.strong?'✓ Stevig':!s.open?'◇ Later':s.introduced?'In ontwikkeling':'Beschikbaar';
window.RechtenJourneyUI={render(root,{state,unlocked,ready,phase,order,requirements,labels,busy,onSelect,onRegion,onAtlas,onRecommend,onStart,onResume,onClose}){
 const j=J.data(state),a=j.active,rec=J.recommend(state,unlocked,ready,order),r=J.regions.find(r=>r.id===j.region)||J.regions[0];
 const selected=r.places.find(p=>p.id===j.selected)||r.places[0],view=j.view,stats=p=>J.status(state,p,unlocked,phase),s=stats(selected);
 const proof=J.skills.filter(k=>j.proof[k]),needs=J.missing(state,ready);
 const resume=a||busy;
 const round=(state.routeStep||0)+1;
 const completed=J.places.filter(p=>j.visits[p.id]).length;
 const activeName=a?.mode==='challenge'?'Onderwerptoets':a?.mode==='camp'?'Gemengd herhalen':J.places.find(p=>p.id===a?.place)?.name;
 const recent=j.last?`<div class="journey-result" role="status"><strong>★ ${j.last.mode==='camp'?'Gemengde ronde':j.last.mode==='challenge'?'Onderwerptoets':J.places.find(p=>p.id===j.last.place)?.name||'Oefenronde'} afgerond</strong><p>${j.last.independent} van ${j.last.answered} opgaven zelfstandig gelukt.${j.last.practice?.length?' We oefenen '+j.last.practice.slice(0,2).map(k=>labels[k]?.label||k).join(' en ')+' later opnieuw.':''}</p>${j.last.newSkills?.length?`<p class="journey-new">Nieuw beschikbaar: ${j.last.newSkills.map(k=>labels[k]?.label||k).join(' · ')}</p>`:''}</div>`:'';
 const recommendation=`<div class="journey-recommend"><div><span>${resume?'Verder waar je was':`Volgende ronde · ronde ${round}`}</span><strong>${resume?(activeName||'Je lopende oefenronde'):(labels[rec.skill]?.label||rec.place.name)}</strong><p>${resume?'Hervat dezelfde opgave, met je eerdere antwoorden.':rec.reason}</p></div><div class="journey-recommend-actions">${resume?'<button class="primary" data-resume>Hervat opdracht →</button>':`<button class="primary" data-next-round>Start volgende ronde →</button><button data-recommend>Bekijk leerdoel op de kaart</button>`}</div></div>`;
 const header=`<div class="journey-heading"><div><span>${view==='atlas'?'Hoofdkaart':'Rechten / deelkaart'}</span><h2 tabindex="-1">${view==='atlas'?'Rechten':r.name}</h2></div>${view==='area'?'<button data-atlas>← Hoofdkaart</button>':''}${resume?'<button data-close aria-label="Hervat je oefening">Hervat →</button>':''}</div>`;
 function placeButton(p,i){const t=stats(p),pos=r.places.length===4?[[23,28],[74,28],[23,73],[74,73]]:r.places.length===2?[[28,60],[73,37]]:[[20,66],[49,31],[79,67]];return `<button class="journey-place ${p.id===selected.id?'selected':''} ${t.open?'':'later'} ${p.id===rec.place.id?'recommended':''}" style="left:${pos[i][0]}%;top:${pos[i][1]}%" data-place="${p.id}" aria-pressed="${p.id===selected.id}">${drawing(p.icon)}<strong>${p.name}</strong><small>${stateLabel(t)}</small>${t.completed?'<small class="journey-earned">★ Ronde afgerond</small>':''}${p.id===rec.place.id?'<small class="journey-direction">← Aanbevolen</small>':''}</button>`}
 const atlas=`<div class="journey-body"><section class="journey-map" aria-label="Hoofdkaart Rechten">${landscape}<p class="journey-map-note">Kies een onderwerp</p>${J.regions.map(region=>{const ss=region.places.map(stats),done=ss.filter(s=>s.completed).length,strong=ss.filter(s=>s.strong).length,open=ss.some(s=>s.open),recommended=rec.place.region===region.id;return `<button class="journey-place ${open?'':'later'} ${recommended?'recommended':''}" style="left:${region.at[0]}%;top:${region.at[1]}%" data-region="${region.id}">${drawing(region.places[0].icon)}<strong>${region.name}</strong><small>${strong===ss.length?'✓ Stevig':open?'Beschikbaar':'◇ Later'}</small>${done?`<small class="journey-earned">★ ${done}/${ss.length} plaatsen geoefend</small>`:''}${recommended?'<small class="journey-direction">← Jouw volgende stap</small>':''}</button>`}).join('')}<span class="journey-map-key">★ Ronde afgerond · ✓ Stevig · ↻ Herhaling</span></section><aside class="journey-details"><span>Je leerroute</span><h3>Stap voor stap verder</h3><p>Open een onderwerp om de leerdoelen te bekijken. De aanbevolen stap past bij je eerdere antwoorden.</p><p><strong>${completed} van 14 stopplaatsen</strong> met een afgeronde ronde.</p><p>Een ster blijft staan. Herhaling uit eerdere onderwerpen komt ook in nieuwe rondes terug.</p><button data-start="camp">Gemengd herhalen</button></aside></div>`;
 const missing=[...new Set(selected.skills.flatMap(k=>(requirements[k]||[]).filter(dep=>!ready(state,dep))))];
 const details=`<aside class="journey-details"><span>Leerdoel</span><h3>${selected.name}</h3><p>${selected.story}</p><p class="journey-goals">${selected.skills.map(k=>`${phase(k)==='stevig'?'✓':unlocked.includes(k)?'•':'◇'} ${labels[k].label}<small class="journey-skill-state">${!unlocked.includes(k)?'Nog niet beschikbaar':!state.skills[k].intro?'Nieuwe stap':ready(state,k)?'Voldoende voorbereid':state.skills[k].seen<4?'Nog aan het opbouwen':'Verder oefenen met nieuwe opgaven'}</small>`).join('<br>')}</p><p class="journey-status">${stateLabel(s)}${s.completed?' · ★ Eerder een ronde afgerond':''}</p>${resume?'<p>Je lopende ronde blijft bewaard. Rond die eerst af.</p><button class="primary" data-resume>Hervat opdracht →</button>':s.open?`<button class="primary" data-start="discover">${s.completed?'Start volgende ronde':s.introduced?'Verder oefenen':'Start oefenronde'} →</button>`:`<p>Bereid eerst ${missing.map(k=>labels[k]?.label||k).join(' en ')||'de eerdere leerdoelen'} voor.</p><button data-recommend>Bekijk je volgende stap →</button>`}<p class="journey-small">12 opgaven met uitleg, variatie en herhaling. Pauzeren kan tussendoor.</p></aside>`;
 const area=`<div class="journey-body"><section class="journey-map journey-area" aria-label="Deelkaart ${r.name}">${landscape}<p class="journey-map-note">Selecteer een leerdoel</p>${r.places.map(placeButton).join('')}<span class="journey-map-key">★ Ronde afgerond · ✓ Stevig · ↻ Herhaling</span></section>${details}</div><div class="journey-footer"><button data-start="camp" ${resume?'disabled':''}>Gemengd herhalen</button>${r.id==='points'?`<div><strong>Onderwerptoets · ${proof.length}/5 doelen</strong><span>${needs.length?'Oefen eerst: '+needs.map(k=>labels[k].label).join(', '):'Punten, verschillen en helling. Hulp mag; zelfstandig bewijs telt.'}</span></div><button data-start="challenge" ${resume||needs.length?'disabled':''}>${proof.length?'Opnieuw toetsen':'Start onderwerptoets'}</button>`:'<p>Je herhaalt ook eerdere onderwerpen. Je hoeft deze deelkaart niet volledig af te werken om elders verder te kunnen.</p>'}</div>`;
 root.innerHTML=`<div class="journey-content">${header}${recommendation}${recent}${view==='atlas'?atlas:area}</div>`;
 root.querySelectorAll('[data-close],[data-resume]').forEach(b=>b.onclick=onResume);
 root.querySelector('[data-atlas]')?.addEventListener('click',onAtlas);
 root.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>onRegion(b.dataset.region));
 root.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>onSelect(b.dataset.place));
 root.querySelector('[data-next-round]')?.addEventListener('click',()=>onStart(rec.place.id,'discover'));
 root.querySelectorAll('[data-recommend]').forEach(b=>b.onclick=onRecommend);
 root.querySelectorAll('[data-start]').forEach(b=>{b.disabled=!!resume;b.onclick=()=>onStart(selected.id,b.dataset.start);if(b.dataset.start==='challenge')b.disabled=!!resume||!!needs.length});
}};
})();
