/* Touch-first controls; no editable elements or native keyboard in exercises. */
(function(root){
'use strict';const C=root.RechtenWave,H=C.html;
const labels={ys:'Kies twee y-coördinaten voor de teller',xs:'Kies twee x-coördinaten voor de noemer',dy:'Bereken Δy',dx:'Bereken Δx',a:'Bereken a = Δy / Δx',point:'Kies een punt om b te berekenen',subY:'Plaats de y-coördinaat links',subX:'Plaats de x-coördinaat bij a',ax:'Bereken a · x',b:'Bereken b = y − ax',formulaA:'Vul de helling in je formule in',formulaB:'Vul de constante term in je formule in',verifyA:'Controleer punt A: bereken de uitvoer',verifyB:'Controleer punt B: bereken de uitvoer',classify:'Welke rechte bepalen deze punten?',property:'Welke eigenschap hoort hierbij?',axis:'Welke coördinaat blijft vast?',constant:'Vul de vaste waarde in',function:'Is deze rechte een functie y = f(x)?',behavior:'Wat gebeurt er als x toeneemt?'};
const point=(name,p)=>`${name}(${H(p.x)}; ${H(p.y)})`;
function graph(p){const xy=v=>100+18*C.num(v),yy=v=>100-18*C.num(v);let s='<svg viewBox="0 0 200 200" role="img" aria-label="Rechte op een rooster van min vijf tot vijf">';for(let i=-5;i<=5;i++)s+=`<path d="M${100+18*i} 10V190 M10 ${100+18*i}H190" stroke="${i?'#dbe5df':'#59747a'}" fill="none"/>`;s+='<text x="181" y="96" font-size="10">x</text><text x="104" y="15" font-size="10">y</text><text x="103" y="112" font-size="9">0</text><text x="180" y="112" font-size="9">5</text><text x="103" y="25" font-size="9">5</text>';const m=p.model;s+='<defs><clipPath id="wave-clip"><rect x="10" y="10" width="180" height="180"/></clipPath></defs>';if(m.kind==='vertical')s+=`<path d="M${xy(m.c)} 10V190" stroke="#4c8fd8" stroke-width="3"/>`;if(m.kind==='affine')s+=`<path d="M10 ${yy(C.add(C.mul(m.a,-5),m.b))}L190 ${yy(C.add(C.mul(m.a,5),m.b))}" clip-path="url(#wave-clip)" stroke="#4c8fd8" stroke-width="3"/>`;for(const name of ['A','B']){const a=p[name];s+=`<circle cx="${xy(a.x)}" cy="${yy(a.y)}" r="3" fill="#245f54"/><text x="${Math.min(181,xy(a.x)+5)}" y="${Math.max(12,yy(a.y)-6)}" font-size="11">${name}</text>`}return s+'</svg>'}
function context(t,w,stage){const p=t.params,m=p.model,v=w.values,A=p[v.point||'A'];let title=['intercept_from_point','equation_from_point_slope'].includes(t.skill)?`${point('A',p.A)} · <span class="wave-a">a = ${H(m.a)}</span>`:`${point('A',p.A)} · ${point('B',p.B)}`;
 if(t.skill==='line_behavior'&&p.representation==='slope')title=`a = ${H(m.a)}`;
 let line='';const diff=axis=>{const tokens=v[axis==='y'?'ys':'xs']||w.tokens;return tokens.map(k=>H(p[k][axis])).join(' − ')||'□ − □'};
 if(['ys','xs','dy','dx','a'].includes(stage)){const y=v.ys||[],x=v.xs||[];line=`<span class="wave-a">a = <span class="frac"><span>${stage==='ys'?diff('y'):y.map(k=>H(p[k].y)).join(' − ')||'□ − □'}</span><span>${stage==='xs'?diff('x'):x.map(k=>H(p[k].x)).join(' − ')||'□ − □'}</span></span></span><small>Δy: ${y.length===2?y[1]+'→'+y[0]:'…'} · Δx: ${x.length===2?x[1]+'→'+x[0]:w.tokens.length===2&&stage==='xs'?w.tokens[1]+'→'+w.tokens[0]:'…'}</small>`;if(v.dy&&v.dx)line+=`<small>Δy = ${H(v.dy)} · Δx = ${H(v.dx)}</small>`}
 else if(['subY','subX','ax','b'].includes(stage))line=`<span class="wave-a">a = ${H(m.a)}</span><br>${v.subY?H(A.y):'□'} = ${H(m.a)} · ${v.subX?`(${H(A.x)})`:'□'} + <span class="wave-b">b</span>${v.ax?`<small>${H(A.y)} = ${H(v.ax)} + b</small>`:''}`;
 else if(['formulaA','formulaB'].includes(stage))line=`<span class="wave-a">a = ${H(m.a)}</span> · <span class="wave-b">b = ${H(m.b)}</span><br>y = ${v.formulaA?H(v.formulaA):'□'}x + □`;
 else if(stage.startsWith('verify')){const P=p[stage==='verifyB'?'B':'A'];line=`${C.formula(m.a,m.b)}<small>y = ${H(m.a)} · (${H(P.x)}) + (${H(m.b)})<br>Gegeven y = ${H(P.y)}</small>`}
 else if(stage==='point')line=`<span class="wave-a">a = ${H(v.a)}</span>`;
 else if(stage==='constant')line=(v.axis||'□')+' = □';
 else if(stage==='function')line=m.kind==='vertical'?`x = ${H(m.c)}`:C.formula(m.a,m.b);
 return `<div class="wave-context"><div class="wave-givens">${title}</div>${line?`<div class="wave-equation">${line}</div>`:p.representation==='graph'?`<div class="wave-graph">${graph(p)}</div>`:''}</div>`;
}
function explanation(skill){const descriptions={slope_from_two_points:['a = <span class="frac"><span>yB − yA</span><span>xB − xA</span></span>','Kies eerst beide y-coördinaten, daarna beide x-coördinaten. B − A en A − B mogen allebei, als teller en noemer dezelfde richting hebben.'],line_behavior:['x neemt toe → kijk naar y','Positieve a: stijgend. Negatieve a: dalend. a = 0: constant. De volgorde van A en B verandert dit niet.'],special_lines:['Gelijke y · gelijke x · identieke punten','Gelijke y: horizontaal, a = 0, y = b, functie. Gelijke x bij verschillende punten: verticaal, Δx = 0, x = c, geen functie. Identiek: geen unieke rechte.'],intercept_from_point:['y = ax + b → b = y − ax','Plaats x en y uit het punt. Bereken eerst ax, trek dit van y af. Als x = 0, is b direct gelijk aan y. Controleer het oorspronkelijke punt.'],equation_from_point_slope:['a + punt → b → formule','Bereken b = y − ax. Vul a en b in y = ax + b in en controleer het oorspronkelijke punt.'],equation_from_two_points:['punten → a → punt → b → formule','Bepaal a en kies zelf A of B voor b. Bouw je formule en controleer beide oorspronkelijke punten. Een juiste a blijft staan als je b verbetert.']};const [big,sub]=descriptions[skill];return {title:C.catalog[skill].label,visual:graph({A:{x:C.q(-1),y:C.q(0)},B:{x:C.q(1),y:C.q(2)},model:{kind:'affine',a:C.q(1),b:C.q(1)}}),big,sub}}
function mount(t,{visual,answers,question,status,footer,onChange,onDone,onNext,dev=false}){
 const w=t.work||(t.work=C.fresh(t)),stage=C.stages(t)[w.index]||'done';question.textContent=w.done?'Controle afgerond':labels[stage];visual.innerHTML=context(t,w,stage);answers.className='answers wave-controls';answers.replaceChildren();footer.replaceChildren();
 const button=(label,action,where=answers)=>{const b=document.createElement('button');b.type='button';b.innerHTML=label;b.onclick=action;where.append(b);return b};
 function redraw(){onChange();mount(t,{visual,answers,question,status,footer,onChange,onDone,onNext,dev})}
 function submit(value){const result=C.submit(t,w,value);status.className='status '+(result.ok?'good':'bad');status.textContent=result.ok?'Stap klopt.':result.message;if(w.done){onDone();status.textContent=w.errors.length||w.help?'Hersteld met hulp. Je correcte deelstappen zijn bewaard.':'Goed gecontroleerd.'}redraw()}
 if(w.done){const m=t.params.model;answers.innerHTML=`<div class="wave-result">${m.kind==='identical'?'Identieke punten bepalen geen unieke rechte.':m.kind==='vertical'?`x = ${H(m.c)}<small>Δx = 0 · geen functie y = f(x)</small>`:t.skill==='line_behavior'?`${C.expected(t,w,'behavior')}<small>Als x toeneemt, ${m.a.n>0?'neemt y toe':m.a.n<0?'neemt y af':'blijft y gelijk'}.</small>`:`${C.formula(m.a,m.b)}<small>${t.skill==='slope_from_two_points'?'a = '+H(m.a):'De oorspronkelijke punten voldoen.'}</small>`}</div>`;button(dev?'Nieuwe variant':'Verder →',onNext,footer);return}
 if(['ys','xs'].includes(stage)){const axis=stage==='ys'?'y':'x';for(const name of ['A','B']){const b=button(`${name}: ${H(t.params[name][axis])}`,()=>{if(w.tokens.length<2){w.tokens.push(name);redraw()}});b.disabled=w.tokens.includes(name)}button('Wis keuze',()=>{w.tokens=[];redraw()});button('Controleer',()=>submit(w.tokens.slice()),footer).disabled=w.tokens.length!==2}
 else if(stage==='point'){for(const name of ['A','B'])button(point(name,t.params[name]),()=>submit(name))}
 else if(stage==='subY'||stage==='subX'){const A=t.params[w.values.point||'A'];for(const axis of ['x','y'])button(`${axis} = ${H(A[axis])}`,()=>submit(axis));if(stage==='subY'&&C.eq(A.x,0))button('x = 0: b = y',()=>{w.values.subY='y';w.values.subX='x';w.values.ax=C.q(0);w.index=C.stages(t).indexOf('b');redraw()})}
 else if(['behavior','classify','property','axis','function'].includes(stage)){const options={behavior:[['stijgend','stijgend'],['dalend','dalend'],['constant','constant']],classify:[['horizontaal','horizontaal'],['verticaal','verticaal'],['identiek','geen unieke rechte']],property:[['a0','a = 0'],['dx0','Δx = 0'],['dy1','Δy = 1']],axis:[['x','x = c'],['y','y = b']],function:[['functie','functie'],['geen functie','geen functie']]};for(const [value,label] of options[stage])button(label,()=>submit(value))}
 else {const output=document.createElement('div');output.className='wave-entry';output.innerHTML=`${['a','formulaA'].includes(stage)?'a':stage==='b'||stage==='formulaB'?'b':stage==='dx'?'Δx':stage==='dy'?'Δy':'waarde'} = <span class="frac"><span class="${w.part===0?'active':''}">${w.entry[0]||'□'}</span><span class="${w.part===1?'active':''}">${w.entry[1]||'□'}</span></span>`;visual.querySelector('.wave-context').append(output);const keys=['7','8','9','teller','noemer','4','5','6','±','⌫','1','2','3','0','wis'];answers.classList.add('wave-keypad');for(const key of keys)button(key,()=>{if(key==='teller'){w.part=0;w.replace=true}else if(key==='noemer'){w.part=1;w.replace=true}else if(key==='wis'){w.entry=['','1'];w.part=0;w.replace=false}else if(key==='⌫')w.entry[w.part]=w.entry[w.part].slice(0,-1);else if(key==='±')w.entry[w.part]=w.entry[w.part].startsWith('-')?w.entry[w.part].slice(1):'-'+w.entry[w.part];else if(w.entry[w.part].length<5)w.entry[w.part]=w.replace?key:w.entry[w.part]+key;if(/^\d$/.test(key))w.replace=false;redraw()});button('Controleer',()=>{const value=C.parse(w.entry.join('/'));if(!value){status.textContent='Vul teller en een noemer ongelijk aan nul in.';return}submit(value)},footer)}
 button('Terug',()=>{C.undo(w);redraw()},footer).disabled=!w.history.length;
}
root.RechtenWaveUI={mount,explanation,graph};
})(globalThis);
