'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const R=require('../games/rechten/trainer-v2/mission-runtime.js'),P=require('../games/rechten/trainer-v2/points-core.js'),V=require('../games/rechten/trainer-v2/components/points-view.js'),A=require('../games/rechten/trainer-v2/content/area-maps.js'),S=require('../games/rechten/trainer-v2/components/shell-view.js'),W=require('../games/rechten/trainer/wave-core.js');
const answer=m=>m.skill==='point'?['answer',String(m.task.options.findIndex(p=>W.eq(p.x,m.task.target.x)&&W.eq(p.y,m.task.target.y)))]:['point',{x:W.num(m.task.target.x),y:W.num(m.task.target.y)}];
const solve=s=>R.advance(R.commit(R.edit(s,...answer(R.active(s)))));
test('both existing skill IDs open separate resumable six-task missions with exact point validation',()=>{
 let s=R.initial();for(const skill of P.skills){s=R.start(s,'puntenbaai',false,skill);const targets=[];for(let i=0;i<P.count;i++){const m=R.active(s);assert.equal(m.task.skill_id,skill);targets.push([W.num(m.task.target.x),W.num(m.task.target.y)]);const before=JSON.stringify(s);const committed=R.commit(R.edit(s,...answer(m)));assert.equal(JSON.stringify(s),before);assert(R.active(committed).feedback.result.ok);assert.deepEqual(R.commit(committed),committed);assert.deepEqual(R.edit(committed,...answer(m)),committed);const loaded=JSON.parse(JSON.stringify(committed));assert.deepEqual(R.advance(loaded),R.advance(committed));s=R.advance(loaded)}assert(R.active(s).completed);assert.equal(R.active(s).completion.length,6);assert(targets.some(([x,y])=>x<0&&y<0));assert(targets.some(([x,y])=>x<0&&y>0));assert(targets.some(([x,y])=>x>0&&y<0));assert(targets.some(([x,y])=>!x&&!y));assert(targets.some(([x,y])=>!x&&y));assert.equal(A.statuses(s,'puntenbaai').nodes.find(n=>n.id===skill).state,'completed')}
 assert.equal(s.events.length,12);assert(s.events.every(e=>!e.mastery));assert(!s.skills&&!s.xp);assert.deepEqual(s.events.map(e=>e.independent),[false,true,true,true,true,true,false,true,true,true,true,true]);
 const old=s.missions.point;s=R.start(s,'point_plot',true);assert.deepEqual(s.missions.point,old);assert.equal(A.statuses(s,'puntenbaai').completed,2,'replay retains completed evidence');
});
test('unique choices include precisely one solution across axes, origin and replay runs, without graph answer leakage',()=>{
 for(const skill of P.skills)for(let run=1;run<=24;run++)for(let index=0;index<6;index++){const t=P.makeTask(skill,index,run);assert.equal(t.options.length,4);assert.equal(new Set(t.options.map(P.pair)).size,4);assert.equal(t.options.filter(p=>W.eq(p.x,t.target.x)&&W.eq(p.y,t.target.y)).length,1);for(const p of t.options)assert(Math.abs(W.num(p.x))<=5&&Math.abs(W.num(p.y))<=5)}
 let s=R.start(R.initial(),'point');let m=R.active(s);assert(!V.graph(m).includes(P.pair(m.task.target)));s=R.commit(R.edit(s,...answer(m)));assert(V.graph(R.active(s)).includes(P.pair(m.task.target)));assert(S.header(s,{mission:true}).includes('Coördinaten lezen'));
});
test('missing responses are interaction errors; swaps get diagnostic feedback; repair stays supported',()=>{
 for(const skill of P.skills){let s=R.start(R.initial(),skill);s=solve(s);s=R.commit(s);assert.equal(R.active(s).errors,0);assert.equal(s.events.at(-1).errorKind,'interaction_error');s=R.advance(s);const m=R.active(s),p={x:W.num(m.task.target.y),y:W.num(m.task.target.x)};s=R.edit(s,...(skill==='point'?['answer',String(m.task.options.findIndex(q=>W.eq(q.x,p.x)&&W.eq(q.y,p.y)))]:['point',p]));s=R.commit(s);assert.equal(R.active(s).feedback.result.code,'wave.point.swapped');assert.equal(R.active(s).errors,1);s=R.advance(s);s=solve(s);assert.equal(s.events.at(-1).independent,false);assert.equal(s.events.at(-1).correct,true)}
});
test('undo, pause and switching skills retain drafts; hints and example replacement cannot grant independent evidence',()=>{
 let s=R.start(R.initial(),'point_plot'),start=structuredClone(s);s=R.edit(s,'point',{x:-3,y:0});assert.deepEqual(R.undo(s),start);const draft=R.active(s);s=R.start(s,'point');s=R.start(s,'point_plot');assert.deepEqual(R.active(s),draft);for(let i=0;i<5;i++)s=R.hint(s);const old=R.active(s).task;s=R.newAfterExample(s);assert.notEqual(R.active(s).task.id,old.id);assert.notDeepEqual(R.active(s).task.target,old.target);assert.equal(R.active(s).hints,0);s=R.hint(s);s=solve(s);assert(!s.events.at(-1).independent);
});
test('both nodes start their own skill and recommendations move only after a full round',()=>{
 let s=A.locationState(R.initial(),'area',{area:'puntenbaai'});const html=S.area(s,{});assert(html.includes('data-start="puntenbaai" data-point-skill="point"'));assert(html.includes('data-start="puntenbaai" data-point-skill="point_plot"'));s=R.start(s,'point');s=solve(s);assert.equal(A.statuses(s,'puntenbaai').completed,0);while(!R.active(s).completed)s=solve(s);assert.equal(A.statuses(s,'puntenbaai').recommended.id,'point_plot');assert.equal(S.header(s,{mission:true}).includes('data-area="puntenbaai"'),true);
});
