'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const R=require('../games/rechten/trainer-v2/mission-runtime.js'),H=require('../games/rechten/trainer-v2/hills-core.js'),V=require('../games/rechten/trainer-v2/components/hills-view.js'),A=require('../games/rechten/trainer-v2/content/area-maps.js'),W=require('../games/rechten/trainer/wave-core.js');
function fill(s,reverse=false){for(const [slot,token] of Object.entries(reverse?{y1:'A.y',y0:'B.y',x1:'A.x',x0:'B.x'}:{y1:'B.y',y0:'A.y',x1:'B.x',x0:'A.x'}))s=R.putCoordinate(s,slot,token);return s}
function solve(s,reverse=false){const m=R.active(s),t=m.task;if(m.phase==='hill-inspect')return R.beginHills(s);if(m.phase==='hill-fill')s=fill(s,reverse);else if(m.phase==='hill-calculate')s=R.edit(s,'a',W.text(t.model.a));else{const key=m.phase==='hill-dx'?'dx':m.phase==='hill-dy'?'dy':'a',want=key==='a'?t.model.a:t[key];s=R.edit(s,key==='a'?'rateChoice':key+'Choice',String(t.options[key].findIndex(q=>W.eq(q,want))))}const input=s,before=JSON.stringify(s);s=R.commit(s);assert(R.active(s).feedback.result.ok);assert.deepEqual(R.commit(s),s);assert.equal(JSON.stringify(input),before);assert.deepEqual(R.advance(JSON.parse(JSON.stringify(s))),R.advance(s));return R.advance(s)}
test('three distinct routes finish six cases using original skill IDs, exact validation and no mastery',()=>{let s=R.initial();for(const skill of ['delta','slope','slope_from_two_points']){s=R.start(s,'hellingrug',false,skill);const old=JSON.stringify(s);assert.equal(s.active,skill);let turns=0;while(!R.active(s).completed){s=solve(s);assert(++turns<=20)}assert.equal(R.active(s).completion.length,6);assert.equal(A.statuses(s,'hellingrug').nodes.find(n=>n.id===skill).state,'completed');assert.notEqual(JSON.stringify(s),old)}assert.equal(s.events.length,30);assert(s.events.every(e=>e.mastery===false));assert(!s.skills&&!s.xp);const old=s.missions.delta;s=R.start(s,'slope',true);assert.deepEqual(s.missions.delta,old);assert.equal(A.statuses(s,'hellingrug').nodes.filter(n=>n.state==='completed').length,3);assert(A.statuses(s,'hellingrug').recommended.playable,'do not recommend a locked preview after the three routes')});
test('each multiple-choice question has exactly one exact solution, includes zero and both slope signs',()=>{for(let run=1;run<=12;run++)for(const skill of ['delta','slope','slope_from_two_points']){const tasks=Array.from({length:6},(_,i)=>H.makeTask(skill,i,run));assert(tasks.some(t=>t.model.a.n===0));assert(tasks.some(t=>t.model.a.n<0));assert(tasks.some(t=>t.model.a.n>0));for(const t of tasks){assert(t.dx.n!==0);for(const p of Object.values(t.points))assert(Math.abs(W.num(p.x))<=5&&Math.abs(W.num(p.y))<=5);for(const key of ['dx','dy','a']){assert.equal(new Set(t.options[key].map(W.text)).size,4);const want=key==='a'?t.model.a:t[key];assert.equal(t.options[key].filter(q=>W.eq(q,want)).length,1)}}}});
test('the requested delta is hidden until explicit control; slope exposes only the given differences',()=>{let s=R.start(R.initial(),'delta');assert(V.graph(R.active(s)).includes('Δx = ?'));assert(V.graph(R.active(s)).includes('Δy = ?'));s=solve(s);assert(V.graph(R.active(s)).includes('Δx = 2'));assert(V.graph(R.active(s)).includes('Δy = ?'));const slope=R.active(R.start(s,'slope'));assert(V.graph(slope).includes('Δx = 2'));assert(V.graph(slope).includes('Δy = −1'));assert(!V.graph(slope).includes('a ='))});
test('coordinate builder accepts both consistent directions, rejects mixed axes and preserves the correct numerator',()=>{for(const reverse of [false,true]){let s=R.beginHills(R.start(R.initial(),'slope_from_two_points'));s=fill(s,reverse);s=R.commit(s);assert(R.active(s).feedback.result.ok);s=R.advance(s);assert(H.slots.every(k=>R.active(s).locks[k]));s=R.edit(s,'a','-4/2');s=R.commit(s);assert(R.active(s).feedback.result.ok,'equivalent rationals accepted')}
 let s=R.beginHills(R.start(R.initial(),'slope_from_two_points'));s=fill(s);s=R.putCoordinate(s,'x1','A.x');s=R.putCoordinate(s,'x0','B.x');s=R.commit(s);assert.equal(R.active(s).feedback.result.code,'delta.direction');s=R.advance(s);assert(R.active(s).locks.y1&&R.active(s).locks.y0);assert.deepEqual(R.putCoordinate(s,'y1','A.y'),s);s=R.putCoordinate(s,'x1','B.x');s=R.putCoordinate(s,'x0','A.x');s=R.commit(s);assert(R.active(s).feedback.result.ok);assert(!s.events.at(-1).independent);assert.deepEqual(R.putCoordinate(s,'x1','A.x'),s);
 s=R.beginHills(R.start(R.initial(),'slope_from_two_points'));s=fill(s);s=R.putCoordinate(s,'y1','B.x');s=R.commit(s);assert.equal(R.active(s).feedback.result.code,'delta.y_coordinates');assert(!R.active(s).feedback.result.keep.y1)
});
test('empty answers are not mathematical errors; undo, hints, drafts and example replacement preserve evidence rules',()=>{let s=R.start(R.initial(),'slope');s=solve(s);s=R.commit(s);assert.equal(R.active(s).errors,0);assert.equal(s.events.at(-1).errorKind,'interaction_error');s=R.advance(s);s=R.hint(s);s=solve(s);assert(!s.events.at(-1).independent);s=R.beginHills(R.start(s,'slope_from_two_points'));const before=structuredClone(s);s=R.putCoordinate(s,'y1','B.y');assert.deepEqual(R.undo(s),before);const draft=structuredClone(R.active(s));s=R.start(s,'delta');s=R.start(s,'slope_from_two_points');assert.deepEqual(R.active(s),draft);for(let i=0;i<5;i++)s=R.hint(s);const task=R.active(s).task;s=R.newAfterExample(s);assert.notEqual(R.active(s).task.id,task.id);assert.notDeepEqual(R.active(s).task.points,task.points);assert.equal(R.active(s).hints,0)});
test('opening the original Hellingrug slice still uses the existing mission and cannot overwrite new skill drafts',()=>{let s=R.start(R.initial(),'delta');s=R.edit(s,'dxChoice','2');const draft=s.missions.delta;s=R.start(s,'hellingrug');assert.equal(s.active,'hellingrug');assert.equal(R.active(s).phase,'deltas');assert.deepEqual(s.missions.delta,draft);assert.equal(R.active(R.start(s,'delta')).values.dxChoice,'2')});
