/* The Grenspas presentation. All commits still go to RechtenV2Runtime/Math unchanged. */
(function(root,factory){if(typeof module==='object')module.exports=factory(require('./workbench.js'),require('./shell-view.js'),require('../../trainer/wave-core.js'));else root.RechtenV2Boundary=factory(root.RechtenV2Workbench,root.RechtenV2Shell,root.RechtenWave)})(globalThis,function(C,S,W){
'use strict';const esc=C.esc;let seq=0;
function graph(m){const t=m.task,v=m.values,f=m.feedback,b=t.bounds,{xMin,xMax,yMin,yMax}=b,id='boundary-plot-'+ ++seq;
 const X=x=>42+(W.num(typeof x==='number'?W.q(x):x)-xMin)/(xMax-xMin)*408,Y=y=>450-(W.num(typeof y==='number'?W.q(y):y)-yMin)/(yMax-yMin)*408;
 const at=x=>W.add(W.mul(t.model.a,typeof x==='number'?W.q(x):x),t.model.b),axisY=Y(0),axisX=X(0),line=`M${X(xMin)} ${Y(at(xMin))}L${X(xMax)} ${Y(at(xMax))}`;
 let grid='';for(let x=xMin;x<=xMax;x++){grid+=`<path d="M${X(x)} 38V454"/>`;if(x%2===0)grid+=`<text class="tick" x="${X(x)}" y="${axisY+25}" text-anchor="middle">${x}</text>`}for(let y=yMin;y<=yMax;y++){grid+=`<path d="M38 ${Y(y)}H454"/>`;if(y!==0&&y%2===0)grid+=`<text class="tick" x="${axisX-14}" y="${Y(y)+7}" text-anchor="end">${y}</text>`}
 const value=m.index===0?v.root:v.boundary,anchor=W.parse(String(value??'')),inRange=anchor&&W.num(anchor)>=xMin&&W.num(anchor)<=xMax;
 const showSign=m.phase==='symbol'||(f?.result.ok&&m.phase==='interval');
 const pin=inRange?`<path class="anchor" d="M${X(anchor)} ${axisY-13}V${axisY+13}"/><circle class="anchor-pin" cx="${X(anchor)}" cy="${axisY}" r="6"/><text class="pin-label" x="${X(anchor)+10}" y="${axisY-19}">x = ${esc(W.text(anchor))}</text>`:'';
 const zone=inRange&&['left','right'].includes(v.side)?`<path class="interval" d="M${v.side==='left'?X(xMin):X(anchor)} ${axisY+43}H${v.side==='left'?X(anchor):X(xMax)}"/><circle class="endpoint ${v.closed?'closed':''}" cx="${X(anchor)}" cy="${axisY+43}" r="6"/>`:v.side==='all'?`<path class="interval" d="M${X(xMin)} ${axisY+43}H${X(xMax)}"/>`:'';
 const probes=(f?.result.probes||[]).filter(p=>p.x&&p.y).map(p=>`<path class="probe" d="M${X(p.x)} ${axisY}V${Y(p.y)}"/><circle class="probe-dot" cx="${X(p.x)}" cy="${Y(p.y)}" r="5"/>`).join('');
 const description=`Rechte door (${xMin}, ${W.text(at(xMin))}) en (${xMax}, ${W.text(at(xMax))}). x en y van ${xMin} tot ${xMax}. Kies je x-grens via het waardeveld of tik op de x-as.`;
 return `<svg class="math-graph boundary-graph" viewBox="0 0 492 492" role="img" aria-label="Grafiek van f en jouw x-gebied" ${m.phase==='root'&&!f?'data-axis-picker="root"':''} data-plot-start="42" data-plot-width="408"><title>Grafiek van f</title><desc>${esc(description)}</desc><defs><clipPath id="${id}"><path d="M38 38h416v416H38z"/></clipPath><clipPath id="${id}-positive"><path d="M38 38H454V${axisY}H38z"/></clipPath><clipPath id="${id}-negative"><path d="M38 ${axisY}H454V454H38z"/></clipPath></defs><g class="graph-grid">${grid}</g><path class="axis" d="M32 ${axisY}H465M${axisX} 460V28"/><path class="axis-arrow" d="m456 ${axisY-6} 10 6-10 6M${axisX-6} 38l6-11 6 11"/><text class="axis-name" x="470" y="${axisY+7}">x</text><text class="axis-name" x="${axisX+13}" y="27">y</text><g clip-path="url(#${id})"><path class="model-line" d="${line}"/>${showSign?`<path class="positive-line" clip-path="url(#${id}-positive)" d="${line}"/><path class="negative-line" clip-path="url(#${id}-negative)" d="${line}"/>`:''}${probes}</g>${pin}${zone}</svg>`;
}
function field(m,name,label){return C.field(name,label,m.values[name]??'',{disabled:!!m.feedback||!!m.locks[name]}).replace('<input ', '<input placeholder="?" ')}
function choice(m,name,value,label,extra=''){const selected=String(m.values[name])===String(value),disabled=m.feedback||m.locks[name];return `<button type="button" class="${extra}" data-choice="${name}" data-value="${esc(value)}" aria-pressed="${selected}" ${disabled?'disabled':''}>${label}${selected?`<span class="choice-tick" aria-hidden="true">${S.icon('check',19)}</span>`:''}</button>`}
function notation(m){const linear=!!m.task.model.a.n;return `<div class="ink-equation" role="group" aria-label="Jouw ongelijkheid">${linear?'<span class="equation-x">x</span>':''}<div class="symbol-choices" role="group" aria-label="Teken">${(linear?[['<','&lt;'],['=','='],['>','&gt;']]:[['all','Alle x'],['none','Geen x']]).map(([v,label])=>choice(m,'symbol',v,label)).join('')}</div>${linear?field(m,'symbolBoundary','Grens'):''}</div>`}
function reminder(m){const expanded=m.task.mode==='discover'||m.hintOpen;
 return `<aside class="reminder-paper ${expanded?'is-open':'is-closed'}"><h2>${S.icon('light',26)} Herinnering</h2>${expanded?`<p class="reminder-formula">f(x) ${m.task.ask==='negative'?'&lt;':'&gt;'} 0</p><p>Waar ligt de grafiek ${m.task.ask==='negative'?'onder':'boven'} de x-as?</p><div class="reminder-rule"></div><p class="reminder-small">Bij de nulwaarde snijdt de lijn de x-as.</p><svg class="reminder-sketch" viewBox="0 0 170 100" aria-hidden="true"><path d="M12 63h142M74 91V12" stroke="#294451" fill="none" stroke-width="2"/><path d="m27 88 47-25" stroke="#b45248" stroke-width="3"/><path d="m74 63 65-36" stroke="#2c79b4" stroke-width="3"/><text x="106" y="24" fill="#246a9d" font-size="16">f(x) &gt; 0</text><circle cx="74" cy="63" r="4" fill="#294451"/></svg>`:'<p>Een geheugensteuntje nodig?</p><button type="button" data-hint>Bekijk een hint</button>'}</aside>`;
}
function render(m){const t=m.task,v=m.values,first=m.index===0,root=first?v.root:v.boundary,linear=!!t.model.a.n;
 const title=`Wanneer is f(x) ${t.ask==='negative'?'&lt;':'&gt;'} 0?`;
 const instruction=m.phase==='root'?'Zoek eerst de grens op de x-as.':m.phase==='symbol'?'Schrijf het gebied dat je koos.':`Jouw grens is x = ${esc(root??'…')}.`;
 const step=m.phase==='root'?0:m.phase==='symbol'?2:1;
 let tray='';
 if(m.phase==='root')tray=`<div class="root-builder"><span class="root-label">De grens ligt bij</span><div class="root-controls"><span class="equation-x">x =</span><button type="button" data-step="root" data-amount="-1" aria-label="Grens één kleiner" ${m.feedback?'disabled':''}>−</button>${field(m,'root','x van je grens')}<button type="button" data-step="root" data-amount="1" aria-label="Grens één groter" ${m.feedback?'disabled':''}>+</button></div><p class="micro-copy">Je kunt ook op de x-as tikken.</p></div>`;
 else if(m.phase==='symbol')tray=`<p class="retained-boundary">Jouw grens: x = ${esc(root)}</p>${notation(m)}`;
 else tray=`${!first&&linear?`<div class="compact-boundary">${field(m,'boundary','Grenspin')}${notation(m)}</div>`:''}<div class="region-choices" role="group" aria-label="x-gebied">${(linear?[['left',`<span class="interval-arrow">←</span><span>Links</span>`],['right',`<span class="interval-arrow">→</span><span>Rechts</span>`]]:[['all','Alle x'],['none','Geen x']]).map(([value,label])=>choice(m,'side',value,label,'region-choice')).join('')}</div>${linear?`<div class="endpoint-choices" role="group" aria-label="Grens inbegrepen">${choice(m,'closed',false,'<span class="endpoint-icon">○</span> Zonder grens')}${choice(m,'closed',true,'<span class="endpoint-icon">●</span> Met grens')}</div>`:notation(m)}`;
 const feedback=m.feedback,phaseText=['Grens','Gebied','Notatie'];
 return {title,workspace:`${reminder(m)}<div class="graph-paper"><button type="button" class="graph-undo icon-button" id="undo" aria-label="Maak laatste bewerking ongedaan" ${feedback||!m.history.length?'disabled':''}>${S.icon('undo',21)}</button><div class="evidence" data-representation="graph">${graph(m)}</div><span class="graph-paper-caption">${m.task.mode==='discover'||m.hintOpen?(t.ask==='negative'?'Onder de x-as':'Boven de x-as'):'Grafiek van f'}</span></div><section class="answer-tray boundary-answer"><div class="exercise-heading"><span class="exercise-kicker">GRENSPAS</span><h1>${title}</h1></div>${first?`<ol class="phase-steps" aria-label="Stappen in deze oefening">${phaseText.map((label,i)=>`<li ${i===step?'aria-current="step"':''} class="${i<step?'is-done':''}"><span>${i<step?'✓':i+1}</span>${label}</li>`).join('')}</ol><p class="phase-instruction">${instruction}</p>`:''}${tray}</section>`};
}
return Object.freeze({render,graph});
});
