/* Formulewerf A paper workbenches. No solution coordinates are drawn before commit. */
(function(root,factory){if(typeof module==='object')module.exports=factory(require('./workbench.js'),require('./shell-view.js'),require('../formula-core.js'),require('../../trainer/wave-core.js'));else root.RechtenV2FormulaView=factory(root.RechtenV2Workbench,root.RechtenV2Shell,root.RechtenV2Formula,root.RechtenWave)})(globalThis,function(C,S,F,W){
'use strict';const esc=C.esc;let seq=0;
const number=v=>{const q=W.parse(v);return q?W.html(q):esc(v)};
function sketch(){return `<svg class="formula-sketch" viewBox="0 0 220 150" aria-hidden="true"><path d="M15 115H210M75 145V10" class="sketch-axis"/><path d="M25 139L180 35" class="sketch-line"/><circle cx="75" cy="105" r="6"/><text x="88" y="115">(0, b)</text><text x="203" y="104">x</text><text x="86" y="20">y</text></svg>`}
function reminder(m){let body;
 if(m.skill==='rewrite_linear_equation')body='<p><strong>Doel:</strong> y alleen links.</p><p>Pas dezelfde bewerking toe op beide leden.</p><p>Werk de x-term links weg. Deel door de coëfficiënt van y.</p><p class="formula-small">Een andere geldige volgorde mag ook.</p>';
 else if(m.skill==='graph_from_equation')body='<p><strong>b</strong> is de y-coördinaat van het snijpunt met de y-as.</p><p><strong>a</strong> is de richtingscoëfficiënt: de verandering van y per stap in x.</p><p class="formula-small">Lees a en b zelf af uit het voorschrift.</p>'+sketch();
 else if(m.skill==='equation_from_graph')body='<p><strong>a</strong> vertelt hoe de rechte stijgt of daalt.</p><p><strong>b</strong> is de y-coördinaat van het snijpunt met de y-as.</p><p>Lees eerst b af, daarna a.</p>'+sketch();
 else body='<p>In y = ax + b is <strong>a</strong> de richtingscoëfficiënt.</p><p><strong>b</strong> is de y-coördinaat van het snijpunt met de y-as.</p><p>Zet a vóór x. Het teken en het laatste getal vormen samen b.</p><p class="formula-small">Een bouwsteen mag je opnieuw gebruiken.</p>';
 return `<aside class="reminder-paper formula-reminder"><h2>${S.icon('light',28)} Herinnering</h2>${body}</aside>`;
}
function graph(m){const t=m.task,plot=m.skill==='graph_from_equation',points=Object.fromEntries(['A','B'].filter(n=>m.values['plot'+n]).map(n=>[n,{x:W.fromNumber(m.values['plot'+n].x),y:W.fromNumber(m.values['plot'+n].y)}])),model=plot?(points.A&&points.B?W.model(points.A,points.B):null):t.model;
 const editable=plot&&!m.feedback&&!m.completed,X=x=>250+40*W.num(x),Y=y=>250-40*W.num(y),clip='formula-clip-'+ ++seq;let grid='';
 for(let i=-10;i<=10;i++){if(i%2&&t.gridStep===1)continue;const q=i/2,pos=250+20*i;grid+=`<path class="${i%2?'half-grid':''}" d="M${pos} 50V450M50 ${pos}H450"/>`;if(!(i%2)&&q)grid+=`<text x="${pos}" y="273" text-anchor="middle">${q}</text><text x="233" y="${256-20*i}" text-anchor="end">${q}</text>`}
 const line=!model||model.kind==='identical'?'':model.kind==='vertical'?`M${X(model.c)} 50V450`:`M50 ${Y(W.add(W.mul(model.a,-5),model.b))}L450 ${Y(W.add(W.mul(model.a,5),model.b))}`;
 const pins=plot?Object.entries(points).map(([n,p])=>`<g class="line-pin pin-${n} ${(m.values.selectedPoint||'A')===n?'is-selected':''}" ${editable&&!m.locks['plot'+n]?`data-line-marker="${n}"`:''}><circle class="line-pin-hit" cx="${X(p.x)}" cy="${Y(p.y)}" r="15"/><circle class="line-pin-dot" cx="${X(p.x)}" cy="${Y(p.y)}" r="6"/><text x="${X(p.x)+(W.num(p.x)<2?12:-12)}" y="${Y(p.y)+(n==='A'?-18:29)}" text-anchor="${W.num(p.x)<2?'start':'end'}">${n} (${esc(W.text(p.x))}; ${esc(W.text(p.y))})</text></g>`).join(''):'';
 return `<svg class="math-graph boundary-graph lines-graph formula-graph" viewBox="0 0 500 500" role="${editable?'group':'img'}" ${editable?'tabindex="0" data-line-picker':''} aria-label="${plot?'Plaats twee verschillende punten. Selecteer A of B en tik, sleep of gebruik de pijltjestoetsen.':'Grafiek van de rechte met genummerde assen.'} Kleine stap: ${t.gridStep===.5?'een halve':'één'} eenheid."><defs><clipPath id="${clip}"><path d="M48 48h404v404H48z"/></clipPath></defs><g class="graph-grid">${grid}</g><path class="axis" d="M30 250H474M250 470V26"/><path class="axis-arrow" d="m465 243 10 7-10 7M243 36l7-11 7 11"/><text x="234" y="273" text-anchor="end">0</text><text class="axis-name" x="480" y="255">x</text><text class="axis-name" x="263" y="28">y</text>${line?`<path class="formula-model ${plot&&!m.feedback?.result.ok?'is-draft':''}" d="${line}" clip-path="url(#${clip})"/>`:''}${pins}</svg>`;
}
function pointTools(m){const editable=!m.feedback;return `<div class="line-tools formula-point-tools" role="group" aria-label="Punten plaatsen">${['A','B'].map(n=>`<button type="button" class="line-point-token token-${n}" data-line-point="${n}" draggable="${editable&&!m.locks['plot'+n]}" aria-pressed="${(m.values.selectedPoint||'A')===n}" aria-label="Punt ${n} selecteren of slepen" ${!editable||m.locks['plot'+n]?'disabled':''}>${n}</button>`).join('')}<button type="button" class="line-clear" id="line-clear" aria-label="Wis je geplaatste punten" ${!editable||!m.values.plotA&&!m.values.plotB?'disabled':''}>Wis</button><span class="formula-plot-note">${m.task.gridStep===.5?'Halve roosterstappen':'Elk hokje is 1 eenheid'}</span></div>`}
function tile(m,slot,label){return `<button type="button" class="formula-slot" data-formula-slot="${slot}" aria-label="${label}: ${esc(m.values[slot]||'nog invullen')}" aria-pressed="${(m.values.formulaSlot||'factor')===slot}" ${m.feedback||m.locks[slot]?'disabled':''}>${m.values[slot]?number(m.values[slot]):'<span aria-hidden="true">?</span>'}</button>`}
function equation(e){const member=(m,order)=>{let out='';for(const k of order){const q=m[k];if(!q.n)continue;const abs=W.q(Math.abs(q.n),q.d);out+=(out?(q.n<0?' − ':' + '):q.n<0?'−':'')+(k!=='c'&&W.eq(abs,1)?'':W.html(abs))+(k==='c'?'':k)}return out||'0'};return member(e.left,['y','x','c'])+' = '+member(e.right,['x','y','c'])}
function algebra(m){const steps=m.values.algebraSteps||[];return `<div class="formula-algebra-row"><span>Gegeven</span><div role="math">${equation(m.task.equation)}</div></div>${steps.slice(-2).map((step,i)=>`<div class="formula-algebra-row"><span>Stap ${steps.length-Math.min(steps.length,2)+i+1}</span><div role="math">${equation(step.equation)}</div><p>${esc(step.operation)} aan beide leden</p></div>`).join('')}${!steps.length?'<p class="formula-algebra-empty">Kies een bewerking.<br>Je uitwerking verschijnt hier.</p>':''}`}
function stepper(m,name){return `<label class="formula-parameter"><span>${name}</span><button type="button" data-formula-step="${name}" data-direction="1" aria-label="Verhoog ${name}" ${m.feedback||m.locks[name]?'disabled':''}>▴</button><input name="${name}" type="text" inputmode="text" autocomplete="off" maxlength="16" aria-label="${name==='a'?'Richtingscoëfficiënt a':'y-afsnede b'}" value="${esc(m.values[name]??'')}" placeholder="?" ${m.feedback||m.locks[name]?'readonly':''}><button type="button" data-formula-step="${name}" data-direction="-1" aria-label="Verlaag ${name}" ${m.feedback||m.locks[name]?'disabled':''}>▾</button></label>`}
function panels(m){const skill=m.skill;let main,side;
 if(skill==='equation_from_ab'){
  main=`<div class="formula-given"><span>Gegeven:</span><strong>a = ${W.html(m.task.model.a)}</strong><strong>b = ${W.html(m.task.model.b)}</strong></div><div class="formula-builder"><span>y =</span>${tile(m,'factor','Coëfficiënt van x')}${tile(m,'variable','Variabele')}${tile(m,'operator','Teken van de constante term')}${tile(m,'constant','Constante term')}</div><p class="formula-build-help">Kies een vakje en tik of sleep een bouwsteen.</p>`;
  side=`<h2>Bouwstenen</h2><div class="formula-tokens" role="group" aria-label="Bouwstenen">${m.task.tokens.map((token,i)=>`<button type="button" data-formula-token="${esc(token)}" draggable="${!m.feedback}" aria-label="Bouwsteen ${esc(token)}" ${m.feedback?'disabled':''}>${number(token)}</button>`).join('')}</div>`;
 }else if(skill==='rewrite_linear_equation'){
  main=algebra(m);side=`<h2>Kies een bewerking</h2><div class="formula-operations" role="group" aria-label="Bewerking op beide leden">${F.operations(m.task,m.values).map((op,i)=>`<button type="button" class="${op.kind==='divide'?'is-scale':''}" data-formula-operation="${i}" aria-label="${esc(F.operationLabel(op))} aan beide leden" ${m.feedback?'disabled':''}>${esc(F.operationLabel(op))}</button>`).join('')}</div>`;
 }else{
  main=`<div class="formula-graph-wrap">${graph(m)}</div>${skill==='graph_from_equation'?pointTools(m):''}`;
  side=skill==='graph_from_equation'?'<div class="formula-task-step"><span>1</span><div><h2>Plaats een eerste punt</h2><p>Gebruik wat je weet over a en b.</p></div></div><div class="formula-task-step"><span>2</span><div><h2>Plaats een tweede punt</h2><p>Gebruik de richtingscoëfficiënt of bereken een functiewaarde.</p></div></div><p class="formula-side-note">Trek daarna de rechte door je punten.</p>':`<div class="formula-parameter-equation"><span>f(x) =</span>${stepper(m,'a')}<span>x +</span>${stepper(m,'b')}</div><p class="formula-side-note">Pijltjes, getal of breuk.</p>`;
 }
 return `<section class="formula-paper formula-work ${skill==='rewrite_linear_equation'?'formula-algebra':''}"><button type="button" class="graph-undo" id="undo" aria-label="Maak laatste bewerking ongedaan" ${m.feedback||!m.history.length?'disabled':''}>${S.icon('undo',26)}</button>${main}</section><section class="formula-paper formula-answer answer-tray">${side}</section>`;
}
function render(m,header){const f=m.feedback,title=m.skill==='equation_from_ab'?'Bouw het functievoorschrift':m.skill==='graph_from_equation'?'Teken '+W.formula(m.task.model.a,m.task.model.b):m.skill==='equation_from_graph'?'Welk functievoorschrift hoort bij deze grafiek?':'Schrijf de vergelijking in de vorm y = ax + b';
 const feedback=f?(f.result.ok?'✓ ':'')+esc(f.result.message):m.values.operationError?esc(m.values.operationError):esc(m.task.hints[m.hintOpen?m.hints-1:0]);
 const done=`<section class="boundary-complete"><h1>Goed gedaan!</h1><p>Je hebt de reeks afgerond.</p><span class="proof-badge">${S.icon('check')} ${F.titles[m.skill]}</span><button type="button" data-restart="formulewerf" data-skill="${m.skill}">Opnieuw oefenen</button></section>`;
 const action=m.completed?`<button type="button" class="paint-button" data-screen="area" data-area="formulewerf" data-zone="bouwen">Naar Formulewerf ${S.icon('arrow')}</button>`:m.hints>=5&&!f?`<button type="button" class="paint-button" id="new-example">Nieuw geval ${S.icon('arrow')}</button>`:f?`<button type="button" class="paint-button" id="continue">${f.result.ok?(m.index===F.count-1?'Afronden':'Volgende'):'Herstel'} ${S.icon(f.result.ok?'arrow':'undo')}</button>`:`<button type="submit" class="paint-button" id="commit">${m.skill==='graph_from_equation'?'Trek de rechte':'Controleer'} ${S.icon('arrow')}</button>`;
 return `<form id="mission" class="boundary-mission formula-mission" data-world="formulewerf" data-skill="${m.skill}" data-phase="${m.phase}" novalidate>${header}<main class="boundary-workspace formula-workspace">${m.completed?done:`${reminder(m)}<header class="formula-heading"><h1>${title}</h1><span>Opgave ${m.index+1} / ${F.count}</span></header>${panels(m)}`}</main><footer class="boundary-footer"><button type="button" class="paper-pill" id="pause" aria-label="Pauzeer en ga naar Formulewerf A">${S.icon('back')}<span>Vorige</span></button><div class="feedback-bubble"><button type="button" class="hint-button" id="hint" aria-label="Volgende hint" ${m.completed||f||m.hints>=5?'disabled':''}>${S.icon('light',23)}</button><div id="feedback" class="feedback ${f?f.result.ok?'success':'error':''}" role="status" aria-live="polite">${m.completed?'Je werk is bewaard.':feedback}</div></div>${action}</footer></form><section id="rotateGate"><span class="rotate-symbol">↻</span><h1>Even je scherm draaien</h1><p>Liggend heb je ruimte voor je werkblad. Je werk blijft bewaard.</p><button type="button" class="paper-pill" data-screen="area" data-area="formulewerf" data-zone="bouwen">Terug naar Formulewerf</button></section>`;
}
return Object.freeze({render,graph,equation});
});
