/* Native SVG and controls: the graph, formula and choices share one exact model. */
(function(root,factory){if(typeof module==='object')module.exports=factory(require('./workbench.js'),require('./shell-view.js'),require('../grens-core.js'),require('../../trainer/wave-core.js'));else root.RechtenV2GrensView=factory(root.RechtenV2Workbench,root.RechtenV2Shell,root.RechtenV2Grens,root.RechtenWave)})(globalThis,function(C,S,G,W){
'use strict';const esc=C.esc;let seq=0;
const formula=t=>W.formula(t.model.a,t.model.b).replace(/^y = /,'f(x) = ');
function sketch(kind){const sign=kind==='signchart'||kind==='positive'||kind==='negative';return `<svg class="grens-sketch" viewBox="0 0 220 155" aria-hidden="true"><path class="sketch-axis" d="M15 115H208m-9-6 9 6-9 6M75 148V12m-6 9 6-9 6 9"/><path class="sketch-line" d="M28 145L181 44"/>${sign?'<path class="sketch-negative" d="M28 145L73 115"/>':''}<circle cx="73" cy="115" r="6"/><text x="204" y="104">x</text><text x="86" y="20">y</text><text x="95" y="145">${sign?'f(x) = 0':'nulwaarde'}</text></svg>`}
function reminder(m){let body;
 if(m.skill==='zeroRead')body='<p>De nulwaarde is de <strong>x-waarde</strong> waar de grafiek de x-as snijdt.</p>'+sketch(m.skill);
 else if(m.skill==='zero')body='<p>Nulwaarde betekent:</p><p class="grens-highlight">f(x) = 0</p><p>Zoek dus voor welke x de formule gelijk is aan 0.</p><p class="grens-reminder-small">Stel ax + b = 0 en los de vergelijking op.</p>';
 else if(m.skill==='signchart'&&m.task.representation==='formula')body='<p>Kijk naar de <strong>richtingscoëfficiënt a</strong>: de coëfficiënt van x.</p><p><strong>a &gt; 0</strong>: stijgend<br>links −, rechts +</p><p><strong>a &lt; 0</strong>: dalend<br>links +, rechts −</p><p>Op de nulwaarde is f(x) = 0.</p>';
 else if(m.skill==='signchart')body='<p>Links en rechts van de nulwaarde kijk je of de grafiek boven of onder de x-as ligt.</p><p><span class="grens-sign-positive">+</span> boven de x-as<br><span class="grens-sign-negative">−</span> onder de x-as</p><p>Op de nulwaarde is f(x) = 0.</p>';
 else body=`<p class="grens-highlight">f(x) ${m.skill==='negative'?'&lt;':'&gt;'} 0</p><p>De grafiek ligt <strong>${m.skill==='negative'?'onder':'boven'} de x-as</strong>.</p><div class="reminder-rule"></div><p class="grens-reminder-small">De nulwaarde zelf telt niet mee: daar is f(x) = 0.</p>${sketch(m.skill)}`;
 return `<aside class="reminder-paper grens-reminder"><h2>${S.icon('light',28)} Herinnering</h2>${body}</aside>`;
}
function graph(m){const t=m.task,X=x=>250+40*x,Y=y=>250-40*y,a=W.num(t.model.a),b=W.num(t.model.b),root=W.num(t.root),clip='grens-clip-'+ ++seq;
 // In a sign chart the zero is given; in inequalities it is revealed only after the root step.
 const showRoot=m.skill==='signchart'||m.phase==='grens-inequality'||!!m.feedback?.result.ok;
 const colorSigns=m.skill==='signchart';let grid='';
 for(let i=-10;i<=10;i++){const q=i/2,n=X(q);if(i%2&&t.root.d===1)continue;grid+=`<path class="${i%2?'half-grid':''}" d="M${n} 50V450M50 ${n}H450"/>`;if(!(i%2)&&q)grid+=`<text x="${n}" y="273" text-anchor="middle">${q}</text><text x="233" y="${Y(q)+7}" text-anchor="end">${q}</text>`}
 const segment=(left,right,cls)=>`<path class="grens-function ${cls}" d="M${X(left)} ${Y(a*left+b)}L${X(right)} ${Y(a*right+b)}"/>`;
 return `<svg class="math-graph boundary-graph grens-graph" viewBox="0 0 500 500" role="img" aria-label="Grafiek van f met genummerde x-as en y-as. De kleine stap is ${t.root.d>1?'een halve':'één'} eenheid."><defs><clipPath id="${clip}"><path d="M48 48h404v404H48z"/></clipPath></defs><g class="graph-grid">${grid}</g><path class="axis" d="M30 250H474M250 470V26"/><path class="axis-arrow" d="m465 243 10 7-10 7M243 36l7-11 7 11"/><text x="234" y="273" text-anchor="end">0</text><text class="axis-name" x="480" y="255">x</text><text class="axis-name" x="263" y="28">y</text><g clip-path="url(#${clip})">${colorSigns?segment(-5,root,a>0?'is-negative':'is-positive')+segment(root,5,a>0?'is-positive':'is-negative'):segment(-5,5,'')}${showRoot?`<circle class="grens-root-halo" cx="${X(root)}" cy="250" r="13"/><circle class="grens-root-pin" cx="${X(root)}" cy="250" r="7"/>`:''}</g>${showRoot?`<text class="grens-root-label" x="${X(root)}" y="219" text-anchor="middle">x = ${esc(W.text(t.root))}</text>`:''}</svg>`;
}
function evidence(m){const t=m.task,isFormula=t.representation==='formula';return `<section class="grens-evidence ${isFormula?'grens-formula-paper':'grens-graph-paper'}"><button type="button" class="graph-undo" id="undo" aria-label="Maak laatste bewerking ongedaan" ${m.feedback||!m.history.length?'disabled':''}>${S.icon('undo',27)}</button>${isFormula?`<div class="grens-formula" role="math">${formula(t)}</div>${m.skill==='zero'?`<p class="grens-formula-prompt">Voor welke x wordt f(x) = 0?</p><div class="grens-equation">${formula(t).replace('f(x) = ','')} = 0</div>`:`<p class="grens-formula-prompt">nulwaarde: <strong>${W.html(t.root)}</strong></p>`}`:graph(m)}</section>`}
function choice(m,field,value,label){const picked=String(m.values[field]??'')===String(value),correct=picked&&m.feedback?.result.ok;return `<button type="button" class="grens-choice ${correct?'is-correct':''}" data-choice="${field}" data-value="${esc(value)}" aria-pressed="${picked}" ${m.feedback||m.locks[field]?'disabled':''}>${label}${correct?'<span class="grens-choice-check" aria-hidden="true">✓</span>':''}</button>`}
function chart(m){const labels=['Links van de nulwaarde','Op de nulwaarde','Rechts van de nulwaarde'],slot=m.values.chartSlot||'chartLeft';return `<table class="grens-chart" aria-label="Tekenschema"><thead><tr><th scope="row">x</th><th scope="col" aria-label="Links van de nulwaarde">−∞</th><th scope="col">${W.html(m.task.root)}</th><th scope="col" aria-label="Rechts van de nulwaarde">+∞</th></tr></thead><tbody><tr><th scope="row">f(x)</th>${G.slots.map((k,i)=>`<td><button type="button" class="grens-slot" data-sign-slot="${k}" aria-label="${labels[i]}: ${m.values[k]||'nog invullen'}" aria-pressed="${slot===k}" ${m.feedback||m.locks[k]?'disabled':''}>${m.values[k]==='-'?'−':m.values[k]||'?'}</button></td>`).join('')}</tr></tbody></table><p class="grens-instruction">Tik de tekens van links naar rechts.</p><div class="grens-signs" role="group" aria-label="Kies een teken">${[['-','−','Negatief'],['0','0','Nul'],['+','+','Positief']].map(([v,label,name])=>`<button type="button" data-sign-value="${v}" aria-label="${name}" ${m.feedback?'disabled':''}>${label}</button>`).join('')}</div>`}
function answer(m){const sign=['positive','negative'].includes(m.skill),phase=m.phase,rootDone=phase==='grens-inequality';
 const title=m.skill==='zeroRead'?'Lees de nulwaarde af.':m.skill==='zero'?'Bereken de nulwaarde.':m.skill==='signchart'?'Vul de tekens in het tekenschema.':G.titles[m.skill];
 return `<section class="grens-answer answer-tray"><div class="exercise-heading"><h1>${esc(title)}</h1></div><p class="grens-counter">Opgave ${m.index+1} / ${G.count}${m.skill==='signchart'?' · '+(m.task.representation==='graph'?'grafiek':'formule'):''}</p>${phase==='grens-chart'?chart(m):`${sign?`<div class="grens-step ${rootDone?'is-done':''}"><span>1</span><h2>Nulwaarde</h2>${rootDone?`<strong class="grens-retained">x = ${W.html(m.task.root)}</strong>`:''}</div>${rootDone?'<div class="grens-step"><span>2</span><h2>Kies het juiste antwoord</h2></div>':''}`:'<p class="grens-instruction">Kies het juiste antwoord.</p>'}<div class="grens-choices ${rootDone?'grens-inequalities':''}" role="group" aria-label="${rootDone?'Kies het x-gebied':'Kies de nulwaarde'}">${rootDone?['<','=','>'].map(v=>choice(m,'inequality',v,`x ${esc(v)} ${W.html(m.task.root)}`)).join(''):m.task.options.map((q,i)=>choice(m,'answer',i,W.html(q))).join('')}</div>`}</section>`;
}
function render(m,header){const f=m.feedback;
 const feedback=f?`${f.result.ok?'✓ ':f.result.kind==='interaction_error'?'':'↻ '}${esc(f.result.message)}`:m.hintOpen?esc(G.hintsFor(m.task)[m.hints-1]):m.phase==='grens-inequality'?`Kijk waar de grafiek ${m.skill==='negative'?'onder':'boven'} de x-as ligt.`:esc(G.hintsFor(m.task)[0]);
 const done=`<section class="boundary-complete"><h1>Goed gedaan!</h1><p>Je hebt de reeks afgerond.</p><span class="proof-badge">${S.icon('check')} ${esc(G.titles[m.skill])}</span><button type="button" data-restart="grenspas" data-skill="${m.skill}">Opnieuw oefenen</button></section>`;
 const action=m.completed?`<button type="button" class="paint-button" data-screen="area" data-area="grenspas">Naar Grenspas ${S.icon('arrow')}</button>`:m.hints>=5&&!f?`<button type="button" class="paint-button" id="new-example">Nieuw geval ${S.icon('arrow')}</button>`:f?`<button type="button" class="paint-button" id="continue">${f.result.ok?(f.next==='next-task'&&m.index===G.count-1?'Afronden':'Volgende'):'Herstel'} ${S.icon(f.result.ok?'arrow':'undo')}</button>`:`<button type="submit" class="paint-button" id="commit">Controleer ${S.icon('arrow')}</button>`;
 return `<form id="mission" class="boundary-mission grens-mission" data-world="grenspas" data-skill="${m.skill}" data-phase="${m.phase}" novalidate>${header}<main class="boundary-workspace grens-workspace">${m.completed?done:reminder(m)+evidence(m)+answer(m)}</main><footer class="boundary-footer"><button type="button" class="paper-pill" id="pause" aria-label="Pauzeer en ga naar Grenspas">${S.icon('back')}<span>Vorige</span></button><div class="feedback-bubble"><button type="button" class="hint-button" id="hint" aria-label="Volgende hint" ${m.completed||f||m.hints>=5?'disabled':''}>${S.icon('light',23)}</button><div id="feedback" class="feedback ${f?f.result.ok?'success':'error':''}" role="status" aria-live="polite">${m.completed?'Je werk is bewaard.':feedback}</div></div>${action}</footer></form><section id="rotateGate"><span class="rotate-symbol">↻</span><h1>Even je scherm draaien</h1><p>Liggend heb je ruimte voor de grafiek en je antwoord. Je werk blijft bewaard.</p><button type="button" class="paper-pill" data-screen="area" data-area="grenspas">Terug naar Grenspas</button></section>`;
}
return Object.freeze({render,graph,formula});
});
