/* Puntenbaai workspace: the drawing and choices are views of the same saved response. */
(function(root,factory){if(typeof module==='object')module.exports=factory(require('./workbench.js'),require('./shell-view.js'),require('../points-core.js'),require('../../trainer/wave-core.js'));else root.RechtenV2PointsView=factory(root.RechtenV2Workbench,root.RechtenV2Shell,root.RechtenV2Points,root.RechtenWave)})(globalThis,function(C,S,P,W){
'use strict';const esc=C.esc,X=x=>250+40*W.num(x),Y=y=>250-40*W.num(y);
function graph(m){
 const read=m.skill==='point',p=read?m.task.target:m.values.point,answered=!!m.feedback?.result.ok;
 let grid='';for(let i=-5;i<=5;i++){grid+=`<path d="M${250+i*40} 50V450M50 ${250+i*40}H450"/>`;if(i)grid+=`<text x="${250+i*40}" y="274" text-anchor="middle">${i}</text><text x="237" y="${256-i*40}" text-anchor="end">${i}</text>`}
 const pin=p?`<path class="point-guides" d="M250 ${Y(p.y)}H${X(p.x)}V250"/><circle class="point-halo" cx="${X(p.x)}" cy="${Y(p.y)}" r="10"/><circle class="point-dot" cx="${X(p.x)}" cy="${Y(p.y)}" r="6"/><text class="point-label" text-anchor="${W.num(p.x)>2?'end':'start'}" x="${X(p.x)+(W.num(p.x)>2?-14:14)}" y="${Y(p.y)-15}">${read&&!answered?'P':esc(P.pair(p))}</text>`:'';
 return `<svg class="math-graph boundary-graph points-graph" viewBox="0 0 500 500" role="${read?'img':'group'}" ${!read&&!m.feedback?'tabindex="0" data-point-picker':''} aria-label="${read?'Rooster met punt P. Lees eerst de horizontale as en daarna de verticale as.':'Punt plaatsen. Tik op het rooster of gebruik de pijltjestoetsen.'}${!read&&p?' Jouw punt: '+esc(P.pair(p)):''}"><title>${read?'Welke coördinaten heeft P?':'Plaats het gevraagde punt'}</title><desc>Beide assen lopen van −5 tot 5. Elk roosterhokje is één eenheid.</desc><g class="graph-grid">${grid}</g><path class="axis" d="M30 250H472M250 470V27"/><path class="axis-arrow" d="m463 243 10 7-10 7M243 37l7-11 7 11"/><text x="238" y="274" text-anchor="end">0</text><text class="axis-name" x="478" y="256">x</text><text class="axis-name" x="263" y="30">y</text>${pin}</svg>`;
}
function reminder(){return `<aside class="reminder-paper points-reminder"><h2>${S.icon('light',26)} Herinnering</h2><p>Een punt noteer je als <strong>(x, y)</strong>.</p><p>Eerst lees je <strong>x</strong>:<br>links of rechts.</p><p>Daarna lees je <strong>y</strong>:<br>omhoog of omlaag.</p><div class="reminder-rule"></div><svg class="reminder-sketch" viewBox="0 0 180 115" aria-hidden="true"><path d="M12 85H162M62 106V12m-5 8 5-8 5 8m87 60 8 5-8 5" stroke="currentColor" stroke-width="2" fill="none"/><path d="M62 42H125V85" stroke="#2987ba" stroke-width="2" stroke-dasharray="5 4" fill="none"/><circle cx="125" cy="42" r="5" fill="#2987ba"/><text x="130" y="34" fill="#2987ba">(x, y)</text><text x="165" y="90">x</text><text x="72" y="16">y</text></svg><p class="reminder-small">x &gt; 0 → rechts<br>x &lt; 0 → links<br>y &gt; 0 → omhoog<br>y &lt; 0 → omlaag</p></aside>`}
function render(m,header){
 const read=m.skill==='point',f=m.feedback,title=read?'Welke coördinaten heeft dit punt?':`Plaats P${esc(P.pair(m.task.target))}`;
 const feedback=f?`${f.result.ok?'✓ ':f.result.kind==='interaction_error'?'':'↻ '}${esc(f.result.message)}`:m.hintOpen?esc(m.task.hints[m.hints-1]):read?'Lees eerst x (horizontaal), daarna y (verticaal).':'Tik op het rooster om je punt te plaatsen of te verplaatsen.';
 const answers=read?`<div class="point-options" role="group" aria-label="Kies de coördinaten van P">${m.task.options.map((p,i)=>`<button type="button" data-choice="answer" data-value="${i}" aria-pressed="${String(m.values.answer)===String(i)}" ${f?'disabled':''}>${esc(P.pair(p))}</button>`).join('')}</div>`:`<div class="point-response ${f?.result.ok?'is-correct':''}">${f?.result.ok?S.icon('check',26):'<span aria-hidden="true">◎</span>'}<span>${m.values.point?'Jouw punt: '+esc(P.pair(m.values.point)):'Er staat nog geen punt.'}</span></div><p class="point-direction">Eerst x: links of rechts.<br>Daarna y: omhoog of omlaag.</p>`;
 const workspace=m.completed?`<section class="boundary-complete"><h1>Goed gedaan!</h1><p>Je hebt zes punten ${read?'gelezen':'geplaatst'}.</p><span class="proof-badge">${S.icon('check')} Oefening afgerond</span><button type="button" data-restart="puntenbaai" data-skill="${m.skill}">Opnieuw oefenen</button>${read?'<button type="button" data-start="puntenbaai" data-skill="point_plot">Nu zelf punten plaatsen →</button>':''}</section>`:`${reminder()}<div class="graph-paper"><button type="button" class="graph-undo icon-button" id="undo" aria-label="Maak laatste bewerking ongedaan" ${f||!m.history.length?'disabled':''}>${S.icon('undo',21)}</button><div class="evidence" data-representation="graph">${graph(m)}</div><span class="graph-paper-caption">${read?'Elk hokje is 1 eenheid':'Tikken of pijltjestoetsen · elk hokje is 1'}</span></div><section class="answer-tray points-answer"><span class="points-progress">${read?'Coördinaten lezen':'Coördinaten plaatsen'} · ${m.index+1} / ${P.count}</span><div class="exercise-heading"><h1>${title}</h1></div><p class="point-instruction">${read?'Kies het juiste antwoord.':'Zet het punt op de juiste plaats in het assenstelsel.'}</p>${answers}</section>`;
 const action=m.completed?`<button type="button" class="paint-button" data-screen="area" data-area="puntenbaai">Naar Puntenbaai ${S.icon('arrow')}</button>`:m.hints>=5&&!f?`<button type="button" class="paint-button" id="new-example">Nieuw punt ${S.icon('arrow')}</button>`:f?`<button type="button" class="paint-button" id="continue">${f.result.ok?(m.index===P.count-1?'Afronden':'Volgende'):'Herstel'} ${S.icon(f.result.ok?'arrow':'undo')}</button>`:`<button type="submit" class="paint-button" id="commit">Controleer ${S.icon('arrow')}</button>`;
 return `<form id="mission" class="boundary-mission points-mission" data-world="puntenbaai" data-skill="${m.skill}" data-phase="${m.phase}" novalidate>${header}<main class="boundary-workspace points-workspace">${workspace}</main><footer class="boundary-footer"><button type="button" class="paper-pill" id="pause" aria-label="Pauzeer en ga naar Puntenbaai">${S.icon('back')}<span>Vorige</span></button><div class="feedback-bubble"><button type="button" class="hint-button" id="hint" aria-label="Volgende hint" ${m.completed||f||m.hints>=5?'disabled':''}>${S.icon('light',23)}</button><div id="feedback" class="feedback ${f?f.result.ok?'success':'error':''}" role="status" aria-live="polite">${m.completed?'Je werk is bewaard in Mijn voortgang.':feedback}</div></div>${action}</footer></form><section id="rotateGate"><span class="rotate-symbol" aria-hidden="true">↻</span><h1>Even je scherm draaien</h1><p>Liggend heb je alle ruimte voor het rooster. Je werk blijft bewaard.</p><button type="button" class="paper-pill" data-screen="area" data-area="puntenbaai">Terug naar Puntenbaai</button></section>`;
}
return Object.freeze({render,graph});
});
