/* Presentation only. World availability is release scope, never a new unlock planner. */
(function(root,factory){if(typeof module==='object')module.exports=factory(require('./workbench.js'),require('../content/area-maps.js'));else root.RechtenV2Shell=factory(root.RechtenV2Workbench,root.RechtenV2Areas)})(globalThis,function(C,A){
'use strict';
const esc=C.esc;
const places=Object.freeze([
 {id:'puntenbaai',name:'Puntenbaai',number:1,art:0,caption:'Coördinaten',family:'F1'},
 {id:'hellingrug',name:'Hellingrug',number:2,art:1,caption:'Richting en helling',family:'F2'},
 {id:'grenspas',name:'Grenspas',number:3,art:3,caption:'Nulwaarden en tekens',family:'F6'},
 {id:'formulewerf',name:'Formulewerf',number:4,art:4,caption:'Voorschriften',family:'F7'},
 {id:'signaalstad',name:'Signaalstad',number:5,art:2,caption:'Functies en grafieken',family:'F3'}
]);
function icon(name,size=24){const paths={
 menu:'M4 6h16M4 12h16M4 18h16',profile:'M8 7a4 4 0 1 0 8 0a4 4 0 1 0-8 0M4 22c0-9 16-9 16 0',
 arrow:'M4 12h15M13 5l7 7-7 7',back:'M20 12H5M11 5l-7 7 7 7',chevron:'M9 5l7 7-7 7',
 lock:'M6 10h12v11H6zM8 10V6a4 4 0 0 1 8 0v4',check:'M5 12l4 5L20 5',
 map:'M3 5l6-3 6 3 6-3v17l-6 3-6-3-6 3zM9 2v17M15 5v17',
 graph:'M4 3v17h18M2 15l7-5 5 2 7-9',calculator:'M5 2h14v20H5zM8 5h8v4H8zM8 13h1M12 13h1M16 13h1M8 17h1M12 17h1M16 17h1',
 table:'M3 3h18v18H3zM3 9h18M3 15h18M9 3v18M15 3v18',
 light:'M8 15c-6-6-1-13 4-13s10 7 4 13l-1 3H9zM9 22h6M12 0v-2',
 undo:'M8 7H3V2M3 7c8-9 22 6 11 13',close:'M6 6l12 12M18 6L6 18',
 flag:'M6 22V3c5-4 8 5 14 0v10c-6 5-9-4-14 0',fire:'M13 2c2 6-4 7-1 11 1-3 4-4 5-6 8 11 1 16-5 16C5 23 1 16 6 10c-1 4 3 5 4 2-3-5 2-7 3-10z'
 };return `<svg class="ui-icon" width="${size}" height="${size}" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]||paths.graph}"/></svg>`}
function logo(){return `<svg class="brand-pencil" viewBox="0 0 28 52" aria-hidden="true"><path d="M3 43 20 7l7 4-18 35-6 4z" fill="#387fa4" stroke="#263e4c" stroke-width="2"/><path d="m3 43 6 3-6 4z" fill="#e9c994"/><path d="m20 7 2-4q2-3 5-1l1 3-1 6z" fill="#df8652"/><path d="m8 39 13-27" stroke="#c8ebf4" stroke-width="2"/></svg><span class="brand-lettering">leraarBob<small>TRAINER</small></span>`}
function route(state){return state.screen==='world'&&state.settings?.shell?.area?(A.selection(state).stop?'stop':'area'):state.screen}
function progress(state){const m=state.missions?.grenspas,done=(m?.completion||[]).filter(c=>c.variant===0||c.variant===1).length;const recorded=state.events?.some(e=>e.skill==='sign'&&e.correct&&((e.variant===0&&e.attemptId.startsWith('symbol:'))||(e.variant===1&&e.phase==='transfer')));const practice=Object.values(state.missions||{}).filter(x=>x.world==='grenspas'&&x.skill),finished=A.statuses(state,'grenspas').completed;return {m,done:done+finished,started:!!m||practice.length>0,complete:done>0||!!m?.completed||!!recorded||finished>0,phase:m?.phase||practice[0]?.phase||'root'};}
function header(state,{menuOpen=false,legacy=null,mission=false}={}){
 const screen=route(state),inArea=screen==='area'||screen==='stop'||mission,selected=A.selection(state),hillMission=mission&&['delta','slope','slope_from_two_points','line_behavior','special_lines'].includes(state.active),pointMission=mission&&state.missions?.[state.active]?.world==='puntenbaai',formulaMission=mission&&state.missions?.[state.active]?.world==='formulewerf',areaName=mission?(formulaMission?'Formulewerf':hillMission?'Hellingrug':pointMission?'Puntenbaai':'Grenspas'):selected.area.name,areaId=mission?(formulaMission?'formulewerf':hillMission?'hellingrug':pointMission?'puntenbaai':'grenspas'):selected.id,raw=legacy?.state||legacy;
 const stats=raw&&Number.isFinite(raw.xp)?`<div class="account-stats" aria-label="Bestaande voortgang">${Number.isFinite(raw.streak)?`<span class="streak">${icon('fire')}<span>${raw.streak} ${raw.streak===1?'dag':'dagen'}</span></span>`:''}<span class="xp-stat">${Math.max(0,raw.xp)} <small>XP</small></span></div>`:'';
 return `<header class="atlas-header"><a href="#wereld" class="atlas-brand" data-screen="world" aria-label="leraarBob, naar de Rechtenwereld">${logo()}</a><nav class="breadcrumbs" aria-label="Broodkruimelpad"><a href="#wereld" data-screen="world">${inArea?'Rechten':'Wereldkaart'}</a>${inArea?`${icon('chevron',17)}<a href="#${areaId}" data-screen="area" data-area="${areaId}" ${screen==='area'?'aria-current="page"':''}>${areaName}</a>`:''}${mission?`${icon('chevron',17)}<span class="crumb-question" aria-current="page">${formulaMission?({equation_from_ab:'Voorschrift uit a en b',graph_from_equation:'Rechte uit voorschrift',equation_from_graph:'Voorschrift uit grafiek',rewrite_linear_equation:'Vergelijking herschrijven',intercept_from_point:'b uit helling en punt',equation_from_point_slope:'Voorschrift uit helling en punt',equation_from_two_points:'Voorschrift uit twee punten'})[state.active]:hillMission?({delta:state.missions[state.active].phase==='hill-dy'?'Δy':'Δx en Δy',slope:'Richtingscoëfficiënt',slope_from_two_points:'Helling uit twee punten',line_behavior:'Stijgend, dalend of constant',special_lines:'Bijzondere rechten'}[state.active]):pointMission?(state.active==='point'?'Coördinaten lezen':'Coördinaten plaatsen'):({zeroRead:'Nulwaarde aflezen',zero:'Nulwaarde berekenen',signchart:'Tekenschema',positive:'Wanneer is f(x) &gt; 0?',negative:'Wanneer is f(x) &lt; 0?'})[state.active]||'Wanneer is f(x) '+(state.missions?.grenspas?.task.ask==='negative'?'&lt;':'&gt;')+' 0?'}</span>`:''}${screen==='book'?`${icon('chevron',17)}<span aria-current="page">Mijn voortgang</span>`:''}${screen==='profile'?`${icon('chevron',17)}<span aria-current="page">Profiel</span>`:''}</nav>${stats}<div class="atlas-actions"><button type="button" class="icon-button" data-screen="profile" aria-label="Profiel">${icon('profile',29)}</button><button type="button" class="icon-button" id="menu" aria-label="Menu" aria-controls="main-menu" aria-expanded="${menuOpen}">${icon(menuOpen?'close':'menu',29)}</button></div><nav class="atlas-menu" id="main-menu" aria-label="Hoofdmenu" ${menuOpen?'':'hidden'}><button type="button" data-screen="world">${icon('map')}Rechtenwereld</button><button type="button" data-screen="area" data-area="grenspas">${icon('flag')}Grenspas</button><button type="button" data-screen="book">${icon('graph')}Mijn voortgang</button><button type="button" data-screen="profile">${icon('profile')}Profiel</button><a href="../trainer/">Huidige trainer ${icon('arrow',18)}</a></nav></header>`;
}
function sprite(place){return `<span class="island-art art-${place.art}" aria-hidden="true"></span>`}
function sea(){return `<div class="sea-atmosphere" aria-hidden="true"><svg class="horizon" viewBox="0 0 1600 250" preserveAspectRatio="none"><path d="M0 190 110 126l84 43 98-114 94 109 48-27 128 62 210-124 144 96 117-80 93 64 182-142 143 142 49-41v137H0z" fill="#88b7c9" opacity=".2"/><path d="M870 68c8-43 59-43 66-10 8-10 29-8 33 9h48M350 90c9-22 36-22 41-5 5-35 57-30 57 0 17-14 34-4 39 5h60" fill="none" stroke="#f7fcf7" stroke-width="8" stroke-linecap="round" opacity=".65"/></svg></div>`}
function world(state,options){const completed=places.reduce((sum,p)=>sum+A.statuses(state,p.id,options?.legacy).completed,0),recommended=A.recommendation(state,options?.legacy);return `<div class="atlas-page world-page">${header(state,options)}<main class="atlas-main">${sea()}<section class="map-intro paper-note"><span class="tape-label">RECHTEN</span><h1>Rechtenwereld</h1><p>Ontdek rechten.<br>Stap voor stap.</p></section><div class="world-map" aria-label="Vijf gebieden van de Rechtenwereld"><div class="world-stage"><svg class="map-paths map-paths-wide" viewBox="0 0 1000 700" preserveAspectRatio="none" aria-hidden="true"><path d="M140 460Q230 140 440 200T510 470Q700 380 820 470T810 180"/></svg><svg class="map-paths map-paths-tall" viewBox="0 0 1000 700" preserveAspectRatio="none" aria-hidden="true"><path d="M250 120Q520 80 750 120L500 360 250 570Q480 490 770 570"/></svg>${places.map(place=>{const summary=A.statuses(state,place.id,options?.legacy),status=summary.completed===summary.total?'completed':place.id===recommended.id?'current':'available';return `<button type="button" class="island-node place-${place.id==='puntenbaai'?'puntbaai':place.id} is-${status}" data-world-node="${place.id}" data-state="${status}" data-screen="area" data-area="${place.id}" aria-label="${place.name}, ${summary.total} haltes, openen">${sprite(place)}<span class="island-marker">${status==='completed'?icon('check',26):place.number}</span><span class="island-label">${place.name}<small>${status==='current'?'Jouw volgende gebied':summary.completed?summary.completed+' / '+summary.total+' afgerond':summary.total+' haltes · ontdek'}</small></span>${status==='current'?'<span class="current-rays" aria-hidden="true"></span>':''}</button>`}).join('')}</div></div><div class="map-compass" aria-hidden="true">N<span>✧</span></div></main><footer class="atlas-footer"><button type="button" class="paper-pill progress-link" data-screen="book">${icon('map',28)}<span>Mijn voortgang<span class="small-meter" aria-hidden="true"><i style="width:${Math.round(completed/28*100)}%"></i></span></span>${icon('chevron',20)}</button><span class="footer-context">Je volgende plek: <strong>${A.get(recommended.id).name}</strong></span><button type="button" class="paint-button" id="start-recommended" data-screen="area" data-area="${recommended.id}" data-zone="${recommended.zone}">Verder ${icon('arrow',27)}</button></footer></div>`}
const stateText={current:'Huidige halte',completed:'Afgerond',locked:'Nog vergrendeld',available:'Beschikbaar'};
function nodeAction(n,id,zone){return n.playable?`data-start="${id}"${id==='formulewerf'?` data-formula-skill="${n.id}"`:id==='grenspas'?` data-grens-skill="${n.key}"`:['puntenbaai','hellingrug'].includes(id)?` data-point-skill="${n.id}"`:''}`:`data-screen="stop" data-area="${id}" data-zone="${zone}" data-stop="${n.key}"`}
function area(state,options){const {id,area:a,zone}=A.selection(state),summary=A.statuses(state,id,options?.legacy),nodes=summary.nodes.filter(n=>zone.nodes.some(s=>s.key===n.key)),recommended=id==='formulewerf'?nodes.find(n=>n.recommended):nodes.find(n=>n.recommended)||nodes.find(n=>n.state==='current'||n.state==='available')||nodes.find(n=>n.state!=='completed')||nodes[0];
 const formula=id==='formulewerf',nextZone=summary.recommended&&a.zones.find(z=>z.nodes.some(n=>n.key===summary.recommended.key));
 const nextAction=formula&&!recommended?(summary.recommended?`<button type="button" class="paint-button" data-screen="area" data-area="formulewerf" data-zone="${nextZone.id}">Naar werkplaats ${nextZone.badge} ${icon('arrow',27)}</button>`:'<button type="button" class="paint-button" disabled>Geen halte beschikbaar</button>'):`<button type="button" class="paint-button" ${nodeAction(recommended,id,zone.id)}> ${recommended.playable?'Oefen halte '+recommended.number:'Volgende: halte '+recommended.number} ${icon('arrow',27)}</button>`;
 const segments=nodes.slice(1).map((n,i)=>`<path d="M${nodes[i].x*10} ${nodes[i].y*10} L${n.x*10} ${n.y*10}"/>`).join('');
 const zones=a.zones.length>1?`<nav class="area-zones" aria-label="Werkplaatsen in Formulewerf">${a.zones.map((z,i)=>`<button type="button" data-screen="area" data-area="${id}" data-zone="${z.id}" ${z===zone?'aria-current="page"':''}><span>${z.badge||i+1}</span> ${z.name}</button>`).join('')}</nav>`:'';
 return `<div class="atlas-page area-page mapped-area" data-area-id="${id}" data-zone-id="${zone.id}">${header(state,options)}<main class="atlas-main">${sea()}<section class="map-intro area-intro"><span class="tape-label">${formula?'FORMULEWERF · WERKPLAATS '+zone.badge:summary.total+' HALTES · '+summary.completed+' AFGEROND'}</span><h1>${formula?zone.name:a.name}</h1><p>${formula?zone.intro:a.intro}</p><div class="area-legend"><span>◉ Volgende</span><span>✓ Afgerond</span><span>${icon('lock',12)} Later</span></div></section>${zones}<div class="area-map" aria-label="${a.name}: ${zone.name}"><div class="area-stage" data-density="${nodes.length>5?'dense':'normal'}"><img class="area-island" src="assets/${a.art}-island.webp" width="1536" height="1024" alt="" fetchpriority="high"><svg class="area-paths" viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-hidden="true">${segments}</svg>${nodes.map(n=>`<button type="button" class="skill-node skill-${n.key} is-${n.state} ${n===recommended?'is-recommended':''}${n.culmination?' is-route-finish':''}" style="--x:${n.x}%;--y:${n.y}%" data-skill="${n.id}" data-node="${n.key}" data-state="${n.state}" ${n.variant?`data-variant="${n.variant}"`:''} ${nodeAction(n,id,zone.id)} ${n===recommended?'aria-current="step"':''} aria-label="${n.number}. ${esc(n.name)}. ${stateText[n.state]}. ${n===recommended?'Aanbevolen volgende halte. ':''}${n.playable?'Oefenen':'Halte bekijken'}"><span class="skill-marker">${n.state==='completed'?icon('check',30):`<span class="stop-number">${n.number}</span>`}${n.state==='locked'?'<span class="skill-lock" aria-hidden="true">'+icon('lock',12)+'</span>':''}</span><span class="skill-label">${n.label}${n.culmination?'<small>Alles komt samen</small>':''}</span></button>`).join('')}</div></div></main><footer class="atlas-footer"><button type="button" class="paper-pill" data-screen="world">${icon('back',25)}<span>Terug naar kaart</span></button><span class="footer-context">${zone.name} · ${nodes.length} haltes</span>${nextAction}</footer></div>`;
}
function stop(state,options){const {id,area:a,zone,stop:n}=A.selection(state);if(!n)return area(state,options);const status=A.statuses(state,id,options?.legacy).nodes.find(s=>s.key===n.key);return `<div class="atlas-page stop-page">${header(state,options)}<main class="stop-main">${sea()}<section class="stop-paper"><span class="tape-label">${a.name} · HALTE ${n.number}</span><h1>${esc(n.name)}</h1><span class="proof-badge">${icon(status.state==='completed'?'check':status.state==='locked'?'lock':'flag')} ${stateText[status.state]}</span>${n.playable?`<button type="button" class="paint-button" ${nodeAction(n,id,zone.id)}>Oefenen ${icon('arrow')}</button>`:'<p>De oefening voor deze halte komt later.</p>'}<p class="stop-note">${status.state==='locked'?'Deze halte is nog vergrendeld. Je kunt de route alvast verkennen.':'Je plek in de route blijft bewaard.'}</p></section></main><footer class="atlas-footer"><button type="button" class="paper-pill" data-screen="world">${icon('back')}Terug naar kaart</button><button type="button" class="paint-button" data-screen="area" data-area="${id}" data-zone="${zone.id}" data-return-node="${n.key}">Terug naar ${a.name} ${icon('arrow')}</button></footer></div>`}
function book(state,options){const p=progress(state),supported=state.events.filter(e=>e.correct&&e.supported).length,independent=state.events.filter(e=>e.correct&&e.independent).length;return `<div class="atlas-page journal-page">${header(state,options)}<main class="journal-main"><section class="journal-paper"><span class="tape-label">MIJN VOORTGANG</span><h1>Elke stap telt.</h1><p class="journal-lead">Je ontdekkingen blijven hier bewaard.</p><div class="progress-story">${sprite(places[2])}<div><span class="eyebrow">GRENSPAS</span><h2>Grenspas</h2><p>${p.complete?'Je eerste oefening is afgerond.':p.started?'Je bent op weg. Je laatste stap staat klaar.':'Je avontuur begint bij de grens.'}</p><span class="proof-badge">${p.complete?icon('check'):icon('flag')}${p.complete?'Oefening afgerond':p.started?'In uitvoering':'Nog te ontdekken'}</span></div></div><div class="proof-counts"><p><strong>${supported}</strong><span>stappen met begeleiding</span></p><p><strong>${independent}</strong><span>stappen zelfstandig</span></p></div><p class="journal-footnote">Afgerond werk is oefenbewijs. Beheersing groeit met herhalen.</p></section></main><footer class="atlas-footer"><button type="button" class="paper-pill" data-screen="world">${icon('back')}<span class="back-label-full">Terug naar kaart</span><span class="back-label-short">Kaart</span></button><button type="button" class="paint-button" data-screen="area" data-area="grenspas">Naar Grenspas ${icon('arrow')}</button></footer></div>`}
function profile(state,options){const {account,status}=options;return `<div class="atlas-page profile-page">${header(state,options)}<main class="journal-main"><section class="journal-paper profile-paper"><span class="profile-avatar">${icon('profile',42)}</span><h1>Jouw plek</h1><p>${account?account.role==='teacher'?'Je bekijkt de wereld als docent.':'Je oefent met je leerlingaccount.':'Je oefent als gast op dit toestel.'}</p><p class="storage-status" id="save-status" role="status">${esc(status)}</p><div class="profile-actions"><a class="paint-button account-link" href="../../../?login=1&amp;return=games/rechten/trainer-v2/">${account?'Account openen':'Inloggen'} ${icon('arrow',22)}</a><button type="button" id="sync">Synchroniseren</button><button type="button" id="backup">Bewaar een kopie</button></div><label class="motion-setting"><input type="checkbox" id="reduced-motion" ${state.settings.reducedMotion?'checked':''}> Minder beweging</label></section></main><footer class="atlas-footer"><button type="button" class="paper-pill" data-screen="world">${icon('back')}<span class="back-label-full">Terug naar kaart</span><span class="back-label-short">Kaart</span></button></footer></div>`}
return Object.freeze({places,icon,header,route,progress,world,area,stop,book,profile});
});
