/* A4 worksheets and worked keys, rendered once for preview, printing and PDF. */
(()=>{'use strict';const C=StelselsCore,W=1240,H=1754;
const names={substitution:'Substitutie',combination:'Combinatie',graphic:'Grafisch'},levels={beginner:'Beginner',basis:'Basis',advanced:'Verdieping'};
function page(title,subtitle,footer){const canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const g=canvas.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,W,H);g.fillStyle='#203f43';g.font='bold 38px Georgia';g.fillText(title,80,90);g.font='22px sans-serif';g.fillText(subtitle,80,132);g.strokeStyle='#66857d';g.beginPath();g.moveTo(80,157);g.lineTo(1160,157);g.stroke();g.font='18px sans-serif';g.fillStyle='#526a6d';g.fillText('leraarBob · Algebra / Stelsels',80,H-48);g.textAlign='right';g.fillText(footer,1160,H-48);g.textAlign='left';return {canvas,g}}
function line(g,text,x,y,max=1050,size=25){g.font=`${size}px sans-serif`;while(g.measureText(text).width>max&&size>16){size--;g.font=`${size}px sans-serif`}g.fillText(text,x,y)}
function system(g,s,x,y,raw){g.fillStyle='#203f43';g.font='70px Georgia';g.fillText('{',x,y+51);s.forEach((e,i)=>line(g,raw&&raw.row===i?raw.text:C.eqText(e),x+38,y+24+i*37,950,27))}
function graph(g,s,x,y,size,answers=false){const extent=8,u=size/(extent*2),px=v=>x+(v+extent)*u,py=v=>y+(extent-v)*u;g.save();g.strokeStyle='#e0e6e4';g.lineWidth=1;for(let v=-extent;v<=extent;v+=.5){g.strokeStyle=Number.isInteger(v)?'#c5d3ce':'#edf0ee';g.beginPath();g.moveTo(px(v),y);g.lineTo(px(v),y+size);g.moveTo(x,py(v));g.lineTo(x+size,py(v));g.stroke()}g.strokeStyle='#526a6d';g.lineWidth=2;g.beginPath();g.moveTo(x,py(0));g.lineTo(x+size,py(0));g.moveTo(px(0),y);g.lineTo(px(0),y+size);g.stroke();g.fillStyle='#203f43';g.font='15px sans-serif';for(let v=-8;v<=8;v+=2){if(!v)continue;g.fillText(v,px(v)+3,py(0)+17);g.fillText(v,px(0)+5,py(v)-3)}g.fillText('x',x+size-12,py(0)-8);g.fillText('y',px(0)+8,y+16);if(answers){g.beginPath();g.rect(x,y,size,size);g.clip();s.forEach((e,i)=>{const r=C.reduced(e);g.strokeStyle=i?'#a6534d':'#24728b';g.lineWidth=3;g.setLineDash(i?[10,5]:[]);g.beginPath();if(r.y.isZero()){const v=r.c.neg().div(r.x).value();g.moveTo(px(v),y);g.lineTo(px(v),y+size)}else{const vy=v=>r.x.mul(C.R(v)).add(r.c).neg().div(r.y).value();g.moveTo(px(-8),py(vy(-8)));g.lineTo(px(8),py(vy(8)))}g.stroke()})}g.restore()}
function result(sol){return sol.kind==='unique'?`Oplossing: (x, y) = (${C.text(sol.x)}, ${C.text(sol.y)})`:sol.kind==='none'?'Geen oplossing.':'Oneindig veel oplossingen.'}
async function build(exercises,method,includeKey){const pages=[];const add=p=>{const url=p.canvas.toDataURL('image/jpeg',.94);pages.push({url,width:W,height:H,bytes:Uint8Array.from(atob(url.split(',')[1]),c=>c.charCodeAt(0))});p.canvas.width=0};
 const perPage=exercises[0]?.level==='advanced'&&method!=='graphic'?1:2;for(let i=0;i<exercises.length;i+=perPage){const {canvas,g}=page('Stelsels · Oefenblad',`${names[method]} · ${levels[exercises[i].level]} · Reeks ${exercises[0].seed.toString(36).toUpperCase()}`,`Opgaven ${i+1}–${Math.min(i+perPage,exercises.length)}`);g.font='22px sans-serif';g.fillText('Naam: __________________________   Klas: __________   Datum: __________',80,202);for(let j=0;j<perPage&&i+j<exercises.length;j++){const ex=exercises[i+j],y=250+j*680;g.fillStyle='#203f43';g.font='bold 24px sans-serif';g.fillText(`${i+j+1}. Los het stelsel op.`,80,y);system(g,ex.start,90,y+20);if(method==='graphic'){graph(g,ex.start,100,y+130,440);line(g,'Teken beide rechten.',590,y+165,540,22);line(g,'Lees de oplossing af en controleer.',590,y+200,540,22);line(g,'Rasterstap: ½ · aslabels per 2.',590,y+235,540,20);line(g,'Oplossing: __________________',590,y+420,540,22)}else{line(g,'Behoud bij elke stap het volledige stelsel.',90,y+130,1050,21);g.strokeStyle='#dbe1dc';g.lineWidth=1;for(let k=0;k<(perPage===1?14:8);k++){g.beginPath();g.moveTo(90,y+210+k*(perPage===1?74:48));g.lineTo(1150,y+210+k*(perPage===1?74:48));g.stroke()}}}add({canvas,g});await new Promise(r=>setTimeout(r,0))}
 if(includeKey)for(let i=0;i<exercises.length;i++){const ex=exercises[i];if(method==='graphic'){const {canvas,g}=page(`Verbetersleutel · ${i+1}`,`${names[method]} · één mogelijke uitwerking`,'Sleutel · '+(i+1));system(g,ex.start,90,185);graph(g,ex.start,210,320,780,true);line(g,'I: volle lijn · II: stippellijn',210,1145,1000,23);ex.start.forEach((e,j)=>{const p=C.graphPoints(e);line(g,`${j?'II':'I'}: bijvoorbeeld (${C.text(p[0].x)}, ${C.text(p[0].y)}) en (${C.text(p[1].x)}, ${C.text(p[1].y)})`,90,1210+j*48,1070,24)});line(g,result(ex.solution),90,1380,1070,28);line(g,'Controle: vul de coördinaten in beide oorspronkelijke vergelijkingen in.',90,1430,1070,21);add({canvas,g})}else{const steps=C.canonical(ex,method);for(let p=0;p<steps.length;p+=12){const {canvas,g}=page(`Verbetersleutel · ${i+1}`,`${names[method]} · andere equivalente routes zijn ook correct`,`Sleutel ${i+1} · deel ${Math.floor(p/12)+1}`);steps.slice(p,p+12).forEach((st,j)=>{const y=205+j*112;g.fillStyle='#526a6d';line(g,`${p+j}. ${st.label}`,80,y,1080,21);system(g,st.system,95,y+20,st.raw)});if(p+12>=steps.length){g.fillStyle='#203f43';line(g,result(ex.solution),80,1580,1080,27)}add({canvas,g})}}await new Promise(r=>setTimeout(r,0))}
 return pages;
}
window.StelselsPaper={build,graph,result};})();
