/* Direct graph measurements, followed by reusable rule tiles. */
(function(root,factory){if(typeof module==='object')module.exports=factory(require('../ab-core.js'),require('./workbench.js'),require('./shell-view.js'),require('../../core/wave-core.js'),require('../semantic-math-core.js'),require('./graph-scale.js'));else root.RechtenV2ABView=factory(root.RechtenV2AB,root.RechtenV2Workbench,root.RechtenV2Shell,root.RechtenWave,root.RechtenV2Math,root.RechtenV2GraphScale)})(globalThis,function(B,C,S,W,M,K){
'use strict';const esc=C.esc;let seq=0;
const number=v=>{const q=M.parse(v);return q?W.html(q):esc(v)};
function graph(m){
 const t=m.task,v=m.values,editable=!m.feedback&&['ab-intercept','ab-slope'].includes(m.phase),scale=K.line(t.model,{step:t.gridStep}),{X,Y,grid}=scale,id='ab-plot-'+ ++seq;
 const b=M.parse(v.b),a=M.parse(v.a),endpoint=b&&a?W.add(b,a):null,visible=q=>q&&Math.abs(W.num(q))<=scale.radius;
 const given=`M${X(-scale.radius)} ${Y(W.add(W.mul(t.model.a,-scale.radius),t.model.b))}L${X(scale.radius)} ${Y(W.add(W.mul(t.model.a,scale.radius),t.model.b))}`;
 const candidate=m.phase==='ab-rule'?B.rule(v):null,candidateLine=candidate?`<path class="ab-candidate" d="M${X(-scale.radius)} ${Y(W.add(W.mul(candidate.a,-scale.radius),candidate.b))}L${X(scale.radius)} ${Y(W.add(W.mul(candidate.a,scale.radius),candidate.b))}"/>`:'';
 const point=(x,y,label,cls)=>`<g class="ab-pin ${cls}"><circle cx="${X(x)}" cy="${Y(y)}" r="7"/><text x="${X(x)-13}" y="${Y(y)-11}" text-anchor="end">${label}</text></g>`;
 const failure=m.feedback&&!m.feedback.result.ok&&m.feedback.result.kind!=='interaction_error'?' is-incorrect':'';
 const pins=(visible(b)?point(0,b,'b','ab-pin-b'+(m.phase==='ab-intercept'?failure:'')):'')+(m.phase!=='ab-intercept'&&visible(endpoint)?point(1,endpoint,'P','ab-pin-step'+(m.phase==='ab-slope'?failure:'')):'');
 let measurement='';if(m.phase!=='ab-intercept'&&visible(b)){
  measurement=`<path class="ab-horizontal-step" d="M${X(0)} ${Y(b)}H${X(1)}" marker-end="url(#${id}-arrow)"/><text class="ab-measure-label" x="${X(.5)}" y="${Y(b)+29}" text-anchor="middle">Δx = 1</text>`;
  if(visible(endpoint))measurement+=`<path class="ab-vertical-step" d="M${X(1)} ${Y(b)}V${Y(endpoint)}"/><text class="ab-measure-label" x="${X(1)+18}" y="${(Y(b)+Y(endpoint))/2-8}">Δy = ${esc(W.text(a))}</text>`;
 }
 const label=m.phase==='ab-intercept'?'Plaats het snijpunt op de y-as. Tik in de grafiek of gebruik omhoog en omlaag.':m.phase==='ab-slope'?'Maak vanaf b één stap naar rechts en de verticale stap naar de rechte. Tik of gebruik omhoog en omlaag.':'De gegeven rechte en jouw meting van a en b.';
 return `<svg class="math-graph boundary-graph formula-graph ab-graph" viewBox="0 0 500 500" ${scale.attributes} role="${editable?'group':'img'}" ${editable?'tabindex="0" data-ab-picker':''} aria-label="${label}"><title>${label}</title><desc>Genummerde assen met gelijke eenheden. Gebruik ook het waardeveld en de plus- en minknoppen.</desc><defs><clipPath id="${id}"><path d="M48 48h404v404H48z"/></clipPath><marker id="${id}-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="4" markerHeight="4" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="#627d88"/></marker></defs><g class="graph-grid">${grid}</g>${editable?`<path class="ab-focus-axis" d="M${X(m.phase==='ab-intercept'?0:1)} 50V450"/>`:''}<path class="axis" d="M30 250H474M250 470V26"/><path class="axis-arrow" d="m465 243 10 7-10 7M243 36l7-11 7 11"/><text class="axis-origin" x="247" y="273" text-anchor="end">0</text><text class="axis-name" x="480" y="255">x</text><text class="axis-name" x="263" y="28">y</text><g clip-path="url(#${id})"><path class="ab-given-line" d="${given}"/>${candidateLine}${measurement}${pins}</g></svg>`;
}
function retained(m){return `<div class="ab-retained" aria-label="Jouw gevonden waarden">${['b','a'].filter(name=>m.locks[name]).map(name=>`<span data-parameter="${name}"><strong>${name}</strong> = ${number(m.values[name])}</span>`).join('')}</div>`}
function measurement(m,name,label){return `<div class="ab-measure-control"><label for="ab-${name}">${label}</label><div><button type="button" data-ab-adjust="-1" aria-label="${name==='b'?'Verplaats b één omlaag':'Maak de verticale stap kleiner'}" ${m.feedback?'disabled':''}>−</button><input id="ab-${name}" name="${name}" type="text" inputmode="text" autocomplete="off" maxlength="16" value="${esc(m.values[name]??'')}" placeholder="?" aria-label="${label}" ${m.feedback?'readonly':''}><button type="button" data-ab-adjust="1" aria-label="${name==='b'?'Verplaats b één omhoog':'Maak de verticale stap groter'}" ${m.feedback?'disabled':''}>+</button></div></div>`}
function builder(m){const slot=m.values.formulaSlot||'factor',labels={factor:'Coëfficiënt a vóór x',variable:'Variabele x',operator:'Teken van de constante term',constant:'Getal van de constante term'},locked=name=>m.feedback||m.locks[name];
 const tokens=m.task.tokens.filter(token=>slot==='variable'?token==='x':slot==='operator'?['+','−'].includes(token):!!M.parse(token));
 return `<div class="ab-builder" role="group" aria-label="Jouw functievoorschrift"><span>y =</span>${Object.keys(labels).map(name=>`<button type="button" class="formula-slot ${m.values[name]?'is-filled':'is-empty'}" data-formula-slot="${name}" aria-label="${labels[name]}: ${esc(m.values[name]||'nog invullen')}" aria-pressed="${slot===name}" ${locked(name)?'disabled':''}>${m.values[name]?number(m.values[name]):'?'}</button>`).join('')}</div><div class="ab-tokens" role="group" aria-label="Bouwstenen voor ${labels[slot]}">${tokens.map(token=>`<button type="button" data-formula-token="${esc(token)}" draggable="${!m.feedback}" aria-label="Bouwsteen ${esc(token)}" ${m.feedback?'disabled':''}>${number(token)}</button>`).join('')}</div><p class="ab-help">Kies een vakje. Tik of sleep daarna een bouwsteen.</p>`;
}
function answer(m){
 if(m.phase==='ab-intercept')return `<h2>Markeer het snijpunt</h2><p class="ab-instruction">Plaats je punt waar de rechte de y-as raakt. Die hoogte is <strong>b</strong>.</p>${measurement(m,'b','b · hoogte op de y-as')}<p class="ab-help">Tik in de grafiek, gebruik de knoppen of vul een getal in.</p>`;
 if(m.phase==='ab-slope')return `<h2>Meet de helling</h2><p class="ab-instruction">Ga één naar rechts. Maak de verticale stap tot je eindpunt op de rechte ligt.</p>${measurement(m,'a','a · verandering per stap x')}<p class="ab-help">Omhoog is positief, omlaag negatief.${m.task.gridStep===.5?' Gebruik halve stappen: 0,5 of 1/2.':''}</p>`;
 return `<h2>Bouw je voorschrift</h2><p class="ab-instruction">Gebruik jouw a en b in de vorm y = ax + b.</p>${builder(m)}`;
}
function steps(m){const current=m.completed?3:B.phases.indexOf(m.phase);return `<ol class="ab-steps" aria-label="Stappen van de oefening">${['Vind b','Meet a','Bouw'].map((label,i)=>`<li ${i===current?'aria-current="step"':''} class="${i<current?'is-done':''}"><span>${i<current?'✓':i+1}</span>${label}</li>`).join('')}</ol>`}
function render(m,header){const f=m.feedback,complete=m.completed,feedback=complete?'Je werk is bewaard.':f?(f.result.ok?'✓ ':'')+esc(f.result.message):m.hintOpen&&m.hints?esc(m.task.hints[m.hints-1]):m.phase==='ab-intercept'?'Plaats eerst het snijpunt.':m.phase==='ab-slope'?'Controleer of je eindpunt op de rechte ligt.':'Laat je voorschrift bij de rechte passen.';
 const done=`<section class="ab-complete"><span class="ab-complete-mark" aria-hidden="true">✓</span><h2>Je vindt a en b in een grafiek</h2><p>Je hebt zes rechten onderzocht en hun voorschrift gebouwd.</p><button type="button" data-restart="signaalstad" data-skill="ab">Opnieuw oefenen</button></section>`;
 const action=complete?'<button type="button" class="primary" data-screen="area" data-area="signaalstad">Naar Signaalstad →</button>':m.hints>=5&&!f?'<button type="button" class="primary" id="new-example">Nieuw geval →</button>':f?`<button type="button" class="primary" id="continue">${f.result.ok?(m.phase==='ab-intercept'?'Meet nu a':m.phase==='ab-slope'?'Bouw de regel':m.index===B.count-1?'Afronden':'Volgende grafiek'):'Probeer opnieuw'} →</button>`:'<button type="submit" class="primary" id="commit">Controleer →</button>';
 return `<form id="mission" class="boundary-mission ab-mission" data-world="signaalstad" data-skill="ab" data-phase="${m.phase}" novalidate>${header}<main class="boundary-workspace ab-workspace"><header class="ab-heading"><div><span class="ab-eyebrow">Signaalstad · Level 2 · Opgave ${Math.min(m.index+1,B.count)} / ${B.count}</span><h1>${complete?'Goed gedaan!':'Vind a en b in de grafiek'}</h1></div>${steps(m)}</header>${complete?done:`<section class="ab-paper ab-graph-paper" aria-label="Gegeven grafiek"><header><h2>Gegeven rechte</h2>${retained(m)}</header><div class="ab-graph-wrap">${graph(m)}</div><p class="ab-graph-caption">${m.phase==='ab-rule'?'<span class="ab-line-key">━ Gegeven rechte</span><span class="ab-draft-key">┄ Jouw voorschrift</span>':m.task.gridStep===.5?'Een klein hokje is ½ = 0,5.':'Een hokje is 1 eenheid.'}</p></section><section class="ab-paper ab-answer answer-tray" aria-label="Jouw antwoord">${answer(m)}</section>`}</main><footer class="boundary-footer ab-footer"><div class="ab-history"><button type="button" id="pause" aria-label="Pauzeer en ga naar Signaalstad">${S.icon('back',22)}</button><button type="button" id="undo" aria-label="Maak laatste bewerking ongedaan" ${f||complete||!m.history.length?'disabled':''}>${S.icon('undo',22)}</button></div><div class="feedback-bubble"><button type="button" class="hint-button" id="hint" aria-label="Volgende hint" ${complete||f||m.hints>=5?'disabled':''}>${S.icon('light',22)}</button><div id="feedback" class="feedback ${f?f.result.ok?'success':'error':''}" role="status" aria-live="polite">${feedback}</div></div>${action}</footer></form><section id="rotateGate"><span class="rotate-symbol" aria-hidden="true">↻</span><h1>Even je scherm draaien</h1><p>Liggend heb je ruimte voor de grafiek en je meting. Je werk blijft bewaard.</p><button type="button" class="paper-pill" data-screen="area" data-area="signaalstad">Terug naar Signaalstad</button></section>`;
}
return Object.freeze({render,graph});
});
