/* The toll gate leads from Formulewerf to Signaalstad after the caravan calculation. */
(function(root,factory){if(typeof module==='object')module.exports=factory(require('./workbench.js'),require('./shell-view.js'),require('../context-core.js'),require('../../core/wave-core.js'));else root.RechtenV2ContextView=factory(root.RechtenV2Workbench,root.RechtenV2Shell,root.RechtenV2Context,root.RechtenWave)})(globalThis,function(C,S,X,W){
'use strict';const esc=C.esc;
const titles={'context-start':'De tolpoort naar Signaalstad','context-add':'Eén kar door de poort','context-table':'Er komt een kar bij','context-check':'De tol voor jouw karavaan','context-rule':'De regel van de tolpoort','context-plot':'De tol in een grafiek'};
const activeField=m=>{const open=X.numericFields(m.phase).filter(k=>!m.locks[k]);return open.includes(m.values.contextField)?m.values.contextField:open[0]};
function field(m,key,label){return `<button type="button" class="context-number" data-context-field="${key}" aria-pressed="${activeField(m)===key}" aria-label="${esc(label)}, munten: ${esc(m.values[key]||'leeg')}" ${m.feedback||m.locks[key]?'disabled':''}><small>${esc(label)}</small><strong><span class="toll-coin" aria-hidden="true">●</span> ${esc(m.values[key]||'?')}</strong></button>`}
function keypad(m){if(m.feedback||!activeField(m))return '';return `<div class="context-keypad" role="group" aria-label="Aantal munten invoeren">${['1','2','3','4','5','6','7','8','9','clear','0','back'].map(k=>`<button type="button" data-context-key="${k}" aria-label="${k==='back'?'Laatste cijfer wissen':k==='clear'?'Vakje leegmaken':k}">${k==='back'?'⌫':k==='clear'?'C':k}</button>`).join('')}</div>`}
function goal(t){return `<div class="toll-goal"><span>Karavaan: <strong>${t.groupSize} karren</strong></span><span>→ <strong>Signaalstad</strong></span></div>`}
function cart(){return `<svg class="toll-cart" viewBox="0 0 70 45" aria-hidden="true"><path d="M7 9h43v22H7Z" fill="#d3ab71" stroke="#506768" stroke-width="2"/><path d="M13 9V3h12v6m5 0V3h13v6" fill="#e4cc9e" stroke="#506768" stroke-width="2"/><path d="M50 26h14" stroke="#506768" stroke-width="3"/><circle cx="17" cy="34" r="8" fill="#284c54"/><circle cx="41" cy="34" r="8" fill="#284c54"/><circle cx="17" cy="34" r="3" fill="#fff9ed"/><circle cx="41" cy="34" r="3" fill="#fff9ed"/></svg>`}
function gate(open=false){return `<svg class="toll-gate ${open?'is-open':''}" viewBox="0 0 72 64" aria-hidden="true"><path d="M7 60V13h12v47m34 0V13h12v47M4 13V4h18v9M50 13V4h18v9" fill="#aac1b9" stroke="#506768" stroke-width="2"/><path d="M19 19h34v5H19Z" fill="#b69263" stroke="#506768" stroke-width="2"/><g class="toll-barrier"><path d="M19 35h34v6H19Z" fill="#edc55b" stroke="#506768" stroke-width="2"/><path d="M28 37h6m6 0h6" stroke="#506768" stroke-width="2"/></g></svg>`}
function picture(m){const t=m.task,first=m.phase==='context-start',n=m.phase==='context-add'?1:t.groupSize;return `<section class="context-evidence">${goal(t)}<div class="toll-pricecards"><div class="toll-fee"><span>Poort openen</span><strong>${t.gateFee}</strong><small>Munten · één keer</small></div><div class="toll-unit"><span>Per kar</span><strong>${t.perUnit}</strong><small>Munten · elke kar</small></div></div><div class="toll-caravan" aria-label="${n} ${n===1?'kar wacht':'karren wachten'} bij de tolpoort"><div class="toll-carts">${Array.from({length:n},cart).join('')}</div>${gate()}</div><p class="context-axis-note">${first?'De wachter vraagt tol voor je karavaan. Bereken hoeveel munten je moet betalen.':'Een extra kar erbij? De poort gaat nog steeds maar één keer open.'}</p></section>`}

function table(m){const v=m.values;return `<section class="context-evidence">${goal(m.task)}<table class="context-table"><caption>Karren + één keer openen</caption><thead><tr><th scope="col">Karren</th><th scope="col">Tol in munten</th></tr></thead><tbody>${[1,2,3].map((x,i)=>{const key=['onePrice','twoPrice','threePrice'][i];return `<tr><th scope="row">${x}</th><td>${m.phase==='context-table'&&x>=2?field(m,key,`Bij ${x} karren`):esc(v[key]??'?')}</td></tr>`}).join('')}</tbody></table></section>`}
function graph(m){
 const t=m.task,v=m.values,editable=!m.feedback&&!m.completed,sx=x=>60+80*x,sy=y=>380-20*y;
 let grid='';for(let x=0;x<=4;x++)grid+=`<path d="M${sx(x)} 60V380"/><text x="${sx(x)}" y="409" text-anchor="middle">${x}</text>`;
 for(let y=0;y<=16;y++)grid+=`<path ${y%2?'class="toll-minor-grid"':''} d="M60 ${sy(y)}H380"/>${y%2?'':`<text x="48" y="${sy(y)+7}" text-anchor="end">${y}</text>`}`;
 const points=X.plotXs.map((x,i)=>{const y=W.parse(v['plotY'+(i+1)]);return y?{x,y:W.num(y)}:null});
 const line=points.every(Boolean)?`<path class="context-line context-line-a" d="M${sx(points[0].x)} ${sy(points[0].y)}L${sx(points[1].x)} ${sy(points[1].y)}"/>`:'';
 const active=activeField(m)==='plotY2'?1:0;
 return `<section class="context-graph-wrap"><svg class="context-graph" viewBox="0 0 440 440" role="img" ${editable?'data-context-graph':''} aria-label="Tolgrafiek. Onderaan: 0 tot 4 karren. Omhoog: 0 tot 16 munten. Elk horizontaal lijntje is één munt. Vul de tol bij 1 en 3 karren in; je kunt ook op de grafiek tikken."><defs><clipPath id="context-clip"><rect x="60" y="60" width="320" height="320"/></clipPath></defs><g class="context-grid">${grid}</g><path class="context-axes" d="M60 48V380H392"/><text x="65" y="30">Tol (munten)</text><text x="285" y="436">Karren</text><g clip-path="url(#context-clip)">${editable?`<path class="toll-guide" d="M${sx(X.plotXs[active])} 60V380"/>`:''}${line}${points.map(p=>p?`<circle class="context-line-a" cx="${sx(p.x)}" cy="${sy(p.y)}" r="7"/>`:'').join('')}</g></svg><div class="context-legend">${t.perUnit} per kar + ${t.gateFee} één keer</div></section>`;
}
function work(m){const p=m.phase,t=m.task;let note='',inputs='';
 if(p==='context-start'){note='Hoeveel munten kost het om de poort te openen?';inputs=field(m,'openingCost','Poort openen');}
 if(p==='context-add'){note='Hoeveel munten kost één kar, met de poort erbij?';inputs=field(m,'onePrice','Tol voor 1 kar');}
 if(p==='context-table'){note=`Een extra kar kost ${t.perUnit} munten. Vul de volgende tolbedragen in.`;}
 if(p==='context-check'){note=`Hoeveel munten moet je voor ${t.groupSize} karren betalen?`;inputs=field(m,'caravanTotal','Tol voor je karavaan');}
 if(p==='context-rule'){note=`Jouw karavaan kost ${m.values.caravanTotal} munten. Maak de regel voor elk aantal karren.`;inputs=`<div class="toll-rule"><span>Tol =</span>${field(m,'perUnit','Per kar')}<span>× karren +</span>${field(m,'gateFee','Openen')}</div>`;}
 if(p==='context-plot'){note=`Bij 1 kar: ${m.values.onePrice} munten. Bij 3 karren: ${m.values.threePrice}. Zet die punten in de grafiek.`;inputs=`<div class="context-proof">${field(m,'plotY1','Tol bij 1 kar')}${field(m,'plotY2','Tol bij 3 karren')}</div>`;}
 return `<section class="context-work"><p class="context-task-note">${note}</p><div class="context-input-area">${inputs}${keypad(m)}</div></section>`;
}
function render(m,header,{nextWorldUnlocked=false}={}){const f=m.feedback,done=m.completed,index=X.phases.indexOf(m.phase),feedback=done?'Je tolberekening is bewaard.':f?(f.result.ok?'✓ ':'')+f.result.message:m.hintOpen?X.hint(m.phase,m.contextHints?.[m.phase]||1):'Lees het tolbord en vul je munten in.';
 const price=X.total(m.task,m.task.groupSize);
 const finish=`<section class="context-finish"><h1>${gate(nextWorldUnlocked)}${nextWorldUnlocked?'De poort gaat open.':'De tol is berekend.'}</h1>${goal(m.task)}<p>De tol voor je karavaan is <strong>${price} munten</strong>.</p><p>${nextWorldUnlocked?'De wachter heeft je berekening gecontroleerd.': 'Rond de andere haltes in Formulewerf af voor Signaalstad.'}</p><p><strong>Tol = ${m.task.perUnit} × karren + ${m.task.gateFee}</strong></p><p class="toll-formula-note">In wiskundetaal: ${W.formula(m.task.model.a,m.task.model.b)}.<br>x is het aantal karren, y de tol in munten.</p><button type="button" class="paper-pill" data-restart="formulewerf" data-skill="equation_from_context">Een nieuwe karavaan</button></section>`;
 const action=done?(nextWorldUnlocked?'<button type="button" class="paint-button" data-screen="area" data-area="signaalstad">Naar Signaalstad →</button>':'<button type="button" class="paint-button" data-screen="area" data-area="formulewerf" data-zone="omzetten">Naar de kaart →</button>'):f?`<button type="button" class="paint-button" id="continue">${f.result.ok?(f.next==='next-task'?'Open de poort':'Verder'):'Probeer opnieuw'} →</button>`:'<button type="submit" class="paint-button" id="commit">Controleer →</button>';

 return `<form id="mission" class="boundary-mission context-mission" data-world="formulewerf" data-skill="equation_from_context" data-phase="${m.phase}" novalidate>${header}<main class="boundary-workspace context-workspace">${done?finish:`<header class="context-heading"><h1>${titles[m.phase]}</h1><span>Stap ${index+1} / ${X.phases.length}</span></header>${m.phase==='context-plot'?graph(m):m.phase==='context-table'?table(m):picture(m)}${work(m)}`}</main><footer class="boundary-footer"><button type="button" class="paper-pill" id="pause" aria-label="Pauzeer en ga naar Formulewerf B">← Kaart</button><div class="feedback-bubble"><button type="button" class="hint-button" id="hint" aria-label="Hint" ${done||f?'disabled':''}>?</button><div id="feedback" class="feedback ${f?(f.result.ok?'success':'error'):''}" role="status" aria-live="polite">${esc(feedback)}</div></div>${action}</footer></form><section id="rotateGate"><h1>Draai je scherm</h1><p>Liggend heb je ruimte om je tol te berekenen. Je werk blijft bewaard.</p><button type="button" class="paper-pill" data-screen="area" data-area="formulewerf" data-zone="omzetten">Terug naar Formulewerf</button></section>`;
}
return Object.freeze({render,graph});
});
