/* Formulewerf B worksheets: student work becomes visible only after checking each step. */
(function(root,factory){if(typeof module==='object')module.exports=factory(require('./workbench.js'),require('./shell-view.js'),require('../derive-core.js'),require('../../core/wave-core.js'));else root.RechtenV2DeriveView=factory(root.RechtenV2Workbench,root.RechtenV2Shell,root.RechtenV2Derive,root.RechtenWave)})(globalThis,function(C,S,D,W){
'use strict';const esc=C.esc,num=W.html,paren=q=>q.n<0?'('+num(q)+')':num(q),pair=p=>`(${num(p.x)}; ${num(p.y)})`;
const frac=(top,bottom)=>{const row=s=>s.includes('derive-slot')?s:`<span class="derive-expression">${s}</span>`;return `<span class="derive-fraction"><span>${row(top)}</span><span>${row(bottom)}</span></span>`};
const stageTitles={'derive-fill':'Tik of sleep de coördinaten.','derive-slope':'Bereken de richtingscoëfficiënt.','derive-substitute':'Vul het punt en de helling in.','derive-product':'Bereken eerst het product.','derive-intercept':'Bepaal de waarde van b.','derive-formula':'Bouw jouw functievoorschrift.'};
function reminder(m){const slope=D.needsSlope(m.skill)&&['derive-fill','derive-slope'].includes(m.phase);return `<aside class="derive-reminder ${slope?'is-two-points':''}"><h2>${S.icon('light',28)} Herinnering</h2>${slope?`${m.task.table?'<p>Elke kolom is een punt:<br>(x; f(x)). Kies er twee.</p>':'<p>A(x<sub>A</sub>, y<sub>A</sub>)<br>B(x<sub>B</sub>, y<sub>B</sub>)</p>'}<p>Bereken eerst de helling:</p><div class="derive-rule">a = ${frac('y<sub>2</sub> − y<sub>1</sub>','x<sub>2</sub> − x<sub>1</sub>')}</div><p>Kies voor beide verschillen dezelfde richting.</p><p class="derive-small">Gebruik daarna één punt om b te bepalen.</p>`:'<p>In y = ax + b is <strong data-parameter="a">a</strong> de richtingscoëfficiënt.</p><p><strong data-parameter="b">b</strong> is de y-coördinaat van het snijpunt met de y-as.</p><p>Een punt op de rechte voldoet aan:</p><div class="derive-rule">y<sub>P</sub> = a · x<sub>P</sub> + b</div><p class="derive-small">Vul het punt in en maak b vrij.</p>'}</aside>`}
function slot(m,k,label){const token=m.values[k],q=D.coordinate(m.task,token)||W.parse(token),shown=q?paren(q):token?esc(token):'<span class="derive-placeholder">'+label+'</span>',active=(!m.task.table||D.tableSelection(m.task,m.values))&&(m.values.deriveSlot||D.slots(m.phase)[0])===k;return `<button type="button" class="derive-slot ${m.locks[k]?'is-kept':''}" data-derive-slot="${k}" ${/^[AB]\.[xy]$/.test(token||'')?`data-coordinate-point="${token[0]}"`:''} aria-pressed="${active}" aria-label="${esc(label.replace(/<[^>]*>/g,''))}: ${esc(q?W.text(q):token||'leeg')}" ${m.feedback||m.locks[k]||(m.task.table&&!D.tableSelection(m.task,m.values))?'disabled':''}>${shown}</button>`}
function bank(m){
 if(m.task.table&&m.phase==='derive-fill'&&!D.tableSelection(m.task,m.values))return '<p class="table-pair-prompt">Een kolom geeft een punt (x; f(x)).</p>';
 const pointPair=['derive-fill','derive-substitute'].includes(m.phase);
 const token=t=>{const q=D.coordinate(m.task,t)||W.parse(t),point=/^[AB]\.[xy]$/.test(t)?t[0]:'',label=point?`${t[2]}<sub>${point}</sub>`:t==='a'?'a =':'';return `<button type="button" class="derive-token" ${point?`data-coordinate-point="${point}"`:''} data-derive-token="${esc(t)}" draggable="${!m.feedback}" aria-label="${t==='a'?'Richtingscoëfficiënt a':point?t[2]+' van '+point:'Bouwsteen'} ${esc(q?W.text(q):t)}" ${m.feedback?'disabled':''}>${label&&(!pointPair||t==='a')?`<small>${label}</small>`:''}${q?num(q):esc(t)}</button>`};
 const content=pointPair?(m.phase==='derive-fill'?Object.keys(m.task.points):[D.selectedPoint(m.values)]).map(name=>`<div class="derive-point-pair" data-coordinate-point="${name}" role="group" aria-label="Punt ${name}, x- en y-coördinaat"><span class="derive-point-name">${name}</span><span aria-hidden="true">(</span>${token(name+'.x')}<span aria-hidden="true">;</span>${token(name+'.y')}<span aria-hidden="true">)</span></div>`).join('')+(m.phase==='derive-substitute'?token('a'):''):D.tokens(m.task,m.values,m.phase).map(token).join('');
 return `<div class="derive-token-bank ${pointPair?'derive-point-bank':''}" role="group" aria-label="Gegevens om in te vullen">${content}</div>`;
}
function input(m,name,label){const q=W.parse(m.values[name]);return `<span class="derive-entry"><button type="button" class="derive-answer-open" data-derive-answer="${name}" aria-haspopup="dialog" aria-controls="derive-answer-dialog" aria-label="${label}: ${esc(q?W.text(q):'kies je antwoord')}" ${m.feedback?'disabled':''}>${q?num(q):'?'}<small>${q?'Wijzig':'Kies'}</small></button></span>`}
function answerDialog(m){const name={'derive-slope':'a','derive-product':'product','derive-intercept':'b'}[m.phase];if(!name||m.feedback||m.completed)return '';
 const label=name==='a'?'Kies de richtingscoëfficiënt a':name==='b'?'Kies de waarde van b':'Kies het product';
 return `<dialog id="derive-answer-dialog" class="derive-answer-dialog" aria-labelledby="derive-answer-title"><div class="derive-dialog-heading"><h2 id="derive-answer-title">${label}</h2><button type="button" data-derive-dismiss aria-label="Sluiten">×</button></div><p>Tik op je antwoord.</p><div class="derive-answer-options">${D.answerChoices(m.task,m.values,m.phase).map(q=>`<button type="button" data-derive-answer-value="${esc(W.text(q))}" data-answer-name="${name}" aria-label="${esc(W.text(q))}" aria-pressed="${!!W.parse(m.values[name])&&W.eq(W.parse(m.values[name]),q)}">${num(q)}</button>`).join('')}</div></dialog>`;
}
function given(m){return `<div class="derive-given"><span>Gegeven</span><div>${Object.entries(m.task.points).map(([name,p])=>`<span data-coordinate-point="${name}">${name}${pair(p)}</span>`).join('<span class="derive-given-and">en</span>')}${!D.needsSlope(m.skill)?`<span class="derive-given-and">en</span><span data-parameter="a">a = ${num(m.task.model.a)}</span>`:''}</div></div>`}
function substitution(m){const p=m.task.points[D.selectedPoint(m.values)];return `${num(p.y)} = ${paren(m.task.model.a)} · ${paren(p.x)} + b`}
function fractionFromWork(m){const v=m.values,t=m.task,term=k=>`<span data-coordinate-point="${v[k][0]}">${paren(D.coordinate(t,v[k]))}</span>`;return frac(`${term('y1')} − ${term('y0')}`,`${term('x1')} − ${term('x0')}`)}
function workspace(m){const p=m.phase,v=m.values,t=m.task,point=t.points[D.selectedPoint(v)];let source='',sourceLabel='Gegeven',work='',title=stageTitles[p],help='Tik een vakje en een bouwsteen aan, of sleep de bouwsteen.';
 if(p==='derive-fill'){
  sourceLabel=t.table?'Jouw gekozen punten':'Gegeven punten';source=bank(m);
  title=t.table&&!D.tableSelection(t,v)?'Kies twee kolommen uit de tabel.':'Vul de coördinaten in de formule in.';
  work=`<div class="derive-math derive-slope-builder"><span>a =</span>${frac(`${slot(m,'y1','y<sub>2</sub>')}<span>−</span>${slot(m,'y0','y<sub>1</sub>')}`,`${slot(m,'x1','x<sub>2</sub>')}<span>−</span>${slot(m,'x0','x<sub>1</sub>')}`)}</div>`;
 }
 if(p==='derive-slope'){sourceLabel=t.table?'Jouw gekozen punten':'Gegeven punten';source=given(m);work=`<div class="derive-math"><span>a =</span>${fractionFromWork(m)}<span>=</span>${input(m,'a','Richtingscoëfficiënt a')}</div>`;help='Tik op het antwoordvak en kies een getal of breuk.'}
 if(p==='derive-substitute'){
  sourceLabel=D.needsSlope(m.skill)?'Jouw punten en berekende helling':'Gegeven punt en helling';
  source=`${t.points.B?`<div class="derive-point-choice" role="group" aria-label="Kies een punt om b te bepalen"><span>Kies een punt</span>${['A','B'].map(n=>`<button type="button" data-derive-point="${n}" data-coordinate-point="${n}" aria-pressed="${D.selectedPoint(v)===n}" ${m.feedback?'disabled':''}>${n} ${pair(t.points[n])}</button>`).join('')}</div>`:''}${bank(m)}`;
  title='Vul de gegevens in om b te bepalen.';
  work=`<div class="derive-math derive-substitution">${slot(m,'subY','y')}<span>=</span>${slot(m,'subA','a')}<span>·</span>${slot(m,'subX','x')}<span>+ b</span></div>`;
 }
 if(p==='derive-product'){sourceLabel='Jouw ingevulde vergelijking';source=`<div class="derive-previous" role="math">${substitution(m)}</div>`;work=`<div class="derive-math"><span>${num(t.model.a)} · ${paren(point.x)} =</span>${input(m,'product','Product van a en x')}</div>`;help='Reken alleen de vermenigvuldiging uit.'}
 if(p==='derive-intercept'){const product=W.parse(v.product);sourceLabel='Al berekend';source=`<div class="derive-math derive-known-equation" role="math"><span class="derive-rational">${num(point.y)}</span><span>=</span><span class="derive-rational">${num(product)}</span><span>+ b</span></div>`;work=`<div class="derive-math"><span>b =</span>${input(m,'b','b: y-coördinaat van het snijpunt met de y-as')}</div>`;help='Bedenk welke bewerking b alleen laat staan.'}
 if(p==='derive-formula'){sourceLabel='Jouw gevonden waarden';source=`<div class="derive-found"><strong data-parameter="a">a = ${num(W.parse(v.a)||t.model.a)}</strong><strong data-parameter="b">b = ${num(W.parse(v.b))}</strong></div>`;work=`<div class="derive-math derive-formula-builder"><span>${t.table?'f(x)':'y'} =</span>${slot(m,'answerFactor','a')}<span>x</span>${slot(m,'answerSign','teken')}${slot(m,'answerConstant','getal')}</div>${bank(m)}`;if(m.feedback?.result.ok){title='Jouw functievoorschrift';work=`<div class="derive-math derive-final" role="math">${t.table?W.formula(t.model.a,t.model.b).replace(/^y/, 'f(x)'):W.formula(t.model.a,t.model.b)}</div><p class="derive-proof">${S.icon('check',23)} Het voorschrift past bij ${t.table?'alle kolommen uit de tabel':t.points.B?'beide punten':'het gegeven punt'}.</p>`}}
 return `<section class="derive-paper derive-work ${p}" aria-label="Werkblad"><div class="derive-working"><section class="derive-source" aria-label="${sourceLabel}"><h2 class="derive-source-label">${sourceLabel}</h2>${source}</section><section class="derive-task" aria-label="Opdracht"><h2>${title}</h2>${work}</section><p class="derive-instruction">${help}</p></div><button type="button" class="derive-undo icon-button" id="undo" aria-label="Maak laatste invoer ongedaan" ${m.feedback||!m.history.length?'disabled':''}>${S.icon('undo',23)}</button></section>`;
}
function steps(m){const single=m.skill==='intercept_from_point',two=D.needsSlope(m.skill),p=m.phase,v=m.values;let active=single?['derive-substitute','derive-product','derive-intercept'].indexOf(p):p==='derive-fill'||p==='derive-slope'?0:p==='derive-formula'?2:1;
 const labels=single?['Vul de gegevens in','Bereken het product','Bepaal b']:['Bepaal de helling','Bepaal b','Schrijf het voorschrift'];
 const texts=single?['Vervang x en y door de coördinaten.','Vermenigvuldig a met x.','Maak b vrij in de vergelijking.']:[two?'Gebruik het y-verschil en het x-verschil.':'De richtingscoëfficiënt is gegeven.','Gebruik één punt op de rechte.','Vul je gevonden a en b in.'];
 const txt=q=>W.text(q),signed=q=>q.n<0?'('+txt(q)+')':txt(q),point=m.task.points[D.selectedPoint(v)];
 const checked=i=>single?i===0?`${txt(point.y)} = ${signed(m.task.model.a)} · ${signed(point.x)} + b`:`${txt(point.y)} = ${txt(W.parse(v.product))} + b`:i===0?`a = ${txt(two?W.parse(v.a):m.task.model.a)}`:`b = ${txt(W.parse(v.b))}`;
 return `<aside class="derive-paper derive-steps"><h2>Stappenplan</h2><ol>${labels.map((label,i)=>`<li class="${i<active?'is-done':i===active?'is-current':'is-later'}" ${i===active?'aria-current="step"':''}><span class="derive-step-number">${i<active?'✓':i+1}</span><div><h3>${label}</h3>${i<active?`<div class="derive-checked" role="math">${checked(i)}</div>`:`<p>${texts[i]}</p>`}</div></li>`).join('')}</ol><div class="derive-goal"><span>${single?'Je zoekt':'Eindvorm'}</span><strong>${single?'b = ?':'y = ax + b'}</strong></div></aside>`;
}
function tablePanel(m){
 const t=m.task,v=m.values,chosen=v.tableColumns||[],selectable=m.phase==='derive-fill'&&!m.feedback&&!m.locks.tableColumns;
 const current=['derive-fill','derive-slope'].includes(m.phase)?0:m.phase==='derive-formula'?2:1;
 const name=i=>chosen.indexOf(i)===0?'A':chosen.indexOf(i)===1?'B':'';
 const cell=(point,i,key)=>`<td ${name(i)?`data-coordinate-point="${name(i)}"`:''}><button type="button" data-table-column="${i}" aria-pressed="${chosen.includes(i)}" aria-label="${chosen.includes(i)?'Gekozen punt '+name(i)+',':'Kies'} kolom ${i+1}: (${esc(W.text(point.x))}; ${esc(W.text(point.y))})" ${selectable?'':'disabled'}>${num(point[key])}</button></td>`;
 return `<aside class="derive-paper table-source" aria-label="Gegeven tabel en stappenplan"><h2>Gegeven tabel</h2><table class="derive-data-table"><caption class="sr-only">Elke kolom geeft x en f(x). Kies twee kolommen om de helling te bepalen.</caption><thead><tr><td></td>${t.table.map((p,i)=>`<th scope="col" ${name(i)?`data-coordinate-point="${name(i)}"`:''}>${name(i)?'Punt '+name(i):'Kolom '+(i+1)}</th>`).join('')}</tr></thead><tbody><tr><th scope="row">x</th>${t.table.map((p,i)=>cell(p,i,'x')).join('')}</tr><tr><th scope="row">f(x)</th>${t.table.map((p,i)=>cell(p,i,'y')).join('')}</tr></tbody></table><p class="table-selection-note">${selectable?'Tik twee kolommen aan. Tik opnieuw om je keuze te wijzigen.':'Je gekozen punten blijven gekleurd.'}</p><ol class="table-road">${['Bepaal a','Bepaal b','Voorschrift'].map((label,i)=>`<li class="${i<current?'is-done':i===current?'is-current':'is-later'}" ${i===current?'aria-current="step"':''}><span>${i<current?'✓':i+1}</span><div>${label}${i<current?`<small>${i===0?'a = '+esc(v.a):'b = '+esc(v.b)}</small>`:''}</div></li>`).join('')}</ol></aside>`;
}
function render(m,header){m={...m,task:D.workTask(m.task,m.values)};const f=m.feedback,hs=D.hints(m.task,m.phase),feedback=m.completed?'Je reeks is afgerond en bewaard.':f?(f.result.ok?'✓ ':'')+esc(f.result.message):esc(hs[m.hintOpen?m.hints-1:0]);
 const done=`<section class="boundary-complete"><h1>Goed gedaan!</h1><p>Je hebt de zes opgaven afgerond.</p><span class="proof-badge">${S.icon('check')} ${D.titles[m.skill]}</span><button type="button" data-restart="formulewerf" data-skill="${m.skill}">Opnieuw oefenen</button></section>`;
 const action=m.completed?`<button type="button" class="paint-button" data-screen="area" data-area="formulewerf" data-zone="omzetten">Naar Formulewerf ${S.icon('arrow')}</button>`:m.hints>=5&&!f?`<button type="button" class="paint-button" id="new-example">Nieuw geval ${S.icon('arrow')}</button>`:f?`<button type="button" class="paint-button" id="continue">${f.result.ok?(f.next==='next-task'?(m.index===D.count-1?'Afronden':'Volgende opgave'):'Volgende stap'):'Herstel'} ${S.icon(f.result.ok?'arrow':'undo')}</button>`:`<button type="submit" class="paint-button" id="commit">Controleer ${S.icon('arrow')}</button>`;
 return `<form id="mission" class="boundary-mission derive-mission" data-world="formulewerf" data-skill="${m.skill}" data-phase="${m.phase}" novalidate>${header}<main class="boundary-workspace derive-workspace">${m.completed?done:`${reminder(m)}<header class="derive-heading"><h1>${D.titles[m.skill]}</h1><p>Opgave ${m.index+1} / ${D.count}</p></header>${workspace(m)}${m.task.table?tablePanel(m):steps(m)}`}</main><footer class="boundary-footer"><button type="button" class="paper-pill" id="pause" aria-label="Pauzeer en ga naar Formulewerf B">${S.icon('back')}<span>Vorige</span></button><div class="feedback-bubble"><button type="button" class="hint-button" id="hint" aria-label="Volgende hint" ${m.completed||f||m.hints>=5?'disabled':''}>${S.icon('light',23)}</button><div id="feedback" class="feedback ${f?f.result.ok?'success':'error':''}" role="status" aria-live="polite">${feedback}</div></div>${action}</footer>${answerDialog(m)}</form><section id="rotateGate"><span class="rotate-symbol" aria-hidden="true">↻</span><h1>Even je scherm draaien</h1><p>Liggend heb je ruimte voor je werkblad. Je werk blijft bewaard.</p><button type="button" class="paper-pill" data-screen="area" data-area="formulewerf" data-zone="omzetten">Terug naar Formulewerf</button></section>`;
}
return Object.freeze({render});
});
