/* Formulewerf A paper workbenches. No solution coordinates are drawn before commit. */
(function(root,factory){if(typeof module==='object')module.exports=factory(require('./workbench.js'),require('./shell-view.js'),require('../formula-core.js'),require('../../core/wave-core.js'),require('./graph-scale.js'));else root.RechtenV2FormulaView=factory(root.RechtenV2Workbench,root.RechtenV2Shell,root.RechtenV2Formula,root.RechtenWave,root.RechtenV2GraphScale)})(globalThis,function(C,S,F,W,K){
'use strict';const esc=C.esc;let seq=0;
const number=v=>{const q=W.parse(v);return q?W.html(q):esc(v)};
function sketch(height=false){return `<svg class="formula-sketch" viewBox="0 0 220 150" aria-hidden="true"><path d="M15 115H210M75 145V10" class="sketch-axis"/><path d="M25 139L180 35" class="sketch-line"/><circle cx="75" cy="105" r="6"/><text x="88" y="115">${height?'(0; hoogte)':'(0, b)'}</text><text x="203" y="104">x</text><text x="86" y="20">y</text></svg>`}
function reminder(m){let body;
 if(m.skill==='intercept')body='<p>De <strong>y-as</strong> is de verticale as door 0.</p><p>Zoek waar de rechte die as raakt. Lees daar de <strong>hoogte</strong> af.</p><p>Boven 0 is positief. Onder 0 is negatief.</p><p class="formula-small">Op de y-as is x altijd 0. Het snijpunt schrijven we als (0; hoogte).</p>'+sketch(true);
 else if(m.skill==='graph_from_table')body='<p>Elke kolom geeft één punt <strong>(x; f(x))</strong>.</p><p>Lees eerst x: links of rechts. Lees daarna f(x): omhoog of omlaag.</p><p>Kies twee verschillende punten en teken de rechte erdoor.</p><p class="formula-small">Gebruik steeds de twee getallen uit dezelfde kolom.</p>';
 else if(m.skill==='rewrite_linear_equation')body='<p><strong>Doel:</strong> y alleen links.</p><p>Pas dezelfde bewerking toe op beide leden.</p><p>Werk de x-term links weg. Deel door de coëfficiënt van y.</p><p class="formula-small">Een andere geldige volgorde mag ook.</p>';
 else if(m.skill==='graph_from_equation')body='<p><strong data-parameter="b">b</strong> is de y-coördinaat van het snijpunt met de y-as.</p><p><strong data-parameter="a">a</strong> is de richtingscoëfficiënt: de verandering van y per stap in x.</p><p class="formula-small">Lees a en b zelf af uit het voorschrift.</p>'+sketch();
 else if(m.skill==='equation_from_graph')body='<p><strong data-parameter="a">a</strong> vertelt hoe de rechte stijgt of daalt.</p><p><strong data-parameter="b">b</strong> is de y-coördinaat van het snijpunt met de y-as.</p><p>Lees eerst b af, daarna a.</p>'+sketch();
 else body='<p>In y = ax + b is <strong data-parameter="a">a</strong> de richtingscoëfficiënt.</p><p><strong data-parameter="b">b</strong> is de y-coördinaat van het snijpunt met de y-as.</p><p>Zet eerst a vóór x en voeg daarna b toe.</p><p class="formula-small">Een bouwsteen mag je opnieuw gebruiken.</p>';
 return `<aside class="reminder-paper formula-reminder"><h2>${S.icon('light',28)} Herinnering</h2>${body}</aside>`;
}
function graph(m){const t=m.task,plot=m.phase==='formula-plot',points=Object.fromEntries(['A','B'].filter(n=>m.values['plot'+n]).map(n=>[n,{x:W.fromNumber(m.values['plot'+n].x),y:W.fromNumber(m.values['plot'+n].y)}])),model=plot?(points.A&&points.B?W.model(points.A,points.B):null):t.model;
 const editable=plot&&!m.feedback&&!m.completed,scale=K.line(t.model,{step:t.gridStep,fixed:plot}),{X,Y,grid}=scale,clip='formula-clip-'+ ++seq;
 const line=!model||model.kind==='identical'?'':model.kind==='vertical'?`M${X(model.c)} 50V450`:`M50 ${Y(W.add(W.mul(model.a,-scale.radius),model.b))}L450 ${Y(W.add(W.mul(model.a,scale.radius),model.b))}`;
 const selected=points[m.values.selectedPoint||'A']||points.A||points.B;
 const guide=editable&&selected?`<path class="coordinate-guide" d="M${X(selected.x)} 250V${Y(selected.y)}H250" fill="none" stroke="#436675" stroke-width="1.4" stroke-dasharray="5 4"/>`:'';
 const pins=plot?Object.entries(points).map(([n,p])=>`<g class="line-pin pin-${n} ${(m.values.selectedPoint||'A')===n?'is-selected':''}" ${editable&&!m.locks['plot'+n]?`data-line-marker="${n}"`:''}><circle class="line-pin-hit" cx="${X(p.x)}" cy="${Y(p.y)}" r="15"/><circle class="line-pin-dot" cx="${X(p.x)}" cy="${Y(p.y)}" r="6"/><text x="${X(p.x)+(W.num(p.x)<2?12:-12)}" y="${Y(p.y)+(n==='A'?-18:29)}" text-anchor="${W.num(p.x)<2?'start':'end'}">${n} (${esc(W.text(p.x))}; ${esc(W.text(p.y))})</text></g>`).join(''):'';
 return `<svg class="math-graph boundary-graph lines-graph formula-graph" viewBox="0 0 500 500" ${scale.attributes} role="${editable?'group':'img'}" ${editable?'tabindex="0" data-line-picker':''} aria-label="${plot?'Plaats twee verschillende punten. Selecteer A of B en tik, sleep of gebruik de pijltjestoetsen.':'Grafiek van de rechte met genummerde assen.'} Kleine stap: ${t.gridStep===.5?'een halve':'één'} eenheid."><defs><clipPath id="${clip}"><path d="M48 48h404v404H48z"/></clipPath></defs><g class="graph-grid">${grid}</g><path class="axis" d="M30 250H474M250 470V26"/><path class="axis-arrow" d="m465 243 10 7-10 7M243 36l7-11 7 11"/><text class="axis-origin" x="247" y="273" text-anchor="end">0</text><text class="axis-name" x="480" y="255">x</text><text class="axis-name" x="263" y="28">y</text>${line?`<path class="formula-model ${plot&&!m.feedback?.result.ok?'is-draft':''}" d="${line}" clip-path="url(#${clip})"/>`:''}${guide}${pins}${t.gridStep===.5?'<g fill="#375b69"><text x="250" y="493" text-anchor="middle" font-size="19">1 klein hokje = ½ = 0,5</text></g>':''}</svg>`;
}
function pointTools(m){const editable=!m.feedback;return `<div class="line-tools formula-point-tools" role="group" aria-label="Punten plaatsen">${['A','B'].map(n=>`<button type="button" class="line-point-token token-${n}" data-line-point="${n}" draggable="${editable&&!m.locks['plot'+n]}" aria-pressed="${(m.values.selectedPoint||'A')===n}" aria-label="Punt ${n} selecteren of slepen" ${!editable||m.locks['plot'+n]?'disabled':''}>${n}</button>`).join('')}<button type="button" class="line-clear" id="line-clear" aria-label="Wis je geplaatste punten" ${!editable||!m.values.plotA&&!m.values.plotB?'disabled':''}>Wis</button><span class="formula-plot-note">${m.task.gridStep===.5?'1 klein hokje = ½ = 0,5':'Elk hokje is 1 eenheid'}</span></div>`}
function tile(m,slot,label){return `<button type="button" class="formula-slot ${m.values[slot]?'is-filled':'is-empty'}" data-formula-slot="${slot}" aria-label="${label}: ${esc(m.values[slot]||'nog invullen')}" aria-pressed="${(m.values.formulaSlot||'factor')===slot}" ${m.feedback||m.locks[slot]?'disabled':''}>${m.values[slot]?number(m.values[slot]):''}</button>`}
function equation(e){const member=(m,order)=>{let out='';for(const k of order){const q=m[k];if(!q.n)continue;const abs=W.q(Math.abs(q.n),q.d);out+=(out?(q.n<0?' − ':' + '):q.n<0?'−':'')+(k!=='c'&&W.eq(abs,1)?'':W.html(abs))+(k==='c'?'':k)}return out||'0'};return member(e.left,['y','x','c'])+' = '+member(e.right,['x','y','c'])}
function algebra(m){const steps=m.values.algebraSteps||[];return `<div class="formula-algebra-row"><span>Gegeven</span><div role="math">${equation(m.task.equation)}</div></div>${steps.slice(-2).map((step,i)=>`<div class="formula-algebra-row"><span>Stap ${steps.length-Math.min(steps.length,2)+i+1}</span><div role="math">${equation(step.equation)}</div><p>${esc(step.operation)} aan beide leden</p></div>`).join('')}${!steps.length?'<p class="formula-algebra-empty">Kies een bewerking.<br>Je uitwerking verschijnt hier.</p>':''}`}
function stepper(m,name){return `<label class="formula-parameter" data-parameter="${name}"><span>${m.skill==='intercept'?'hoogte':name}</span><button type="button" data-formula-step="${name}" data-direction="1" aria-label="Verhoog ${name}" ${m.feedback||m.locks[name]?'disabled':''}>▴</button><input name="${name}" type="text" inputmode="text" autocomplete="off" maxlength="16" aria-label="${m.skill==='intercept'?'Hoogte van het snijpunt met de y-as':name==='a'?'Richtingscoëfficiënt a':'b: y-coördinaat van het snijpunt met de y-as'}" value="${esc(m.values[name]??'')}" placeholder="?" ${m.feedback||m.locks[name]?'readonly':''}><button type="button" data-formula-step="${name}" data-direction="-1" aria-label="Verlaag ${name}" ${m.feedback||m.locks[name]?'disabled':''}>▾</button></label>`}
function tablePrompt(m){const rows=m.task.table,match=p=>['A','B'].find(n=>{const q=m.values['plot'+n];return q&&W.eq(W.fromNumber(q.x),p.x)&&W.eq(W.fromNumber(q.y),p.y)}),cell=(p,k)=>`<td ${match(p)?`data-coordinate-point="${match(p)}"`:''}>${W.html(p[k])}</td>`;
 return `<section class="plot-table-source" aria-label="Gegeven tabel"><h2>Gegeven tabel</h2><table class="plot-data-table"><caption class="sr-only">Elke kolom geeft één punt: x en f(x).</caption><tbody><tr><th scope="row">x</th>${rows.map(p=>cell(p,'x')).join('')}</tr><tr><th scope="row">f(x)</th>${rows.map(p=>cell(p,'y')).join('')}</tr></tbody></table><p>Elke kolom is een punt (x; f(x)).</p></section><section class="plot-table-task" aria-label="Opdracht"><h2>Plaats twee punten uit de tabel</h2><p>Tik in het rooster. De rechte verschijnt zodra je twee verschillende punten hebt geplaatst.</p><div class="plot-point-status" aria-label="Jouw geplaatste punten">${['A','B'].map(n=>`<span data-coordinate-point="${n}"><strong>${n}</strong> ${m.values['plot'+n]?`(${number(m.values['plot'+n].x)}; ${number(m.values['plot'+n].y)})`:'nog te plaatsen'}</span>`).join('')}</div></section>`;
}
function panels(m,hint){const skill=m.skill;let main,side;
 if(skill==='equation_from_ab'){
  main=`<div class="formula-given"><span>Gegeven:</span><strong data-parameter="a">a = ${W.html(m.task.model.a)}</strong><strong data-parameter="b">b = ${W.html(m.task.model.b)}</strong></div><div class="formula-builder"><span>y =</span>${tile(m,'factor','Coëfficiënt van x')}${tile(m,'variable','Variabele')}${tile(m,'operator','Teken van de constante term')}${tile(m,'constant','Constante term')}</div><p class="formula-build-help">Kies een vakje en tik of sleep een bouwsteen.</p>${hint}`;
  side=`<h2><svg class="build-puzzle" viewBox="0 0 32 32" aria-hidden="true"><path d="M12 5V3a4 4 0 0 1 8 0v2h7v8h2a4 4 0 0 1 0 8h-2v8h-8v-2a4 4 0 0 0-8 0v2H3v-8H1a4 4 0 0 1 0-8h2V5Z" transform="translate(2 2) scale(.86)"/></svg>Bouwstenen</h2><div class="formula-tokens" role="group" aria-label="Bouwstenen">${m.task.tokens.map((token,i)=>`<button type="button" data-formula-token="${esc(token)}" draggable="${!m.feedback}" aria-label="Bouwsteen ${esc(token)}" ${m.feedback?'disabled':''}>${number(token)}</button>`).join('')}</div><p class="formula-token-help"><svg viewBox="0 0 55 40" aria-hidden="true"><path d="M50 35Q16 34 9 5m-2 16L9 5l13 8"/></svg>Sleep of tik een bouwsteen</p>`;
 }else if(skill==='rewrite_linear_equation'){
  main=algebra(m);side=`<h2>Kies een bewerking</h2><div class="formula-operations" role="group" aria-label="Bewerking op beide leden">${F.operations(m.task,m.values).map((op,i)=>`<button type="button" class="${op.kind==='divide'?'is-scale':''}" data-formula-operation="${i}" aria-label="${esc(F.operationLabel(op))} aan beide leden" ${m.feedback?'disabled':''}>${esc(F.operationLabel(op))}</button>`).join('')}</div>`;
 }else{
  main=`<div class="formula-graph-wrap">${graph(m)}</div>${m.phase==='formula-plot'?pointTools(m):''}`;
  side=skill==='intercept'?`<h2>Lees de hoogte af</h2><p>Waar raakt de rechte de verticale y-as?</p><div class="formula-parameter-equation signal-intercept-answer"><span>(0;</span>${stepper(m,'b')}<span>)</span></div><p class="formula-side-note">Vul alleen de hoogte in. Je hoeft niets te berekenen.</p>`:skill==='graph_from_table'?tablePrompt(m):skill==='graph_from_equation'?'<div class="formula-task-step"><span>1</span><div><h2>Plaats een eerste punt</h2><p>Gebruik wat je weet over a en b.</p></div></div><div class="formula-task-step"><span>2</span><div><h2>Plaats een tweede punt</h2><p>Gebruik de richtingscoëfficiënt of bereken een functiewaarde.</p></div></div><p class="formula-side-note">Trek daarna de rechte door je punten.</p>':`<div class="formula-parameter-equation"><span>f(x) =</span>${stepper(m,'a')}<span>x +</span>${stepper(m,'b')}</div><p class="formula-side-note">Pijltjes, getal of breuk.</p>`;
 }
 return `<section class="formula-paper formula-work ${skill==='rewrite_linear_equation'?'formula-algebra':''}"><button type="button" class="graph-undo" id="undo" aria-label="Maak laatste bewerking ongedaan" ${m.feedback||!m.history.length?'disabled':''}>${S.icon('undo',26)}</button>${main}</section><section class="formula-paper formula-answer answer-tray">${side}</section>`;
}
function render(m,header){const world=m.world,areaName=world==='signaalstad'?'Signaalstad':'Formulewerf',zone=world==='signaalstad'?'route':'bouwen',f=m.feedback,title=m.skill==='intercept'?'Waar snijdt de rechte de y-as?':m.skill==='graph_from_table'?'Teken de rechte bij de tabel':m.skill==='equation_from_ab'?'Bouw het functievoorschrift':m.skill==='graph_from_equation'?'Teken '+W.formula(m.task.model.a,m.task.model.b):m.skill==='equation_from_graph'?'Welk functievoorschrift hoort bij deze grafiek?':'Schrijf de vergelijking in de vorm y = ax + b';
 const feedback=f?(f.result.ok?'✓ ':'')+esc(f.result.message):m.values.operationError?esc(m.values.operationError):esc(m.task.hints[m.hintOpen?m.hints-1:0]);
 const done=`<section class="boundary-complete"><h1>Goed gedaan!</h1><p>Je hebt de reeks afgerond.</p><span class="proof-badge">${S.icon('check')} ${F.titles[m.skill]}</span><button type="button" data-restart="${world}" data-skill="${m.skill}">Opnieuw oefenen</button></section>`;
 const action=m.completed?`<button type="button" class="paint-button" data-screen="area" data-area="${world}" data-zone="${zone}">Naar ${areaName} ${S.icon('arrow')}</button>`:m.hints>=5&&!f?`<button type="button" class="paint-button" id="new-example">Nieuw geval ${S.icon('arrow')}</button>`:f?`<button type="button" class="paint-button" id="continue">${f.result.ok?(m.index===F.count-1?'Afronden':'Volgende'):'Herstel'} ${S.icon(f.result.ok?'arrow':'undo')}</button>`:`<button type="submit" class="paint-button" id="commit">${m.skill==='graph_from_equation'?'Trek de rechte':'Controleer'} ${S.icon('arrow')}</button>`;
 const build=m.skill==='equation_from_ab'&&!m.completed;
 const hint=`<div class="feedback-bubble"><button type="button" class="hint-button" id="hint" aria-label="Volgende hint" ${m.completed||f||m.hints>=5?'disabled':''}>${S.icon('light',23)}</button><div id="feedback" class="feedback ${f?f.result.ok?'success':'error':''}" role="status" aria-live="polite">${m.completed?'Je werk is bewaard.':feedback}</div></div>`;
 const progress=`<div class="formula-build-progress"><span>Opgave ${m.index+1} / ${F.count}</span><span class="formula-progress-dots" aria-hidden="true">${Array.from({length:F.count},(_,i)=>`<i class="${i<m.index?'is-done':i===m.index?'is-current':''}"></i>`).join('')}</span></div>`;
 return `<form id="mission" class="boundary-mission formula-mission${build?' formula-build-mission':''}" data-world="${world}" data-skill="${m.skill}" data-phase="${m.phase}" novalidate>${header}<main class="boundary-workspace formula-workspace">${m.completed?done:`${reminder(m)}<header class="formula-heading"><h1>${title}</h1>${build?progress:`<span>Opgave ${m.index+1} / ${F.count}</span>`}</header>${panels(m,build?hint:'')}`}</main><footer class="boundary-footer"><button type="button" class="paper-pill" id="pause" aria-label="Pauzeer en ga naar ${areaName}">${S.icon('back')}<span>Vorige</span></button>${build?'':hint}${action}</footer></form><section id="rotateGate"><span class="rotate-symbol">↻</span><h1>Even je scherm draaien</h1><p>Liggend heb je ruimte voor je werkblad. Je werk blijft bewaard.</p><button type="button" class="paper-pill" data-screen="area" data-area="${world}" data-zone="${zone}">Terug naar ${areaName}</button></section>`;
}
return Object.freeze({render,graph,equation});
});
