/* Function arithmetic and a table with independently retained cells. */
(function(root,factory){if(typeof module==='object')module.exports=factory(require('../values-core.js'),require('./workbench.js'),require('./shell-view.js'),require('../../core/wave-core.js'));else root.RechtenV2ValuesView=factory(root.RechtenV2Values,root.RechtenV2Workbench,root.RechtenV2Shell,root.RechtenWave)})(globalThis,function(V,C,S,W){
'use strict';const esc=C.esc;
const formula=t=>W.formula(t.model.a,t.model.b).replace(/^y =/,'f(x) =');
function fractionDisplay(value,start=null,end=start){
 const raw=String(value),slash=raw.indexOf('/');if(slash<0)return '';
 const numerator=raw.slice(0,slash),denominator=raw.slice(slash+1),negative=/^[−-]/.test(numerator),prefix=negative?1:0;
 function part(text,offset,kind){
  const a=start===null?null:Math.max(0,Math.min(text.length,start-offset)),b=end===null?null:Math.max(0,Math.min(text.length,end-offset)),active=start!==null&&(kind==='numerator'?start<=slash:end>slash);
  const display=s=>esc(s.replaceAll('-','−'));
  let body=display(text)||'<span class="value-fraction-placeholder">?</span>';
  if(active&&start===end&&!(negative&&kind==='numerator'&&start===0)){const at=a;body=display(text.slice(0,at))+'<i class="value-math-caret"></i>'+display(text.slice(at))+(text?'':'<span class="value-fraction-placeholder">?</span>');}
  else if(a!==null&&b>a)body=display(text.slice(0,a))+'<span class="value-math-selection">'+display(text.slice(a,b))+'</span>'+display(text.slice(b));
  return `<span data-fraction-part="${kind}" class="${active?'is-editing':''}">${body}</span>`;
 }
 // Keep the student's entered numerator and denominator; do not reduce or solve them.
 return `${negative?'<span class="value-fraction-sign '+(start===0&&end>0?'value-math-selection':'')+'" data-fraction-part="sign">'+(start===0&&end===0?'<i class="value-math-caret"></i>':'')+'−</span>':''}<span class="frac value-entered-fraction">${part(numerator.slice(prefix),prefix,'numerator')}${part(denominator.includes('/')?'':denominator,slash+1,'denominator')}</span>`;
}
function syncInput(el){const entry=el.closest('.value-entry');if(!entry)return;const preview=entry.querySelector('.value-math-preview'),fraction=el.value.includes('/');entry.classList.toggle('has-fraction',fraction);preview.hidden=!fraction;const focused=el.ownerDocument.activeElement===el&&!el.readOnly;if(focused)entry.dataset.caretSet='true';if(fraction){preview.innerHTML=fractionDisplay(el.value,focused?el.selectionStart:null,focused?el.selectionEnd:null);preview.style.fontSize='';const natural=Array.from(preview.children).reduce((sum,node)=>sum+node.getBoundingClientRect().width,2),available=preview.clientWidth;if(available>0&&natural>available)preview.style.fontSize=(parseFloat(getComputedStyle(preview).fontSize)*available/natural)+'px';}}
function input(m,name,label,adapter=V){const value=String(m.values[name]??'');return `<span class="value-entry ${value.includes('/')?'has-fraction':''}"><input class="value-input ${adapter.selected(m)===name?'is-selected':''} ${m.locks[name]||m.feedback?.result.keep?.[name]?'is-correct':m.feedback?.result.kind==='hypothesis'?'is-incorrect':''}" data-value-field="${name}" name="${name}" type="text" inputmode="none" autocomplete="off" maxlength="16" aria-label="${esc(label)}" value="${esc(value)}" placeholder="?" ${m.feedback||m.locks[name]?'readonly':''}><span class="value-math-preview" aria-hidden="true" ${value.includes('/')?'':'hidden'}>${fractionDisplay(value)}</span></span>`}
function keypad(m){const keys=[['7','7'],['8','8'],['9','9'],['minus','±'],['back','⌫'],['4','4'],['5','5'],['6','6'],['/','/'],['clear','Wis'],['1','1'],['2','2'],['3','3'],['0','0'],[',',',']],labels={minus:'Wissel het teken',back:'Wis laatste teken',clear:'Wis geselecteerde waarde','/':'Breukstreep',',':'Decimale komma'};
 return `<div class="value-keypad" role="group" aria-label="Getallen invoeren in de geselecteerde cel">${keys.map(([key,label])=>`<button type="button" data-value-key="${key}" aria-label="${esc(labels[key]||label)}" ${m.feedback||m.completed?'disabled':''}>${key==='/'?'<span class="value-fraction-key" aria-hidden="true"><i></i><b></b><i></i></span>':label}</button>`).join('')}</div>`;
}
function source(m){return `<section class="value-paper value-source" aria-label="Getallen invoeren"><h2>Getallen invoeren</h2><p class="value-source-help">Selecteer een antwoordvak. Gebruik de getallenknoppen of je toetsenbord.</p>${keypad(m)}</section>`}
function fx(m){const t=m.task,sign=t.model.b.n<0?'−':'+',b=W.q(Math.abs(t.model.b.n),t.model.b.d);
 if(m.phase==='fx-substitute')return `<section class="value-paper value-answer answer-tray" aria-label="x vervangen in het voorschrift"><h2>1 · Vervang x</h2><p class="value-request">Bepaal f(${W.html(t.x)}).</p><div class="value-substitution value-replace" role="group" aria-label="Vervang x door de invoer"><span>f(${W.html(t.x)}) = ${W.html(t.model.a)} · (</span>${input(m,'substitution','Vervang x in het voorschrift')}<span>) ${sign} ${W.html(b)}</span></div><p class="value-answer-help">Vul de invoer in op de plaats van x. Reken daarna pas verder.</p></section>`;
 const x=W.parse(m.values.substitution)||t.x;
 return `<section class="value-paper value-answer answer-tray" aria-label="Berekening van de functiewaarde"><h2>2 · Bereken f(${W.html(t.x)})</h2><p class="value-substitution value-retained" role="math">f(${W.html(t.x)}) = ${W.html(t.model.a)} · (<strong>${W.html(x)}</strong>) ${sign} ${W.html(b)}</p><div class="value-calculation"><label class="value-step"><span>Product</span><div><span>${W.html(t.model.a)} · (${W.html(x)}) =</span>${input(m,'product','Product van de coëfficiënt en x')}</div></label><label class="value-step"><span>Functiewaarde</span><div><span>f(${W.html(t.x)}) =</span>${input(m,'answer','Functiewaarde f('+W.text(t.x)+')')}</div></label></div><p class="value-answer-help">Vermenigvuldig eerst. Verwerk daarna de constante term.</p></section>`;
}
function table(m){const t=m.task;
 return `<section class="value-paper value-answer answer-tray" aria-label="Functietabel aanvullen"><h2>Vul de tabel aan</h2><table class="value-table"><caption class="sr-only">Bereken de functiewaarde voor elke x. De kolom met x = 0 is gegeven.</caption><thead><tr><th scope="row">x</th>${t.inputs.map(x=>`<th scope="col">${W.html(x)}</th>`).join('')}</tr></thead><tbody><tr><th scope="row">f(x)</th>${t.inputs.map((x,i)=>i===t.givenColumn?`<td class="value-given" aria-label="Gegeven f(${esc(W.text(x))}) = ${esc(W.text(V.output(t,x)))}">${W.html(V.output(t,x))}<span>gegeven</span></td>`:`<td>${input(m,'cell'+i,'f('+W.text(x)+'), kolom '+(i+1))}</td>`).join('')}</tr></tbody></table><p class="value-answer-help">Elke kolom geeft één invoer en haar functiewaarde. Gebruik steeds het voorschrift.</p><p class="value-table-note">${t.index?'Let op: de x-waarden staan niet steeds één stap uit elkaar.':'De kolom bij x = 0 is al ingevuld.'}</p></section>`;
}
function render(m,header){const f=m.feedback,t=m.task,isFx=m.skill==='fx',level=isFx?3:4,complete=m.completed;
 const feedback=complete?'Je werk is bewaard.':f?(f.result.ok?'✓ ':'')+esc(f.result.message):m.hintOpen&&m.hints?esc(t.hints[m.hints-1]):m.phase==='fx-substitute'?'Vervang eerst x door de gegeven invoer.':isFx?'Vul het product en de functiewaarde in.':'Selecteer een lege cel en bereken f(x).';
 const done=`<section class="value-complete"><span aria-hidden="true">✓</span><h2>${isFx?'Je berekent functiewaarden':'Je vult functietabellen aan'}</h2><p>Je hebt zes voorschriften gebruikt.</p><button type="button" data-restart="signaalstad" data-skill="${m.skill}">Opnieuw oefenen</button></section>`;
 const action=complete?'<button type="button" class="primary" data-screen="area" data-area="signaalstad">Naar Signaalstad →</button>':m.hints>=5&&!f?'<button type="button" class="primary" id="new-example">Nieuw geval →</button>':f?`<button type="button" class="primary" id="continue">${f.result.ok?(m.phase==='fx-substitute'?'Bereken nu':m.index===V.count-1?'Afronden':'Volgende'):'Herstel'} →</button>`:'<button type="submit" class="primary" id="commit">Controleer →</button>';
 return `<form id="mission" class="boundary-mission value-mission" data-world="signaalstad" data-skill="${m.skill}" data-phase="${m.phase}" novalidate>${header}<main class="boundary-workspace value-workspace"><header class="value-heading"><div><span>Signaalstad · Level ${level} · Opgave ${Math.min(m.index+1,V.count)} / ${V.count}</span><h1>${complete?'Goed gedaan!':isFx?'Bereken de functiewaarde':'Vul de functietabel aan'}</h1></div>${complete?'':`<div class="value-formula" role="math" aria-label="Gegeven functievoorschrift">${formula(t)}</div>`}</header>${complete?done:(isFx?fx(m):table(m))+source(m)}</main><footer class="boundary-footer value-footer"><div class="value-history"><button type="button" id="pause" aria-label="Pauzeer en ga naar Signaalstad">${S.icon('back',22)}</button><button type="button" id="undo" aria-label="Maak laatste invoer ongedaan" ${f||complete||!m.history.length?'disabled':''}>${S.icon('undo',22)}</button></div><div class="feedback-bubble"><button type="button" class="hint-button" id="hint" aria-label="Volgende hint" ${complete||f||m.hints>=5?'disabled':''}>${S.icon('light',22)}</button><div id="feedback" class="feedback ${f?f.result.ok?'success':'error':''}" role="status" aria-live="polite">${feedback}</div></div>${action}</footer></form><section id="rotateGate"><span class="rotate-symbol" aria-hidden="true">↻</span><h1>Even je scherm draaien</h1><p>Liggend heb je ruimte voor het voorschrift en je antwoorden. Je werk blijft bewaard.</p><button type="button" class="paper-pill" data-screen="area" data-area="signaalstad">Terug naar Signaalstad</button></section>`;
}
return Object.freeze({render,input,keypad,source,formula,fractionDisplay,syncInput});
});
