/* Hellingrug presentation: graphs, exact fractions, and an accessible coordinate builder. */
(function(root,factory){if(typeof module==='object')module.exports=factory(require('./workbench.js'),require('./shell-view.js'),require('../hills-core.js'),require('../../trainer/wave-core.js'));else root.RechtenV2HillsView=factory(root.RechtenV2Workbench,root.RechtenV2Shell,root.RechtenV2Hills,root.RechtenWave)})(globalThis,function(C,S,H,W){
'use strict';const esc=C.esc,frac=H.fraction,notation=text=>esc(text).replace(/([xy])([AB])\b/g,'$1<sub>$2</sub>');let seq=0;
const val=q=>q.n<0?'('+W.html(q)+')':W.html(q),pair=p=>`(${W.text(p.x)}, ${W.text(p.y)})`;
function graph(m){const t=m.task,{A,B}=t.points,X=q=>250+40*W.num(q),Y=q=>250-40*W.num(q),id='hill-clip-'+ ++seq;
 let grid='';for(let i=-5;i<=5;i++){grid+=`<path d="M${250+i*40} 50V450M50 ${250+i*40}H450"/>`;if(i)grid+=`<text x="${250+i*40}" y="274" text-anchor="middle">${i}</text><text x="236" y="${256-i*40}" text-anchor="end">${i}</text>`}
 const slope=m.skill==='slope',dxKnown=slope||m.phase==='hill-dy'||m.feedback?.result.ok,dyKnown=slope||m.phase==='hill-dy'&&m.feedback?.result.ok;
 const line=`M50 ${Y(W.add(W.mul(t.model.a,-5),t.model.b))}L450 ${Y(W.add(W.mul(t.model.a,5),t.model.b))}`;
 const labels=Object.entries(t.points).map(([name,p])=>{const right=name==='B'&&W.num(p.x)<2;return `<circle class="hill-halo" cx="${X(p.x)}" cy="${Y(p.y)}" r="11"/><circle class="hill-dot" cx="${X(p.x)}" cy="${Y(p.y)}" r="6"/><text class="hill-point-label" text-anchor="${right?'start':'end'}" x="${X(p.x)+(right?14:-12)}" y="${Y(p.y)+(name==='A'?-23:31)}">${name} ${esc(pair(p))}</text>`}).join('');
 return `<svg class="math-graph boundary-graph hill-graph" viewBox="0 0 500 500" role="img" aria-label="Rechte door A ${esc(pair(A))} en B ${esc(pair(B))}. Volg de richting A naar B."><defs><clipPath id="${id}"><path d="M45 45h410v410H45z"/></clipPath></defs><g class="graph-grid">${grid}</g><path class="axis" d="M30 250H472M250 470V27"/><path class="axis-arrow" d="m463 243 10 7-10 7M243 37l7-11 7 11"/><text x="238" y="274" text-anchor="end">0</text><text class="axis-name" x="478" y="256">x</text><text class="axis-name" x="263" y="30">y</text><g clip-path="url(#${id})"><path class="hill-line" d="${line}"/><path class="hill-steps" d="M${X(A.x)} ${Y(A.y)}H${X(B.x)}V${Y(B.y)}"/></g>${labels}<text class="hill-delta-label" x="${(X(A.x)+X(B.x))/2}" y="${Y(A.y)-9}" text-anchor="middle">Δx = ${dxKnown?esc(W.text(t.dx)):'?'}</text><text class="hill-delta-label" x="${X(B.x)+12}" y="${(Y(A.y)+Y(B.y))/2-3}">Δy = ${dyKnown?esc(W.text(t.dy)):'?'}</text></svg>`;
}
function reminder(m){const delta=m.skill==='delta',axis=m.phase==='hill-dy'?'y':'x',build=m.skill==='slope_from_two_points';return `<aside class="reminder-paper points-reminder hill-reminder"><h2>${S.icon('light',26)} Herinnering</h2>${delta?`<p>Δ${axis} is de ${axis==='x'?'horizontale':'verticale'} verandering.</p><p>${axis==='x'?'Rechts is positief,<br>links is negatief.':'Omhoog is positief,<br>omlaag is negatief.'}</p><p>Δ${axis} = ${axis}<sub>B</sub> − ${axis}<sub>A</sub></p>`:build?`<p>A(x<sub>A</sub>, y<sub>A</sub>)<br>B(x<sub>B</sub>, y<sub>B</sub>)</p><p>1. Bekijk de punten.<br>2. Vul de coördinaten in.<br>3. Bereken de helling.</p><p class="hill-reminder-formula">a = ${frac('y<sub>B</sub> − y<sub>A</sub>','x<sub>B</sub> − x<sub>A</sub>')}</p>`:`<p><i>a</i> is de richtingscoëfficiënt.</p><p>Je berekent:</p><p class="hill-reminder-formula">a = ${frac('Δy','Δx')}</p>`}<p class="reminder-small">Gebruik voor Δx en Δy dezelfde richting.</p><svg class="reminder-sketch" viewBox="0 0 180 110" aria-hidden="true"><path d="M12 86H166M40 103V12" stroke="currentColor" fill="none" stroke-width="2"/><path d="M65 30H137V72" stroke="#7770bd" stroke-dasharray="5 4" stroke-width="3" fill="none"/><path d="m128 66 9 7 6-9" fill="none" stroke="#7770bd" stroke-width="2"/><circle cx="65" cy="30" r="5" fill="#268ab8"/><circle cx="137" cy="72" r="5" fill="#268ab8"/><text x="85" y="24">Δx</text><text x="142" y="58">Δy</text></svg></aside>`}
function choices(m){const key=m.phase==='hill-dx'?'dx':m.phase==='hill-dy'?'dy':'a',field=key==='a'?'rateChoice':key+'Choice';return `<div class="point-options hill-options" role="group" aria-label="Kies ${key==='a'?'de helling':'Δ'+key[1]}">${m.task.options[key].map((q,i)=>`<button type="button" data-choice="${field}" data-value="${i}" aria-pressed="${String(m.values[field])===String(i)}" ${m.feedback?'disabled':''}>${W.html(q)}</button>`).join('')}</div>`}
function stepper(m){const phase=m.phase==='hill-inspect'?0:m.phase==='hill-fill'?1:2;return `<aside class="hill-stepper"><h2>Stap ${phase+1} van 3</h2><ol>${['Punten','Invullen','Berekenen'].map((name,i)=>`<li ${i===phase?'aria-current="step"':''} class="${i<phase?'is-done':''}"><span>${i<phase?'✓':i+1}</span><div><strong>${name}</strong><small>${['Bekijk de gegeven punten.','Zet de coördinaten in de formule.','Reken de helling uit.'][i]}</small></div></li>`).join('')}</ol><p>De volgorde is steeds:<br>eindpunt − beginpunt.</p></aside>`}
function token(m,name,axis){const key=name+'.'+axis,enabled=m.phase==='hill-fill'&&!m.feedback;return `<button type="button" class="coordinate-token" data-coordinate-token="${key}" draggable="${enabled}" aria-label="${axis} van ${name}: ${esc(W.text(m.task.points[name][axis]))}" ${enabled?'':'disabled'}><small>${axis}<sub>${name}</sub></small>${W.html(m.task.points[name][axis])}</button>`}
function slot(m,name){const q=H.coordinate(m.task,m.values[name]),selected=m.values.selectedSlot===name;return `<button type="button" class="coordinate-slot" data-coordinate-slot="${name}" aria-pressed="${selected}" aria-label="${{y1:'Eerste y-coördinaat',y0:'Tweede y-coördinaat',x1:'Eerste x-coördinaat',x0:'Tweede x-coördinaat'}[name]}${q?': '+W.text(q):', leeg'}" ${m.feedback||m.locks[name]?'disabled':''}>${q?W.html(q):'?'}</button>`}
function construction(m){const t=m.task,phase=m.phase,calc=phase==='hill-calculate';const fraction=calc?frac(`${val(H.coordinate(t,m.values.y1))} − ${val(H.coordinate(t,m.values.y0))}`,`${val(H.coordinate(t,m.values.x1))} − ${val(H.coordinate(t,m.values.x0))}`):frac(`${slot(m,'y1')}<span>−</span>${slot(m,'y0')}`,`${slot(m,'x1')}<span>−</span>${slot(m,'x0')}`);
 return `${reminder(m)}<section class="hill-construction"><div class="hill-construction-heading"><h1>Helling uit twee punten</h1><span>Opgave ${m.index+1} / ${H.count} · stap ${phase==='hill-inspect'?1:phase==='hill-fill'?2:3}</span></div><div class="hill-point-cards">${['A','B'].map(name=>`<div class="hill-point-card" data-point="${name}"><strong>${name}</strong><span>(</span>${token(m,name,'x')}<span>,</span>${token(m,name,'y')}<span>)</span></div>`).join('')}</div><p class="hill-builder-instruction">${phase==='hill-inspect'?'Bekijk de x- en y-coördinaten van A en B.':calc?'Bereken de teller en de noemer. Deel daarna.':'Tik een vakje en een coördinaat aan, of sleep de coördinaat.'}</p>${phase==='hill-inspect'?`<div class="hill-builder hill-intro-formula">a = ${frac('y<sub>B</sub> − y<sub>A</sub>','x<sub>B</sub> − x<sub>A</sub>')}</div>`:`<div class="hill-builder"><span>a =</span>${fraction}${calc?`<label class="hill-result"><span>Jouw helling a</span><input name="a" type="text" inputmode="text" autocomplete="off" aria-label="Helling a" placeholder="bijv. −1/2" value="${esc(m.values.a||'')}" ${m.feedback?'readonly':''}></label>`:''}</div>`}<button type="button" class="hill-builder-undo icon-button" id="undo" aria-label="Maak laatste bewerking ongedaan" ${m.feedback||!m.history.length?'disabled':''}>${S.icon('undo',21)}</button></section>${stepper(m)}`;
}
function render(m,header){const f=m.feedback,build=m.skill==='slope_from_two_points',delta=m.skill==='delta';
 const title=delta?`Hoe groot is Δ${m.phase==='hill-dy'?'y':'x'}?`:'Hoeveel is a?';
 const feedback=m.completed?'Je reeks is afgerond en bewaard.':f?`${f.result.ok?'✓ ':f.result.kind==='interaction_error'?'':'↻ '}${notation(f.result.message)}`:m.hintOpen?notation(m.task.hints[m.hints-1]):build?'Boven: y-verschil. Onder: x-verschil. Houd dezelfde richting.':delta?'Volg A → B. Eindcoördinaat min begincoördinaat.':'De richtingscoëfficiënt is de verhouding Δy / Δx.';
 const complete=`<section class="boundary-complete"><h1>Goed gedaan!</h1><p>Je hebt de zes opgaven afgerond.</p><span class="proof-badge">${S.icon('check')} ${H.names[m.skill]}</span><button type="button" data-restart="hellingrug" data-skill="${m.skill}">Opnieuw oefenen</button></section>`;
 const workspace=m.completed?complete:build?construction(m):`${reminder(m)}<div class="graph-paper"><button type="button" class="graph-undo icon-button" id="undo" aria-label="Maak laatste bewerking ongedaan" ${f||!m.history.length?'disabled':''}>${S.icon('undo',21)}</button><div class="evidence">${graph(m)}</div><span class="graph-paper-caption">Richting A → B · elk hokje is 1</span></div><section class="answer-tray points-answer hills-answer"><span class="points-progress">${H.names[m.skill]} · ${m.index+1} / ${H.count}${delta?' · '+(m.phase==='hill-dx'?'Δx':'Δy'):''}</span><div class="exercise-heading"><h1>${title}</h1></div><p class="point-instruction">${delta?'Kies het juiste antwoord.':'Gebruik Δy / Δx.'}</p>${delta?'':`<div class="hill-formula">a = ${frac('Δy','Δx')}</div>`}${choices(m)}</section>`;
 const action=m.completed?`<button type="button" class="paint-button" data-screen="area" data-area="hellingrug">Naar Hellingrug ${S.icon('arrow')}</button>`:m.hints>=5&&!f?`<button type="button" class="paint-button" id="new-example">Nieuw geval ${S.icon('arrow')}</button>`:m.phase==='hill-inspect'?`<button type="button" class="paint-button" id="hill-begin">Invullen ${S.icon('arrow')}</button>`:f?`<button type="button" class="paint-button" id="continue">${f.result.ok?(f.next==='next-task'&&m.index===H.count-1?'Afronden':'Volgende'):'Herstel'} ${S.icon(f.result.ok?'arrow':'undo')}</button>`:`<button type="submit" class="paint-button" id="commit">Controleer ${S.icon('arrow')}</button>`;
 return `<form id="mission" class="boundary-mission points-mission hills-mission ${build?'hill-builder-mission':''}" data-world="hellingrug" data-skill="${m.skill}" data-phase="${m.phase}" novalidate>${header}<main class="boundary-workspace points-workspace hills-workspace">${workspace}</main><footer class="boundary-footer"><button type="button" class="paper-pill" id="pause" aria-label="Pauzeer en ga naar Hellingrug">${S.icon('back')}<span>Vorige</span></button><div class="feedback-bubble"><button type="button" class="hint-button" id="hint" aria-label="Volgende hint" ${m.completed||f||m.hints>=5?'disabled':''}>${S.icon('light',23)}</button><div id="feedback" class="feedback ${f?f.result.ok?'success':'error':''}" role="status" aria-live="polite">${feedback}</div></div>${action}</footer></form><section id="rotateGate"><span class="rotate-symbol" aria-hidden="true">↻</span><h1>Even je scherm draaien</h1><p>Liggend heb je ruimte om de helling te ontdekken. Je werk blijft bewaard.</p><button type="button" class="paper-pill" data-screen="area" data-area="hellingrug">Terug naar Hellingrug</button></section>`;
}
return Object.freeze({render,graph});
});
