/* Three representations of line behaviour, plus classification of special lines. */
(function(root,factory){if(typeof module==='object')module.exports=factory(require('./workbench.js'),require('./shell-view.js'),require('../lines-core.js'),require('../../trainer/wave-core.js'));else root.RechtenV2LinesView=factory(root.RechtenV2Workbench,root.RechtenV2Shell,root.RechtenV2Lines,root.RechtenWave)})(globalThis,function(C,S,L,W){
'use strict';const esc=C.esc;let seq=0;
const pair=p=>`(${W.text(p.x)}; ${W.text(p.y)})`,coords=t=>['A','B'].map(n=>`<span>${n}(${W.html(t.points[n].x)}; ${W.html(t.points[n].y)})</span>`).join('');
function graph(m){const t=m.task,special=m.skill==='special_lines',editable=!m.feedback&&['line-plot','line-special'].includes(m.phase),given=t.representation==='graph'||special&&m.feedback?.result.ok;
 const points=given?t.points:Object.fromEntries(['A','B'].filter(n=>m.values['plot'+n]).map(n=>[n,{x:W.fromNumber(m.values['plot'+n].x),y:W.fromNumber(m.values['plot'+n].y)}]));
 const model=given?t.model:points.A&&points.B?W.model(points.A,points.B):null,id='line-clip-'+ ++seq,X=x=>250+40*W.num(x),Y=y=>250-40*W.num(y);
 let grid='';for(let tick=-10;tick<=10;tick++){const q=tick/2;if(t.gridStep===1&&tick%2)continue;const n=250+20*tick;grid+=`<path class="${tick%2?'half-grid':''}" d="M${n} 50V450M50 ${n}H450"/>`;if(!(tick%2)&&q)grid+=`<text x="${n}" y="272" text-anchor="middle">${q}</text><text x="236" y="${256-20*tick}" text-anchor="end">${q}</text>`}
 const line=!model||model.kind==='identical'?'':model.kind==='vertical'?`M${X(model.c)} 50V450`:`M50 ${Y(W.add(W.mul(model.a,-5),model.b))}L450 ${Y(W.add(W.mul(model.a,5),model.b))}`;
 const pins=Object.entries(points).map(([n,p])=>{const selected=(m.values.selectedPoint||'A')===n,locked=m.locks['plot'+n],right=W.num(p.x)<2,dy=n==='A'?-20:29;return `<g class="line-pin pin-${n} ${selected?'is-selected':''}" ${editable&&!locked?`data-line-marker="${n}"`:''}><circle class="line-pin-hit" cx="${X(p.x)}" cy="${Y(p.y)}" r="15"/><circle class="line-pin-dot" cx="${X(p.x)}" cy="${Y(p.y)}" r="6"/><text text-anchor="${right?'start':'end'}" x="${X(p.x)+(right?12:-12)}" y="${Y(p.y)+dy}">${n} ${esc(pair(p))}</text></g>`}).join('');
 return `<svg class="math-graph boundary-graph lines-graph" viewBox="0 0 500 500" role="${editable?'group':'img'}" ${editable?'tabindex="0" data-line-picker':''} aria-label="${editable?'Selecteer A of B. Tik in het rooster of gebruik de pijltjestoetsen.':'Grafiek van de rechte.'} Kleine stap: ${t.gridStep===.5?'een halve':'één'} eenheid."><defs><clipPath id="${id}"><path d="M45 45h410v410H45z"/></clipPath></defs><g class="graph-grid">${grid}</g><path class="axis" d="M30 250H472M250 470V27"/><path class="axis-arrow" d="m463 243 10 7-10 7M243 37l7-11 7 11"/><text x="236" y="273" text-anchor="end">0</text><text class="axis-name" x="479" y="256">x</text><text class="axis-name" x="263" y="30">y</text><path class="lines-model ${given||m.phase==='line-behavior'||m.feedback?.result.ok?'':'is-draft'}" clip-path="url(#${id})" d="${line}"/>${pins}</svg>`;
}
function reminder(m){const special=m.skill==='special_lines',rep=m.task.representation;return `<aside class="line-reminder"><h2>${S.icon('light',27)} Herinnering</h2>${special?'<p>Verschillende punten met dezelfde <strong>y</strong> bepalen een horizontale rechte.</p><p>Dezelfde <strong>x</strong> geeft een verticale rechte.</p><p>Een verticale rechte is geen functie. Een horizontale of schuine rechte is dat wel.</p><p class="line-small-note">Samenvallende punten bepalen geen unieke rechte.</p>':rep==='slope'?'<p>Het teken van <i>a</i> bepaalt of de grafiek stijgt, daalt of constant is.</p><div class="line-rules"><p>a &gt; 0 → stijgend</p><p>a &lt; 0 → dalend</p><p>a = 0 → constant</p></div>':rep==='points'?'<p>Plaats eerst A en B. Kijk daarna naar de rechte van links naar rechts.</p><p>Let op: A is niet altijd het linkse punt.</p><div class="line-rules">A(x<sub>A</sub>, y<sub>A</sub>)<br>B(x<sub>B</sub>, y<sub>B</sub>)</div>':'<p><strong>Stijgend:</strong> y wordt groter.</p><p><strong>Dalend:</strong> y wordt kleiner.</p><p><strong>Constant:</strong> y blijft gelijk.</p><p class="line-small-note">Lees steeds van links naar rechts.</p>'}</aside>`}
function choice(m,field,value,label,disabled=false){return `<button type="button" class="line-choice" data-choice="${field}" data-value="${value}" aria-pressed="${m.values[field]===value}" ${m.feedback||m.locks[field]||disabled?'disabled':''}>${label}</button>`}
function tools(m){const edit=!m.feedback&&['line-plot','line-special'].includes(m.phase),name=m.values.selectedPoint||'A',p=m.values['plot'+name];return `<div class="line-tools" role="group" aria-label="Punten plaatsen">${['A','B'].map(n=>`<button type="button" class="line-point-token token-${n}" data-line-point="${n}" draggable="${edit&&!m.locks['plot'+n]}" aria-pressed="${name===n}" aria-label="Punt ${n} selecteren of slepen" ${!edit||m.locks['plot'+n]?'disabled':''}>${n}</button>`).join('')}<button type="button" class="line-clear" id="line-clear" aria-label="Wis je geplaatste punten" ${!edit||!m.values.plotA&&!m.values.plotB?'disabled':''}>Wis</button><span class="line-placement" role="status">${p?`${name} (${p.x}; ${p.y})`:`Selecteer ${name} en tik in het rooster.`}</span></div>`}
function evidence(m){const t=m.task,special=m.skill==='special_lines',plot=t.representation==='points';
 if(t.representation==='slope')return `<section class="line-evidence slope-evidence"><p class="line-general-formula">y = ax + b</p><p>Gegeven is de richtingscoëfficiënt:</p><div class="line-given-slope">a = ${W.html(t.model.a)}</div><p class="line-small-note">Kijk naar het teken van a.</p></section>`;
 return `<section class="line-evidence ${plot?'has-line-picker':''}">${plot?`<div class="line-given-coords">${coords(t)}</div>`:''}<div class="line-graph-wrap">${graph(m)}</div>${plot?tools(m):''}<span class="line-grid-caption">${t.gridStep===.5?'Kleine hokjes: ½ eenheid':'Elk hokje is 1 eenheid'}${special?' · plaatsen mag, hoeft niet':''}</span></section>`;
}
function render(m,header){const special=m.skill==='special_lines',f=m.feedback,plot=m.phase==='line-plot',title=special?'Welke rechte bepalen deze punten?':'Wat gebeurt er met y als x toeneemt?';
 const answers=special?`<section class="line-answers special-answers answer-tray"><div><h2><span>1</span> Welke rechte is dit?</h2><div class="line-kind-choices" role="group" aria-label="Soort rechte">${[['horizontal','horizontaal'],['vertical','verticaal'],['neither','geen van beide']].map(([v,l])=>choice(m,'lineKind',v,l)).join('')}</div></div><div><h2><span>2</span> Is dit een functie?</h2><div class="line-function-choices" role="group" aria-label="Is dit een functie?">${[['yes','ja'],['no','nee'],['unknown','niet te bepalen']].map(([v,l])=>choice(m,'isFunction',v,l)).join('')}</div></div></section>`:`<section class="line-answers behavior-answers answer-tray">${plot?'<p class="line-step-label">1. Plaats eerst A en B.</p>':'<p class="line-step-label">Kies het juiste antwoord.</p>'}<div role="group" aria-label="Gedrag van de rechte">${['stijgend','dalend','constant'].map(v=>choice(m,'behavior',v,v,plot)).join('')}</div>${plot?'<p class="line-answer-note">Na controle beantwoord je de vraag.</p>':''}</section>`;
 const feedback=f?`${f.result.ok?'✓ ':f.result.kind==='interaction_error'?'':'↻ '}${esc(f.result.message)}`:m.hintOpen?esc(m.task.hints[m.hints-1]):special?'Zet de punten als je wilt zien hoe de rechte loopt.':plot?'Selecteer A of B. Sleep, tik of gebruik de pijltjestoetsen.':'Lees van links naar rechts: x neemt toe.';
 const done=`<section class="boundary-complete"><h1>Goed gedaan!</h1><p>Je hebt de reeks afgerond.</p><span class="proof-badge">${S.icon('check')} ${special?'Bijzondere rechten':'Stijgend, dalend of constant'}</span><button type="button" data-restart="hellingrug" data-skill="${m.skill}">Opnieuw oefenen</button></section>`;
 const workspace=m.completed?done:`<header class="line-question"><h1>${title}</h1><span>Opgave ${m.index+1} / ${m.task.count} · ${special?'bijzondere rechten':{graph:'grafiek lezen',slope:'gegeven helling',points:'twee punten'}[m.task.representation]}</span></header>${reminder(m)}${evidence(m)}${answers}`;
 const action=m.completed?`<button type="button" class="paint-button" data-screen="area" data-area="hellingrug">Naar Hellingrug ${S.icon('arrow')}</button>`:m.hints>=5&&!f?`<button type="button" class="paint-button" id="new-example">Nieuw geval ${S.icon('arrow')}</button>`:f?`<button type="button" class="paint-button" id="continue">${f.result.ok?(f.next==='next-task'&&m.index===m.task.count-1?'Afronden':'Volgende'):'Herstel'} ${S.icon(f.result.ok?'arrow':'undo')}</button>`:`<button type="submit" class="paint-button" id="commit">${plot?'Controleer punten':'Controleer'} ${S.icon('arrow')}</button>`;
 return `<form id="mission" class="boundary-mission lines-mission hills-mission" data-world="hellingrug" data-skill="${m.skill}" data-phase="${m.phase}" data-representation="${m.task.representation}" novalidate>${header}<main class="boundary-workspace lines-workspace">${workspace}</main><footer class="boundary-footer"><button type="button" class="paper-pill" id="pause" aria-label="Pauzeer en ga naar Hellingrug">${S.icon('back')}<span>Vorige</span></button><div class="feedback-bubble"><button type="button" class="hint-button" id="hint" aria-label="Volgende hint" ${m.completed||f||m.hints>=5?'disabled':''}>${S.icon('light',23)}</button><div id="feedback" class="feedback ${f?f.result.ok?'success':'error':''}" role="status" aria-live="polite">${m.completed?'Je werk is bewaard.':feedback}</div><button type="button" class="line-undo icon-button" id="undo" aria-label="Maak laatste bewerking ongedaan" ${f||m.completed||!m.history.length?'disabled':''}>${S.icon('undo',22)}</button></div>${action}</footer></form><section id="rotateGate"><span class="rotate-symbol">↻</span><h1>Even je scherm draaien</h1><p>Liggend heb je ruimte om de rechte te onderzoeken. Je werk blijft bewaard.</p><button type="button" class="paper-pill" data-screen="area" data-area="hellingrug">Terug naar Hellingrug</button></section>`;
}
return Object.freeze({render,graph});
});
