(async()=>{
 'use strict';
 function routeLearner(account){if(account?.role!=='student')return false;document.body.dataset.lessonRole='student';for(const d of document.querySelectorAll('dialog[open]'))d.close();const url=new URL('join.html',location.href),code=new URLSearchParams(location.search).get('code');if(code)url.searchParams.set('code',code);location.replace(url.href);return true;}
 const identity=await AxiomaAuth.ready().catch(()=>({account:null}));if(routeLearner(identity.account))return;
 document.body.dataset.lessonRole=identity.account?.role||'preview';AxiomaAuth.onChange(({account,pending})=>{if(!pending)routeLearner(account);});
 const $=id=>document.getElementById(id),lesson=LessonStageContent,art=LivingBlackboard.mount($('blackboard'));
 let engine,view='narrative',event=null,busy=false,boardReady=false,boardKey='',audio=null,sound=false,pdfSlot='taak1',checkReturn=null,renderSignature='';
 let sessionTransition=false,deskLoading=false,resumeReplay=null;
 let previousIndex=-2,continueScene=false,sceneReplay=crypto.randomUUID(),sentScene='',syncTimer=0,syncRunning=false,lastReport=null,reportAccount=null;
 const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
 const panels=['narrative','livePanel','documents','battlePanel','modulePanel'];
 const read=(k,f=null)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
 function notice(e){$('notice').textContent=e?.message||e||'';}
 async function act(fn){if(busy)return;busy=true;try{notice('');await fn();}catch(e){notice(e);}finally{busy=false;renderLive();}}
 function show(id){for(const p of panels)$(p).hidden=p!==id;}
 const live=LessonLive.create(()=>{renderLive();renderBoard();syncScene();},notice);
 const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
 const countdownKey='lesson-stage-countdown:'+lesson.id+':'+(identity.account?.id||'preview');
 const readerKey='lesson-stage-readers:'+lesson.id;
 const storedReaders=read(readerKey,{}),readerState={absent:Array.isArray(storedReaders?.absent)?storedReaders.absent:[],assignments:storedReaders?.assignments&&typeof storedReaders.assignments==='object'?storedReaders.assignments:{}};
 let readingStep=null,spokenEvent=null;
 function renderReading(step=readingStep){
  readingStep=step;const role=step?.reading||{lead:'teacher',pair:null},resolved=LessonReaders.resolve(role,lesson,readerState);
  $('readingNames').textContent=resolved.speakers.join(' / ');
  $('readingRole').textContent=role.lead==='teacher'?'LERAAR':'AAN ZET';
  $('readingHint').textContent=resolved.speakers.length>1?'Kies zelf wie leest':'';
  $('changeReader').hidden=role.pair==null;
  if(spokenEvent){$('sceneNote').replaceChildren();if(spokenEvent.noteSpeaker!=null){const reply=LessonReaders.resolve({...role,lead:spokenEvent.noteSpeaker},lesson,readerState).speakers.join(' / ');$('sceneNote').append(node('span',reply+': ','reply-reader'));}$('sceneNote').append(document.createTextNode(spokenEvent.note||''));}
 }
 function saveReaders(){save(readerKey,readerState);renderReading();syncScene();}
 function renderAttendance(){
  $('readerAttendance').replaceChildren();for(const name of lesson.readers){const label=node('label'),input=node('input');input.type='checkbox';input.checked=!readerState.absent.includes(name);input.value=name;input.onchange=()=>{readerState.absent=readerState.absent.filter(n=>n!==name);if(!input.checked)readerState.absent.push(name);saveReaders();};label.append(input,document.createTextNode(name));$('readerAttendance').append(label);}
 }
 renderAttendance();$('resetReaders').onclick=()=>{readerState.absent=[];readerState.assignments={};renderAttendance();saveReaders();};
 $('changeReader').onclick=e=>{e.stopPropagation();const role=readingStep.reading,team=LessonReaders.resolve(role,lesson,readerState).team,available=lesson.readers.filter(n=>!readerState.absent.includes(n));
  for(const [i,id] of ['readerFirst','readerSecond'].entries()){const select=$(id);select.replaceChildren();for(const name of [...available,LessonReaders.teacher])select.append(new Option(name,name));select.value=team[i]||team[0];}
  $('readerDialog').showModal();
 };
 $('cancelReaders').onclick=()=>$('readerDialog').close();
 $('readerForm').onsubmit=e=>{e.preventDefault();readerState.assignments[readingStep.reading.pair]=[$('readerFirst').value,$('readerSecond').value];saveReaders();$('readerDialog').close();};
 function setLive(title){show('livePanel');$('liveTitle').textContent=title;$('liveContent').replaceChildren();$('liveAction').hidden=true;}
 function actionButton(label,fn){$('liveAction').hidden=false;$('liveAction').textContent=label;$('liveAction').disabled=busy;$('liveAction').onclick=()=>act(fn);}
 function needRoom(){const {account,room}=live.state;if(room&&room.phase!=='closed')return false;setLive('De klas sluit aan.');$('liveContent').append(node('p',account?.role==='teacher'?'Eén sessie. Eén code. De hele les.':'Meld je aan met je leerkrachtaccount om de klas te laten aansluiten.'));actionButton(account?.role==='teacher'?'Groepssessie starten':'Aanmelden bij leraarBob',async()=>{if(account?.role!=='teacher'){document.querySelector('[data-axioma-login]').click();return;}await startLesson();});return true;}
 function join(){if(needRoom())return;const {room}=live.state;setLive('SESSIE OPEN');const url=new URL('join.html',location.href);url.searchParams.set('code',room.code);$('liveContent').append(node('strong',room.code,'code'),node('p','Klik bovenaan op Live en vul deze code in, of open de deelnamelink. Gebruik je eigen leraarBob-account.'),node('p',url.href,'join-url'),node('p',`${room.members.length} leerlingen aangesloten`));actionButton('Kopieer deelnamelink',async()=>{await navigator.clipboard.writeText(url.href);notice('Deelnamelink gekopieerd.');});}
 function renderPoll(){if(needRoom())return;const p=live.state.lesson?.poll;
  const matching=p&&(!event?.id||p.id===event.id);
  if(!matching){setLive(event?.question||'Een korte check.');$('liveContent').append(node('p',event?.anonymous===false?'Antwoorden zijn zichtbaar voor de leerkracht.':'Anoniem · alleen de groepsuitslag wordt getoond.'));actionButton('Open de vraag',()=>live.act('open_poll',{poll:event.id,question:event.question,options:event.options,anonymous:event.anonymous!==false}));return;}
  setLive(p.question);$('liveContent').append(node('p',p.anonymous?'Anoniem · geen namen bij antwoorden.':'Niet anoniem · antwoorden zijn zichtbaar voor de leerkracht.'));
  if(!p.closed){$('liveContent').append(node('p','Antwoord op je eigen toestel. De uitslag blijft verborgen tot de stemming sluit.'));actionButton('Sluit stemming en toon groep',()=>live.act('close_poll'));}
  else {bars(p);if(checkReturn)actionButton('Terug naar de correctie',()=>{view='pdf';event=checkReturn;checkReturn=null;showPDF(event);return live.act('mode',{mode:'narrative'});});}
 }
 function bars(p){const total=p.counts.reduce((a,b)=>a+b,0),wrap=node('div',null,'poll-bars');p.options.forEach((option,i)=>{const row=node('div',null,'poll-row'),label=node('div',null,'poll-label'),bar=node('div',null,'poll-bar'),fill=node('i');label.append(node('span',option),node('span',`${p.counts[i]} · ${total?Math.round(100*p.counts[i]/total):0}%`));fill.style.width=(total?100*p.counts[i]/total:0)+'%';bar.append(fill);row.append(label,bar);wrap.append(row);});$('liveContent').append(wrap,node('p',total?`${total} antwoorden · ${Math.max(0,live.state.room.members.length-total)} niet beantwoord`:'Nog geen antwoorden.'));
  // Named detail is deliberate, available only after a non-anonymous poll closes.
  if(p.named?.length){const list=node('details');list.append(node('summary','Antwoorden per leerling'));for(const a of p.named)list.append(node('p',a.alias+' · '+p.options[a.choice]));$('liveContent').append(list);}
 }
 const labels={point:'Coördinaten lezen',point_plot:'Punten plaatsen',line_behavior:'Stijgen en dalen',special_lines:'Bijzondere rechten',zeroRead:'Nulwaarde aflezen',delta:'Δx en Δy',slope:'Richtingscoëfficiënt',equation_from_ab:'Voorschrift bouwen',graph_from_equation:'Rechte tekenen',graph_from_table:'Rechte uit tabel',zero:'Nulwaarde berekenen',equation_from_graph:'Voorschrift uit grafiek',positive:'Positief gebied',negative:'Negatief gebied',signchart:'Tekenschema'};
 function results(){if(event.source==='poll'){const p=live.state.lesson?.history?.find(p=>p.id===event.poll)||(live.state.lesson?.poll?.id===event.poll?live.state.lesson.poll:null);if(p){if(!p.closed){setLive('De stemming is nog open.');actionButton('Sluit stemming en toon groep',()=>live.act('close_poll'));}else{setLive('Dit is onze groep.');bars(p);}}else{setLive('Er is nog geen stemming afgenomen.');}return;}
  setLive('Wat de arbeid heeft achtergelaten.');const rows=live.state.lesson?.summary||[];if(!rows.length){$('liveContent').append(node('p','Nog geen afgeronde battlevragen.'));return;}
  const total=rows.reduce((a,r)=>a+r.opportunities,0),correct=rows.reduce((a,r)=>a+r.correct,0),answered=rows.reduce((a,r)=>a+r.answered,0);
  $('liveContent').append(node('p',`${correct} van ${total} antwoorden juist · ${total?Math.round(correct*100/total):0}% · ${total-answered} niet ingediend`));const table=node('table',null,'skill-summary'),head=node('tr');for(const t of ['Vaardigheid','Juist','Volgende stap'])head.append(node('th',t));table.append(head);for(const r of rows){const tr=node('tr');for(const t of [labels[r.skill]||r.skill,`${r.correct}/${r.opportunities}`,r.correct/r.opportunities>=.75?'Verder bouwen':'Samen opnieuw bekijken'])tr.append(node('td',t));table.append(tr);}$('liveContent').append(table,node('p','Dit is een beeld van deze sessie, geen nieuwe leer-XP of volledige beheersingsmeting.'));
 }
 function renderLive(){const {room,account}=live.state;$('countdownJoin').textContent=room&&room.phase!=='closed'?'Live · '+room.code:'';if(reportAccount!==account?.id){reportAccount=account?.id;lastReport=null;$('sessionReport').replaceChildren();$('lessonHistory').replaceChildren();$('downloadSessionReport').disabled=true;}if(live.state.lesson?.mode==='clay')view='clay';$('sessionInfo').textContent=room?`Sessie ${room.code} · ${room.members.length} leerlingen`:account?.role==='teacher'?'Leerkrachtaccount aangemeld.':'Nog geen leerkrachtaccount aangemeld.';
  $('actualProgress').dataset.value=room?Math.max(0,room.round+(['results','finished','closed'].includes(room.phase)?1:0)):0;
  const signature=JSON.stringify([view,event,live.state.lesson,room?.id,room?.round,room?.members,room?.phase,account?.id,busy]);if(signature===renderSignature)return;renderSignature=signature;
  renderDesk();if(view==='clay')clayView();if(view==='liveJoin')join();if(view==='poll')renderPoll();if(view==='results')results();if(view==='battle')battle();
 }
 function snapshot(){const step=engine?.step;if(!step||!live.state.room)return null;const role=step.reading||{lead:'teacher'},text=step.events.find(e=>e.type==='text');let mode='narrative';if(step.events.some(e=>e.type==='battle'))mode='battle';if(view==='poll'&&live.state.lesson?.poll?.id===event?.id)mode='poll';return {step:step.id,replay:sceneReplay,speaker:LessonReaders.resolve(role,lesson,readerState).speakers.join(' / '),reply:text?.noteSpeaker==null?'':LessonReaders.resolve({...role,lead:text.noteSpeaker},lesson,readerState).speakers.join(' / '),view:mode};}
 function syncScene(){if(sessionTransition||live.state.room?.phase==='closed')return;if(live.state.account?.role!=='teacher'||!engine||!live.state.room)return;const data=snapshot(),signature=JSON.stringify([live.state.room.id,data]);if(signature===sentScene||syncRunning)return;clearTimeout(syncTimer);syncTimer=setTimeout(async()=>{syncRunning=true;try{await live.act('present',data);sentScene=signature;$('syncStatus').textContent='Leerlingen volgen deze scène live.';}catch(e){$('syncStatus').textContent='Synchronisatie onderbroken: '+e.message;}finally{syncRunning=false;if(sentScene===signature&&JSON.stringify([live.state.room?.id,snapshot()])!==signature)syncScene();}},120);}
 function renderDesk(){
  const {room,lesson:state,account}=live.state,active=!!room&&room.phase!=='closed',teacher=account?.role==='teacher',locked=busy||deskLoading||sessionTransition;
  $('deskStatus').textContent=deskLoading?'Je lessessies worden opgehaald…':active?`Les loopt · code ${room.code} · ${room.members.length} leerlingen aangesloten`:room?`Les ${room.code} beëindigd · resultaten bewaard`:teacher?'Er loopt geen lessessie.':'Gebruik je bestaande leerkrachtaccount.';
  $('sessionDesk').textContent=active?'Les '+room.code:'Les starten';
  $('deskPrepare').hidden=active;$('deskPrepare').disabled=locked||!teacher;
  $('resumeSession').hidden=!active;$('resumeSession').disabled=locked;
  $('closeSession').hidden=!active;$('closeSession').disabled=locked;
  $('sessionHelp').textContent=active?'Hervatten behoudt deze code en je plaats. Was dit een try-out? Beëindig die eerst en start daarna een nieuwe les.':'Een nieuwe les krijgt een eigen code. De aftelling van vijf minuten start automatisch.';
  $('startCountdown').hidden=!active;$('startCountdown').disabled=locked||!teacher;
  $('lessonActivityTools').hidden=!active;$('showHistoryReport').disabled=locked||!$('lessonHistory').options.length;$('copySessionLink').hidden=!active;$('copySessionLink').disabled=!active||locked;$('openClay').disabled=!active||locked;$('startClay').disabled=!active||locked||state?.activity?.status!=='waiting';$('returnStory').disabled=!active||locked||state?.mode!=='clay';$('showSessionReport').disabled=!room||locked;
 }
 function restorePresentation(){const p=live.state.lesson?.presentation;if(p?.step&&lesson.steps.some(s=>s.id===p.step)){resumeReplay=p.replay;engine.go(p.step);}}
 async function startLesson(){
  sessionTransition=true;clearTimeout(syncTimer);renderDesk();
  try{await live.create(lesson.deck);if(live.state.lesson?.presentation?.step)restorePresentation();else engine.go('aftellen');$('sessionDialog').close();$('settings').close();}
  finally{sessionTransition=false;renderDesk();syncScene();}
 }
 async function openSessionDesk(){
  if(!$('sessionDialog').open)$('sessionDialog').showModal();$('sessionDialog').scrollTop=0;$('lessonActivityTools').open=false;$('lessonReports').open=false;if(deskLoading)return;deskLoading=true;renderDesk();
  try{if(live.state.account?.role!=='teacher')return;
   const data=await live.inspect('history');$('lessonHistory').replaceChildren();for(const s of data.history||[])$('lessonHistory').append(new Option(`${new Date(s.created_at).toLocaleString('nl-BE')} · ${s.code} · ${s.phase==='closed'?'beëindigd':'lesverslag'}`,s.id));
   const previous=(!live.state.room||live.state.room.phase==='closed')&&(data.history||[]).find(s=>!['closed','finished'].includes(s.phase)&&Date.now()-Date.parse(s.created_at)<8*60*60*1000);
   if(previous){sessionTransition=true;clearTimeout(syncTimer);await live.inspect('state',{id:previous.id});await live.battle('state',{id:previous.id});await live.refresh();restorePresentation();}
  }catch(e){notice(e);}finally{sessionTransition=false;deskLoading=false;renderDesk();syncScene();}
 }
 function clayView(){if(needRoom())return;const a=live.state.lesson?.activity;setLive('Kleiduifschieten · samen');if(!a||live.state.lesson?.mode!=='clay'){$('liveContent').append(node('p','Eerst twee oefenschoten, zonder klok of score. Daarna starten we samen.'),node('p',`Sluit aan via Live · code ${live.state.room.code}`));actionButton('Open twee oefenschoten',()=>live.act('open_clay',{speed:Number($('claySpeed').value)}));return;}$('liveContent').append(node('p',a.status==='waiting'?`Nog even aansluiten · code ${live.state.room.code}. Laat leerlingen eerst de twee oefenrondes proberen; start daarna samen.`:a.status==='running'?'De race loopt. Zeven juiste antwoorden op rij.':a.status==='finished'?`${a.winner} wint. De resultaten zijn bewaard.`:'Activiteit afgesloten.'));for(const m of a.members||[])$('liveContent').append(node('p',`${m.alias} · ${m.streak}/7 · ${m.misses} missers`));actionButton(a.status==='waiting'?'Start samen':'Stop activiteit · terug naar verhaal',async()=>{if(a.status==='waiting')await live.act('start_clay');else await returnToStory();});}
 async function returnToStory(){await live.act('stop_clay');if(engine.step.events.some(e=>e.type==='clay'))engine.next();else engine.show();}
 $('sessionDesk').onclick=openSessionDesk;
 $('resumeSession').onclick=()=>{$('sessionDialog').close();};
 $('startCountdown').onclick=()=>act(async()=>{if(live.state.lesson?.mode==='clay')await live.act('stop_clay');engine.go('aftellen');$('sessionDialog').close();});
 $('deskPrepare').onclick=()=>act(startLesson);
 $('copySessionLink').onclick=()=>act(async()=>{const url=new URL('join.html',location.href);url.searchParams.set('code',live.state.room.code);await navigator.clipboard.writeText(url.href);$('syncStatus').textContent='Deelnamelink gekopieerd.';});
 $('openClay').onclick=()=>act(async()=>{await live.act('open_clay',{speed:Number($('claySpeed').value)});view='clay';$('sessionDialog').close();clayView();});
 $('startClay').onclick=()=>act(async()=>{await live.act('start_clay');view='clay';$('sessionDialog').close();clayView();});
 $('returnStory').onclick=()=>act(async()=>{await returnToStory();$('sessionDialog').close();});
 async function showReport(id){lastReport=await live.inspect('report',{id});$('sessionReport').replaceChildren();$('sessionReport').append(node('h3','Lesverslag · '+lastReport.code));for(const member of lastReport.members||[]){const section=node('details');section.append(node('summary',member.alias));for(const poll of member.polls)section.append(node('p',poll.question+' → '+poll.answer));section.append(node('p',`Battle: ${member.battle.filter(q=>q.correct).length} juist / ${member.battle.length} ingediend`));for(const c of member.clay)section.append(node('p',`Kleiduiven: ${c.correct}/${c.attempts} juist · ${c.misses} missers${c.won?' · gewonnen':''}`));$('sessionReport').append(section);}$('downloadSessionReport').disabled=false;}
 $('showSessionReport').onclick=()=>act(()=>showReport(live.state.room.id));$('showHistoryReport').onclick=()=>act(()=>showReport($('lessonHistory').value));
 $('downloadSessionReport').onclick=()=>{if(!lastReport)return;const rows=[['Sessie','Alias','Activiteit','Vraag / poging','Antwoord','Juist']];for(const m of lastReport.members){for(const p of m.polls)rows.push([lastReport.code,m.alias,'Vraag',p.question,p.answer,'']);for(const q of m.battle)rows.push([lastReport.code,m.alias,'Battle',q.round+' · '+(labels[q.skill]||q.skill),JSON.stringify(q.answer),q.correct?'Ja':'Neen']);for(const c of m.clay)for(const shot of c.shots)rows.push([lastReport.code,m.alias,'Kleiduiven · '+c.speed+' s',shot.attempt,shot.answer??'Niet geantwoord',shot.correct?'Ja':'Neen']);}const csv='\uFEFF'+rows.map(row=>row.map(value=>'"'+String(value).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=node('a');a.href=url;a.download='les-'+lastReport.code+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 function send(data){if(boardReady)$('battleBoard').contentWindow.postMessage(data,location.origin);}
 function renderBoard(){const {room}=live.state;if(!room||!boardReady||!room.spec)return;const key=room.id+':'+room.round;if(key!==boardKey){boardKey=key;send({type:'vector-battle-question',match:room.id,index:room.round,...room.spec,singleAttempt:true,projector:true});}send({type:'vector-battle-resolved',match:room.id,index:room.round,message:'Werk op je eigen toestel. Gebruik papier waar nodig.'});}
 function battle(){if(needRoom())return;show('battlePanel');const frame=$('battleBoard'),r=live.state.room;frame.hidden=!r.spec;$('battleWaiting').hidden=!!r.spec;if(r.spec&&!frame.src)frame.src=frame.dataset.src;$('battleBand').textContent=lesson.band(Math.max(0,r.round));$('battlePanel').dataset.band=String(Math.min(4,Math.floor(Math.max(0,r.round)/5)));$('battleCount').textContent=`${Math.max(0,r.round+1)} / ${r.total}`;
  $('battleAction').disabled=busy||r.phase==='grading'||(r.phase==='lobby'&&!r.members.length);$('battleAction').textContent=({lobby:'Start vraag 1',question:'Sluit deze vraag',grading:'Antwoorden nakijken…',results:r.round+1===r.total?'Bekijk klasresultaat':'Volgende vraag →',finished:'Bekijk klasresultaat',closed:'Bekijk klasresultaat'})[r.phase];
  $('battleStatus').textContent=r.phase==='lobby'?`${r.members.length} leerlingen · nog even aansluiten via code ${r.code}`:r.phase==='results'?`${r.members.filter(m=>m.correct).length} juiste antwoorden in deze ronde`:r.phase==='question'?`${r.members.filter(m=>m.answered).length} / ${r.members.filter(m=>m.eligible_from_round<=r.round).length} ingediend`:r.phase==='grading'?'Server kijkt de antwoorden na.':'Deze battle is afgelopen.';renderBoard();
 }
 function endBattle(){if(lesson.battleResultStep)engine.go(lesson.battleResultStep);else engine.next();}
 $('battleAction').onclick=()=>act(async()=>{const r=live.state.room;if(['finished','closed'].includes(r.phase)){endBattle();return;}await live.act('mode',{mode:'battle'});if(r.phase==='question')await live.act('end_round');else await live.battle(r.phase==='lobby'?'start':'next');await live.refresh();if(live.state.room.phase==='finished')endBattle();});
 addEventListener('message',e=>{if(e.origin===location.origin&&e.source===$('battleBoard').contentWindow&&e.data?.type==='vector-battle-ready'){boardReady=true;boardKey='';renderBoard();}});
 setInterval(()=>{const r=live.state.room;$('battleTime').textContent=r?.phase==='question'?Math.max(0,Math.ceil((Date.parse(r.deadline)-Date.now()-(r.clockOffset||0))/1000))+' s':'';},250);

 // Local PDFs use IndexedDB, never classroom storage. Each iframe remains mounted.
 const docs=new Map(),urls=new Map(),ink=new Map(read('lesson-stage-ink:'+lesson.id,[]));let dbPromise;
 function db(){return dbPromise??=new Promise((resolve,reject)=>{const req=indexedDB.open('leraarbob-lesson-documents',1);req.onupgradeneeded=()=>req.result.createObjectStore('files');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
 async function fileStore(slot,file){const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('files',file?'readwrite':'readonly'),store=tx.objectStore('files'),req=file?store.put(file,lesson.id+':'+slot):store.get(lesson.id+':'+slot);let result;req.onsuccess=()=>result=req.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);});}
 function attachPDF(slot,file){let frame=docs.get(slot);if(!frame){frame=node('iframe');frame.title=slot==='taak1'?'Eerste taak · correctie':'Tweede taak';$('documentArea').prepend(frame);docs.set(slot,frame);}if(urls.has(slot))URL.revokeObjectURL(urls.get(slot));const url=URL.createObjectURL(file);urls.set(slot,url);frame.src=url;frame.hidden=slot!==pdfSlot;$('documentEmpty').hidden=docs.has(pdfSlot);}
 async function showPDF(e){show('documents');pdfSlot=e.slot;$('documentTitle').textContent=e.slot==='taak1'?'Taak 1 · correctie':'Taak 2 · zelfstandig werk';for(const [slot,frame] of docs)frame.hidden=slot!==pdfSlot;$('documentEmpty').hidden=docs.has(pdfSlot);$('documentInk').hidden=true;$('inkToggle').setAttribute('aria-pressed','false');if(!docs.has(e.slot)){try{const file=await fileStore(e.slot);if(file)attachPDF(e.slot,file);}catch{notice('Je browser kan PDF’s niet bewaren. Opnieuw kiezen blijft mogelijk.');}}drawInk();}
 $('pdfFile').onchange=()=>act(async()=>{const file=$('pdfFile').files[0];if(!file)return;if(file.size>40*1024*1024)throw Error('Kies een PDF kleiner dan 40 MB.');if((await file.slice(0,5).text())!=='%PDF-')throw Error('Dit bestand is geen PDF.');attachPDF(pdfSlot,file);await fileStore(pdfSlot,file);notice('PDF bewaard op dit toestel.');});
 const canvas=$('documentInk');let stroke=null;
 function drawInk(){const r=$('documentArea').getBoundingClientRect();canvas.width=Math.max(1,r.width);canvas.height=Math.max(1,r.height);const c=canvas.getContext('2d');c.strokeStyle='#bf4f26';c.lineWidth=3;c.lineCap='round';for(const points of ink.get(pdfSlot)||[]){c.beginPath();points.forEach(([x,y],i)=>c[i?'lineTo':'moveTo'](x*canvas.width,y*canvas.height));c.stroke();}}
 const saveInk=()=>save('lesson-stage-ink:'+lesson.id,[...ink]);
 $('inkToggle').onclick=()=>{canvas.hidden=!canvas.hidden;$('inkToggle').setAttribute('aria-pressed',String(!canvas.hidden));drawInk();};$('eraseInk').onclick=()=>{ink.set(pdfSlot,[]);saveInk();drawInk();};
 canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);stroke=[];if(!ink.has(pdfSlot))ink.set(pdfSlot,[]);ink.get(pdfSlot).push(stroke);canvas.onpointermove(e);};canvas.onpointermove=e=>{if(!stroke)return;const r=canvas.getBoundingClientRect();stroke.push([(e.clientX-r.x)/r.width,(e.clientY-r.y)/r.height]);drawInk();};canvas.onpointerup=canvas.onpointercancel=()=>{stroke=null;saveInk();};new ResizeObserver(drawInk).observe($('documentArea'));
 for(const [i,check] of (lesson.checks||[]).entries())$('checkPreset').append(new Option(check.label,String(i)));$('checkPreset').onchange=()=>{const preset=lesson.checks[Number($('checkPreset').value)];$('checkQuestion').value=preset.question;$('checkOptions').value=preset.options.join('\n');};$('insertCheck').onclick=()=>$('checkDialog').showModal();$('cancelCheck').onclick=()=>$('checkDialog').close();
 $('checkForm').onsubmit=e=>{e.preventDefault();act(async()=>{if(!live.state.room)throw Error('Start eerst de groepssessie via het lesmenu.');const options=$('checkOptions').value.split('\n').map(x=>x.trim()).filter(Boolean);if(options.length<2||options.length>6)throw Error('Geef 2 tot 6 keuzes.');const poll={id:crypto.randomUUID(),type:'poll',question:$('checkQuestion').value.trim(),options,anonymous:$('checkAnonymous').checked};await live.act('open_poll',{poll:poll.id,question:poll.question,options,anonymous:poll.anonymous});checkReturn=event;event=poll;view='poll';$('checkDialog').close();renderLive();});};

 function fillCaption(e){
  const words=$('words');words.replaceChildren();
  const phrases=(e.emphasis||[]).filter(Boolean).sort((a,b)=>b.length-a.length);let rest=e.text;
  while(rest){let found=null,at=rest.length;for(const phrase of phrases){const i=rest.indexOf(phrase);if(i>=0&&i<at){at=i;found=phrase;}}
   if(!found){words.append(document.createTextNode(rest));break;}
   words.append(document.createTextNode(rest.slice(0,at)),node('span',found,'word-accent'));rest=rest.slice(at+found.length);
  }
  spokenEvent=e;renderReading();$('sceneChoices').replaceChildren();
  for(const label of e.choices||[]){const button=node('button',label);button.onclick=ev=>{ev.stopPropagation();advance();};$('sceneChoices').append(button);}
  return words;
 }
 function revealText(e,{signal}){
  const words=fillCaption(e);words.closest('.caption').style.visibility='visible';
  if(!reducedMotion.matches){const caption=words.closest('.caption'),animation=caption.animate(e.impact?
   [{opacity:0,transform:'translateY(9px) scale(.95)'},{opacity:1,transform:'translateY(0) scale(1.015)',offset:.65},{opacity:1,transform:'none'}]:
   [{opacity:0,transform:'translateY(9px)'},{opacity:1,transform:'none'}],{duration:e.impact?460:380,easing:'cubic-bezier(.16,1,.3,1)'});
   signal.addEventListener('abort',()=>animation.cancel(),{once:true});
   const stop=()=>{if(reducedMotion.matches)animation.cancel();};reducedMotion.addEventListener('change',stop);animation.finished.catch(()=>{}).finally(()=>reducedMotion.removeEventListener('change',stop));
  }
 }
 const adapters={scene:(e,{signal})=>{show('narrative');$('stage').dataset.art=e.art;$('stage').dataset.tone=e.tone||'paper';$('stage').dataset.color=e.color||'ink';art.start(e,signal,{continueScene});},text:revealText,draw:(e,ctx)=>{if(e.action==='erase')art.start({art:'empty'},ctx.signal);else art.start({...e,art:e.paths?'paths':e.art},ctx.signal);},animate:(e,ctx)=>{if(e.action==='silence')art.silence();else if(e.action==='morph')art.start({...e,art:'morph'},ctx.signal);else art.start(e,ctx.signal);},
  audio:(e,{signal})=>{if(!sound)return;audio??=new AudioContext();audio.resume().catch(()=>{});const gain=audio.createGain();gain.gain.value=.018;gain.connect(audio.destination);const osc=audio.createOscillator();osc.type='sine';osc.frequency.setValueAtTime(196,audio.currentTime);osc.frequency.linearRampToValueAtTime(e.cue==='overload'?390:220,audio.currentTime+2);osc.connect(gain);gain.gain.setTargetAtTime(0,audio.currentTime+2,.2);osc.start();osc.stop(audio.currentTime+3);signal.addEventListener('abort',()=>{gain.disconnect();},{once:true});},
  pause:(e,{signal})=>{if(engine.step.id==='aftellen'&&identity.account?.role==='teacher'&&((!live.state.room&&!live.state.id)||live.state.room?.phase==='closed')){$('clock').hidden=false;$('clock').textContent='5:00';return;}const start=engine.step.id==='aftellen'?Number(sceneReplay.split(':')[0])-(live.state.room?.clockOffset||0):Date.now(),end=start+e.duration;$('clock').hidden=false;const tick=()=>{const s=Math.max(0,Math.ceil((end-Date.now())/1000));$('clock').textContent=s?`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`:(e.finished||'Werktijd voorbij. Rond je gedachte af.');if(!s&&e.next&&!signal.aborted)engine.go(e.next);};const timer=setInterval(tick,500);signal.addEventListener('abort',()=>clearInterval(timer),{once:true});tick();},
  clay:e=>{event=e;view='clay';renderLive();},liveJoin:e=>{event=e;view=e.type;renderLive();},poll:e=>{event=e;view=e.type;renderLive();},results:e=>{event=e;view=e.type;renderLive();},pdf:e=>{event=e;view=e.type;return showPDF(e);},battle:e=>{event=e;view=e.type;renderLive();},
  exercise:moduleEvent,game:moduleEvent};
 const modules=new Map();function moduleEvent(e){const url=new URL(e.src,location.href);if(url.origin!==location.origin)throw Error('Gebruik een bestaande LeraarBob-module.');show('modulePanel');for(const f of modules.values())f.hidden=true;let frame=modules.get(url.href);if(!frame){frame=node('iframe');frame.title=e.title||'LeraarBob-module';frame.src=url.href;modules.set(url.href,frame);$('modulePanel').append(frame);}frame.hidden=false;}
 engine=LessonStage.create({lesson,adapters,storage:localStorage,onError:notice,onChange:({index,step,total})=>{continueScene=index===previousIndex+1;const firstShow=previousIndex===-2;previousIndex=index;sceneReplay=resumeReplay||crypto.randomUUID();const restoring=!!resumeReplay;resumeReplay=null;if(step.id==='aftellen'){const saved=firstShow&&read(countdownKey);sceneReplay=restoring?sceneReplay:typeof saved==='string'&&/^\d{13}:/.test(saved)?saved:(Date.now()+(live.state.room?.clockOffset||0))+':'+sceneReplay;save(countdownKey,sceneReplay);}else{try{localStorage.removeItem(countdownKey);}catch{}}$('stage').dataset.step=step.id;spokenEvent=null;renderReading(step);view='narrative';event=null;checkReturn=null;renderSignature='';show('narrative');$('words').textContent='';$('sceneNote').textContent='';$('sceneChoices').replaceChildren();$('stage').dataset.tone='paper';$('stage').dataset.art='';$('stage').dataset.color='ink';$('clock').hidden=true;$('speakerNotes').textContent=step.notes||'Laat het beeld en de zin spreken. Klik verder wanneer je klaar bent.';$('position').textContent=`${index+1} / ${total}`;$('eyebrow').textContent=(step.chapter||step.title).toUpperCase();$('previous').disabled=index===0;$('next').disabled=index===total-1;$('route').value=step.id;const spoken=step.events.find(e=>e.type==='text');$('words').closest('.caption').style.visibility='hidden';if(spoken)fillCaption(spoken);notice('');syncScene();}});
 // Navigation never starts/closes/recreates a session or a question.
 $('previous').onclick=()=>engine.previous();$('next').onclick=()=>advance();$('restart').onclick=()=>engine.restart();$('skip').onclick=()=>{engine.skip();$('settings').close();};
 function advance(){if(view==='clay'){$('liveAction').click();return;}if(view==='battle'&&live.state.room&&!['finished','closed'].includes(live.state.room.phase)){$('battleAction').click();return;}if(view==='liveJoin'&&!live.state.room||view==='poll'&&(!live.state.lesson?.poll?.closed||live.state.lesson.poll.id!==event.id)||view==='results'&&event.source==='poll'&&live.state.lesson?.poll&&!live.state.lesson.poll.closed){$('liveAction').click();return;}engine.next();}
 $('route').onchange=()=>{$('speakerNotes').textContent=lesson.steps.find(s=>s.id===$('route').value)?.notes||'Laat het beeld en de zin spreken.';};$('narrative').onclick=advance;for(const step of lesson.steps)$('route').append(new Option(step.title,step.id));$('jump').onclick=()=>{engine.go($('route').value);$('settings').close();};$('teacherMenu').onclick=()=>$('settings').showModal();
 $('prepareSession').onclick=()=>{$('settings').close();openSessionDesk();};$('soundToggle').onclick=()=>{sound=!sound;$('soundToggle').textContent=sound?'Geluid aan':'Geluid uit';$('soundToggle').setAttribute('aria-pressed',String(sound));};
 $('closeSession').onclick=()=>{const r=live.state.room;if(r&&r.phase!=='closed'){$('stopSummary').textContent=`Lescode ${r.code} · ${r.members.length} leerlingen`; $('stopDialog').showModal();}};
 $('keepSession').onclick=()=>$('stopDialog').close();
 $('confirmClose').onclick=()=>act(async()=>{
  sessionTransition=true;clearTimeout(syncTimer);$('confirmClose').disabled=true;
  try{if(live.state.room?.phase!=='finished'&&live.state.lesson?.poll&&!live.state.lesson.poll.closed)await live.act('close_poll');if(live.state.lesson?.activity&&['waiting','running','finished'].includes(live.state.lesson.activity.status))await live.act('stop_clay');await live.battle('close');await live.refresh();engine.go('uitloop');$('stopDialog').close();$('settings').close();await openSessionDesk();notice('Les beëindigd. Je kunt het lesverslag bekijken of een nieuwe les starten.');}
  finally{sessionTransition=false;$('confirmClose').disabled=false;}
 });
 let awake;function wake(){document.body.classList.add('controls-awake');clearTimeout(awake);awake=setTimeout(()=>document.body.classList.remove('controls-awake'),2400);}addEventListener('pointermove',wake);addEventListener('pointerdown',wake);wake();
 addEventListener('keydown',e=>{if(e.defaultPrevented||e.altKey||e.ctrlKey||e.metaKey||e.repeat||e.target.closest('input,textarea,select,button,a,[contenteditable]')||document.querySelector('dialog[open]'))return;if(['ArrowRight',' ','PageDown'].includes(e.key)){e.preventDefault();advance();}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();engine.previous();}else if(e.key.toLowerCase()==='r'){e.preventDefault();engine.restart();}wake();});
 const theme=read('lesson-stage-theme','light');function applyTheme(mode){document.documentElement.dataset.mode=mode;$('themeBtn').setAttribute('aria-pressed',String(mode==='dark'));$('themeBtn').textContent=mode==='dark'?'Lichte weergave':'Donkere weergave';save('lesson-stage-theme',mode);}applyTheme(theme);$('themeBtn').onclick=()=>applyTheme(document.documentElement.dataset.mode==='dark'?'light':'dark');
 window.lessonStage=engine;engine.show();if(location.hash==='#lessessie')queueMicrotask(openSessionDesk);
})();
