(()=>{
 const $=id=>document.getElementById(id),art=LivingBlackboard.mount($('blackboard'));let busy=false,signature='',resultSignature='',sceneKey='',sceneAbort,frameKey='',clockTimer;
 const notice=e=>$('notice').textContent=e?.message||e||'';
 const live=LessonLive.create(render,notice);
 let invite=new URLSearchParams(location.search).get('code');if(/^[a-f\d]{6}$/i.test(invite||''))$('joinCode').value=invite.toUpperCase();
 async function act(fn){if(busy)return;busy=true;render(live.state);try{notice('');await fn();}catch(e){notice(e);}finally{busy=false;render(live.state);}}
 $('joinForm').onsubmit=e=>{e.preventDefault();act(()=>live.join($('joinCode').value.trim().toUpperCase()));};
 function show(id){for(const name of ['stage','studentTask','studentActivity','studentPoll','studentResults'])$(name).hidden=name!==id;$('studentActivity').inert=id!=='studentActivity';if(id!=='stage'){sceneAbort?.abort();sceneKey='';clearInterval(clockTimer);}}
 function mode(text){$('interactionMode').textContent=text;}
 const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
 function pollResults(p){show('studentResults');mode('Samen bekijken');const key=JSON.stringify(['poll',p.id,p.counts]);if(key===resultSignature)return;resultSignature=key;$('resultsTitle').textContent=p.question;$('resultsContent').replaceChildren();const total=p.counts.reduce((a,b)=>a+b,0),bars=node('div',null,'poll-bars');p.options.forEach((option,i)=>{const row=node('div',null,'poll-row'),label=node('div',null,'poll-label'),bar=node('div',null,'poll-bar'),fill=node('i');label.append(node('span',option),node('span',`${p.counts[i]} · ${total?Math.round(100*p.counts[i]/total):0}%`));fill.style.width=(total?100*p.counts[i]/total:0)+'%';bar.append(fill);row.append(label,bar);bars.append(row);});$('resultsContent').append(bars,node('p',`${total} ${total===1?'antwoord':'antwoorden'} in de klas`));}
 function battleResults(rows){show('studentResults');mode('Samen bekijken');const key=JSON.stringify(['battle',rows]);if(key===resultSignature)return;resultSignature=key;$('resultsTitle').textContent='Wat we samen hebben gedaan.';$('resultsContent').replaceChildren();const possible=rows.reduce((s,r)=>s+r.opportunities,0),correct=rows.reduce((s,r)=>s+r.correct,0),answered=rows.reduce((s,r)=>s+r.answered,0);$('resultsContent').append(node('p',`${correct} van ${possible} juist · ${possible-answered} niet ingediend`));}
 $('changeSession').onclick=()=>{invite='';const url=new URL(location.href);url.searchParams.delete('code');history.replaceState(null,'',url);live.forget();$('joinCode').value='';$('joinCode').focus();};
 function task(title,note){show('studentTask');$('taskTitle').textContent=title;$('taskNote').textContent=note;}
 function follow(room,state){
  mode('Je volgt live');if(room.phase==='closed'){mode('Les afgelopen');task('De lessessie is afgesloten.','Je antwoorden zijn bewaard.');$('studentActivity').replaceChildren();frameKey='';return;}
  if(state?.mode==='poll'&&state.poll){if(state.poll.closed)pollResults(state.poll);else{show('studentPoll');mode(state.poll.voted?'Antwoord ontvangen · even wachten':'Jij bent aan zet');}return;}
  const activity=state?.mode==='clay'?state.activity:null;
  if(activity||state?.mode==='battle'){
   if(!activity&&room.phase==='lobby'){task('De klasbattle staat klaar.','Je bent al aangesloten met je alias. De leerkracht start de eerste vraag.');return;}
   mode(activity?'Klasactiviteit':room.phase==='question'&&!room.mine?.submitted?'Jij bent aan zet':'Battle · volg de uitslag');show('studentActivity');const key=activity?'clay:'+activity.id:'battle:'+room.id;if(frameKey!==key){frameKey=key;const frame=document.createElement('iframe');frame.title=activity?'Kleiduifschieten · deze lessessie':'Klasbattle · deze lessessie';const url=new URL(activity?'../../games/rechten/kleiduiven/':'../../games/rechten/rechtenwereld/classroom.html',location.href);url.searchParams.set(activity?'lesson':'code',activity?room.id:room.code);if(!activity)url.searchParams.set('hub','1');frame.src=url.href;$('studentActivity').replaceChildren(frame);}return;
  }
  if(frameKey.startsWith('clay:')){$('studentActivity').replaceChildren();frameKey='';}
  const presentation=state?.presentation,step=LessonStageContent.steps.find(s=>s.id===presentation?.step),scene=step?.events.find(e=>e.type==='scene'),text=step?.events.find(e=>e.type==='text');
  if(!step){task('Je bent aangesloten.','De leerkracht start zo het lesverhaal.');return;}
  if(!scene){const e=step.events[0];if(e.type==='results'){if(e.source==='poll'){const p=state.history?.find(p=>p.id===e.poll);if(p?.closed){pollResults(p);return;}}else{battleResults(state.summary||[]);return;}}task(e.question||step.title,e.type==='poll'?'De leerkracht opent zo de vraag. Daarna kun jij antwoorden.':e.type==='pdf'?'Volg de correctie op het klasbord. Het PDF-document staat op het toestel van de leerkracht.':e.type==='liveJoin'?'Je bent al aangesloten. Even wachten op de rest van de klas.':'Volg de bespreking op het klasbord.');return;}
  show('stage');$('stage').dataset.step=step.id;$('stage').dataset.art=scene.art;$('stage').dataset.tone=scene.tone||'paper';$('stage').dataset.color=scene.color||'ink';$('readingNames').textContent=presentation.speaker||'LeraarBob';$('readingRole').textContent=step.reading?.lead==='teacher'?'LERAAR':'AAN ZET';$('words').textContent=text?.text||'';$('sceneNote').replaceChildren();if(presentation.reply)$('sceneNote').append(node('span',presentation.reply+': ','reply-reader'));$('sceneNote').append(document.createTextNode(text?.note||''));$('eyebrow').textContent=(step.chapter||step.title).toUpperCase();
  const key=step.id+':'+presentation.replay;if(key!==sceneKey){sceneKey=key;sceneAbort?.abort();sceneAbort=new AbortController();clearInterval(clockTimer);const elapsed=Math.max(0,Date.parse(state.server_time||new Date().toISOString())-Date.parse(presentation.started_at||new Date().toISOString()));art.start(scene,sceneAbort.signal,{elapsed});const pause=step.events.find(e=>e.type==='pause');$('clock').hidden=!pause;if(pause){const start=step.id==='aftellen'&&/^\d{13}:/.test(presentation.replay||'')?Number(presentation.replay.split(':')[0])-(room.clockOffset||0):Date.now()-elapsed,end=start+pause.duration,tick=()=>{const s=Math.max(0,Math.ceil((end-Date.now())/1000));$('clock').textContent=s?Math.floor(s/60)+':'+String(s%60).padStart(2,'0'):(pause.finished||'Werktijd voorbij. Rond je gedachte af.');};tick();clockTimer=setInterval(tick,500);}}
 }
 function render({account,room,lesson}){
  if(invite&&room&&room.code!==invite.toUpperCase()){room=null;lesson=null;}
  $('signIn').hidden=!!account;$('joinForm').hidden=!account||!!room;$('joinIntro').hidden=!!room;$('studentMain').classList.toggle('following',!!room);
  $('changeSession').hidden=!account||!room;$('interactionMode').hidden=!room;
  $('joinStatus').textContent=!account?'Gebruik je bestaande leraarBob-aanmelding.':!room?'Vul de code op het klasbord in.':`Je doet mee · ${account.alias||'Leerling'} · ${room.code}`;
  if(room&&account){localStorage.setItem(`rechten-class-session:${account.id}`,JSON.stringify(room.id));$('actualProgress').dataset.value=Math.max(0,room.round+(['results','finished','closed'].includes(room.phase)?1:0));follow(room,lesson);}else{show(null);resultSignature='';sceneAbort?.abort();sceneKey='';clearInterval(clockTimer);$('studentActivity').replaceChildren();frameKey='';}
  const p=lesson?.poll,sig=JSON.stringify([p,busy]);if(sig===signature)return;signature=sig;if(!p)return;
  $('question').textContent=p.question;$('privacy').textContent=p.anonymous?'Anoniem: alleen groepstotalen. Je keuze wordt niet bij je account opgeslagen.':'Antwoord per alias: je leerkracht ziet jouw antwoord in het lesverslag.';
  $('choices').hidden=p.closed||p.voted;$('choices').replaceChildren();p.options.forEach((text,i)=>{const b=document.createElement('button');b.textContent=text;b.disabled=busy||p.closed||p.voted;b.onclick=()=>act(()=>live.act('vote',{poll:p.id,choice:i}));$('choices').append(b);});
  $('voteStatus').textContent=p.closed?(p.voted?'Je antwoord is bewaard.':'Deze stemming is gesloten.'):p.voted?'Je antwoord is ontvangen.':'Kies één antwoord.';
 }
 $('themeBtn').onclick=()=>{const dark=document.documentElement.dataset.mode!=='dark';document.documentElement.dataset.mode=dark?'dark':'light';$('themeBtn').setAttribute('aria-pressed',String(dark));};
})();
